[PHB/DMG] Class File Split and Full OCF Support
AuroraLegacy/elements pull request #104
Opened 2021-10-05 15:35 UTC by kgirtxd

2021-11-12 22:13 UTC, Azzzzzy approved these changes

2022-01-03 17:51 UTC, AngryGuineaPig approved these changes

2022-01-11 22:08 UTC, NickVendel requested changes
additionally, i want to change names of the files, like i think it would be better to have `fighter-eldritch-knight` than `fighter-eldritchknight`, i just don't see reason for us to continue using old formatting since we now know it doesn't matter. And also, if we gonna change it to this format then we're okay with core classes being stuck between valor bard and knowledge cleric? Again, not that it matters a lot how it looks, i just wonder if that's exactly what we should do.

2022-01-11 22:23 UTC, kgirtxd commented on core/players-handbook/classes/class-paladin.xml
> +		<requirements>!ID_KBP_DMBD_CLASS_FEATURE_ANTIPALADIN_UNHOLY_SMITE, !ID_INTERNAL_FEATURE_REPLACEMENT_PALADIN_DIVINE_SMITE</requirements>
I didnt notice that but I'm perfectly happy with removing it

2022-01-11 22:38 UTC, kgirtxd commented on core/dungeon-masters-guide/classes/class-oathbreaker.xml
> +	<element name="Channel Divinity Feature Replacement" type="Grants" source="Internal" id="ID_INTERNAL_FEATURE_REPLACEMENT_PALADIN_OATHBREAKER_CHANNEL_DIVINITY" />
With the way Channel Divinity works for Paladins it just grants the to features so my thought was to remove the parent and then you can make your own CD feature with your choice of the types

2022-01-11 22:45 UTC, NickVendel commented on core/dungeon-masters-guide/classes/class-oathbreaker.xml
> +	<element name="Channel Divinity Feature Replacement" type="Grants" source="Internal" id="ID_INTERNAL_FEATURE_REPLACEMENT_PALADIN_OATHBREAKER_CHANNEL_DIVINITY" />
yes, i don't have issues with that, i'm saying shouldn't we specify names, like "Oathbreaker Channel Divinity", etc.

2022-01-11 22:46 UTC, NickVendel commented on core/players-handbook/classes/class-paladin.xml
> +		<requirements>!ID_KBP_DMBD_CLASS_FEATURE_ANTIPALADIN_UNHOLY_SMITE, !ID_INTERNAL_FEATURE_REPLACEMENT_PALADIN_DIVINE_SMITE</requirements>
no, we're literally stuck with that ID, since it's a support for third-party...

2022-01-12 03:22 UTC, kgirtxd commented on core/players-handbook/classes/class-rogue.xml
> +		<requirements>!ID_INTERNAL_FEATURE_REPLACEMENT_ROGUE_ROGUISHARCHETYPE</requirements>
The other classes were done but most dont have the word "archetype" in the feature name

2022-01-12 03:23 UTC, kgirtxd commented on core/players-handbook/classes/class-paladin.xml
> +		<requirements>!ID_KBP_DMBD_CLASS_FEATURE_ANTIPALADIN_UNHOLY_SMITE, !ID_INTERNAL_FEATURE_REPLACEMENT_PALADIN_DIVINE_SMITE</requirements>
Leaving to maintain support for the old third-party archive.  May remove in the future

2022-01-12 03:58 UTC, NickVendel approved these changes

2022-01-12 04:03 UTC, merged