[PHB] Typo Fixes
AuroraLegacy/elements pull request #108
Opened 2021-11-11 20:59 UTC by sammy6345

Typo fixes for Criminal and Urban Bounty Hunter backgrounds and in the Asleep spell description.

2021-11-11 21:03 UTC, NickVendel commented on core/players-handbook/spells.xml
> +		<update version="0.4.10">
we usually change it like this, when going from 9 to 10
```suggestion
		<update version="0.5.0">
```

2021-11-11 21:08 UTC, NickVendel commented
Also change title to `[MISC]`, since you make updates to multiple sources (PHB and SCAG)

2021-11-11 21:14 UTC, sammy6345 commented
Ok, will do those next time. Thanks for the feedback.

2021-11-11 21:50 UTC, kgirtxd requested changes
Once you commit Nick's suggestion Id say this pull is ready for merge

2021-11-12 13:38 UTC, kgirtxd approved these changes

2021-11-12 13:40 UTC, NickVendel approved these changes

2021-11-12 13:41 UTC, AngryGuineaPig approved these changes

2021-11-12 13:46 UTC, merged