[UA] 20220425: Heroes of Krynn Revisited
AuroraLegacy/elements pull request #139
Opened 2022-05-03 13:31 UTC by NickVendel

Additionally includes fixes for previous UA, details are in the 8e55913094254f6b6dd2c564ca6ad0da5981a53a commit.

2022-05-11 23:54 UTC, kgirtxd requested changes

2022-05-11 23:54 UTC, kgirtxd commented on unearthed-arcana/2022/20220425.xml
> +			Whenever you finish a long rest, you can replace the maneuver you learned from this feat with the other maneuver offered by it.</description>
```suggestion
			<description>If the maneuver requires a saving throw, the save DC is {{ua:squire of solamnia:dc}}.&#13;
			Whenever you finish a long rest, you can replace the maneuvers you learned from these feats with the other maneuvers offered by it.</description>
```

2022-05-12 00:19 UTC, kgirtxd approved these changes

2022-05-16 15:29 UTC, Azzzzzy approved these changes

2022-05-16 15:35 UTC, merged