[CoS] Sunsword Missing Bonus and Info
AuroraLegacy/elements pull request #145
Opened 2022-05-12 03:05 UTC by mamawerecat

resolves #126

2022-05-16 15:41 UTC, Azzzzzy approved these changes

2022-05-18 01:17 UTC, kgirtxd requested changes

2022-05-18 01:17 UTC, kgirtxd commented on supplements/curse-of-strahd/items.xml
> +			<p class="indent"><strong><em>Versatile.</em></strong> This weapon can be used with one or two hands. A damage value in parentheses appears with the property—the damage when the weapon is used wit
```suggestion
			<p class="indent"><strong><em>Versatile (1d10).</em></strong> This weapon can be used with one or two hands. A damage value in parentheses appears with the property—the damage when the weapon is used with two hands to make a melee attack.</p>
```
References the versatile damage but it is not shown anywhere

2022-05-18 02:58 UTC, kgirtxd approved these changes

2022-05-24 16:01 UTC, merged