[VRGtR] The Undead Warlock, Subclass level indicators
AuroraLegacy/elements pull request #155
Opened 2022-06-02 18:28 UTC by Zencha70

Changed subclass text info to include the required level milestones & updated file version

2022-06-02 18:29 UTC, NickVendel commented on supplements/van-richtens-guide-to-ravenloft/warlock-undead.xml
> +<?xml version="1.1" encoding="utf-8" ?>
wrong version

2022-06-02 18:31 UTC, NickVendel commented
also just in general, that's not how it was done in the book

2022-07-13 20:18 UTC, NickVendel requested changes

2022-07-13 20:18 UTC, NickVendel commented on supplements/van-richtens-guide-to-ravenloft/warlock-undead.xml
> +			<p>At 1st level, the Undead lets you choose from an expanded list of spells when you learn a warlock spell. The following spells are added to the warlock spell list for you.</p>
```suggestion
			<p><em>1st-level Undead feature</em></p>
			<p>The Undead lets you choose from an expanded list of spells when you learn a warlock spell. The following spells are added to the warlock spell list for you.</p>
```

2022-07-13 20:18 UTC, NickVendel commented on supplements/van-richtens-guide-to-ravenloft/warlock-undead.xml
> +			<p>At 1st level, you manifest an aspect of your patron’s dreadful power. As a bonus action, you transform for 1 minute. You gain the following benefits while transformed:</p>
```suggestion
			<p><em>1st-level Undead feature</em></p>
			<p>You manifest an aspect of your patron’s dreadful power. As a bonus action, you transform for 1 minute. You gain the following benefits while transformed:</p>
```

2022-07-13 20:18 UTC, NickVendel commented on supplements/van-richtens-guide-to-ravenloft/warlock-undead.xml
> +			<p>At 6th level, your patron’s powers have a profound effect on your body and magic. You don’t need to eat, drink, or breathe.</p>
```suggestion
			<p><em>6th-level Undead feature</em></p>
			<p>Your patron’s powers have a profound effect on your body and magic. You don’t need to eat, drink, or breathe.</p>
```

2022-07-13 20:18 UTC, NickVendel commented on supplements/van-richtens-guide-to-ravenloft/warlock-undead.xml
> +			<p>At 10th level, your connection to undeath and necrotic energy now saturates your body. You have resistance to necrotic damage. If you are transformed using your Form of Dread, you instead becom
```suggestion
			<p><em>10th-level Undead feature</em></p>
			<p>Your connection to undeath and necrotic energy now saturates your body. You have resistance to necrotic damage. If you are transformed using your Form of Dread, you instead become immune to necrotic damage.</p>
```

2022-07-13 20:18 UTC, NickVendel commented on supplements/van-richtens-guide-to-ravenloft/warlock-undead.xml
> +			<p>At 14th level, your spirit can become untethered from your physical form. As an action, you can project your spirit from your body. The body you leave behind is unconscious and in a state of su
```suggestion
			<p><em>14th-level Undead feature</em></p>
			<p>Your spirit can become untethered from your physical form. As an action, you can project your spirit from your body. The body you leave behind is unconscious and in a state of suspended animation.</p>
```

2022-08-31 18:04 UTC, Zencha70 reviewed
Looks better and more complete than how I did it, and still quite new at this, so got nothing to add ^^

2022-08-31 18:17 UTC, NickVendel approved these changes

2022-09-02 17:25 UTC, Azzzzzy approved these changes

2022-09-03 19:46 UTC, merged