[UA] 20220523: Giant Options
AuroraLegacy/elements pull request #156
Opened 2022-06-03 22:36 UTC by NickVendel

2022-06-09 20:22 UTC, Azzzzzy approved these changes

2022-06-12 18:00 UTC, kgirtxd approved these changes

2022-06-12 18:08 UTC, AngryGuineaPig requested changes

2022-06-12 18:08 UTC, AngryGuineaPig commented on unearthed-arcana/2022/20220523.xml
> +			<grant type="Language" id="ID_LANGUAGE_GIANT" />
"you learn to speak, read, and write Giant or one other language of your choice if you already know Giant" 
From what i can see this line doesn't allow that to happen, it does the first bit fine but doesn't let you choose another if you already know giant.

2022-06-12 22:40 UTC, kgirtxd approved these changes

2022-06-12 22:58 UTC, merged