[TCOE] Artificer Infusion Item Rarity
AuroraLegacy/elements pull request #167
Opened 2022-07-16 02:20 UTC by ErrantFamiliar

Recommending changes for Arcane Propulsion Armor, and Armor of Magical Strength, so they aren't listed improperly as common.

2022-07-16 02:22 UTC, kgirtxd requested changes
File version need to be incremented

2022-07-16 02:46 UTC, kgirtxd approved these changes

2022-07-24 14:46 UTC, AngryGuineaPig approved these changes

2022-08-23 12:14 UTC, NickVendel commented
I in general not sure what label should be used to describe these items, since in general they're only available to the specific subclass and were done for people who want it as an Armor.

2022-08-23 12:16 UTC, NickVendel approved these changes

2022-08-24 22:48 UTC, merged