[TCOE] Symbiotic Entity damage type fix
AuroraLegacy/elements pull request #183
Opened 2022-09-27 13:41 UTC by tm992

Corrected damage type of symbiotic entity extra damage on melee attacks to Necrotic.

2022-09-27 13:42 UTC, kgirtxd requested changes
Increment file version

2023-12-14 18:50 UTC, MeriadarGoblin approved these changes

2023-12-14 18:51 UTC, kgirtxd approved these changes

2024-03-24 19:41 UTC, FreshRoyal approved these changes

2024-03-25 10:23 UTC, NickVendel approved these changes

2024-03-25 14:25 UTC, merged