[DSDQ] Dragonlance: Shadow of the Dragon Queen + Fixes
AuroraLegacy/elements pull request #187
Opened 2022-12-16 00:01 UTC by NickVendel

details are in the first commit.

2022-12-18 01:51 UTC, kgirtxd requested changes

2022-12-18 01:51 UTC, kgirtxd commented on supplements/dragonlance-shadow-of-the-dragon-queen/items.xml
> +			<file name="items.xml" url="https://raw.githubusercontent.com/AuroraLegacy/elements/master/supplements/journeys-through-the-radiant-citadel/items.xml" />
Wrong source URL

2022-12-18 01:53 UTC, NickVendel commented on supplements/dragonlance-shadow-of-the-dragon-queen/race-kender.xml
> +		</sheet>
that part must stay, because it's only used if you succeed, if you don't you don't waste a use, so it's not "1/Long Rest".

2022-12-18 01:54 UTC, kgirtxd commented on supplements/dragonlance-shadow-of-the-dragon-queen/race-kender.xml
> +		</sheet>
I dont think there is a way for you to fail to use this feature

2022-12-18 01:59 UTC, kgirtxd commented on supplements/dragonlance-shadow-of-the-dragon-queen/race-kender.xml
> +		</sheet>
Go ahead and keep it as is so that the first part is not confusing

2022-12-18 03:01 UTC, kgirtxd approved these changes

2022-12-19 11:49 UTC, AngryGuineaPig approved these changes

2022-12-19 18:07 UTC, merged