[UA] Love Domain Cleric
AuroraLegacy/elements pull request #198
Opened 2023-02-28 08:32 UTC by FreshRoyal

Original iteration of the Unity Domain that was leaked.

2023-08-30 08:45 UTC, AngryGuineaPig commented on unearthed-arcana/2020/20200206.xml
> +		<sheet action="Action">
```suggestion
		<sheet action="Action" usage="1/Long Rest">
```

2023-09-30 16:49 UTC, AngryGuineaPig commented
The URL in the Source needs to be changed to
https://web.archive.org/web/20200204140440/https://media.wizards.com/2020/dnd/downloads/UA2020-Subclasses02.pdf

2023-09-30 16:55 UTC, FreshRoyal commented
> The URL in the Source needs to be changed to https://web.archive.org/web/20200204140440/https://media.wizards.com/2020/dnd/downloads/UA2020-Subclasses02.pdf

Done

2023-09-30 16:56 UTC, AngryGuineaPig approved these changes

2023-10-01 04:15 UTC, NickVendel requested changes

2023-10-01 04:15 UTC, NickVendel commented on unearthed-arcana/2020/20200206.xml
> +			<description>While either creature chosen for your Emboldening Bond feature is within 30 feet of the other, the creature can use its reaction to grant resistance to all damage to the other creatur
```suggestion
			<description>While either creature chosen for your Emboldening Bond feature is within 30 feet of the other, the creature can use its reaction to grant resistance to all damage to the other creature when that other creature takes damage. This resistance lasts until the end of the current turn.</description>
			<description level="17">While creatures chosen for your Emboldening Bond feature are on the same plane of existence, either creature can use its reaction to grant resistance to all damage to the other creature when that other creature takes damage. This resistance lasts until the end of the current turn.</description>
```

2023-10-01 04:15 UTC, NickVendel commented on unearthed-arcana/2020/20200206.xml
> +			• As an action, the creature can touch their bonded partner to expend and roll any number of Hit Dice. Their bonded partner regains a number of hp equal to the total rolled.</description>
```suggestion
			<description>When a creature chosen for your Emboldening Bond is reduced to 0 hp, their bonded partner gains the following benefits for 1 minute, or until the creature regains at least 1 hp: &#13;
			• The creature has advantage on attack rolls, ability checks, and saving throws &#13;
			• The creature gains resistance to all damage &#13;
			• As an action, the creature can touch their bonded partner to expend and roll any number of Hit Dice. Their bonded partner regains a number of hit points equal to the total rolled.</description>
```

2023-10-01 04:15 UTC, NickVendel commented on unearthed-arcana/2020/20200206.xml
>  </elements>
```suggestion
</elements>

```

2023-12-14 18:21 UTC, MeriadarGoblin approved these changes

2023-12-27 00:44 UTC, NickVendel approved these changes

2024-03-06 19:06 UTC, merged