Custom Lineage
AuroraLegacy/elements pull request #20
Opened 2020-12-11 21:46 UTC by kgirtxd

Mostly Complete Starting file for custom lineage.

2020-12-17 20:36 UTC, AngryGuineaPig approved these changes

2020-12-18 07:27 UTC, Azzzzzy requested changes

2020-12-18 07:27 UTC, Azzzzzy commented on core/players-handbook/races/race-halfling.xml
> +			<select type="Ability Score Improvement" name="Custom Ability Score Improvement +2 (Halfling)" supports="Custom Ability Score Increase 2" requirements="ID_WOTC_TCOE_OPTION_CUSTOMIZED_ASI" />
Tab vs Space, I think the entire Halfling File might need to be reformatted.

2020-12-18 07:27 UTC, Azzzzzy commented on core/players-handbook/races/race-human.xml
> +			<select type="Language" name="Customized Language" supports="Custom Race Language" requirements="ID_WOTC_TCOE_OPTION_CUSTOMIZED_LANGUAGE" />
Tab vs Space again.

2020-12-18 07:27 UTC, Azzzzzy commented on supplements/extra-life/locathah-rising.xml
> +			<select type="Ability Score Improvement" name="Custom Ability Score Improvement +1 (Locathah)" supports="Custom Ability Score Increase 1" requirements="ID_WOTC_TCOE_OPTION_CUSTOMIZED_ASI" />
Tab vs Space.

2020-12-18 07:27 UTC, Azzzzzy commented on supplements/mordenkainens-tome-of-foes/races/subrace-shadarkai.xml
> +			<select type="Ability Score Improvement" name="Custom Ability Score Improvement +1 (Shadar-Kai)" supports="Custom Ability Score Increase 1" requirements="ID_WOTC_TCOE_OPTION_CUSTOMIZED_ASI" />
Space vs Tab.

2020-12-18 07:27 UTC, Azzzzzy commented on supplements/tomb-of-annihilation/races/race-tortle.xml
> +			<select type="Language" name="Customized Language" supports="Custom Race Language||Tortle Language" number="2" requirements="ID_WOTC_TCOE_OPTION_CUSTOMIZED_LANGUAGE" />
Tab vs Space.

2020-12-18 07:27 UTC, Azzzzzy commented on unearthed-arcana/planeshift/amonkhet/race-khenra.xml
> +			<select type="Ability Score Improvement" name="Custom Ability Score Improvement +2 (Khenra)" supports="Custom Ability Score Increase 2" requirements="ID_WOTC_TCOE_OPTION_CUSTOMIZED_ASI" />
Space vs Tab.

2020-12-18 07:27 UTC, Azzzzzy commented on unearthed-arcana/planeshift/dominaria/race-keldon-human.xml
> +			<select type="Ability Score Improvement" name="Custom Ability Score Improvement +2 (Keldon Human)" supports="Custom Ability Score Increase 2" requirements="ID_WOTC_TCOE_OPTION_CUSTOMIZED_ASI" />
Space vs Tab.

2020-12-18 07:27 UTC, Azzzzzy commented on unearthed-arcana/planeshift/innistrad/race-human-innistrad.xml
> +			<select type="Ability Score Improvement" name="Custom Ability Score Improvement +1 (Kessig Human)" number="2" supports="Custom Ability Score Increase 1" requirements="ID_WOTC_TCOE_OPTION_CUSTOMIZE
Space vs Tab.

2020-12-18 07:27 UTC, Azzzzzy commented on unearthed-arcana/planeshift/ixalan/race-siren.xml
> +			<select type="Ability Score Improvement" name="Custom Ability Score Improvement +2 (Siren)" supports="Custom Ability Score Increase 2" requirements="ID_WOTC_TCOE_OPTION_CUSTOMIZED_ASI" />
Tab vs Space.

2020-12-18 07:27 UTC, Azzzzzy commented on unearthed-arcana/planeshift/ixalan/subrace-merfolk.xml
> +			<select type="Ability Score Improvement" name="Custom Ability Score Improvement +2 (Merfolk (Green))" supports="Custom Ability Score Increase 2" requirements="ID_WOTC_TCOE_OPTION_CUSTOMIZED_ASI" /
Tab vs Space.

2020-12-18 07:27 UTC, Azzzzzy commented on unearthed-arcana/planeshift/kaladesh/race-aetherborn.xml
> +			<select type="Ability Score Improvement" name="Custom Ability Score Improvement +1 (Aetherborn)" number="2" supports="Custom Ability Score Increase 1" requirements="ID_WOTC_TCOE_OPTION_CUSTOMIZED_
Tab vs Space.

2020-12-18 07:27 UTC, Azzzzzy commented on unearthed-arcana/planeshift/kaladesh/race-vedalken.xml
> +			<select type="Ability Score Improvement" name="Custom Ability Score Improvement +1 (Vedalken)" supports="Custom Ability Score Increase 1" requirements="ID_WOTC_TCOE_OPTION_CUSTOMIZED_ASI" />
Tab vs Space.

2020-12-18 07:27 UTC, Azzzzzy commented on unearthed-arcana/planeshift/zendikar/race-kor.xml
> +			<select type="Ability Score Improvement" name="Custom Ability Score Improvement +1 (Kor)" supports="Custom Ability Score Increase 1" requirements="ID_WOTC_TCOE_OPTION_CUSTOMIZED_ASI" />
Tab vs Space.

2020-12-18 07:27 UTC, Azzzzzy commented on unearthed-arcana/planeshift/zendikar/race-merfolk.xml
> +			<select type="Ability Score Improvement" name="Custom Ability Score Improvement +1 (Merfolk)" supports="Custom Ability Score Increase 1" requirements="ID_WOTC_TCOE_OPTION_CUSTOMIZED_ASI" />
Tab vs Space.

2020-12-18 07:27 UTC, Azzzzzy commented on unearthed-arcana/planeshift/zendikar/race-vampire.xml
> +			<select type="Ability Score Improvement" name="Custom Ability Score Improvement +2 (Vampire)" supports="Custom Ability Score Increase 2" requirements="ID_WOTC_TCOE_OPTION_CUSTOMIZED_ASI" />
Tab vs Space.

2020-12-18 23:56 UTC, Azzzzzy approved these changes

2020-12-19 13:31 UTC, JayPea00101010 approved these changes

2020-12-19 23:26 UTC, NickVendel requested changes

2020-12-19 23:26 UTC, NickVendel commented on unearthed-arcana/planeshift/ixalan/subrace-merfolk.xml
> +			<grant type="Proficiency" id="ID_PROFICIENCY_SKILL_NATURE" />
No select for these Skills

2020-12-19 23:26 UTC, NickVendel commented on unearthed-arcana/planeshift/kaladesh/race-aetherborn.xml
> +			<stat name="innate speed" value="30" bonus="base" />
could you move line 43 to line 46? Just because it looks weird in the middle of ASI

2020-12-19 23:26 UTC, NickVendel commented on unearthed-arcana/planeshift/kaladesh/race-aetherborn.xml
> +	</element> -->
i'm guessing it's more of a question for @Azzzzzy, but what's the point in this comment?

2020-12-19 23:26 UTC, NickVendel commented on unearthed-arcana/planeshift/kaladesh/race-vedalken.xml
> +	</append>
> again, language is in the file below, so using append is pointless

same goes here.

2020-12-19 23:26 UTC, NickVendel commented on unearthed-arcana/planeshift/zendikar/race-kor.xml
> +	</append>
> again, language is in the file below, so using append is pointless

same goes here.

2020-12-19 23:26 UTC, NickVendel commented on unearthed-arcana/planeshift/zendikar/race-merfolk.xml
> +	</append>
> again, language is in the file below, so using append is pointless

same goes here.

2020-12-19 23:26 UTC, NickVendel commented on unearthed-arcana/planeshift/zendikar/race-vampire.xml
> +	</append>
> again, language is in the file below, so using append is pointless

same goes here.

2020-12-20 01:32 UTC, kgirtxd commented on supplements/guildmasters-guide-to-ravnica/races/simic-hybrid.xml
> +			<select type="Ability Score Improvement" name="Ability Score Increase (Simic Hybrid)" supports="ID_PHB_FEAT_ASI_STRENGTH|ID_PHB_FEAT_ASI_DEXTERITY|ID_PHB_FEAT_ASI_INTELLIGENCE|ID_PHB_FEAT_ASI_WISD
Agreed, we may want to look into changing that in the future.

2020-12-20 04:26 UTC, NickVendel commented on supplements/guildmasters-guide-to-ravnica/races/simic-hybrid.xml
> +    <append id="ID_GGTR_LANGUAGE_VEDALKEN">
didn't actually fix it

2020-12-20 04:27 UTC, NickVendel commented on supplements/guildmasters-guide-to-ravnica/races/vedalken.xml
>      <element name="Vedalken Dispassion" type="Racial Trait" source="Guildmasters’ Guide to Ravnica" id="ID_WOTC_GGTR_RACIAL_TRAIT_VEDALKEN_VEDALKEN_DISPASSION">
same thing here

2020-12-20 15:27 UTC, kgirtxd commented on supplements/guildmasters-guide-to-ravnica/races/simic-hybrid.xml
> +    <append id="ID_GGTR_LANGUAGE_VEDALKEN">
Found the spaces

2020-12-20 15:27 UTC, kgirtxd commented on supplements/guildmasters-guide-to-ravnica/races/vedalken.xml
>      <element name="Vedalken Dispassion" type="Racial Trait" source="Guildmasters’ Guide to Ravnica" id="ID_WOTC_GGTR_RACIAL_TRAIT_VEDALKEN_VEDALKEN_DISPASSION">
found the spaces

2020-12-20 15:48 UTC, NickVendel approved these changes

2020-12-20 16:02 UTC, merged