[MISC] Artificer Infusion Update
AuroraLegacy/elements pull request #26
Opened 2020-12-21 02:50 UTC by Azzzzzy

Split the Artificer Infusions into their own supplements
Added Missing TCOE Infusions
Slight Renaming to Spellwrought Tattoo to fit new naming Scheme

2020-12-21 22:44 UTC, kgirtxd commented on supplements/waterdeep-dungeon-of-the-mad-mage.index
> +        <file name="replicate-infusions.xml" url="https://raw.githubusercontent.com/AuroraLegacy/elements/master/supplements/waterdeep-dungeon-of-the-mad-mage/replicate-infusions.xml" />
Forgot to increment version number

2020-12-21 23:27 UTC, kgirtxd requested changes

2020-12-21 23:27 UTC, kgirtxd commented on supplements/tashas-cauldron-of-everything/replicate-infusions.xml
> +			<p>The armor regains ld6 expended charges daily at dawn.</p>
1d6 not ld6

2020-12-21 23:27 UTC, kgirtxd commented on supplements/tashas-cauldron-of-everything/replicate-infusions.xml
> +			<p>The armor regains ld6 expended charges daily at dawn.</p>
1d6 again

2020-12-21 23:27 UTC, kgirtxd commented on supplements/tashas-cauldron-of-everything/replicate-infusions.xml
> +			<p>The infused item can send a jolt to the wearer to refocus their mind. The item has 4 charges. When the wearer fails a Constitution saving throw to maintain concentration on a spell, the wearer
1d4

2020-12-21 23:27 UTC, kgirtxd commented on supplements/tashas-cauldron-of-everything/replicate-infusions.xml
> +			<p>The infused item can send a jolt to the wearer to refocus their mind. The item has 4 charges. When the wearer fails a Constitution saving throw to maintain concentration on a spell, the wearer
1d4 again

2020-12-21 23:27 UTC, kgirtxd commented on supplements/tashas-cauldron-of-everything/replicate-infusions.xml
> +			<li>The armor includes gauntlets, each of which is a magic melee weapon that can be wielded only when the hand is holding nothing. The wearer is proficient with the gauntlets, and each one deals l
1d8 not ld8

2020-12-21 23:27 UTC, kgirtxd commented on supplements/tashas-cauldron-of-everything/replicate-infusions.xml
> +			<li>The armor includes gauntlets, each of which is a magic melee weapon that can be wielded only when the hand is holding nothing. The wearer is proficient with the gauntlets, and each one deals l
1d8 again

2020-12-30 16:01 UTC, kgirtxd requested changes
Change IDs in the TCoE infusions from ERLW to TCOE.  They are not currently in the builder so it should not break anything.  I think we should leave the rest of the IDs as they are.

2021-01-01 00:18 UTC, kgirtxd approved these changes

2021-01-06 18:01 UTC, AngryGuineaPig approved these changes

2021-01-06 19:36 UTC, NickVendel requested changes

2021-01-10 20:06 UTC, NickVendel approved these changes

2021-01-10 20:25 UTC, merged