[DSDQ] Added languages
AuroraLegacy/elements pull request #268
Opened 2024-09-04 06:44 UTC by FreshRoyal

2026-03-25 16:52 UTC, NickVendel requested changes

2026-03-25 16:52 UTC, NickVendel commented on supplements/dragonlance-shadow-of-the-dragon-queen/languages.xml
> +
```suggestion
```

2026-03-25 16:52 UTC, NickVendel commented on supplements/dragonlance-shadow-of-the-dragon-queen/languages.xml
> +		<description />
```suggestion
```

2026-03-25 16:52 UTC, NickVendel commented on supplements/dragonlance-shadow-of-the-dragon-queen/languages.xml
> +		<description />
```suggestion
```

2026-03-25 16:52 UTC, NickVendel commented on supplements/dragonlance-shadow-of-the-dragon-queen/languages.xml
> +		<description />
```suggestion
```

2026-03-25 16:52 UTC, NickVendel commented on supplements/dragonlance-shadow-of-the-dragon-queen/languages.xml
> +		<description />
```suggestion
```

2026-03-25 16:52 UTC, NickVendel commented on supplements/dragonlance-shadow-of-the-dragon-queen/languages.xml
> +		<description />
```suggestion
```

2026-03-25 16:52 UTC, NickVendel commented on supplements/dragonlance-shadow-of-the-dragon-queen/languages.xml
> +		<description />
```suggestion
```

2026-03-25 16:52 UTC, NickVendel commented on supplements/dragonlance-shadow-of-the-dragon-queen/languages.xml
> +		<description />
```suggestion
```

2026-03-25 16:52 UTC, NickVendel commented on supplements/dragonlance-shadow-of-the-dragon-queen/languages.xml
> +
```suggestion
```

2026-03-25 16:52 UTC, NickVendel commented on supplements/dragonlance-shadow-of-the-dragon-queen/languages.xml
> +		<description />
```suggestion
```

2026-03-25 16:52 UTC, NickVendel commented on supplements/dragonlance-shadow-of-the-dragon-queen/languages.xml
> +		<description />
```suggestion
```

2026-03-25 16:52 UTC, NickVendel commented on supplements/dragonlance-shadow-of-the-dragon-queen/languages.xml
> +		<description />
```suggestion
```

2026-03-25 16:52 UTC, NickVendel commented on supplements/dragonlance-shadow-of-the-dragon-queen/languages.xml
> +		<description />
```suggestion
```

2026-04-16 20:29 UTC, NickVendel approved these changes

2026-04-17 22:18 UTC, Tel0k approved these changes

2026-04-22 14:56 UTC, merged