[PHB24] Items, proficiencies, properties, languages and alignments
AuroraLegacy/elements pull request #275
Opened 2024-09-16 14:28 UTC by Tel0k

2024-11-20 15:10 UTC, tregolani requested changes
Noticed a few missing "2024" notations in proficiencies-all.xml. 

Also, should we keep vehicle proficiencies? They seem to have been removed from the PHB24.

2024-11-20 15:10 UTC, tregolani commented on core/players-handbook-2024/misc/proficiencies-all.xml
> +	<element name="Tool Proficiency (Gaming set)" type="Proficiency" source="Player’s Handbook"  id="ID_WOTC_PHB24_PROFICIENCY_GAMING_SET_PROFICIENCY_GAMING_SET">
```suggestion
	<element name="Tool Proficiency (Gaming set)" type="Proficiency" source="Player’s Handbook 2024"  id="ID_WOTC_PHB24_PROFICIENCY_GAMING_SET_PROFICIENCY_GAMING_SET">
```

2024-11-20 15:10 UTC, tregolani commented on core/players-handbook-2024/misc/proficiencies-all.xml
> +	<element name="Tool Proficiency (Dice set)" type="Proficiency" source="Player’s Handbook"  id="ID_WOTC_PHB24_PROFICIENCY_GAMING_SET_PROFICIENCY_DICE_SET">
```suggestion
	<element name="Tool Proficiency (Dice set)" type="Proficiency" source="Player’s Handbook 2024"  id="ID_WOTC_PHB24_PROFICIENCY_GAMING_SET_PROFICIENCY_DICE_SET">
```

2024-11-20 15:10 UTC, tregolani commented on core/players-handbook-2024/misc/proficiencies-all.xml
> +	<element name="Tool Proficiency (Dragonchess set)" type="Proficiency" source="Player’s Handbook"  id="ID_WOTC_PHB24_PROFICIENCY_GAMING_SET_PROFICIENCY_DRAGONCHESS_SET">
```suggestion
	<element name="Tool Proficiency (Dragonchess set)" type="Proficiency" source="Player’s Handbook 2024"  id="ID_WOTC_PHB24_PROFICIENCY_GAMING_SET_PROFICIENCY_DRAGONCHESS_SET">
```

2024-11-20 15:10 UTC, tregolani commented on core/players-handbook-2024/misc/proficiencies-all.xml
> +	<element name="Tool Proficiency (Playing card set)" type="Proficiency" source="Player’s Handbook"  id="ID_WOTC_PHB24_PROFICIENCY_GAMING_SET_PROFICIENCY_PLAYING_CARD_SET">
```suggestion
	<element name="Tool Proficiency (Playing card set)" type="Proficiency" source="Player’s Handbook 2024"  id="ID_WOTC_PHB24_PROFICIENCY_GAMING_SET_PROFICIENCY_PLAYING_CARD_SET">
```

2024-11-20 15:10 UTC, tregolani commented on core/players-handbook-2024/misc/proficiencies-all.xml
> +	<element name="Tool Proficiency (Three-Dragon Ante set)" type="Proficiency" source="Player’s Handbook"  id="ID_WOTC_PHB24_PROFICIENCY_GAMING_SET_PROFICIENCY_THREE_DRAGON_ANTE_SET">
```suggestion
	<element name="Tool Proficiency (Three-Dragon Ante set)" type="Proficiency" source="Player’s Handbook 2024"  id="ID_WOTC_PHB24_PROFICIENCY_GAMING_SET_PROFICIENCY_THREE_DRAGON_ANTE_SET">
```

2024-11-20 15:10 UTC, tregolani commented on core/players-handbook-2024/misc/proficiencies-all.xml
> +
I've noticed these aren't actually in the PHB24 book anywhere. It seems they removed vehicle proficiencies with the version update?

2024-11-20 15:17 UTC, Tel0k commented on core/players-handbook-2024/misc/proficiencies-all.xml
> +
pages 229 and 230 of PHB24, those have actually been added to the new PHB while in the previous edition they were part of DMG

2024-12-03 04:29 UTC, tregolani reviewed
just some typos found in my latest testing sessions.

2024-12-03 04:29 UTC, tregolani commented on core/players-handbook-2024/items/items-gear.xml
> +			<p>As a Utilize action, you can spill Ball Bearings from their pouch. They spread to cover a level, 10-footsquare area within 10 feet of yourself. A creature that enters this area for the first ti
```suggestion
			<p>As a Utilize action, you can spill Ball Bearings from their pouch. They spread to cover a level, 10-foot square area within 10 feet of yourself. A creature that enters this area for the first time on a turn must succeed on a DC 10 Dexterity saving throw or have the Prone condition. It takes 10 minutes to recover the Ball Bearings.</p>
```

2024-12-03 04:29 UTC, tregolani commented on core/players-handbook-2024/items/items-gear.xml
> +			<p class="indent">Each set o' Manacles comes with a key. Without the key, a creature can use Thieves' Tools to pick the Manacles' lock with a successful DC 15 Dexterity (Sleight of Hand) check.</p
```suggestion
			<p>As a Utilize action, you can use Manacles to bind an unwilling Small or Medium creature within 5 feet of yourself that has the Grappled, Incapacitated, or Restrained condition if you succeed on a DC 13 Dexterity (Sleight of Hand) check. While bound, a creature has Disadvantage on attack rolls, and the creature is Restrained if the Manacles are attached to a chain or hook that is fixed in place. Escaping the Manacles requires a successful DC 20 Dexterity (Sleight of Hand) check as an action. Bursting them requires a successful DC 25 Strength (Athletics) check as an action.</p>
			<p class="indent">Each set of Manacles comes with a key. Without the key, a creature can use Thieves' Tools to pick the Manacles' lock with a successful DC 15 Dexterity (Sleight of Hand) check.</p>
```

2024-12-03 04:29 UTC, tregolani commented on core/players-handbook-2024/items/items-gear.xml
> +			<p class="indent"><b><i>Fuel.</i></b> Oil ser 'ns as fuel for Lamps and Lanterns. Once lit, a flask cf Oil burns for 6 hours in a Lamp or Lantern. That duration doesn't need to be consecutive; you
```suggestion
			<p class="indent"><b><i>Dousing a Space.</i></b> You can take the Utilize action to pour an Oil flask on level ground to cover a 5-foot square area within 5 feet of yourself. If lit, the oil burns until the end of the turn 2 rounds from when the oil was lit (or 12 seconds) and deals 5 Fire damage to any creature that enters the area or ends its turn there. A creature can take this damage only once per turn.</p>
			<p class="indent"><b><i>Fuel.</i></b> Oil serves as fuel for Lamps and Lanterns. Once lit, a flask of Oil burns for 6 hours in a Lamp or Lantern. That duration doesn't need to be consecutive; you can extinguish the burning Oil (as a Utilize action) and rekindle it again until it has burned for a total of 6 hours.</p>
```

2024-12-03 04:29 UTC, tregolani commented on core/players-handbook-2024/items/items-gear.xml
> +			<p>Rations consist of travel-ready food, includingjerky, dried fruit, hardtack, and nuts. See “Malnutrition” in the rules glossary for the risks of not eating.</p>
```suggestion
			<p>Rations consist of travel-ready food, including jerky, dried fruit, hardtack, and nuts. See “Malnutrition” in the rules glossary for the risks of not eating.</p>
```

2024-12-03 04:29 UTC, tregolani commented on core/players-handbook-2024/items/items-gear.xml
> +			<p>A Spell Scroll (Cantrip) or Spell Scroll (Level 1) is a magic item that bears the words of a cantrip or level 1 spell, respectively, determined by the scroll's reator. If the spell is on your c
```suggestion
			<p>A Spell Scroll (Cantrip) or Spell Scroll (Level 1) is a magic item that bears the words of a cantrip or level 1 spell, respectively, determined by the scroll's creator. If the spell is on your class's spell list, you can read the scroll and cast the spell using its normal casting time and without providing any Material components.</p>
```

2024-12-03 04:29 UTC, tregolani commented on core/players-handbook-2024/items/items-gear.xml
> +			<p>A Spell Scroll (Cantrip) or Spell Scroll (Level 1) is a magic item that bears the words of a cantrip or level 1 spell, respectively, determined by the scroll's reator. If the spell is on your c
```suggestion
			<p>A Spell Scroll (Cantrip) or Spell Scroll (Level 1) is a magic item that bears the words of a cantrip or level 1 spell, respectively, determined by the scroll's creator. If the spell is on your class's spell list, you can read the scroll and cast the spell using its normal casting time and without providing any Material components.</p>
```

2024-12-03 04:29 UTC, tregolani commented on core/players-handbook-2024/items/items-tools.xml
> +				<tr><td><b>Utilize:</b> Discern whether someone is cheating (DC 10), orwin the game (DC 20)</td></tr>
```suggestion
				<tr><td><b>Utilize:</b> Discern whether someone is cheating (DC 10), or win the game (DC 20)</td></tr>
```

2024-12-03 04:29 UTC, tregolani commented on core/players-handbook-2024/items/items-tools.xml
> +				<tr><td><b>Utilize:</b> Discern whether someone is cheating (DC 10), orwin the game (DC 20)</td></tr>
```suggestion
				<tr><td><b>Utilize:</b> Discern whether someone is cheating (DC 10), or win the game (DC 20)</td></tr>
```

2024-12-03 04:29 UTC, tregolani commented on core/players-handbook-2024/items/items-tools.xml
> +				<tr><td><b>Utilize:</b> Discern whether someone is cheating (DC 10), orwin the game (DC 20)</td></tr>
```suggestion
				<tr><td><b>Utilize:</b> Discern whether someone is cheating (DC 10), or win the game (DC 20)</td></tr>
```

2024-12-03 04:29 UTC, tregolani commented on core/players-handbook-2024/items/items-tools.xml
> +				<tr><td><b>Utilize:</b> Discern whether someone is cheating (DC 10), orwin the game (DC 20)</td></tr>
```suggestion
				<tr><td><b>Utilize:</b> Discern whether someone is cheating (DC 10), or win the game (DC 20)</td></tr>
```

2024-12-03 04:29 UTC, tregolani commented on core/players-handbook-2024/misc/proficiencies-all.xml
> +			<p>Of all the armor categories, heavy armor offers the best protection. These suits of armor cover the entire body and are designed to stop a wide range of attacks. Only proficient w arriors can m
```suggestion
			<p>Of all the armor categories, heavy armor offers the best protection. These suits of armor cover the entire body and are designed to stop a wide range of attacks. Only proficient warriors can manage their weight and bulk.</p>
```

2024-12-12 05:21 UTC, tregolani commented on core/players-handbook-2024/misc/proficiencies-all.xml
> +		<supports>Skill,Charisma,ID_PROFICIENCY_SKILL,ID_WOTC_PHB24_CLASS_ROGUE,Rogue,ID_WOTC_PHB24_CLASS_SORCERER,Sorcerer,ID_WOTC_PHB24_CLASS_CLERIC,Cleric,ID_WOTC_PHB24_CLASS_BARD,Bard,ID_WOTC_PHB24_CLA
```suggestion
		<supports>Skill,Charisma,ID_PROFICIENCY_SKILL,ID_WOTC_PHB24_CLASS_ROGUE,Rogue,ID_WOTC_PHB24_CLASS_SORCERER,Sorcerer,ID_WOTC_PHB24_CLASS_CLERIC,Cleric,ID_WOTC_PHB24_CLASS_BARD,Bard,ID_WOTC_PHB24_CLASS_PALADIN,Paladin,ID_WOTC_PHB24_CLASS_FIGHTER,Fighter</supports>
```

2024-12-17 18:42 UTC, tregolani commented on core/players-handbook-2024/items/items-weapons.xml
> +		<supports>ID_INTERNAL_WEAPON_CATEGORY_FIREARM, ID_INTERNAL_WEAPON_CATEGORY_MARTIAL_RANGED, ID_INTERNAL_DAMAGE_TYPE_PIERCING, ID_WOTC_PHB24_WEAPON_PROPERTY_AMMUNITION, ID_WOTC_PHB24_WEAPON_PROPERTY_
```suggestion
		<supports>ID_INTERNAL_WEAPON_CATEGORY_FIREARM, ID_INTERNAL_WEAPON_CATEGORY_MARTIAL_RANGED, ID_INTERNAL_DAMAGE_TYPE_PIERCING, ID_WOTC_PHB24_WEAPON_PROPERTY_AMMUNITION, ID_WOTC_PHB24_WEAPON_PROPERTY_LOADING, ID_WOTC_PHB24_WEAPON_PROPERTY_VEX</supports>
```

2025-03-06 21:46 UTC, Netrinil commented on core/players-handbook-2024/misc/weapon-mastery-properties.xml
It's my understanding that the Weapon Mastery class feature grants the mastery effects of specific weapons. Would this not be giving mastery for several extra weapons?

2025-03-06 23:23 UTC, Tel0k commented on core/players-handbook-2024/misc/weapon-mastery-properties.xml
It can be interpreted like that, but as long as you keep track of what weapon you are choosing to have mastery, it's not really a big problem.. even then it's still pending a review so it may change in the future

2025-03-07 04:49 UTC, FreshRoyal commented on core/players-handbook-2024/misc/weapon-mastery-properties.xml
DDB has you select specific weapons

2025-03-07 05:00 UTC, Netrinil commented on core/players-handbook-2024/misc/weapon-mastery-properties.xml
what was DDB?

2025-03-07 05:05 UTC, FreshRoyal commented on core/players-handbook-2024/misc/weapon-mastery-properties.xml
D&D Beyond

2025-06-29 20:07 UTC, tregolani commented on core/players-handbook-2024/items/items-weapons.xml
> +			<set name="versatile">1d8</set>
Trident's damage was increased from 1d6/1d8 -> 1d8/1d10 with PHB24
```suggestion
			<set name="damage" type="piercing">1d8</set>
			<set name="versatile">1d10</set>
```

2025-12-08 15:02 UTC, NickVendel requested changes
Review, Part 1

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-armor.xml
> +		<author url="http://dnd.wizards.com/products/tabletop-games/rpg-products/rpg_playershandbook">Wizards of the Coast</author>
```suggestion
		<description>Armors from the Player’s Handbook 2024.</description>
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-armor.xml
> +	<!-- light armor -->
```suggestion
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-armor.xml
> +			<p>Padded armor consists of quilted layers of cloth and batting.</p>
```suggestion
			<p class="flavor">1 Minute to Don or Doff</p>
			<p>Padded armor consists of quilted layers of cloth and batting.</p>
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-armor.xml
> +			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_ARMOR_PROFICIENCY_PADDED</set>
```suggestion
			<set name="category">Armor</set>
			<set name="armor">Light</set>
			<set name="armorClass">11 + Dex modifier</set>
			<set name="stealth">Disadvantage</set>
			<set name="weight" lb="8">8 lb.</set>
			<set name="cost" currency="gp">5</set>
			<set name="slot">body</set>
			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_ARMOR_PROFICIENCY_PADDED</set>
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-armor.xml
> +	</element>
```suggestion
	</element>

```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-armor.xml
> +			<p>The breastplate and shoulder protectors of this armor are made of leather that has been stiffened by being boiled in oil. The rest of the armor is made of softer and more flexible materials.</p
```suggestion
			<p class="flavor">1 Minute to Don or Doff</p>
			<p>The breastplate and shoulder protectors of this armor are made of leather that has been stiffened by being boiled in oil. The rest of the armor is made of softer and more flexible materials.</p>
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-armor.xml
> +			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_ARMOR_PROFICIENCY_LEATHER</set>
```suggestion
			<set name="category">Armor</set>
			<set name="armor">Light</set>
			<set name="armorClass">11 + Dex modifier</set>
			<set name="weight" lb="10">10 lb.</set>
			<set name="cost" currency="gp">10</set>
			<set name="slot">body</set>
			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_ARMOR_PROFICIENCY_LEATHER</set>
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-armor.xml
> +	</element>
```suggestion
	</element>

```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-armor.xml
> +			<p>Made from tough but flexible leather, studded leather is reinforced with close-set rivets or spikes.</p>
```suggestion
			<p class="flavor">1 Minute to Don or Doff</p>
			<p>Made from tough but flexible leather, studded leather is reinforced with close-set rivets or spikes.</p>
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-armor.xml
> +			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_ARMOR_PROFICIENCY_STUDDED_LEATHER</set>
```suggestion
			<set name="category">Armor</set>
			<set name="armor">Light</set>
			<set name="armorClass">12 + Dex modifier</set>
			<set name="weight" lb="13">13 lb.</set>
			<set name="cost" currency="gp">45</set>
			<set name="slot">body</set>
			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_ARMOR_PROFICIENCY_STUDDED_LEATHER</set>
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-armor.xml
> +	<!-- medium armor -->
```suggestion
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-armor.xml
> +			<p>This crude armor consists of thick furs and pelts. It is commonly worn by barbarian tribes, evil humanoids, and other folk who lack access to the tools and materials needed to create better arm
```suggestion
			<p class="flavor">5 Minutes to Don and 1 Minute to Doff</p>
			<p>This crude armor consists of thick furs and pelts. It is commonly worn by barbarian tribes, evil humanoids, and other folk who lack access to the tools and materials needed to create better armor.</p>
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-armor.xml
> +			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_ARMOR_PROFICIENCY_HIDE</set>
```suggestion
			<set name="category">Armor</set>
			<set name="armor">Medium</set>
			<set name="armorClass">12 + Dex modifier (max 2)</set>
			<set name="weight" lb="12">12 lb.</set>
			<set name="cost" currency="gp">10</set>
			<set name="slot">body</set>
			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_ARMOR_PROFICIENCY_HIDE</set>
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-armor.xml
> +	</element>
```suggestion
	</element>

```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-armor.xml
> +			<p>Made of interlocking metal rings, a chain shirt is worn between layers of clothing or leather. This armor offers modest protection to the wearer’s upper body and allows the sound of the rings r
```suggestion
			<p class="flavor">5 Minutes to Don and 1 Minute to Doff</p>
			<p>Made of interlocking metal rings, a chain shirt is worn between layers of clothing or leather. This armor offers modest protection to the wearer’s upper body and allows the sound of the rings rubbing against one another to be muffled by outer layers.</p>
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-armor.xml
> +			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_ARMOR_PROFICIENCY_CHAIN_SHIRT</set>
```suggestion
			<set name="category">Armor</set>
			<set name="armor">Medium</set>
			<set name="armorClass">13 + Dex modifier (max 2)</set>
			<set name="weight" lb="20">20 lb.</set>
			<set name="cost" currency="gp">50</set>
			<set name="slot">body</set>
			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_ARMOR_PROFICIENCY_CHAIN_SHIRT</set>
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-armor.xml
> +	</element>
```suggestion
	</element>

```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-armor.xml
> +			<p>This armor consists of a coat and leggings (and perhaps a separate skirt) of leather covered with overlapping pieces of metal, much like the scales of a fish. The suit includes gauntlets.</p>
```suggestion
			<p class="flavor">5 Minutes to Don and 1 Minute to Doff</p>
			<p>This armor consists of a coat and leggings (and perhaps a separate skirt) of leather covered with overlapping pieces of metal, much like the scales of a fish. The suit includes gauntlets.</p>
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-armor.xml
> +			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_ARMOR_PROFICIENCY_SCALE_MAIL</set>
```suggestion
			<set name="category">Armor</set>
			<set name="armor">Medium</set>
			<set name="armorClass">14 + Dex modifier (max 2)</set>
			<set name="stealth">Disadvantage</set>
			<set name="weight" lb="45">45 lb.</set>
			<set name="cost" currency="gp">50</set>
			<set name="slot">body</set>
			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_ARMOR_PROFICIENCY_SCALE_MAIL</set>
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-armor.xml
> +	</element>
```suggestion
	</element>

```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-armor.xml
> +			<p>This armor consists of a fitted metal chest piece worn with supple leather. Although it leaves the legs and arms relatively unprotected, this armor provides good protection for the wearer’s vit
```suggestion
			<p class="flavor">5 Minutes to Don and 1 Minute to Doff</p>
			<p>This armor consists of a fitted metal chest piece worn with supple leather. Although it leaves the legs and arms relatively unprotected, this armor provides good protection for the wearer’s vital organs while leaving the wearer relatively unencumbered.</p>
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-armor.xml
> +			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_ARMOR_PROFICIENCY_BREASTPLATE</set>
```suggestion
			<set name="category">Armor</set>
			<set name="armor">Medium</set>
			<set name="armorClass">14 + Dex modifier (max 2)</set>
			<set name="weight" lb="20">20 lb.</set>
			<set name="cost" currency="gp">400</set>
			<set name="slot">body</set>
			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_ARMOR_PROFICIENCY_BREASTPLATE</set>
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-armor.xml
> +	</element>
```suggestion
	</element>

```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-armor.xml
> +			<p>Half plate consists of shaped metal plates that cover most of the wearer’s body. It does not include leg protection beyond simple greaves that are attached with leather straps.</p>
```suggestion
			<p class="flavor">5 Minutes to Don and 1 Minute to Doff</p>
			<p>Half plate consists of shaped metal plates that cover most of the wearer’s body. It does not include leg protection beyond simple greaves that are attached with leather straps.</p>
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-armor.xml
> +			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_ARMOR_PROFICIENCY_HALF_PLATE</set>
```suggestion
			<set name="category">Armor</set>
			<set name="armor">Medium</set>
			<set name="armorClass">15 + Dex modifier (max 2)</set>
			<set name="stealth">Disadvantage</set>
			<set name="weight" lb="40">40 lb.</set>
			<set name="cost" currency="gp">750</set>
			<set name="slot">body</set>
			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_ARMOR_PROFICIENCY_HALF_PLATE</set>
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-armor.xml
> +	<!-- heavy armor -->
```suggestion
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-armor.xml
> +			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_ARMOR_PROFICIENCY_RING_MAIL</set>
```suggestion
			<set name="category">Armor</set>
			<set name="armor">Heavy</set>
			<set name="armorClass">14</set>
			<set name="stealth">Disadvantage</set>
			<set name="weight" lb="40">40 lb.</set>
			<set name="cost" currency="gp">30</set>
			<set name="slot">body</set>
			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_ARMOR_PROFICIENCY_RING_MAIL</set>
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-armor.xml
> +	</element>
```suggestion
	</element>

```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-armor.xml
> +			<p>Made of interlocking metal rings, chain mail includes a layer of quilted fabric worn underneath the mail to prevent chafing and to cushion the impact of blows. The suit includes gauntlets.</p>
```suggestion
			<p class="flavor">10 Minutes to Don and 5 Minute to Doff</p>
			<p>Made of interlocking metal rings, chain mail includes a layer of quilted fabric worn underneath the mail to prevent chafing and to cushion the impact of blows. The suit includes gauntlets.</p>
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-armor.xml
> +			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_ARMOR_PROFICIENCY_CHAIN_MAIL</set>
```suggestion
			<set name="category">Armor</set>
			<set name="armor">Heavy</set>
			<set name="armorClass">16</set>
			<set name="strength">13</set>
			<set name="stealth">Disadvantage</set>
			<set name="weight" lb="55">55 lb.</set>
			<set name="cost" currency="gp">75</set>
			<set name="slot">body</set>
			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_ARMOR_PROFICIENCY_CHAIN_MAIL</set>
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-armor.xml
> +	</element>
```suggestion
	</element>

```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-armor.xml
> +			<p>This armor is made of narrow vertical strips of metal riveted to a backing of leather that is worn over cloth padding. Flexible chain mail protects the joints.</p>
```suggestion
			<p class="flavor">10 Minutes to Don and 5 Minute to Doff</p>
			<p>This armor is made of narrow vertical strips of metal riveted to a backing of leather that is worn over cloth padding. Flexible chain mail protects the joints.</p>
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-armor.xml
> +			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_ARMOR_PROFICIENCY_SPLINT</set>
```suggestion
			<set name="category">Armor</set>
			<set name="armor">Heavy</set>
			<set name="armorClass">17</set>
			<set name="strength">15</set>
			<set name="stealth">Disadvantage</set>
			<set name="weight" lb="60">60 lb.</set>
			<set name="cost" currency="gp">200</set>
			<set name="slot">body</set>
			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_ARMOR_PROFICIENCY_SPLINT</set>
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-armor.xml
> +	</element>
```suggestion
	</element>

```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-armor.xml
> +			<p>Plate consists of shaped, interlocking metal plates to cover the entire body. A suit of plate includes gauntlets, heavy leather boots, a visored helmet, and thick layers of padding underneath t
```suggestion
			<p class="flavor">10 Minutes to Don and 5 Minute to Doff</p>
			<p>Plate consists of shaped, interlocking metal plates to cover the entire body. A suit of plate includes gauntlets, heavy leather boots, a visored helmet, and thick layers of padding underneath the armor. Buckles and straps distribute the weight over the body.</p>
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-armor.xml
> +			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_ARMOR_PROFICIENCY_PLATE</set>
```suggestion
			<set name="category">Armor</set>
			<set name="armor">Heavy</set>
			<set name="armorClass">18</set>
			<set name="strength">15</set>
			<set name="stealth">Disadvantage</set>
			<set name="weight" lb="65">65 lb.</set>
			<set name="cost" currency="gp">1500</set>
			<set name="slot">body</set>
			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_ARMOR_PROFICIENCY_PLATE</set>
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-armor.xml
> +	<!--shield-->
```suggestion
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-armor.xml
> +			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_ARMOR_PROFICIENCY_SHIELD</set>
```suggestion
			<set name="category">Armor</set>
			<set name="type">Shield</set>
			<set name="armor">Shield</set>
			<set name="armorClass">+2</set>
			<set name="weight" lb="6">6 lb.</set>
			<set name="cost" currency="gp">10</set>
			<set name="slot">onehand,secondary</set>
			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_ARMOR_PROFICIENCY_SHIELD</set>
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +		<author url="http://dnd.wizards.com/products/tabletop-games/rpg-products/rpg_playershandbook">Wizards of the Coast</author>
```suggestion
		<description>Adventuring Gear from the Player’s Handbook 2024.</description>
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	</element>-->
```suggestion

```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	<element name="Acid" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_ACID">
```suggestion

	<element name="Acid" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_ACID">
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	</element>
```suggestion
	</element>

```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +			<p>When you take the Attack action, you can replace one of your attacks with throwing a flask of Alchemist's Fire. Target one creature or object you can see within 20 feet of yourself. The target
```suggestion
			<p>When you take the Attack action, you can replace one of your attacks with throwing a flask of Alchemist's Fire. Target one creature or object you can see within 20 feet of yourself. The target must succeed on a Dexterity saving throw (DC 8 plus your Dexterity modifier and Proficiency Bonus) or take ld4 Fire damage and start burning.</p>
			<div class="reference">
				<div element="ID_WOTC_PHB24_RULE_BURNING" />
			</div>
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	<!-- ammunition individual, price and weight recalculated -->
```suggestion
	</element>
	<!-- to do: move all PHB24 Rule type elements into their own file -->
	<element name="Burning [Hazard]" type="Rule" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_RULE_BURNING">
		<description>
			<p>A burning creature or object takes 1d4 Fire damage at the start of each of its turns. As an action, you can extinguish fire on yourself by giving yourself the Prone condition and rolling on the ground. The fire also goes out if it is doused, submerged, or suffocated.</p>
		</description>
		<setters>
			<set name="keywords">fire, on fire</set>
		</setters>
	</element>

	<!-- Individual pieces of ammunition, price and weight were recalculated. Sling Bullets are a bit of an exception, more in the relevant element -->
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	<element name="Blowgun Needle" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_BLOWGUNNEEDLE">
```suggestion

	<element name="Bolt" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_BOLT">
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +			<set name="stackable">true</set>
```suggestion
			<set name="category">Ammunition</set>
			<set name="cost" currency="cp">5</set>
			<set name="weight" lb="0.075">3/40 lb.</set>
			<set name="type">Ammunition</set>
			<set name="stackable">true</set>
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	<element name="Crossbow Bolt" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_CROSSBOWBOLT">
```suggestion

	<element name="Bullet, Firearm" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_BULLET_FIREARM">
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +			<set name="stackable">true</set>
```suggestion
			<set name="category">Ammunition</set>
			<set name="cost" currency="sp">3</set>
			<set name="weight" lb="0.2">1/5 lb.</set>
			<set name="type">Ammunition</set>
			<set name="stackable">true</set>
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	<element name="Sling Bullet" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_SLINGBULLET">
```suggestion

	<element name="Bullets, Sling" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_BULLET_SLING">
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +		</description>
```suggestion
		<p><b>Note:</b> Due to the fact that lowest amount of coin app allows is 1cp, bullets for slings can only be sold in bundles of 5.</p>
		</description>
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +			<set name="stackable">true</set>
```suggestion
			<set name="category">Ammunition</set>
			<set name="cost" currency="cp">1</set>
			<set name="weight" lb="0.375">15/40 lb.</set>
			<set name="type">Ammunition</set>
			<set name="stackable">true</set>
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	<element name="Firearm Bullet" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_FIREARMBULLET">
```suggestion

	<element name="Needle" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_NEEDLE">
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +			<set name="stackable">true</set>
```suggestion
			<set name="category">Ammunition</set>
			<set name="cost" currency="cp">2</set> 
			<set name="weight" lb="0.02">1/50 lb.</set>
			<set name="type">Ammunition</set>
			<set name="stackable">true</set>
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	<element name="Antitoxin (vial)" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_ANTITOXIN_VIAL">
```suggestion

	<element name="Antitoxin" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_ANTITOXIN">
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	<element name="Crystal" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_CRYSTAL">
```suggestion

	<element name="Crystal" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_ARCANE_FOCUS_CRYSTAL">
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +			<p>An Arcane Focus takes one of the forms in the Arcane Focuses table and is bejeweled or carved to channel arcane magic. A Sorcerer, Warlock, or Wizard can use such an item as a Spellcasting Focu
```suggestion
			<p>An Arcane Focus is bejeweled or carved to channel arcane magic. A Sorcerer, Warlock, or Wizard can use such an item as a Spellcasting Focus.</p>
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	<element name="Orb" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_ORB">
```suggestion

	<element name="Orb" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_ARCANE_FOCUS_ORB">
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +			<p>An Arcane Focus takes one of the forms in the Arcane Focuses table and is bejeweled or carved to channel arcane magic. A Sorcerer, Warlock, or Wizard can use such an item as a Spellcasting Focu
```suggestion
			<p>An Arcane Focus is bejeweled or carved to channel arcane magic. A Sorcerer, Warlock, or Wizard can use such an item as a Spellcasting Focus</p>
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +			<p>An Arcane Focus takes one of the forms in the Arcane Focuses table and is bejeweled or carved to channel arcane magic. A Sorcerer, Warlock, or Wizard can use such an item as a Spellcasting Focu
```suggestion
			<p>An Arcane Focus is bejeweled or carved to channel arcane magic. A Sorcerer, Warlock, or Wizard can use such an item as a Spellcasting Focus</p>
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +			<p>An Arcane Focus takes one of the forms in the Arcane Focuses table and is bejeweled or carved to channel arcane magic. A Sorcerer, Warlock, or Wizard can use such an item as a Spellcasting Focu
```suggestion
			<p>An Arcane Focus is bejeweled or carved to channel arcane magic. A Sorcerer, Warlock, or Wizard can use such an item as a Spellcasting Focus</p>
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	<element name="Rod" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_ROD">
```suggestion

	<element name="Rod" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_ARCANE_FOCUS_ROD">
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	</element>
```suggestion

	<!-- commented out, as any Quarterstaff is considered Arcane Focus -->
	<!-- <element name="Staff" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_ARCANE_FOCUS_STAFF">
		<description>
			<p>An Arcane Focus is bejeweled or carved to channel arcane magic. A Sorcerer, Warlock, or Wizard can use such an item as a Spellcasting Focus</p>
		</description>
		<setters>
			<set name="category">Spellcasting Focus</set>
			<set name="cost" currency="gp">5</set>
			<set name="weight" lb="4">4 lb.</set>
			<set name="container">Arcane Focus</set>
			<set name="slot">onehand</set>
		</setters>
	</element> -->

```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	<element name="Wand" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_WAND">
```suggestion
	<element name="Wand" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_ARCANE_FOCUS_WAND">
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	<!-- -->
```suggestion

```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	<element name="Backpack" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_BACKPACK">
```suggestion

	<element name="Backpack" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_BACKPACK">
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	<element name="Ball Bearings" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_BALLBEARINGS">
```suggestion

	<element name="Ball Bearings" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_BALL_BEARINGS">
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	</element>
```suggestion
	</element>

```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	</element>
```suggestion
	</element>

```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	</element>
```suggestion
	</element>

```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +			<p>A Bedroll sleeps one Small or Medium creature. While in a Bedroll, you automatically succeed on saving throws against extreme cold (see the Dungeon Master's Guide).</p>
```suggestion
			<p>A Bedroll sleeps one Small or Medium creature. While in a Bedroll, you automatically succeed on saving throws against extreme cold.</p>
			<!-- to do: put reference here once DMG24 content is ready
			<div class="reference">
				<div element="ID_WOTC_DMG24_RULE_EXTREME_COLD" />
			</div> -->
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	</element>
```suggestion
	</element>

```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	</element>
```suggestion
	</element>

```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +			<p>While wrapped in a blanket, you have Advantage on saving throws against extreme cold (see the Dungeon Master's Guide).</p>
```suggestion
			<p>While wrapped in a blanket, you have Advantage on saving throws against extreme cold.</p>
			<!-- to do: put reference here once DMG24 content is ready
			<div class="reference">
				<div element="ID_WOTC_DMG24_RULE_EXTREME_COLD" />
			</div> -->
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	<element name="Block and Tackle" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_BLOCKANDTACKLE">
```suggestion

	<element name="Block and Tackle" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_BLOCK_AND_TACKLE">
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +			<p>A Block and Tackle allows you to hoist up to four times the weight you can normally lift. </p>
```suggestion
			<p>A Block and Tackle allows you to hoist up to four times the weight you can normally lift.</p>
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	</element>
```suggestion
	</element>

```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	</element>
```suggestion
	</element>

```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +			<p>A Glass Bottle holds up to 1 1/2 pints.</p>
```suggestion
			<p>A Glass Bottle holds up to 1½ pints.</p>
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	</element>
```suggestion
	</element>

```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	</element>
```suggestion
	</element>

```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	</element>
```suggestion
	</element>

```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	<element name="Case, Crossbow Bolt" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_CASE_CROSSBOWBOLT">
```suggestion

	<element name="Case, Crossbow Bolt" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_CASE_CROSSBOW_BOLT">
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	<element name="Case, Map or Scroll" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_CASE_MAPORSCROLL">
```suggestion

	<element name="Case, Map or Scroll" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_CASE_MAP_OR_SCROLL">
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +			<p>A Map or Scroll Case holds up to 10 sheets of paper or 5 sheets of parchment. </p>
```suggestion
			<p>A Map or Scroll Case holds up to 10 sheets of paper or 5 sheets of parchment.</p>
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	<element name="Chain" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_CHAIN_10FEET">
```suggestion

	<element name="Chain" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_CHAIN">
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	</element>-->
```suggestion
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	<element name="Chest" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_CHEST">
```suggestion

	<element name="Chest" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_CHEST">
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	<element name="Climber's Kit" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_CLIMBERSKIT">
```suggestion

	<element name="Climber's Kit" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_CLIMBERS_KIT">
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +			<p>A Climber's Kit includes boot tips, gloves, pitons,and a harness. As a Utilize action, you can use the Climber's Kit to anchor yourself; when you do, you can't fall more than 25 feet from the a
```suggestion
			<p>A Climber's Kit includes boot tips, gloves, pitons, and a harness. As a Utilize action, you can use the Climber's Kit to anchor yourself; when you do, you can't fall more than 25 feet from the anchor point, and you can't move more than 25 feet from there without undoing the anchor as a Bonus Action.</p>
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	</element>
```suggestion
	</element>

```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	</element>-->
```suggestion
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	</element>
```suggestion
	</element>

```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	<element name="Component Pouch" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_COMPONENTPOUCH">
```suggestion

	<element name="Component Pouch" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_COMPONENT_POUCH">
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	</element>
```suggestion
	</element>

```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	</element>
```suggestion
	</element>

```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +			<p>Using a Crowbar grants Advantage to Strength checks where the Crowbar's leverage can be applied.</p>
```suggestion
			<p>Using a Crowbar gives you Advantage on Strength checks where the Crowbar's leverage can be applied.</p>
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	<element name="Sprig of Mistletoe" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_SPRIGOFMISTLETOE">
```suggestion

	<element name="Sprig of Mistletoe" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_DRUIDIC_FOCUS_SPRIG_OF_MISTLETOE">
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +			<p>A Druidic Focus takes one of the forms in the Druidic Focuses table and is carved, tied with ribbon, or painted to channel primal magic. A Druid or Ranger can use such an object as a Spellcasti
```suggestion
			<p>A Druidic Focus is carved, tied with ribbon, or painted to channel primal magic. A Druid or Ranger can use such an object as a Spellcasting Focus.</p>
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +			<p>A Druidic Focus takes one of the forms in the Druidic Focuses table and is carved, tied with ribbon, or painted to channel primal magic. A Druid or Ranger can use such an object as a Spellcasti
```suggestion
			<p>A Druidic Focus is carved, tied with ribbon, or painted to channel primal magic. A Druid or Ranger can use such an object as a Spellcasting Focus.</p>
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	</element>
```suggestion
	</element>

```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	</element>-->
```suggestion
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	</element>
```suggestion

	<!-- commented out, as any Quarterstaff is considered Druidic Focus -->
	<!-- <element name="Wooden Staff" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_DRUIDIC_FOCUS_WOODEN_STAFF">
		<description>
			<p>A Druidic Focus is carved, tied with ribbon, or painted to channel primal magic. A Druid or Ranger can use such an object as a Spellcasting Focus.</p>
		</description>
		<setters>
			<set name="category">Spellcasting Focus</set>
			<set name="cost" currency="gp">5</set>
			<set name="weight" lb="4">4 lb.</set>
			<set name="container">Druidic Focus</set>
			<set name="slot">onehand</set>
		</setters>
	</element> -->

```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	<element name="Yew Wand" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_YEWWAND">
```suggestion
	<element name="Yew Wand" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_DRUIDIC_FOCUS_YEW_WAND">
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	</element>
```suggestion
	</element>

```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	</element>-->
```suggestion
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	<element name="Grappling Hook" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_GRAPPLINGHOOK">
```suggestion

	<element name="Grappling Hook" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_GRAPPLING_HOOK">
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	<element name="Healer's Kit" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_HEALERSKIT">
```suggestion

	<element name="Healer's Kit" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_HEALERS_KIT">
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	<element name="Amulet" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_AMULET">
```suggestion

	<element name="Amulet" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_HOLY_SYMBOL_AMULET">
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +			<p class="indent">The table indicates whether a Holy Symbol needs to be held, worn, or borne on fabric (such as a tabard or banner) or a Shield.</p>
```suggestion
			<p>A Holy Symbol is bejeweled or painted to channel divine magic. A Cleric or Paladin can use a Holy Symbol as a Spellcasting Focus.</p>
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +			<p class="indent">The table indicates whether a Holy Symbol needs to be held, worn, or borne on fabric (such as a tabard or banner) or a Shield.</p>
```suggestion
			<p>A Holy Symbol is bejeweled or painted to channel divine magic. A Cleric or Paladin can use a Holy Symbol as a Spellcasting Focus.</p>
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +			<p class="indent">The table indicates whether a Holy Symbol needs to be held, worn, or borne on fabric (such as a tabard or banner) or a Shield.</p>
```suggestion
			<p>A Holy Symbol is bejeweled or painted to channel divine magic. A Cleric or Paladin can use a Holy Symbol as a Spellcasting Focus.</p>
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +			<set name="slot">onehand</set>
```suggestion
			<set name="slot">misc</set>
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	<element name="Emblem" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_EMBLEM">
```suggestion

	<element name="Emblem" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_HOLY_SYMBOL_EMBLEM">
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +			<set name="slot">onehand</set>
```suggestion
			<set name="slot">misc</set>
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	<element name="Reliquary" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_RELIQUARY">
```suggestion

	<element name="Reliquary" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_HOLY_SYMBOL_RELIQUARY">
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	<element name="Holy Water" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_HOLYWATER">
```suggestion

	<element name="Holy Water" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_HOLY_WATER">
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	<element name="Hunting Trap" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_HUNTINGTRAP">
```suggestion

	<element name="Hunting Trap" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_HUNTING_TRAP">
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	<element name="Ink (1 ounce bottle)" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_INK_1OUNCEBOTTLE">
```suggestion

	<element name="Ink" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_INK">
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	<element name="Ink Pen" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_INKPEN">
```suggestion

	<element name="Ink Pen" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_INK_PEN">
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	</element>
```suggestion
	</element>

```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	<element name="Ladder (10—feet)" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_LADDER_10_FEET">
```suggestion

	<element name="Ladder" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_LADDER">
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	</element>
```suggestion
	</element>

```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	</element>
```suggestion
	</element>

```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	</element>
```suggestion
	</element>

```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	</element>
```suggestion
	</element>

```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	<element name="Magnifying Glass" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_MAGNIFYINGGLASS">
```suggestion

	<element name="Magnifying Glass" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_MAGNIFYING_GLASS">
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	</element>
```suggestion
	</element>

```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	</element>
```suggestion
	</element>

```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	</element>-->
```suggestion
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	</element>
```suggestion
	</element>

```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	</element>
```suggestion
	</element>

```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	<element name="Oil (flask)" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_OIL_FLASK">
```suggestion

	<element name="Oil" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_OIL">
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	<element name="Paper (one sheet)" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_PAPER_ONESHEET">
```suggestion

	<element name="Paper" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_PAPER">
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	<element name="Parchment (one sheet)" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_PARCHMENT_ONESHEET">
```suggestion

	<element name="Parchment" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_PARCHMENT">
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	<element name="Perfume (vial)" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_PERFUME_VIAL">
```suggestion

	<element name="Perfume" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_PERFUME">
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	<element name="Poison, Basic (vial)" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_POISON_BASIC_VIAL">
```suggestion

	<element name="Poison, Basic" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_POISON_BASIC">
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	<element name="Pole (10—foot)" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_POLE_10_FOOT">
```suggestion

	<element name="Pole" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_POLE">
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	</element>
```suggestion
	</element>

```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	<element name="Potion of Healing" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_POTIONOFHEALING">
```suggestion

	<element name="Potion of Healing" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_POTION_OF_HEALING">
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	</element>
```suggestion
	</element>

```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	</element>
```suggestion
	</element>

```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	</element>
```suggestion
	</element>

```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	<element name="Rations (1 day)" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_RATIONS_1DAY">
```suggestion

	<element name="Rations" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_RATIONS">
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +			<p>Rations consist of travel-ready food, including jerky, dried fruit, hardtack, and nuts. See “Malnutrition” in the rules glossary for the risks of not eating.</p>
```suggestion
			<p>Rations consist of travel-ready food, including jerky, dried fruit, hardtack, and nuts. If you don't eat sufficient amount of food, you risk malnutrition.</p>
			<div class="reference">
				<div element="ID_WOTC_PHB24_RULE_MALNUTRITION" />
			</div>
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	</element>
```suggestion
	</element>
	<!-- to do: move all PHB24 Rule type elements into their own file -->
	<element name="Malnutrition [Hazard]" type="Rule" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_RULE_MALNUTRITION">
		<description>
			<p>A creature needs an amount of food per day based on its size, as shown in the Food Needs per Day table. A creature that eats but consumes less than half the required food for a day must succeed on a DC 10 Constitution saving throw or gain 1 Exhaustion level at the day's end. A creature that eats nothing for 5 days automatically gains 1 Exhaustion level at the end of the fifth day as well as an additional level at the end of each subsequent day without food.</p>
			<p class="indent">Exhaustion caused by malnutrition can't be removed until the creature eats the full amount of food required for a day.</p>
			<h5>Food Needs per Day</h5>
			<table>
				<thead>
					<tr><td>Size</td><td>Food</td></tr>
				</thead>
				<tr><td>Tiny</td><td>1/4 pound</td></tr>
				<tr><td>Small</td><td>1 pound</td></tr>
				<tr><td>Medium</td><td>1 pound</td></tr>
				<tr><td>Large</td><td>4 pounds</td></tr>
				<tr><td>Huge</td><td>16 pounds</td></tr>
				<tr><td>Gargantuan</td><td>64 pounds</td></tr>
			</table>
		</description>
		<setters>
			<set name="keywords">food, eating, exhaustion</set>
		</setters>
	</element>

```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	</element>
```suggestion
	</element>

```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	</element>
```suggestion
	</element>

```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	</element>
```suggestion
	</element>

```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	</element>-->
```suggestion
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	<element name="Signal Whistle" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_SIGNALWHISTLE">
```suggestion

	<element name="Signal Whistle" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_SIGNAL_WHISTLE">
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	<element name="Spell Scroll, Cantrip" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_SPELLSCROLL_CANTRIP">
```suggestion

	<element name="Spell Scroll, Cantrip" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_SPELL_SCROLL_CANTRIP">
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +			<p>A Spell Scroll (Cantrip) or Spell Scroll (Level 1) is a magic item that bears the words of a cantrip or level 1 spell, respectively, determined by the scroll's creator. If the spell is on your
```suggestion
			<p>A <i>Spell Scroll</i> is a magic item that bears the words of a cantrip, respectively, determined by the scroll's creator. If the spell is on your class's spell list, you can read the scroll and cast the spell using its normal casting time and without providing any Material components.</p>
			<p class="indent">If the spell requires a saving throw or an attack roll, the spell save DC is 15, and the attack bonus is +5. The scroll disintegrates when the casting is completed.</p>
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	<element name="Spell Scroll, Level 1" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_SPELLSCROLL_LEVEL1">
```suggestion

	<element name="Spell Scroll, Level 1" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_SPELL_SCROLL_LEVEL1">
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +			<p>A Spell Scroll (Cantrip) or Spell Scroll (Level 1) is a magic item that bears the words of a cantrip or level 1 spell, respectively, determined by the scroll's creator. If the spell is on your
```suggestion
			<p>A <i>Spell Scroll</i> is a magic item that bears the words of a level 1 spell, respectively, determined by the scroll's creator. If the spell is on your class's spell list, you can read the scroll and cast the spell using its normal casting time and without providing any Material components.</p>
			<p class="indent">If the spell requires a saving throw or an attack roll, the spell save DC is 15, and the attack bonus is +5. The scroll disintegrates when the casting is completed.</p>
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	<element name="Spikes, Iron (10)" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_SPIKES_IRON_10">
```suggestion

	<element name="Spikes, Iron" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_SPIKES_IRON">
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +			<p>Iron Spikes come in bundles of ten. As a Utilize action, you can use a blunt object, such as a Light Hammer, to hammer a spike into wood, earth, or a similar material. You can do so to j.;:it a
```suggestion
			<p>Iron Spikes come in bundles of ten. As a Utilize action, you can use a blunt object, such as a Light Hammer, to hammer a spike into wood, earth, or a similar material. You can do so to jam a door shut or to then tie a Rope or Chain to the Spike.</p>
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	</element>
```suggestion
	</element>

```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	<element name="String (10 feet)" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_STRING_10FEET">
```suggestion

	<element name="String" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_STRING">
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +			<set name="cost" currency="gp">0</set>
```suggestion
			<set name="cost" currency="sp">1</set>
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	<element name="Tent" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_TENT_TWOPERSON">
```suggestion

	<element name="Tent" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_TENT">
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	</element>
```suggestion
	</element>

```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	</element>
```suggestion
	</element>

```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	</element>
```suggestion
	</element>

```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	</element>
```suggestion
	</element>

```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +			<p>A Waterskin holds up to 4 pints. If you don't drink sufficient water, you risk dehydration (see the rules glossary).</p>
```suggestion
			<p>A Waterskin holds up to 4 pints. If you don't drink sufficient water, you risk dehydration.</p>
			<div class="reference">
				<div element="ID_WOTC_PHB24_RULE_DEHYDRATION" />
			</div>
```

2025-12-08 15:02 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +	</element>-->
```suggestion
	<!-- to do: move all PHB24 Rule type elements into their own file -->
	<element name="Dehydration [Hazard]" type="Rule" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_RULE_DEHYDRATION">
		<description>
			<p>A creature requires an amount of water per day based on its size, as shown in the Water Needs per Day table. A creature that drinks less than half the required water for a day gains 1 Exhaustion level at the day's end. Exhaustion caused by dehydration can't be removed until the creature drinks the full amount of water required for a day.</p>
			<h5>Water Needs per Day</h5>
			<table>
				<thead>
					<tr><td>Size</td><td>Water</td></tr>
				</thead>
				<tr><td>Tiny</td><td>1/4 gallon</td></tr>
				<tr><td>Small</td><td>1 gallon</td></tr>
				<tr><td>Medium</td><td>1 gallon</td></tr>
				<tr><td>Large</td><td>4 gallons</td></tr>
				<tr><td>Huge</td><td>16 gallons</td></tr>
				<tr><td>Gargantuan</td><td>64 gallons</td></tr>
			</table>
		</description>
		<setters>
			<set name="keywords">drinking, water, exhaustion</set>
		</setters>
	</element>
```

2025-12-08 15:02 UTC, NickVendel requested changes
Review, Part 1

2025-12-12 14:49 UTC, NickVendel requested changes
Part 2. The rest of the files, including Proficiencies, Languages and Expertise elements are likely going to be changed during last stages of PHB24 review.

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-instrument.xml
this file should be deleted, as i moved all of the Musical Instruments into `items-tools.xml`

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-mounts-vehicles.xml
> +		<author url="http://dnd.wizards.com/products/tabletop-games/rpg-products/rpg_playershandbook">Wizards of the Coast</author>
```suggestion
		<name>Mounts and Vehicles</name>
		<description>Mounts and Vehicles from Player's Handbook 2024</description>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-mounts-vehicles.xml
> +	<element name="Camel" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_CAMEL">
```suggestion
	</info>

	<!-- Barding was never properly implemented, and is currently not planned, as it don't affect the character in any way. Still maybe at some point in the future it would make sense to adapt normal armor into barding at least for an ease of tracking it for users -->
	<element name="Barding" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_BARDING">
		<description>
			<p>Barding is armor designed for a mount. Any type of armor on the Armor table in this chapter can be purchased as barding. The cost is four times the normal cost, and it weighs twice as much.</p>
		</description>
		<setters>
			<set name="category">Mounts &amp; Vehicles</set>
			<set name="cost" currency="gp">0</set>
			<set name="weight" lb="0">—</set>
		</setters>
	</element>

	<element name="Camel" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_CAMEL">
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-mounts-vehicles.xml
> +			<p><strong><em>Speed.</em></strong> 50 ft.<br/><strong><em>Carrying Capacity.</em></strong> 450 lb.</p>
```suggestion
			<h4 style="margin-top:0px" />
			<p><em>Large Beast, Unaligned</em></p>
			<ul class="unstyled mb">
				<li style="margin-bottom:-1em"><strong>AC</strong> 10</li>
				<li style="text-align:right; margin-top:-1em"><strong>Initiative</strong> -1 (9)</li>
				<li style="margin-bottom:-1em"><strong>HP</strong> 17 (2d10 + 6)</li>
				<li style="text-align:right; margin-top:-1em"><strong>Carrying Capacity</strong> 450 lb.</li>
				<li><strong>Speed</strong> 50 ft.</li>
			</ul>
			<table style="text-align:center">
				<thead><tr><td> </td><td> </td><td>MOD</td><td>SAVE</td><td> </td><td> </td><td>MOD</td><td>SAVE</td><td> </td><td> </td><td>MOD</td><td>SAVE</td></tr></thead>
				<tr><td>STR</td><td>15</td><td>+2</td><td>+2</td><td>DEX</td><td>8</td><td>-1</td><td>-1</td><td>CON</td><td>17</td><td>+3</td><td>+5</td></tr>
				<tr><td>INT</td><td>2</td><td>-4</td><td>-4</td><td>WIS</td><td>11</td><td>+0</td><td>+0</td><td>CHA</td><td>5</td><td>-3</td><td>-3</td></tr>
			</table>
			<ul class="unstyled">
				<li><strong>Senses</strong> Darkvision 60ft., Passive Perception 10</li>
				<li><strong>Languages</strong> None</li>
				<li><strong>Challenge</strong> 1/8 (XP 25; PB +2)</li>
			</ul>
			<h4 style="margin-top:10px">Actions</h4>
			<ul class="unstyled">
				<li><strong><em>Bite. </em></strong><em>Melee Weapon Attack:</em> +4, reach 5 ft. <em>Hit:</em> 4 (1d4 + 2) Bludgeoning damage.</li>
			</ul>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-mounts-vehicles.xml
> +	</element>
Mule is moved below
```suggestion
	</element>

```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-mounts-vehicles.xml
> +			<p><strong><em>Speed.</em></strong> 40 ft.<br/><strong><em>Carrying Capacity.</em></strong> 1320 lb.</p>
```suggestion
			<h4 style="margin-top:0px" />
			<p><em>Huge Beast, Unaligned</em></p>
			<ul class="unstyled mb">
				<li style="margin-bottom:-1em"><strong>AC</strong> 12</li>
				<li style="text-align:right; margin-top:-1em"><strong>Initiative</strong> -1 (9)</li>
				<li style="margin-bottom:-1em"><strong>HP</strong> 76 (8d12 + 24)</li>
				<li style="text-align:right; margin-top:-1em"><strong>Carrying Capacity</strong> 1320 lb.</li>
				<li><strong>Speed</strong> 40 ft.</li>
			</ul>
			<table style="text-align:center">
				<thead><tr><td> </td><td> </td><td>MOD</td><td>SAVE</td><td> </td><td> </td><td>MOD</td><td>SAVE</td><td> </td><td> </td><td>MOD</td><td>SAVE</td></tr></thead>
				<tr><td>STR</td><td>22</td><td>+6</td><td>+6</td><td>DEX</td><td>9</td><td>-1</td><td>-1</td><td>CON</td><td>17</td><td>+3</td><td>+3</td></tr>
				<tr><td>INT</td><td>3</td><td>-4</td><td>-4</td><td>WIS</td><td>11</td><td>+0</td><td>+0</td><td>CHA</td><td>6</td><td>-2</td><td>-2</td></tr>
			</table>
			<ul class="unstyled">
				<li><strong>Senses</strong> Passive Perception 10</li>
				<li><strong>Languages</strong> None</li>
				<li><strong>Challenge</strong> 4 (XP 1,100; PB +2)</li>
			</ul>
			<h4 style="margin-top:10px">Actions</h4>
			<ul class="unstyled">
				<li><strong><em>Multiattack. </em></strong> The elephant makes two Gore attacks.</li>
				<li><strong><em>Gore. </em></strong><em>Melee Weapon Attack:</em> +8, reach 5 ft. <em>Hit:</em> 15 (2d8 + 6) Piercing damage. lf the elephant moved at least 20 feet straight toward the target immediately before the hit, the target also has the Prone condition.</li>
			</ul>
			<h4 style="margin-top:10px">Bonus Actions</h4>
			<ul class="unstyled">
				<li><strong><em>Trample. </em></strong><em>Dexterity Saving Throw:</em> DC16, one creature within 5 feet that has the Prone condition. <em>Failure:</em> 17 (2d10 + 6) Bludgeoning damage. <em>Success:</em> Half damage.</li>
			</ul>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-mounts-vehicles.xml
> +	</element>
```suggestion
	</element>

```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-mounts-vehicles.xml
> +			<p><strong><em>Speed.</em></strong> 40 ft.<br/><strong><em>Carrying Capacity.</em></strong> 540 lb.</p>
```suggestion
			<h4 style="margin-top:0px" />
			<p><em>Large Beast, Unaligned</em></p>
			<ul class="unstyled mb">
				<li style="margin-bottom:-1em"><strong>AC</strong> 10</li>
				<li style="text-align:right; margin-top:-1em"><strong>Initiative</strong> +0 (10)</li>
				<li style="margin-bottom:-1em"><strong>HP</strong> 15 (2d10 + 4)</li>
				<li style="text-align:right; margin-top:-1em"><strong>Carrying Capacity</strong> 540 lb.</li>
				<li><strong>Speed</strong> 40 ft.</li>
			</ul>
			<table style="text-align:center">
				<thead><tr><td> </td><td> </td><td>MOD</td><td>SAVE</td><td> </td><td> </td><td>MOD</td><td>SAVE</td><td> </td><td> </td><td>MOD</td><td>SAVE</td></tr></thead>
				<tr><td>STR</td><td>18</td><td>+4</td><td>+4</td><td>DEX</td><td>10</td><td>+0</td><td>+0</td><td>CON</td><td>15</td><td>+2</td><td>+2</td></tr>
				<tr><td>INT</td><td>2</td><td>-4</td><td>-4</td><td>WIS</td><td>11</td><td>+0</td><td>+0</td><td>CHA</td><td>7</td><td>-2</td><td>-2</td></tr>
			</table>
			<ul class="unstyled">
				<li><strong>Senses</strong> Passive Perception 10</li>
				<li><strong>Languages</strong> None</li>
				<li><strong>Challenge</strong> 1/4 (XP 50; PB +2)</li>
			</ul>
			<h4 style="margin-top:10px">Actions</h4>
			<ul class="unstyled">
				<li><strong><em>Hooves. </em></strong><em>Melee Weapon Attack:</em> +6, reach 5 ft. <em>Hit:</em> 6 (1d4 + 4) Bludgeoning damage.</li>
			</ul>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-mounts-vehicles.xml
> +	</element>
```suggestion
	</element>

```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-mounts-vehicles.xml
> +			<p><strong><em>Speed.</em></strong> 60 ft.<br/><strong><em>Carrying Capacity.</em></strong> 480 lb.</p>
```suggestion
			<h4 style="margin-top:0px" />
			<p><em>Large Beast, Unaligned</em></p>
			<ul class="unstyled mb">
				<li style="margin-bottom:-1em"><strong>AC</strong> 11</li>
				<li style="text-align:right; margin-top:-1em"><strong>Initiative</strong> +1 (11)</li>
				<li style="margin-bottom:-1em"><strong>HP</strong> 13 (2d10 + 2)</li>
				<li style="text-align:right; margin-top:-1em"><strong>Carrying Capacity</strong> 480 lb.</li>
				<li><strong>Speed</strong> 60 ft.</li>
			</ul>
			<table style="text-align:center">
				<thead><tr><td> </td><td> </td><td>MOD</td><td>SAVE</td><td> </td><td> </td><td>MOD</td><td>SAVE</td><td> </td><td> </td><td>MOD</td><td>SAVE</td></tr></thead>
				<tr><td>STR</td><td>16</td><td>+3</td><td>+3</td><td>DEX</td><td>13</td><td>+1</td><td>+1</td><td>CON</td><td>12</td><td>+1</td><td>+1</td></tr>
				<tr><td>INT</td><td>2</td><td>-4</td><td>-4</td><td>WIS</td><td>11</td><td>+0</td><td>+0</td><td>CHA</td><td>7</td><td>-2</td><td>-2</td></tr>
			</table>
			<ul class="unstyled">
				<li><strong>Senses</strong> Passive Perception 10</li>
				<li><strong>Languages</strong> None</li>
				<li><strong>Challenge</strong> 1/4 (XP 50; PB +2)</li>
			</ul>
			<h4 style="margin-top:10px">Actions</h4>
			<ul class="unstyled">
				<li><strong><em>Hooves. </em></strong><em>Melee Weapon Attack:</em> +5, reach 5 ft. <em>Hit:</em> 7 (1d8 + 3) Bludgeoning damage.</li>
			</ul>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-mounts-vehicles.xml
> +	</element>
```suggestion
	</element>

```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-mounts-vehicles.xml
> +			<p><strong><em>Speed.</em></strong> 40 ft.<br/><strong><em>Carrying Capacity.</em></strong> 195 lb.</p>
```suggestion
			<h4 style="margin-top:0px" />
			<p><em>Medium Beast, Unaligned</em></p>
			<ul class="unstyled mb">
				<li style="margin-bottom:-1em"><strong>AC</strong> 12</li>
				<li style="text-align:right; margin-top:-1em"><strong>Initiative</strong> +2 (12)</li>
				<li style="margin-bottom:-1em"><strong>HP</strong> 5 (1d8 + 1)</li>
				<li style="text-align:right; margin-top:-1em"><strong>Carrying Capacity</strong> 195 lb.</li>
				<li><strong>Speed</strong> 40 ft.</li>
			</ul>
			<table style="text-align:center">
				<thead><tr><td> </td><td> </td><td>MOD</td><td>SAVE</td><td> </td><td> </td><td>MOD</td><td>SAVE</td><td> </td><td> </td><td>MOD</td><td>SAVE</td></tr></thead>
				<tr><td>STR</td><td>13</td><td>+1</td><td>+1</td><td>DEX</td><td>14</td><td>+2</td><td>+2</td><td>CON</td><td>12</td><td>+1</td><td>+1</td></tr>
				<tr><td>INT</td><td>3</td><td>-4</td><td>-4</td><td>WIS</td><td>12</td><td>+1</td><td>+3</td><td>CHA</td><td>7</td><td>-2</td><td>-2</td></tr>
			</table>
			<ul class="unstyled">
				<li><strong>Skills</strong> Perception +5</li>
				<li><strong>Senses</strong> Darkvision 60 ft., Passive Perception 15</li>
				<li><strong>Languages</strong> None</li>
				<li><strong>Challenge</strong> 1/8 (XP 25; PB +2)</li>
			</ul>
			<h4 style="margin-top:10px">Actions</h4>
			<ul class="unstyled">
				<li><strong><em>Bite. </em></strong><em>Melee Weapon Attack:</em> +2, reach 5 ft. <em>Hit:</em> 1 Piercing damage.</li>
			</ul>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-mounts-vehicles.xml
> +	</element>
```suggestion
	</element>

	<element name="Mule" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_MULE">
		<description>
			<h4 style="margin-top:0px" />
			<p><em>Medium Beast, Unaligned</em></p>
			<ul class="unstyled mb">
				<li style="margin-bottom:-1em"><strong>AC</strong> 10</li>
				<li style="text-align:right; margin-top:-1em"><strong>Initiative</strong> +0 (10)</li>
				<li style="margin-bottom:-1em"><strong>HP</strong> 11 (2d8 + 2)</li>
				<li style="text-align:right; margin-top:-1em"><strong>Carrying Capacity</strong> 420 lb.</li>
				<li><strong>Speed</strong> 40 ft.</li>
			</ul>
			<table style="text-align:center">
				<thead><tr><td> </td><td> </td><td>MOD</td><td>SAVE</td><td> </td><td> </td><td>MOD</td><td>SAVE</td><td> </td><td> </td><td>MOD</td><td>SAVE</td></tr></thead>
				<tr><td>STR</td><td>14</td><td>+2</td><td>+4</td><td>DEX</td><td>10</td><td>+0</td><td>+0</td><td>CON</td><td>13</td><td>+1</td><td>+1</td></tr>
				<tr><td>INT</td><td>2</td><td>-4</td><td>-4</td><td>WIS</td><td>10</td><td>+0</td><td>+0</td><td>CHA</td><td>5</td><td>-3</td><td>-3</td></tr>
			</table>
			<ul class="unstyled">
				<li><strong>Senses</strong> Passive Perception 10</li>
				<li><strong>Languages</strong> None</li>
				<li><strong>Challenge</strong> 1/8 (XP 25; PB +2)</li>
			</ul>
			<h4 style="margin-top:10px">Traits</h4>
			<ul class="unstyled">
				<li><strong><em>Beast of Burden. </em></strong><em>Melee Weapon Attack:</em> The mule counts as one size larger for the purpose of determining its carrying capacity.</li>
			</ul>
			<h4 style="margin-top:10px">Actions</h4>
			<ul class="unstyled">
				<li><strong><em>Hooves. </em></strong><em>Melee Weapon Attack:</em> +4, reach 5 ft. <em>Hit:</em> 4 (1d4 + 2) Bludgeoning damage.</li>
			</ul>
		</description>
		<setters>
			<set name="category">Mounts &amp; Vehicles</set>
			<set name="cost" currency="gp">8</set>
			<set name="weight" lb="0">—</set>
			<set name="type">Mount</set>
		</setters>
	</element>

```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-mounts-vehicles.xml
> +			<p><strong><em>Speed.</em></strong> 40 ft.<br/><strong><em>Carrying Capacity.</em></strong> 225 lb.</p>
```suggestion
			<h4 style="margin-top:0px" />
			<p><em>Medium Beast, Unaligned</em></p>
			<ul class="unstyled mb">
				<li style="margin-bottom:-1em"><strong>AC</strong> 10</li>
				<li style="text-align:right; margin-top:-1em"><strong>Initiative</strong> +0 (10)</li>
				<li style="margin-bottom:-1em"><strong>HP</strong> 11 (2d8 + 2)</li>
				<li style="text-align:right; margin-top:-1em"><strong>Carrying Capacity</strong> 225 lb.</li>
				<li><strong>Speed</strong> 40 ft.</li>
			</ul>
			<table style="text-align:center">
				<thead><tr><td> </td><td> </td><td>MOD</td><td>SAVE</td><td> </td><td> </td><td>MOD</td><td>SAVE</td><td> </td><td> </td><td>MOD</td><td>SAVE</td></tr></thead>
				<tr><td>STR</td><td>15</td><td>+2</td><td>+4</td><td>DEX</td><td>10</td><td>+0</td><td>+0</td><td>CON</td><td>13</td><td>+1</td><td>+1</td></tr>
				<tr><td>INT</td><td>2</td><td>-4</td><td>-4</td><td>WIS</td><td>11</td><td>+0</td><td>+0</td><td>CHA</td><td>7</td><td>-2</td><td>-2</td></tr>
			</table>
			<ul class="unstyled">
				<li><strong>Senses</strong> Passive Perception 10</li>
				<li><strong>Languages</strong> None</li>
				<li><strong>Challenge</strong> 1/8 (XP 25; PB +2)</li>
			</ul>
			<h4 style="margin-top:10px">Actions</h4>
			<ul class="unstyled">
				<li><strong><em>Hooves. </em></strong><em>Melee Weapon Attack:</em> +4, reach 5 ft. <em>Hit:</em> 4 (1d4 + 2) Bludgeoning damage.</li>
			</ul>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-mounts-vehicles.xml
> +	</element>
```suggestion
	</element>

```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-mounts-vehicles.xml
> +			<p><strong><em>Speed.</em></strong> 60 ft.<br/><strong><em>Carrying Capacity.</em></strong> 540 lb.</p>
```suggestion
			<h4 style="margin-top:0px" />
			<p><em>Large Beast, Unaligned</em></p>
			<ul class="unstyled mb">
				<li style="margin-bottom:-1em"><strong>AC</strong> 11</li>
				<li style="text-align:right; margin-top:-1em"><strong>Initiative</strong> +1 (11)</li>
				<li style="margin-bottom:-1em"><strong>HP</strong> 19 (3d10 + 3)</li>
				<li style="text-align:right; margin-top:-1em"><strong>Carrying Capacity</strong> 540 lb.</li>
				<li><strong>Speed</strong> 60 ft.</li>
			</ul>
			<table style="text-align:center">
				<thead><tr><td> </td><td> </td><td>MOD</td><td>SAVE</td><td> </td><td> </td><td>MOD</td><td>SAVE</td><td> </td><td> </td><td>MOD</td><td>SAVE</td></tr></thead>
				<tr><td>STR</td><td>18</td><td>+4</td><td>+4</td><td>DEX</td><td>12</td><td>+1</td><td>+1</td><td>CON</td><td>13</td><td>+1</td><td>+1</td></tr>
				<tr><td>INT</td><td>2</td><td>-4</td><td>-4</td><td>WIS</td><td>12</td><td>+1</td><td>+3</td><td>CHA</td><td>7</td><td>-2</td><td>-2</td></tr>
			</table>
			<ul class="unstyled">
				<li><strong>Senses</strong> Passive Perception 11</li>
				<li><strong>Languages</strong> None</li>
				<li><strong>Challenge</strong> 1/2 (XP 100; PB +2)</li>
			</ul>
			<h4 style="margin-top:10px">Actions</h4>
			<ul class="unstyled">
				<li><strong><em>Hooves. </em></strong><em>Melee Weapon Attack:</em> +6, reach 5 ft. <em>Hit:</em> 9 (2d4 + 4) Bludgeoning damage. lf the horse moved at least 20 feet straight toward the target immediately before the hit, the target takes an extra 5 (2d4) Bludgeoning damage and, if it is Huge or smaller, has the Prone condition.</li>
			</ul>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-mounts-vehicles.xml
> +	</element> -->
```suggestion
	</element>

```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-mounts-vehicles.xml
> +		</description>
```suggestion
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-mounts-vehicles.xml
> +	</element>
```suggestion
	</element>

```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-mounts-vehicles.xml
> +		</description>
```suggestion
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-mounts-vehicles.xml
> +	</element>
```suggestion
	</element>

```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-mounts-vehicles.xml
> +		</description>
```suggestion
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-mounts-vehicles.xml
> +	</element>
```suggestion
	</element>

```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-mounts-vehicles.xml
> +		</description>
```suggestion
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-mounts-vehicles.xml
> +	</element>
```suggestion
	</element>

```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-mounts-vehicles.xml
> +			<p>A saddle comes with a bit, a bridle, reins, and any other equipment needed to use the saddle. A Military Saddle gives Advantage on any ability check you make to remain mounted. An Exotic Saddle
```suggestion
			<p>A saddle comes with a bit, a bridle, reins, and any other equipment needed to use the saddle. An Exotic Saddle allows riding an aquatic or a flying mount.</p>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-mounts-vehicles.xml
> +	</element>
```suggestion
	</element>

```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-mounts-vehicles.xml
> +			<p>A saddle comes with a bit, a bridle, reins, and any other equipment needed to use the saddle. A Military Saddle gives Advantage on any ability check you make to remain mounted. An Exotic Saddle
```suggestion
			<p>A saddle comes with a bit, a bridle, reins, and any other equipment needed to use the saddle. A Military Saddle gives Advantage on any ability check you make to remain mounted.</p>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-mounts-vehicles.xml
> +	</element>
```suggestion
	</element>

```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-mounts-vehicles.xml
> +			<p>A saddle comes with a bit, a bridle, reins, and any other equipment needed to use the saddle. A Military Saddle gives Advantage on any ability check you make to remain mounted. An Exotic Saddle
```suggestion
			<p>A saddle comes with a bit, a bridle, reins, and any other equipment needed to use the saddle.</p>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-mounts-vehicles.xml
> +	</element> -->
```suggestion
	</element>

```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-mounts-vehicles.xml
> +		</description>
```suggestion
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-mounts-vehicles.xml
> +	</element>
```suggestion
	</element>

	<!-- doesn't seem to be appropriate for an "Item", but instead of being completely removed, it has been commented out in case someone finds this item useful -->
	<!-- <element name="Stabling (per day)" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_STABLING">
		<setters>
			<set name="category">Mounts &amp; Vehicles</set>
			<set name="cost" currency="sp">5</set>
			<set name="weight" lb="0">0 lb.</set>
			<set name="stackable">true</set>
		</setters>
	</element> -->

```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-mounts-vehicles.xml
> +		</description>
```suggestion
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-mounts-vehicles.xml
> +<!-- Previously introduced in 2014 DMG -->
```suggestion
	</element> 

```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-mounts-vehicles.xml
> +	</element>
```suggestion
	</element>

```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-mounts-vehicles.xml
> +	</element>
```suggestion
	</element>

```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-mounts-vehicles.xml
> +	</element>
```suggestion
	</element>

```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-mounts-vehicles.xml
> +	</element>
```suggestion
	</element>

```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-mounts-vehicles.xml
> +	</element>
```suggestion
	</element>

```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-mounts-vehicles.xml
> +	</element>
```suggestion
	</element>

```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-packs.xml
> +		<author url="http://dnd.wizards.com/products/tabletop-games/rpg-products/rpg_playershandbook">Wizards of the Coast</author>
```suggestion
		<description>Equipment Packs from the Player’s Handbook 2024.</description>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-packs.xml
> +	</info>
```suggestion
	</info>

```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-packs.xml
> +			<item>ID_WOTC_PHB24_ITEM_ROPE</item>
```suggestion
			<item>ID_WOTC_PHB24_ITEM_BACKPACK</item>
			<item>ID_WOTC_PHB24_ITEM_BALL_BEARINGS</item>
			<item>ID_WOTC_PHB24_ITEM_STRING</item>
			<item>ID_WOTC_PHB24_ITEM_BELL</item>
			<item amount="10">ID_WOTC_PHB24_ITEM_CANDLE</item>
			<item>ID_WOTC_PHB24_ITEM_CROWBAR</item>
			<item>ID_WOTC_PHB24_ITEM_LANTERN_HOODED</item>
			<item amount="7">ID_WOTC_PHB24_ITEM_OIL</item>
			<item amount="5">ID_WOTC_PHB24_ITEM_RATIONS</item>
			<item>ID_WOTC_PHB24_ITEM_ROPE</item>
			<item>ID_WOTC_PHB24_ITEM_TINDERBOX</item>
			<item>ID_WOTC_PHB24_ITEM_WATERSKIN</item>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-packs.xml
> +	</element>
```suggestion
	</element>

```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-packs.xml
> +			<item>ID_WOTC_PHB24_ITEM_TINDERBOX</item>
```suggestion
			<item>ID_WOTC_PHB24_ITEM_CHEST</item>
			<item>ID_WOTC_PHB24_ITEM_CLOTHES_FINE</item>
			<item>ID_WOTC_PHB24_ITEM_INK</item>
			<item amount="5">ID_WOTC_PHB24_ITEM_INK_PEN</item>
			<item>ID_WOTC_PHB24_ITEM_LAMP</item>
			<item amount="2">ID_WOTC_PHB24_ITEM_CASE_MAP_OR_SCROLL</item>
			<item amount="4">ID_WOTC_PHB24_ITEM_OIL</item>
			<item amount="5">ID_WOTC_PHB24_ITEM_PAPER</item>
			<item amount="5">ID_WOTC_PHB24_ITEM_PARCHMENT</item>
			<item>ID_WOTC_PHB24_ITEM_PERFUME</item>
			<item>ID_WOTC_PHB24_ITEM_TINDERBOX</item>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-packs.xml
> +	</element>
```suggestion
	</element>

```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-packs.xml
> +			<item amount="10">ID_WOTC_PHB24_ITEM_RATIONS_1DAY</item>
```suggestion
			<item amount="2">ID_WOTC_PHB24_ITEM_OIL</item>
			<item amount="10">ID_WOTC_PHB24_ITEM_RATIONS</item>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-packs.xml
> +	</element>
```suggestion
	</element>

```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-packs.xml
> +			<item amount="9">ID_WOTC_PHB24_ITEM_RATIONS_1DAY</item>
```suggestion
			<item amount="8">ID_WOTC_PHB24_ITEM_OIL</item>
			<item amount="9">ID_WOTC_PHB24_ITEM_RATIONS</item>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-packs.xml
> +	</element>
```suggestion
	</element>

```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-packs.xml
> +			<item amount="10">ID_WOTC_PHB24_ITEM_RATIONS_1DAY</item>
```suggestion
			<item amount="2">ID_WOTC_PHB24_ITEM_OIL</item>
			<item amount="10">ID_WOTC_PHB24_ITEM_RATIONS</item>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-packs.xml
> +	</element>
```suggestion
	</element>

```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-packs.xml
> +			<item amount="7">ID_WOTC_PHB24_ITEM_RATIONS_1DAY</item>
```suggestion
			<item>ID_WOTC_PHB24_ITEM_HOLY_WATER</item>
			<item>ID_WOTC_PHB24_ITEM_LAMP</item>
			<item amount="7">ID_WOTC_PHB24_ITEM_RATIONS</item>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-packs.xml
> +	</element>
```suggestion
	</element>

```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-packs.xml
> +			<item>ID_WOTC_PHB24_ITEM_TINDERBOX</item>
```suggestion
			<item>ID_WOTC_PHB24_ITEM_BACKPACK</item>
			<item>ID_WOTC_PHB24_ITEM_BOOK</item>
			<item>ID_WOTC_PHB24_ITEM_INK</item>
			<item>ID_WOTC_PHB24_ITEM_INK_PEN</item>
			<item>ID_WOTC_PHB24_ITEM_LAMP</item>
			<item amount="10">ID_WOTC_PHB24_ITEM_OIL</item>
			<item amount="10">ID_WOTC_PHB24_ITEM_PARCHMENT</item>
			<item>ID_WOTC_PHB24_ITEM_TINDERBOX</item>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-packs.xml
> +</elements>
```suggestion
</elements>

```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-tools.xml
> +		<author url="http://dnd.wizards.com/products/tabletop-games/rpg-products/rpg_playershandbook">Wizards of the Coast</author>
```suggestion
		<description>Tools, Gaming Sets and Musical Instruments from the Player’s Handbook 2024.</description>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-tools.xml
> +	</info>
```suggestion
	</info>

```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-tools.xml
> +			</table>
```suggestion
			<ul class="unstyled">
				<li style="margin-bottom:-1em"><strong>Ability:</strong> Intelligence</li>
				<li style="text-align:right; margin-top:-1em"><strong>Weight:</strong> 8 lb.</li>
				<li><strong>Utilize:</strong> Identify a substance (DC 15), or start a fire (DC 15)</li>
				<li><strong>Craft:</strong> Acid, Alchemist's Fire, Component Pouch, Oil, Paper, Perfume</li>
			</ul>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-tools.xml
> +	</element>
```suggestion
	</element>

```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-tools.xml
> +			</table>
```suggestion
			<ul class="unstyled">
				<li style="margin-bottom:-1em"><strong>Ability:</strong> Intelligence</li>
				<li style="text-align:right; margin-top:-1em"><strong>Weight:</strong> 9 lb.</li>
				<li><strong>Utilize:</strong> Detect poisoned drink (DC 15), or identify alcohol (DC 10)</li>
				<li><strong>Craft:</strong> Antitoxin</li>
			</ul>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-tools.xml
> +	</element>
```suggestion
	</element>

```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-tools.xml
> +			</table>
```suggestion
			<ul class="unstyled">
				<li style="margin-bottom:-1em"><strong>Ability:</strong> Dexterity</li>
				<li style="text-align:right; margin-top:-1em"><strong>Weight:</strong> 5 lb.</li>
				<li><strong>Utilize:</strong> Write text with impressive flourishes that guard against forgery (DC 15)</li>
				<li><strong>Craft:</strong> Ink, <i>Spell Scroll</i></li>
			</ul>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-tools.xml
> +	</element>
```suggestion
	</element>

```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-tools.xml
> +			</table>
```suggestion
			<ul class="unstyled">
				<li style="margin-bottom:-1em"><strong>Ability:</strong> Strength</li>
				<li style="text-align:right; margin-top:-1em"><strong>Weight:</strong> 6 lb.</li>
				<li><strong>Utilize:</strong> Seal or pry open a door or container (DC 20)</li>
				<li><strong>Craft:</strong> Club, Greatclub, Quarterstaff, Barrel, Chest, Ladder, Pole, Portable Ram, Torch</li>
			</ul>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-tools.xml
> +	</element>
```suggestion
	</element>

```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-tools.xml
> +			</table>
```suggestion
			<ul class="unstyled">
				<li style="margin-bottom:-1em"><strong>Ability:</strong> Wisdom</li>
				<li style="text-align:right; margin-top:-1em"><strong>Weight:</strong> 6 lb.</li>
				<li><strong>Utilize:</strong> Draft a map of a small area (DC 15)</li>
				<li><strong>Craft:</strong> Map</li>
			</ul>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-tools.xml
> +	</element>
```suggestion
	</element>

```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-tools.xml
> +			</table>
```suggestion
			<ul class="unstyled">
				<li style="margin-bottom:-1em"><strong>Ability:</strong> Dexterity</li>
				<li style="text-align:right; margin-top:-1em"><strong>Weight:</strong> 5 lb.</li>
				<li><strong>Utilize:</strong> Modify footwear to give Advantage on the wearer’s next Dexterity (Acrobatics) check (DC 10)</li>
				<li><strong>Craft:</strong> Climber's Kit</li>
			</ul>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-tools.xml
> +	</element>
```suggestion
	</element>

```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-tools.xml
> +			</table>
```suggestion
			<ul class="unstyled">
				<li style="margin-bottom:-1em"><strong>Ability:</strong> Wisdom</li>
				<li style="text-align:right; margin-top:-1em"><strong>Weight:</strong> 8 lb.</li>
				<li><strong>Utilize:</strong> Improve food’s flavor (DC 10), or detect spoiled or poisoned food (DC 15)</li>
				<li><strong>Craft:</strong> Rations</li>
			</ul>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-tools.xml
> +	</element>
Disguise Kit and Forgery Kit are moved below 
```suggestion
	</element>

```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-tools.xml
> +			</table>
```suggestion
			<ul class="unstyled">
				<li style="margin-bottom:-1em"><strong>Ability:</strong> Intelligence</li>
				<li style="text-align:right; margin-top:-1em"><strong>Weight:</strong> 5 lb.</li>
				<li><strong>Utilize:</strong> Discern what a glass object held in the past 24 hours (DC 15)</li>
				<li><strong>Craft:</strong> Glass Bottle, Magnifying Glass, Spyglass, Vial</li>
			</ul>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-tools.xml
> +	</element>
Herbalism Kit is moved below
```suggestion
	</element>

```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-tools.xml
> +			</table>
```suggestion
			<ul class="unstyled">
				<li style="margin-bottom:-1em"><strong>Ability:</strong> Intelligence</li>
				<li style="text-align:right; margin-top:-1em"><strong>Weight:</strong> 2 lb.</li>
				<li><strong>Utilize:</strong> Discern a gem’s value (DC 15)</li>
				<li><strong>Craft:</strong> Arcane Focus, Holy Symbol</li>
			</ul>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-tools.xml
> +	</element>
```suggestion
	</element>

```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-tools.xml
> +			</table>
```suggestion
			<ul class="unstyled">
				<li style="margin-bottom:-1em"><strong>Ability:</strong> Dexterity</li>
				<li style="text-align:right; margin-top:-1em"><strong>Weight:</strong> 5 lb.</li>
				<li><strong>Utilize:</strong> Add a design to a leather item (DC 10)</li>
				<li><strong>Craft:</strong> Sling, Whip, Hide Armor, Leather Armor, Studded Leather Armor, Backpack, Crossbow Bolt Case, Map or Scroll Case, Parchment, Pouch, Quiver, Waterskin</li>
			</ul>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-tools.xml
> +	</element>
```suggestion
	</element>

```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-tools.xml
> +			</table>
```suggestion
			<ul class="unstyled">
				<li style="margin-bottom:-1em"><strong>Ability:</strong> Strength</li>
				<li style="text-align:right; margin-top:-1em"><strong>Weight:</strong> 8 lb.</li>
				<li><strong>Utilize:</strong> Chisel a symbol or hole in stone (DC 10)</li>
				<li><strong>Craft:</strong> Block and Tackle</li>
			</ul>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-tools.xml
> +	</element>
Navigator’s Tools are moved below
```suggestion
	</element>

```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-tools.xml
> +			</table>
```suggestion
			<ul class="unstyled">
				<li style="margin-bottom:-1em"><strong>Ability:</strong> Wisdom</li>
				<li style="text-align:right; margin-top:-1em"><strong>Weight:</strong> 5 lb.</li>
				<li><strong>Utilize:</strong> Paint a recognizable image of something you've seen (DC 10)</li>
				<li><strong>Craft:</strong> Druidic Focus, Holy Symbol</li>
			</ul>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-tools.xml
> +	</element>
Poisoner's Kit is moved below
```suggestion
	</element>

```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-tools.xml
> +			</table>
```suggestion
			<ul class="unstyled">
				<li style="margin-bottom:-1em"><strong>Ability:</strong> Intelligence</li>
				<li style="text-align:right; margin-top:-1em"><strong>Weight:</strong> 3 lb.</li>
				<li><strong>Utilize:</strong> Discern what a ceramic object held in the past 24 hours (DC 15)</li>
				<li><strong>Craft:</strong> Jug, Lamp</li>
			</ul>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-tools.xml
> +	</element>
```suggestion
	</element>

```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-tools.xml
> +			</table>
```suggestion
			<ul class="unstyled">
				<li style="margin-bottom:-1em"><strong>Ability:</strong> Strength</li>
				<li style="text-align:right; margin-top:-1em"><strong>Weight:</strong> 8 lb.</li>
				<li><strong>Utilize:</strong> Pry open a door or container (DC 20)</li>
				<li><strong>Craft:</strong> Any Melee weapon (except Club, Greatclub, Quarterstaff, and Whip), Medium armor (except Hide), Heavy armor, Ball Bearings, Bucket, Caltrops, Chain, Crowbar, Firearm Bullets, Grappling Hook, Iron Pot, Iron Spikes, Sling Bullets</li>
			</ul>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-tools.xml
> +	</element>
Thieves’ Tools are moved below
```suggestion
	</element>

```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-tools.xml
> +			</table>
```suggestion
			<ul class="unstyled">
				<li style="margin-bottom:-1em"><strong>Ability:</strong> Dexterity</li>
				<li style="text-align:right; margin-top:-1em"><strong>Weight:</strong> 10 lb.</li>
				<li><strong>Utilize:</strong> Assemble a Tiny item composed of scrap, which falls apart in 1 minute (DC 20)</li>
				<li><strong>Craft:</strong> Musket, Pistol, Bell, Bullseye Lantern, Flask, Hooded Lantern, Hunting Trap, Lock, Manacles, Mirror, Shovel, Signal Whistle, Tinderbox</li>
			</ul>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-tools.xml
> +	</element>
```suggestion
	</element>

```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-tools.xml
> +			</table>
```suggestion
			<ul class="unstyled">
				<li style="margin-bottom:-1em"><strong>Ability:</strong> Dexterity</li>
				<li style="text-align:right; margin-top:-1em"><strong>Weight:</strong> 5 lb.</li>
				<li><strong>Utilize:</strong> Mend a tear in clothing (DC 10), or sew a Tiny design (DC 10)</li>
				<li><strong>Craft:</strong> Padded Armor, Basket, Bedroll, Blanket, Fine Clothes, Net, Robe, Rope, Sack, String, Tent, Traveler’s Clothes</li>
			</ul>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-tools.xml
> +	</element>
```suggestion
	</element>

```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-tools.xml
> +			</table>
```suggestion
			<ul class="unstyled">
				<li style="margin-bottom:-1em"><strong>Ability:</strong> Dexterity</li>
				<li style="text-align:right; margin-top:-1em"><strong>Weight:</strong> 5 lb.</li>
				<li><strong>Utilize:</strong> Carve a pattern in wood (DC 10)</li>
				<li><strong>Craft:</strong> Club, Greatclub, Quarterstaff, Ranged weapons (except Pistol, Musket, and Sling), Arcane Focus, Arrows, Bolts, Druidic Focus, Ink Pen, Needles</li>
			</ul>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-tools.xml
> +	</element>
```suggestion
	</element>

	<element name="Disguise Kit" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_TOOL_DISGUISE_KIT">
		<description>
			<ul class="unstyled">
				<li style="margin-bottom:-1em"><strong>Ability:</strong> Charisma</li>
				<li style="text-align:right; margin-top:-1em"><strong>Weight:</strong> 3 lb.</li>
				<li><strong>Utilize:</strong> Apply makeup (DC 10)</li>
				<li><strong>Craft:</strong> Costume</li>
			</ul>
		</description>
		<setters>
			<set name="category">Tools</set>
			<set name="cost" currency="gp">25</set>
			<set name="weight" lb="3">3 lbs.</set>
			<set name="type">Tool</set>
			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_TOOL_PROFICIENCY_DISGUISE_KIT</set>
		</setters>
	</element>

	<element name="Forgery Kit" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_TOOL_FORGERY_KIT">
		<description>
			<ul class="unstyled">
				<li style="margin-bottom:-1em"><strong>Ability:</strong> Dexterity</li>
				<li style="text-align:right; margin-top:-1em"><strong>Weight:</strong> 5 lb.</li>
				<li><strong>Utilize:</strong> Mimic 10 or fewer words of someone else’s handwriting (DC 15), or duplicate a wax seal (DC 20)</li>
			</ul>
		</description>
		<setters>
			<set name="category">Tools</set>
			<set name="cost" currency="gp">15</set>
			<set name="weight" lb="5">5 lbs.</set>
			<set name="type">Tool</set>
			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_TOOL_PROFICIENCY_FORGERY_KIT</set>
		</setters>
	</element>

```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-tools.xml
> +			</table>
```suggestion
			<ul class="unstyled">
				<li style="margin-bottom:-1em"><strong>Ability:</strong> Wisdom</li>
				<li style="text-align:right; margin-top:-1em"><strong>Weight:</strong> — lb.</li>
				<li><strong>Utilize:</strong> Discern whether someone is cheating (DC 10), or win the game (DC 20)</li>
			</ul>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-tools.xml
> +	</element>
```suggestion
	</element>

```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-tools.xml
> +			</table>
```suggestion
			<ul class="unstyled">
				<li style="margin-bottom:-1em"><strong>Ability:</strong> Wisdom</li>
				<li style="text-align:right; margin-top:-1em"><strong>Weight:</strong> — lb.</li>
				<li><strong>Utilize:</strong> Discern whether someone is cheating (DC 10), or win the game (DC 20)</li>
			</ul>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-tools.xml
> +			<set name="cost" currency="gp">1</set>
```suggestion
			<set name="cost" currency="sp">1</set>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-tools.xml
> +	</element>
```suggestion
	</element>

```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-tools.xml
> +			</table>
```suggestion
			<ul class="unstyled">
				<li style="margin-bottom:-1em"><strong>Ability:</strong> Wisdom</li>
				<li style="text-align:right; margin-top:-1em"><strong>Weight:</strong> — lb.</li>
				<li><strong>Utilize:</strong> Discern whether someone is cheating (DC 10), or win the game (DC 20)</li>
			</ul>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-tools.xml
> +			<set name="cost" currency="sp">5</set>
```suggestion
			<set name="keywords">game, gaming set</set>
			<set name="category">Tools</set>
			<set name="cost" currency="sp">1</set>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-tools.xml
> +	</element>
```suggestion
	</element>

```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-tools.xml
> +			</table>
```suggestion
			<ul class="unstyled">
				<li style="margin-bottom:-1em"><strong>Ability:</strong> Wisdom</li>
				<li style="text-align:right; margin-top:-1em"><strong>Weight:</strong> — lb.</li>
				<li><strong>Utilize:</strong> Discern whether someone is cheating (DC 10), or win the game (DC 20)</li>
			</ul>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-tools.xml
> +			<set name="cost" currency="gp">1</set>
```suggestion
			<set name="keywords">game, gaming set</set>
			<set name="category">Tools</set>
			<set name="cost" currency="sp">1</set>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-tools.xml
> +
```suggestion

	<element name="Herbalism Kit" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_TOOL_HERBALISM_KIT">
		<description>
			<ul class="unstyled">
				<li style="margin-bottom:-1em"><strong>Ability:</strong> Intelligence</li>
				<li style="text-align:right; margin-top:-1em"><strong>Weight:</strong> 3 lb.</li>
				<li><strong>Utilize:</strong> Identify a plant (DC 10)</li>
				<li><strong>Craft:</strong> Antitoxin, Candle, Healer’s Kit, <i>Potion of Healing</i></li>
			</ul>
		</description>
		<setters>
			<set name="category">Tools</set>
			<set name="cost" currency="gp">5</set>
			<set name="weight" lb="3">3 lbs.</set>
			<set name="type">Tool</set>
			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_TOOL_PROFICIENCY_HERBALISM_KIT</set>
		</setters>
	</element>

	<element name="Bagpipes" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_INSTRUMENT_BAGPIPES">
		<description>
			<ul class="unstyled">
				<li style="margin-bottom:-1em"><strong>Ability:</strong> Charisma</li>
				<li style="text-align:right; margin-top:-1em"><strong>Weight:</strong> 6 lb.</li>
				<li><strong>Utilize:</strong> Play a known tune (DC 10), or improvise a song (DC 15)</li>
			</ul>
		</description>
		<setters>
			<set name="category">Musical Instruments</set>
			<set name="cost" currency="gp">30</set>
			<set name="weight" lb="6">6 lbs.</set>
			<set name="slot">onehand</set>
			<set name="type">Tool</set>
			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_TOOL_PROFICIENCY_BAGPIPES</set>
		</setters>
	</element>

	<element name="Drum" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_INSTRUMENT_DRUM">
		<description>
			<ul class="unstyled">
				<li style="margin-bottom:-1em"><strong>Ability:</strong> Charisma</li>
				<li style="text-align:right; margin-top:-1em"><strong>Weight:</strong> 3 lb.</li>
				<li><strong>Utilize:</strong> Play a known tune (DC 10), or improvise a song (DC 15)</li>
			</ul>
		</description>
		<setters>
			<set name="category">Musical Instruments</set>
			<set name="cost" currency="gp">6</set>
			<set name="weight" lb="3">3 lbs.</set>
			<set name="slot">onehand</set>
			<set name="type">Tool</set>
			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_TOOL_PROFICIENCY_DRUM</set>
		</setters>
	</element>

	<element name="Dulcimer" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_INSTRUMENT_DULCIMER">
		<description>
			<ul class="unstyled">
				<li style="margin-bottom:-1em"><strong>Ability:</strong> Charisma</li>
				<li style="text-align:right; margin-top:-1em"><strong>Weight:</strong> 10 lb.</li>
				<li><strong>Utilize:</strong> Play a known tune (DC 10), or improvise a song (DC 15)</li>
			</ul>
		</description>
		<setters>
			<set name="category">Musical Instruments</set>
			<set name="cost" currency="gp">25</set>
			<set name="weight" lb="10">10 lbs.</set>
			<set name="slot">onehand</set>
			<set name="type">Tool</set>
			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_TOOL_PROFICIENCY_DULCIMER</set>
		</setters>
	</element>

	<element name="Flute" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_INSTRUMENT_FLUTE">
		<description>
			<ul class="unstyled">
				<li style="margin-bottom:-1em"><strong>Ability:</strong> Charisma</li>
				<li style="text-align:right; margin-top:-1em"><strong>Weight:</strong> 1 lb.</li>
				<li><strong>Utilize:</strong> Play a known tune (DC 10), or improvise a song (DC 15)</li>
			</ul>
		</description>
		<setters>
			<set name="category">Musical Instruments</set>
			<set name="cost" currency="gp">2</set>
			<set name="weight" lb="1">1 lbs.</set>
			<set name="slot">onehand</set>
			<set name="type">Tool</set>
			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_TOOL_PROFICIENCY_FLUTE</set>
		</setters>
	</element>

	<element name="Horn" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_INSTRUMENT_HORN">
		<description>
			<ul class="unstyled">
				<li style="margin-bottom:-1em"><strong>Ability:</strong> Charisma</li>
				<li style="text-align:right; margin-top:-1em"><strong>Weight:</strong> 2 lb.</li>
				<li><strong>Utilize:</strong> Play a known tune (DC 10), or improvise a song (DC 15)</li>
			</ul>
		</description>
		<setters>
			<set name="category">Musical Instruments</set>
			<set name="cost" currency="gp">3</set>
			<set name="weight" lb="2">2 lbs.</set>
			<set name="slot">onehand</set>
			<set name="type">Tool</set>
			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_TOOL_PROFICIENCY_HORN</set>
		</setters>
	</element>

	<element name="Lute" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_INSTRUMENT_LUTE">
		<description>
			<ul class="unstyled">
				<li style="margin-bottom:-1em"><strong>Ability:</strong> Charisma</li>
				<li style="text-align:right; margin-top:-1em"><strong>Weight:</strong> 2 lb.</li>
				<li><strong>Utilize:</strong> Play a known tune (DC 10), or improvise a song (DC 15)</li>
			</ul>
		</description>
		<setters>
			<set name="category">Musical Instruments</set>
			<set name="cost" currency="gp">35</set>
			<set name="weight" lb="2">2 lbs.</set>
			<set name="slot">onehand</set>
			<set name="type">Tool</set>
			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_TOOL_PROFICIENCY_LUTE</set>
		</setters>
	</element>

	<element name="Lyre" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_INSTRUMENT_LYRE">
		<description>
			<ul class="unstyled">
				<li style="margin-bottom:-1em"><strong>Ability:</strong> Charisma</li>
				<li style="text-align:right; margin-top:-1em"><strong>Weight:</strong> 2 lb.</li>
				<li><strong>Utilize:</strong> Play a known tune (DC 10), or improvise a song (DC 15)</li>
			</ul>
		</description>
		<setters>
			<set name="category">Musical Instruments</set>
			<set name="cost" currency="gp">30</set>
			<set name="weight" lb="2">2 lbs.</set>
			<set name="slot">onehand</set>
			<set name="type">Tool</set>
			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_TOOL_PROFICIENCY_LYRE</set>
		</setters>
	</element>

	<element name="Pan flute" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_INSTRUMENT_PANFLUTE">
		<description>
			<ul class="unstyled">
				<li style="margin-bottom:-1em"><strong>Ability:</strong> Charisma</li>
				<li style="text-align:right; margin-top:-1em"><strong>Weight:</strong> 2 lb.</li>
				<li><strong>Utilize:</strong> Play a known tune (DC 10), or improvise a song (DC 15)</li>
			</ul>
		</description>
		<setters>
			<set name="category">Musical Instruments</set>
			<set name="cost" currency="gp">12</set>
			<set name="weight" lb="2">2 lbs.</set>
			<set name="slot">onehand</set>
			<set name="type">Tool</set>
			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_TOOL_PROFICIENCY_PAN_FLUTE</set>
		</setters>
	</element>

	<element name="Shawm" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_INSTRUMENT_SHAWM">
		<description>
			<ul class="unstyled">
				<li style="margin-bottom:-1em"><strong>Ability:</strong> Charisma</li>
				<li style="text-align:right; margin-top:-1em"><strong>Weight:</strong> 1 lb.</li>
				<li><strong>Utilize:</strong> Play a known tune (DC 10), or improvise a song (DC 15)</li>
			</ul>
		</description>
		<setters>
			<set name="category">Musical Instruments</set>
			<set name="cost" currency="gp">2</set>
			<set name="weight" lb="1">1 lbs.</set>
			<set name="slot">onehand</set>
			<set name="type">Tool</set>
			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_TOOL_PROFICIENCY_SHAWM</set>
		</setters>
	</element>

	<element name="Viol" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_INSTRUMENT_VIOL">
		<description>
			<ul class="unstyled">
				<li style="margin-bottom:-1em"><strong>Ability:</strong> Charisma</li>
				<li style="text-align:right; margin-top:-1em"><strong>Weight:</strong> 1 lb.</li>
				<li><strong>Utilize:</strong> Play a known tune (DC 10), or improvise a song (DC 15)</li>
			</ul>
		</description>
		<setters>
			<set name="category">Musica [...]

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +		<name>Weapons</name>
```suggestion
		<name>Weapons</name>
		<description>Weapons from the Player’s Handbook 2024.</description>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +	<!-- simple -->
```suggestion
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +		<supports>ID_INTERNAL_WEAPON_CATEGORY_SIMPLE_MELEE, ID_INTERNAL_DAMAGE_TYPE_BLUDGEONING, ID_WOTC_PHB24_WEAPON_PROPERTY_LIGHT, ID_INTERNAL_WEAPON_GROUP_CLUBS, ID_WOTC_PHB24_WEAPON_PROPERTY_SLOW</sup
```suggestion
		<supports>ID_INTERNAL_WEAPON_CATEGORY_SIMPLE_MELEE, ID_INTERNAL_DAMAGE_TYPE_BLUDGEONING, ID_INTERNAL_WEAPON_PROPERTY_LIGHT, ID_INTERNAL_WEAPON_GROUP_CLUBS, ID_WOTC_PHB24_WEAPON_PROPERTY_SLOW</supports>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +			<p></p>
```suggestion
			<div class="sidebar" style="margin-top:10px">
				<h5>MASTERY</h5>
				<p><b>Slow.</b> If you hit a creature with this weapon and deal damage to it, you can reduce its Speed by 10 feet until the start of your next turn. If the creature is hit more than once by weapons that have this property, the Speed reduction doesn't exceed 10 feet.</p>
			</div>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_WEAPON_PROFICIENCY_CLUB</set>
```suggestion
			<set name="category">Weapons</set>
			<set name="damage" type="bludgeoning">1d4</set>
			<set name="weight" lb="2">2 lb.</set>
			<set name="cost" currency="sp">1</set>
			<set name="slot">onehand</set>
			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_WEAPON_PROFICIENCY_CLUB</set>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +	</element>
```suggestion
	</element>

```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +		<supports>ID_INTERNAL_WEAPON_CATEGORY_SIMPLE_MELEE, ID_INTERNAL_DAMAGE_TYPE_PIERCING, ID_WOTC_PHB24_WEAPON_PROPERTY_FINESSE, ID_WOTC_PHB24_WEAPON_PROPERTY_LIGHT, ID_WOTC_PHB24_WEAPON_PROPERTY_THROW
```suggestion
		<supports>ID_INTERNAL_WEAPON_CATEGORY_SIMPLE_MELEE, ID_INTERNAL_DAMAGE_TYPE_PIERCING, ID_INTERNAL_WEAPON_PROPERTY_FINESSE, ID_INTERNAL_WEAPON_PROPERTY_LIGHT, ID_INTERNAL_WEAPON_PROPERTY_THROWN, ID_WOTC_PHB24_WEAPON_PROPERTY_NICK</supports>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +			<p></p>
```suggestion
			<div class="sidebar" style="margin-top:10px">
				<h5>MASTERY</h5>
				<p><b>Nick.</b> When you make the extra attack of the Light property, you can make it as part of the Attack action instead of as a Bonus Action. You can make this extra attack only once per turn.</p>
			</div>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_WEAPON_PROFICIENCY_DAGGER</set>
```suggestion
			<set name="category">Weapons</set>
			<set name="damage" type="piercing">1d4</set>
			<set name="range">20/60</set>
			<set name="weight" lb="1">1 lb.</set>
			<set name="cost" currency="gp">2</set>
			<set name="slot">onehand</set>
			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_WEAPON_PROFICIENCY_DAGGER</set>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +	</element>
```suggestion
	</element>

```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +		<supports>ID_INTERNAL_WEAPON_CATEGORY_SIMPLE_MELEE, ID_INTERNAL_DAMAGE_TYPE_BLUDGEONING, ID_WOTC_PHB24_WEAPON_PROPERTY_TWOHANDED, ID_INTERNAL_WEAPON_GROUP_CLUBS, ID_WOTC_PHB24_WEAPON_PROPERTY_PUSH<
```suggestion
		<supports>ID_INTERNAL_WEAPON_CATEGORY_SIMPLE_MELEE, ID_INTERNAL_DAMAGE_TYPE_BLUDGEONING, ID_INTERNAL_WEAPON_PROPERTY_TWOHANDED, ID_INTERNAL_WEAPON_GROUP_CLUBS, ID_WOTC_PHB24_WEAPON_PROPERTY_PUSH</supports>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +			<p></p>
```suggestion
			<div class="sidebar" style="margin-top:10px">
				<h5>MASTERY</h5>
				<p><b>Push.</b> If you hit a creature with this weapon, you can push the creature up to 10 feet straight away from yourself if it is Large or smaller.</p>
			</div>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_WEAPON_PROFICIENCY_GREATCLUB</set>
```suggestion
			<set name="category">Weapons</set>
			<set name="damage" type="bludgeoning">1d8</set>
			<set name="weight" lb="10">10 lb.</set>
			<set name="cost" currency="sp">2</set>
			<set name="slot">twohand</set>
			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_WEAPON_PROFICIENCY_GREATCLUB</set>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +	</element>
```suggestion
	</element>

```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +		<supports>ID_INTERNAL_WEAPON_CATEGORY_SIMPLE_MELEE, ID_INTERNAL_DAMAGE_TYPE_SLASHING, ID_WOTC_PHB24_WEAPON_PROPERTY_LIGHT, ID_WOTC_PHB24_WEAPON_PROPERTY_THROWN, ID_INTERNAL_WEAPON_GROUP_AXES, ID_WO
```suggestion
		<supports>ID_INTERNAL_WEAPON_CATEGORY_SIMPLE_MELEE, ID_INTERNAL_DAMAGE_TYPE_SLASHING, ID_INTERNAL_WEAPON_PROPERTY_LIGHT, ID_INTERNAL_WEAPON_PROPERTY_THROWN, ID_INTERNAL_WEAPON_GROUP_AXES, ID_WOTC_PHB24_WEAPON_PROPERTY_VEX</supports>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +			<p></p>
```suggestion
			<div class="sidebar" style="margin-top:10px">
				<h5>MASTERY</h5>
				<p><b>Vex.</b> If you hit a creature with this weapon and deal damage to the creature, you have Advantage on your next attack roll against that creature before the end of your next turn.</p>
			</div>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_WEAPON_PROFICIENCY_HANDAXE</set>
```suggestion
			<set name="category">Weapons</set>
			<set name="damage" type="slashing">1d6</set>
			<set name="range">20/60</set>
			<set name="weight" lb="2">2 lb.</set>
			<set name="cost" currency="gp">5</set>
			<set name="slot">onehand</set>
			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_WEAPON_PROFICIENCY_HANDAXE</set>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +	</element>
```suggestion
	</element>

```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +		<supports>ID_INTERNAL_WEAPON_CATEGORY_SIMPLE_MELEE, ID_INTERNAL_DAMAGE_TYPE_PIERCING, ID_WOTC_PHB24_WEAPON_PROPERTY_THROWN, ID_WOTC_PHB24_WEAPON_PROPERTY_SLOW</supports>
```suggestion
		<supports>ID_INTERNAL_WEAPON_CATEGORY_SIMPLE_MELEE, ID_INTERNAL_DAMAGE_TYPE_PIERCING, ID_INTERNAL_WEAPON_PROPERTY_THROWN, ID_WOTC_PHB24_WEAPON_PROPERTY_SLOW</supports>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +			<p></p>
```suggestion
			<div class="sidebar" style="margin-top:10px">
				<h5>MASTERY</h5>
				<p><b>Slow.</b> If you hit a creature with this weapon and deal damage to it, you can reduce its Speed by 10 feet until the start of your next turn. If the creature is hit more than once by weapons that have this property, the Speed reduction doesn't exceed 10 feet.</p>
			</div>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_WEAPON_PROFICIENCY_JAVELIN</set>
```suggestion
			<set name="category">Weapons</set>
			<set name="damage" type="piercing">1d6</set>
			<set name="range">30/120</set>
			<set name="weight" lb="2">2 lb.</set>
			<set name="cost" currency="sp">5</set>
			<set name="slot">onehand</set>
			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_WEAPON_PROFICIENCY_JAVELIN</set>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +	</element>
```suggestion
	</element>

```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +		<supports>ID_INTERNAL_WEAPON_CATEGORY_SIMPLE_MELEE, ID_INTERNAL_DAMAGE_TYPE_BLUDGEONING, ID_WOTC_PHB24_WEAPON_PROPERTY_LIGHT, ID_WOTC_PHB24_WEAPON_PROPERTY_THROWN, ID_INTERNAL_WEAPON_GROUP_HAMMERS,
```suggestion
		<supports>ID_INTERNAL_WEAPON_CATEGORY_SIMPLE_MELEE, ID_INTERNAL_DAMAGE_TYPE_BLUDGEONING, ID_INTERNAL_WEAPON_PROPERTY_LIGHT, ID_INTERNAL_WEAPON_PROPERTY_THROWN, ID_INTERNAL_WEAPON_GROUP_HAMMERS, ID_WOTC_PHB24_WEAPON_PROPERTY_NICK</supports>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +			<p></p>
```suggestion
			<div class="sidebar" style="margin-top:10px">
				<h5>MASTERY</h5>
				<p><b>Nick.</b> When you make the extra attack of the Light property, you can make it as part of the Attack action instead of as a Bonus Action. You can make this extra attack only once per turn.</p>
			</div>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_WEAPON_PROFICIENCY_LIGHT_HAMMER</set>
```suggestion
			<set name="category">Weapons</set>
			<set name="damage" type="bludgeoning">1d4</set>
			<set name="range">20/60</set>
			<set name="weight" lb="2">2 lb.</set>
			<set name="cost" currency="gp">2</set>
			<set name="slot">onehand</set>
			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_WEAPON_PROFICIENCY_LIGHT_HAMMER</set>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +	</element>
```suggestion
	</element>

```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +			<p></p>
```suggestion
			<div class="sidebar" style="margin-top:10px">
				<h5>MASTERY</h5>
				<p><b>Sap.</b> If you hit a creature with this weapon, that creature has Disadvantage on its next attack roll before the start of your next turn.</p>
			</div>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_WEAPON_PROFICIENCY_MACE</set>
```suggestion
			<set name="category">Weapons</set>
			<set name="damage" type="bludgeoning">1d6</set>
			<set name="weight" lb="4">4 lb.</set>
			<set name="cost" currency="gp">5</set>
			<set name="slot">onehand</set>
			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_WEAPON_PROFICIENCY_MACE</set>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +	</element>
```suggestion
	</element>

```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +		<supports>ID_INTERNAL_WEAPON_CATEGORY_SIMPLE_MELEE, ID_INTERNAL_DAMAGE_TYPE_BLUDGEONING, ID_WOTC_PHB24_WEAPON_PROPERTY_VERSATILE, ID_WOTC_PHB24_WEAPON_PROPERTY_TOPPLE</supports>
```suggestion
		<supports>ID_INTERNAL_WEAPON_CATEGORY_SIMPLE_MELEE, ID_INTERNAL_DAMAGE_TYPE_BLUDGEONING, ID_INTERNAL_WEAPON_PROPERTY_VERSATILE, ID_WOTC_PHB24_WEAPON_PROPERTY_TOPPLE</supports>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +			<p></p>
```suggestion
			<div class="sidebar" style="margin-top:10px">
				<h5>MASTERY</h5>
				<p><b>Topple.</b> If you hit a creature with this weapon, you can force the creature to make a Constitution saving throw (DC 8 plus the ability modifier used to make the attack roll and your Proficiency Bonus). On a failed save, the creature has the Prone condition.</p>
			</div>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_WEAPON_PROFICIENCY_QUARTERSTAFF</set>
```suggestion
			<set name="category">Weapons</set>
			<set name="damage" type="bludgeoning">1d6</set>
			<set name="versatile">1d8</set>
			<set name="weight" lb="4">4 lb.</set>
			<set name="cost" currency="sp">2</set>
			<set name="slot">onehand</set>
			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_WEAPON_PROFICIENCY_QUARTERSTAFF</set>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +	</element>
```suggestion
	</element>

```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +		<supports>ID_INTERNAL_WEAPON_CATEGORY_SIMPLE_MELEE, ID_INTERNAL_DAMAGE_TYPE_SLASHING, ID_WOTC_PHB24_WEAPON_PROPERTY_LIGHT,ID_WOTC_PHB24_WEAPON_PROPERTY_NICK</supports>
```suggestion
		<supports>ID_INTERNAL_WEAPON_CATEGORY_SIMPLE_MELEE, ID_INTERNAL_DAMAGE_TYPE_SLASHING, ID_INTERNAL_WEAPON_PROPERTY_LIGHT,ID_WOTC_PHB24_WEAPON_PROPERTY_NICK</supports>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +			<p></p>
```suggestion
			<div class="sidebar" style="margin-top:10px">
				<h5>MASTERY</h5>
				<p><b>Nick.</b> When you make the extra attack of the Light property, you can make it as part of the Attack action instead of as a Bonus Action. You can make this extra attack only once per turn.</p>
			</div>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_WEAPON_PROFICIENCY_SICKLE</set>
```suggestion
			<set name="category">Weapons</set>
			<set name="damage" type="slashing">1d4</set>
			<set name="weight" lb="2">2 lb.</set>
			<set name="cost" currency="gp">1</set>
			<set name="slot">onehand</set>
			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_WEAPON_PROFICIENCY_SICKLE</set>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +	</element>
```suggestion
	</element>

```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +		<supports>ID_INTERNAL_WEAPON_CATEGORY_SIMPLE_MELEE, ID_INTERNAL_DAMAGE_TYPE_PIERCING, ID_WOTC_PHB24_WEAPON_PROPERTY_THROWN, ID_WOTC_PHB24_WEAPON_PROPERTY_VERSATILE, ID_INTERNAL_WEAPON_GROUP_SPEARS,
```suggestion
		<supports>ID_INTERNAL_WEAPON_CATEGORY_SIMPLE_MELEE, ID_INTERNAL_DAMAGE_TYPE_PIERCING, ID_INTERNAL_WEAPON_PROPERTY_THROWN, ID_INTERNAL_WEAPON_PROPERTY_VERSATILE, ID_INTERNAL_WEAPON_GROUP_SPEARS, ID_WOTC_PHB24_WEAPON_PROPERTY_SAP</supports>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +			<p></p>
```suggestion
			<div class="sidebar" style="margin-top:10px">
				<h5>MASTERY</h5>
				<p><b>Sap.</b> If you hit a creature with this weapon, that creature has Disadvantage on its next attack roll before the start of your next turn.</p>
			</div>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_WEAPON_PROFICIENCY_SPEAR</set>
```suggestion
			<set name="category">Weapons</set>
			<set name="damage" type="piercing">1d6</set>
			<set name="range">20/60</set>
			<set name="versatile">1d8</set>
			<set name="weight" lb="3">3 lb.</set>
			<set name="cost" currency="gp">1</set>
			<set name="slot">onehand</set>
			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_WEAPON_PROFICIENCY_SPEAR</set>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +	</element>
```suggestion
	</element>

	<element name="Dart" type="Weapon" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_WEAPON_DART">
		<supports>ID_INTERNAL_WEAPON_CATEGORY_SIMPLE_RANGED, ID_INTERNAL_DAMAGE_TYPE_PIERCING, ID_INTERNAL_WEAPON_PROPERTY_FINESSE, ID_INTERNAL_WEAPON_PROPERTY_THROWN, ID_WOTC_PHB24_WEAPON_PROPERTY_VEX</supports>
		<description>
			<div class="sidebar" style="margin-top:10px">
				<h5>MASTERY</h5>
				<p><b>Vex.</b> If you hit a creature with this weapon and deal damage to the creature, you have Advantage on your next attack roll against that creature before the end of your next turn.</p>
			</div>
		</description>
		<setters>
			<set name="category">Weapons</set>
			<set name="damage" type="piercing">1d4</set>
			<set name="range">20/60</set>
			<set name="weight" lb="0.25">1/4 lb.</set>
			<set name="cost" currency="cp">5</set>
			<set name="slot">onehand</set>
			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_WEAPON_PROFICIENCY_DART</set>
		</setters>
	</element>

	<element name="Crossbow, Light" type="Weapon" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_WEAPON_CROSSBOW_LIGHT">
		<supports>ID_INTERNAL_WEAPON_CATEGORY_SIMPLE_RANGED, ID_INTERNAL_DAMAGE_TYPE_PIERCING, ID_INTERNAL_WEAPON_PROPERTY_AMMUNITION, ID_INTERNAL_WEAPON_PROPERTY_LOADING, ID_INTERNAL_WEAPON_PROPERTY_TWOHANDED, ID_INTERNAL_WEAPON_GROUP_CROSSBOWS, ID_WOTC_PHB24_WEAPON_PROPERTY_SLOW</supports>
		<description>
			<div class="sidebar" style="margin-top:10px">
				<h5>MASTERY</h5>
				<p><b>Slow.</b> If you hit a creature with this weapon and deal damage to it, you can reduce its Speed by 10 feet until the start of your next turn. If the creature is hit more than once by weapons that have this property, the Speed reduction doesn't exceed 10 feet.</p>
			</div>
		</description>
		<setters>
			<set name="category">Weapons</set>
			<set name="damage" type="piercing">1d8</set>
			<set name="range">80/320; Bolt</set>
			<set name="weight" lb="5">5 lb.</set>
			<set name="cost" currency="gp">25</set>
			<set name="slot">twohand</set>
			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_WEAPON_PROFICIENCY_CROSSBOW_LIGHT</set>
		</setters>
	</element>

```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +		<supports>ID_INTERNAL_WEAPON_CATEGORY_SIMPLE_RANGED, ID_INTERNAL_DAMAGE_TYPE_PIERCING, ID_WOTC_PHB24_WEAPON_PROPERTY_AMMUNITION, ID_WOTC_PHB24_WEAPON_PROPERTY_TWOHANDED, ID_INTERNAL_WEAPON_GROUP_BO
```suggestion
		<supports>ID_INTERNAL_WEAPON_CATEGORY_SIMPLE_RANGED, ID_INTERNAL_DAMAGE_TYPE_PIERCING, ID_INTERNAL_WEAPON_PROPERTY_AMMUNITION, ID_INTERNAL_WEAPON_PROPERTY_TWOHANDED, ID_INTERNAL_WEAPON_GROUP_BOWS, ID_WOTC_PHB24_WEAPON_PROPERTY_VEX</supports>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +			<p></p>
```suggestion
			<div class="sidebar" style="margin-top:10px">
				<h5>MASTERY</h5>
				<p><b>Vex.</b> If you hit a creature with this weapon and deal damage to the creature, you have Advantage on your next attack roll against that creature before the end of your next turn.</p>
			</div>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_WEAPON_PROFICIENCY_SHORTBOW</set>
```suggestion
			<set name="category">Weapons</set>
			<set name="damage" type="piercing">1d6</set>
			<set name="range">80/320; Arrow</set>
			<set name="weight" lb="2">2 lb.</set>
			<set name="cost" currency="gp">25</set>
			<set name="slot">twohand</set>
			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_WEAPON_PROFICIENCY_SHORTBOW</set>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +	</element>
```suggestion
	</element>

```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +		<supports>ID_INTERNAL_WEAPON_CATEGORY_SIMPLE_RANGED, ID_INTERNAL_DAMAGE_TYPE_BLUDGEONING, ID_WOTC_PHB24_WEAPON_PROPERTY_AMMUNITION, ID_WOTC_PHB24_WEAPON_PROPERTY_SLOW</supports>
```suggestion
		<supports>ID_INTERNAL_WEAPON_CATEGORY_SIMPLE_RANGED, ID_INTERNAL_DAMAGE_TYPE_BLUDGEONING, ID_INTERNAL_WEAPON_PROPERTY_AMMUNITION, ID_WOTC_PHB24_WEAPON_PROPERTY_SLOW</supports>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +			<p></p>
```suggestion
			<div class="sidebar" style="margin-top:10px">
				<h5>MASTERY</h5>
				<p><b>Slow.</b> If you hit a creature with this weapon and deal damage to it, you can reduce its Speed by 10 feet until the start of your next turn. If the creature is hit more than once by weapons that have this property, the Speed reduction doesn't exceed 10 feet.</p>
			</div>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_WEAPON_PROFICIENCY_SLING</set>
```suggestion
			<set name="category">Weapons</set>
			<set name="damage" type="bludgeoning">1d4</set>
			<set name="range">30/120; Bullet</set>
			<set name="weight" lb="0">—</set>
			<set name="cost" currency="sp">1</set>
			<set name="slot">onehand</set>
			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_WEAPON_PROFICIENCY_SLING</set>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +	<!-- martial -->
```suggestion
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +		<supports>ID_INTERNAL_WEAPON_CATEGORY_MARTIAL_MELEE, ID_INTERNAL_DAMAGE_TYPE_SLASHING, ID_WOTC_PHB24_WEAPON_PROPERTY_VERSATILE, ID_INTERNAL_WEAPON_GROUP_AXES, ID_WOTC_PHB24_WEAPON_PROPERTY_TOPPLE</
```suggestion
		<supports>ID_INTERNAL_WEAPON_CATEGORY_MARTIAL_MELEE, ID_INTERNAL_DAMAGE_TYPE_SLASHING, ID_INTERNAL_WEAPON_PROPERTY_VERSATILE, ID_INTERNAL_WEAPON_GROUP_AXES, ID_WOTC_PHB24_WEAPON_PROPERTY_TOPPLE</supports>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +			<p></p>
```suggestion
			<div class="sidebar" style="margin-top:10px">
				<h5>MASTERY</h5>
				<p><b>Topple.</b> If you hit a creature with this weapon, you can force the creature to make a Constitution saving throw (DC 8 plus the ability modifier used to make the attack roll and your Proficiency Bonus). On a failed save, the creature has the Prone condition.</p>
			</div>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_WEAPON_PROFICIENCY_BATTLEAXE</set>
```suggestion
			<set name="category">Weapons</set>
			<set name="damage" type="slashing">1d8</set>
			<set name="versatile">1d10</set>
			<set name="weight" lb="4">4 lb.</set>
			<set name="cost" currency="gp">10</set>
			<set name="slot">onehand</set>
			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_WEAPON_PROFICIENCY_BATTLEAXE</set>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +	</element>
```suggestion
	</element>

```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +			<p></p>
```suggestion
			<div class="sidebar" style="margin-top:10px">
				<h5>MASTERY</h5>
				<p><b>Sap.</b> If you hit a creature with this weapon, that creature has Disadvantage on its next attack roll before the start of your next turn.</p>
			</div>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_WEAPON_PROFICIENCY_FLAIL</set>
```suggestion
			<set name="category">Weapons</set>
			<set name="damage" type="bludgeoning">1d8</set>
			<set name="weight" lb="2">2 lb.</set>
			<set name="cost" currency="gp">10</set>
			<set name="slot">onehand</set>
			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_WEAPON_PROFICIENCY_FLAIL</set>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +	</element>
```suggestion
	</element>

```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +		<supports>ID_INTERNAL_WEAPON_CATEGORY_MARTIAL_MELEE, ID_INTERNAL_DAMAGE_TYPE_SLASHING, ID_WOTC_PHB24_WEAPON_PROPERTY_HEAVY, ID_WOTC_PHB24_WEAPON_PROPERTY_REACH, ID_WOTC_PHB24_WEAPON_PROPERTY_TWOHAN
```suggestion
		<supports>ID_INTERNAL_WEAPON_CATEGORY_MARTIAL_MELEE, ID_INTERNAL_DAMAGE_TYPE_SLASHING, ID_INTERNAL_WEAPON_PROPERTY_HEAVY, ID_INTERNAL_WEAPON_PROPERTY_REACH, ID_INTERNAL_WEAPON_PROPERTY_TWOHANDED, ID_WOTC_PHB24_WEAPON_PROPERTY_GRAZE</supports>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +			<p></p>
```suggestion
			<div class="sidebar" style="margin-top:10px">
				<h5>MASTERY</h5>
				<p><b>Graze.</b> If your attack roll with this weapon misses a creature, you can deal damage to that creature equal to the ability modifier you used to make the attack roll. This damage is the same type dealt by the weapon, and the damage can be increased only by increasing the ability modifier.</p>
			</div>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_WEAPON_PROFICIENCY_GLAIVE</set>
```suggestion
			<set name="category">Weapons</set>
			<set name="damage" type="slashing">1d10</set>
			<set name="weight" lb="6">6 lb.</set>
			<set name="cost" currency="gp">20</set>
			<set name="slot">twohand</set>
			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_WEAPON_PROFICIENCY_GLAIVE</set>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +	</element>
```suggestion
	</element>

```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +		<supports>ID_INTERNAL_WEAPON_CATEGORY_MARTIAL_MELEE, ID_INTERNAL_DAMAGE_TYPE_SLASHING, ID_WOTC_PHB24_WEAPON_PROPERTY_HEAVY, ID_WOTC_PHB24_WEAPON_PROPERTY_TWOHANDED, ID_INTERNAL_WEAPON_GROUP_AXES, I
```suggestion
		<supports>ID_INTERNAL_WEAPON_CATEGORY_MARTIAL_MELEE, ID_INTERNAL_DAMAGE_TYPE_SLASHING, ID_INTERNAL_WEAPON_PROPERTY_HEAVY, ID_INTERNAL_WEAPON_PROPERTY_TWOHANDED, ID_INTERNAL_WEAPON_GROUP_AXES, ID_WOTC_PHB24_WEAPON_PROPERTY_CLEAVE</supports>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +			<p></p>
```suggestion
			<div class="sidebar" style="margin-top:10px">
				<h5>MASTERY</h5>
				<p><b>Cleave.</b> If you hit a creature with a melee attack roll using this weapon, you can make a melee attack roll with the weapon against a second creature within 5 feet of the first that is also within your reach. On a hit, the second creature takes the weapon's damage, but don't add your ability modifier to that damage unless that modifier is negative. You can make this extra attack only once per turn.</p>
			</div>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_WEAPON_PROFICIENCY_GREATAXE</set>
```suggestion
			<set name="category">Weapons</set>
			<set name="damage" type="slashing">1d12</set>
			<set name="weight" lb="7">7 lb.</set>
			<set name="cost" currency="gp">30</set>
			<set name="slot">twohand</set>
			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_WEAPON_PROFICIENCY_GREATAXE</set>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +	</element>
```suggestion
	</element>

```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +		<supports>ID_INTERNAL_WEAPON_CATEGORY_MARTIAL_MELEE, ID_INTERNAL_DAMAGE_TYPE_SLASHING, ID_WOTC_PHB24_WEAPON_PROPERTY_HEAVY, ID_WOTC_PHB24_WEAPON_PROPERTY_TWOHANDED, ID_INTERNAL_WEAPON_GROUP_SWORDS,
```suggestion
		<supports>ID_INTERNAL_WEAPON_CATEGORY_MARTIAL_MELEE, ID_INTERNAL_DAMAGE_TYPE_SLASHING, ID_INTERNAL_WEAPON_PROPERTY_HEAVY, ID_INTERNAL_WEAPON_PROPERTY_TWOHANDED, ID_INTERNAL_WEAPON_GROUP_SWORDS, ID_WOTC_PHB24_WEAPON_PROPERTY_GRAZE</supports>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +			<p></p>
```suggestion
			<div class="sidebar" style="margin-top:10px">
				<h5>MASTERY</h5>
				<p><b>Graze.</b> If your attack roll with this weapon misses a creature, you can deal damage to that creature equal to the ability modifier you used to make the attack roll. This damage is the same type dealt by the weapon, and the damage can be increased only by increasing the ability modifier.</p>
			</div>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_WEAPON_PROFICIENCY_GREATSWORD</set>
```suggestion
			<set name="category">Weapons</set>
			<set name="damage" type="slashing">2d6</set>
			<set name="weight" lb="6">6 lb.</set>
			<set name="cost" currency="gp">50</set>
			<set name="slot">twohand</set>
			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_WEAPON_PROFICIENCY_GREATSWORD</set>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +	</element>
```suggestion
	</element>

```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +		<supports>ID_INTERNAL_WEAPON_CATEGORY_MARTIAL_MELEE, ID_INTERNAL_DAMAGE_TYPE_SLASHING, ID_WOTC_PHB24_WEAPON_PROPERTY_HEAVY, ID_WOTC_PHB24_WEAPON_PROPERTY_REACH, ID_WOTC_PHB24_WEAPON_PROPERTY_TWOHAN
```suggestion
		<supports>ID_INTERNAL_WEAPON_CATEGORY_MARTIAL_MELEE, ID_INTERNAL_DAMAGE_TYPE_SLASHING, ID_INTERNAL_WEAPON_PROPERTY_HEAVY, ID_INTERNAL_WEAPON_PROPERTY_REACH, ID_INTERNAL_WEAPON_PROPERTY_TWOHANDED, ID_WOTC_PHB24_WEAPON_PROPERTY_CLEAVE</supports>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +			<p></p>
```suggestion
			<div class="sidebar" style="margin-top:10px">
				<h5>MASTERY</h5>
				<p><b>Cleave.</b> If you hit a creature with a melee attack roll using this weapon, you can make a melee attack roll with the weapon against a second creature within 5 feet of the first that is also within your reach. On a hit, the second creature takes the weapon's damage, but don't add your ability modifier to that damage unless that modifier is negative. You can make this extra attack only once per turn.</p>
			</div>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_WEAPON_PROFICIENCY_HALBERD</set>
```suggestion
			<set name="category">Weapons</set>
			<set name="damage" type="slashing">1d10</set>
			<set name="weight" lb="6">6 lb.</set>
			<set name="cost" currency="gp">20</set>
			<set name="slot">twohand</set>
			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_WEAPON_PROFICIENCY_HALBERD</set>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +	</element>
```suggestion
	</element>

```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +		<supports>ID_INTERNAL_WEAPON_CATEGORY_MARTIAL_MELEE, ID_INTERNAL_DAMAGE_TYPE_PIERCING, ID_WOTC_PHB24_WEAPON_PROPERTY_HEAVY, ID_WOTC_PHB24_WEAPON_PROPERTY_REACH, ID_WOTC_PHB24_WEAPON_PROPERTY_TWOHAN
```suggestion
		<supports>ID_INTERNAL_WEAPON_CATEGORY_MARTIAL_MELEE, ID_INTERNAL_DAMAGE_TYPE_PIERCING, ID_INTERNAL_WEAPON_PROPERTY_HEAVY, ID_INTERNAL_WEAPON_PROPERTY_REACH, ID_INTERNAL_WEAPON_PROPERTY_TWOHANDED, ID_WOTC_PHB24_WEAPON_PROPERTY_TOPPLE</supports>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +			<div element="ID_INTERNAL_WEAPON_PROPERTY_SPECIAL_LANCE" />
```suggestion
			<h5>TWO-HANDED (UNLESS MOUNTED)</h5>
			<p>While mounted, you can use this weapon in one hand. <br />
			<b>Note:</b> To equip Lance as two-handed weapon, use the "Equip Versatile" button.</p>
			<div class="sidebar" style="margin-top:10px">
				<h5>MASTERY</h5>
				<p><b>Topple.</b> If you hit a creature with this weapon, you can force the creature to make a Constitution saving throw (DC 8 plus the ability modifier used to make the attack roll and your Proficiency Bonus). On a failed save, the creature has the Prone condition.</p>
			</div>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_WEAPON_PROFICIENCY_LANCE</set>
```suggestion
			<set name="category">Weapons</set>
			<set name="damage" type="piercing">1d10</set>
			<set name="versatile">1d10</set>
			<set name="weight" lb="6">6 lb.</set>
			<set name="cost" currency="gp">10</set>
			<set name="slot">onehand</set>
			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_WEAPON_PROFICIENCY_LANCE</set>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +	</element>
```suggestion
	</element>

```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +		<supports>ID_INTERNAL_WEAPON_CATEGORY_MARTIAL_MELEE, ID_INTERNAL_DAMAGE_TYPE_SLASHING, ID_WOTC_PHB24_WEAPON_PROPERTY_VERSATILE, ID_INTERNAL_WEAPON_GROUP_SWORDS, ID_WOTC_PHB24_WEAPON_PROPERTY_SAP</s
```suggestion
		<supports>ID_INTERNAL_WEAPON_CATEGORY_MARTIAL_MELEE, ID_INTERNAL_DAMAGE_TYPE_SLASHING, ID_INTERNAL_WEAPON_PROPERTY_VERSATILE, ID_INTERNAL_WEAPON_GROUP_SWORDS, ID_WOTC_PHB24_WEAPON_PROPERTY_SAP</supports>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +			<p></p>
```suggestion
			<div class="sidebar" style="margin-top:10px">
				<h5>MASTERY</h5>
				<p><b>Sap.</b> If you hit a creature with this weapon, that creature has Disadvantage on its next attack roll before the start of your next turn.</p>
			</div>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_WEAPON_PROFICIENCY_LONGSWORD</set>
```suggestion
			<set name="category">Weapons</set>
			<set name="damage" type="slashing">1d8</set>
			<set name="versatile">1d10</set>
			<set name="weight" lb="3">3 lb.</set>
			<set name="cost" currency="gp">15</set>
			<set name="slot">onehand</set>
			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_WEAPON_PROFICIENCY_LONGSWORD</set>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +	</element>
```suggestion
	</element>

```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +		<supports>ID_INTERNAL_WEAPON_CATEGORY_MARTIAL_MELEE, ID_INTERNAL_DAMAGE_TYPE_BLUDGEONING, ID_WOTC_PHB24_WEAPON_PROPERTY_HEAVY, ID_WOTC_PHB24_WEAPON_PROPERTY_TWOHANDED, ID_INTERNAL_WEAPON_GROUP_MAUL
```suggestion
		<supports>ID_INTERNAL_WEAPON_CATEGORY_MARTIAL_MELEE, ID_INTERNAL_DAMAGE_TYPE_BLUDGEONING, ID_INTERNAL_WEAPON_PROPERTY_HEAVY, ID_INTERNAL_WEAPON_PROPERTY_TWOHANDED, ID_INTERNAL_WEAPON_GROUP_MAULS, ID_WOTC_PHB24_WEAPON_PROPERTY_TOPPLE</supports>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +			<p></p>
```suggestion
			<div class="sidebar" style="margin-top:10px">
				<h5>MASTERY</h5>
				<p><b>Topple.</b> If you hit a creature with this weapon, you can force the creature to make a Constitution saving throw (DC 8 plus the ability modifier used to make the attack roll and your Proficiency Bonus). On a failed save, the creature has the Prone condition.</p>
			</div>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_WEAPON_PROFICIENCY_MAUL</set>
```suggestion
			<set name="category">Weapons</set>
			<set name="damage" type="bludgeoning">2d6</set>
			<set name="weight" lb="10">10 lb.</set>
			<set name="cost" currency="gp">10</set>
			<set name="slot">twohand</set>
			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_WEAPON_PROFICIENCY_MAUL</set>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +	</element>
```suggestion
	</element>

```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +			<p></p>
```suggestion
			<div class="sidebar" style="margin-top:10px">
				<h5>MASTERY</h5>
				<p><b>Sap.</b> If you hit a creature with this weapon, that creature has Disadvantage on its next attack roll before the start of your next turn.</p>
			</div>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_WEAPON_PROFICIENCY_MORNINGSTAR</set>
```suggestion
			<set name="category">Weapons</set>
			<set name="damage" type="piercing">1d8</set>
			<set name="weight" lb="4">4 lb.</set>
			<set name="cost" currency="gp">15</set>
			<set name="slot">onehand</set>
			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_WEAPON_PROFICIENCY_MORNINGSTAR</set>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +	</element>
```suggestion
	</element>

```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +		<supports>ID_INTERNAL_WEAPON_CATEGORY_MARTIAL_MELEE, ID_INTERNAL_DAMAGE_TYPE_PIERCING, ID_WOTC_PHB24_WEAPON_PROPERTY_HEAVY, ID_WOTC_PHB24_WEAPON_PROPERTY_REACH, ID_WOTC_PHB24_WEAPON_PROPERTY_TWOHAN
```suggestion
		<supports>ID_INTERNAL_WEAPON_CATEGORY_MARTIAL_MELEE, ID_INTERNAL_DAMAGE_TYPE_PIERCING, ID_INTERNAL_WEAPON_PROPERTY_HEAVY, ID_INTERNAL_WEAPON_PROPERTY_REACH, ID_INTERNAL_WEAPON_PROPERTY_TWOHANDED, ID_WOTC_PHB24_WEAPON_PROPERTY_PUSH</supports>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +			<p></p>
```suggestion
			<div class="sidebar" style="margin-top:10px">
				<h5>MASTERY</h5>
				<p><b>Push.</b> If you hit a creature with this weapon, you can push the creature up to 10 feet straight away from yourself if it is Large or smaller.</p>
			</div>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_WEAPON_PROFICIENCY_PIKE</set>
```suggestion
			<set name="category">Weapons</set>
			<set name="damage" type="piercing">1d10</set>
			<set name="weight" lb="18">18 lb.</set>
			<set name="cost" currency="gp">5</set>
			<set name="slot">twohand</set>
			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_WEAPON_PROFICIENCY_PIKE</set>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +	</element>
```suggestion
	</element>

```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +		<supports>ID_INTERNAL_WEAPON_CATEGORY_MARTIAL_MELEE, ID_INTERNAL_DAMAGE_TYPE_PIERCING, ID_WOTC_PHB24_WEAPON_PROPERTY_FINESSE, ID_INTERNAL_WEAPON_GROUP_SWORDS, ID_WOTC_PHB24_WEAPON_PROPERTY_VEX</sup
```suggestion
		<supports>ID_INTERNAL_WEAPON_CATEGORY_MARTIAL_MELEE, ID_INTERNAL_DAMAGE_TYPE_PIERCING, ID_INTERNAL_WEAPON_PROPERTY_FINESSE, ID_INTERNAL_WEAPON_GROUP_SWORDS, ID_WOTC_PHB24_WEAPON_PROPERTY_VEX</supports>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +			<p></p>
```suggestion
			<div class="sidebar" style="margin-top:10px">
				<h5>MASTERY</h5>
				<p><b>Vex.</b> If you hit a creature with this weapon and deal damage to the creature, you have Advantage on your next attack roll against that creature before the end of your next turn.</p>
			</div>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_WEAPON_PROFICIENCY_RAPIER</set>
```suggestion
			<set name="category">Weapons</set>
			<set name="damage" type="piercing">1d8</set>
			<set name="weight" lb="2">2 lb.</set>
			<set name="cost" currency="gp">25</set>
			<set name="slot">onehand</set>
			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_WEAPON_PROFICIENCY_RAPIER</set>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +	</element>
```suggestion
	</element>

```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +		<supports>ID_INTERNAL_WEAPON_CATEGORY_MARTIAL_MELEE, ID_INTERNAL_DAMAGE_TYPE_SLASHING, ID_WOTC_PHB24_WEAPON_PROPERTY_FINESSE, ID_WOTC_PHB24_WEAPON_PROPERTY_LIGHT, ID_INTERNAL_WEAPON_GROUP_SWORDS, I
```suggestion
		<supports>ID_INTERNAL_WEAPON_CATEGORY_MARTIAL_MELEE, ID_INTERNAL_DAMAGE_TYPE_SLASHING, ID_INTERNAL_WEAPON_PROPERTY_FINESSE, ID_INTERNAL_WEAPON_PROPERTY_LIGHT, ID_INTERNAL_WEAPON_GROUP_SWORDS, ID_WOTC_PHB24_WEAPON_PROPERTY_NICK</supports>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +			<p></p>
```suggestion
			<div class="sidebar" style="margin-top:10px">
				<h5>MASTERY</h5>
				<p><b>Nick.</b> When you make the extra attack of the Light property, you can make it as part of the Attack action instead of as a Bonus Action. You can make this extra attack only once per turn.</p>
			</div>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_WEAPON_PROFICIENCY_SCIMITAR</set>
```suggestion
			<set name="category">Weapons</set>
			<set name="damage" type="slashing">1d6</set>
			<set name="weight" lb="3">3 lb.</set>
			<set name="cost" currency="gp">25</set>
			<set name="slot">onehand</set>
			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_WEAPON_PROFICIENCY_SCIMITAR</set>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +	</element>
```suggestion
	</element>

```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +		<supports>ID_INTERNAL_WEAPON_CATEGORY_MARTIAL_MELEE, ID_INTERNAL_DAMAGE_TYPE_PIERCING, ID_WOTC_PHB24_WEAPON_PROPERTY_FINESSE, ID_WOTC_PHB24_WEAPON_PROPERTY_LIGHT, ID_INTERNAL_WEAPON_GROUP_SWORDS, I
```suggestion
		<supports>ID_INTERNAL_WEAPON_CATEGORY_MARTIAL_MELEE, ID_INTERNAL_DAMAGE_TYPE_PIERCING, ID_INTERNAL_WEAPON_PROPERTY_FINESSE, ID_INTERNAL_WEAPON_PROPERTY_LIGHT, ID_INTERNAL_WEAPON_GROUP_SWORDS, ID_WOTC_PHB24_WEAPON_PROPERTY_VEX</supports>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +			<p></p>
```suggestion
			<div class="sidebar" style="margin-top:10px">
				<h5>MASTERY</h5>
				<p><b>Vex.</b> If you hit a creature with this weapon and deal damage to the creature, you have Advantage on your next attack roll against that creature before the end of your next turn.</p>
			</div>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_WEAPON_PROFICIENCY_SHORTSWORD</set>
```suggestion
			<set name="category">Weapons</set>
			<set name="damage" type="piercing">1d6</set>
			<set name="weight" lb="2">2 lb.</set>
			<set name="cost" currency="gp">10</set>
			<set name="slot">onehand</set>
			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_WEAPON_PROFICIENCY_SHORTSWORD</set>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +	</element>
```suggestion
	</element>

```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +		<supports>ID_INTERNAL_WEAPON_CATEGORY_MARTIAL_MELEE, ID_INTERNAL_DAMAGE_TYPE_PIERCING, ID_WOTC_PHB24_WEAPON_PROPERTY_THROWN, ID_WOTC_PHB24_WEAPON_PROPERTY_VERSATILE, ID_WOTC_PHB24_WEAPON_PROPERTY_T
```suggestion
		<supports>ID_INTERNAL_WEAPON_CATEGORY_MARTIAL_MELEE, ID_INTERNAL_DAMAGE_TYPE_PIERCING, ID_INTERNAL_WEAPON_PROPERTY_THROWN, ID_INTERNAL_WEAPON_PROPERTY_VERSATILE, ID_WOTC_PHB24_WEAPON_PROPERTY_TOPPLE</supports>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +			<p></p>
```suggestion
			<div class="sidebar" style="margin-top:10px">
				<h5>MASTERY</h5>
				<p><b>Topple.</b> If you hit a creature with this weapon, you can force the creature to make a Constitution saving throw (DC 8 plus the ability modifier used to make the attack roll and your Proficiency Bonus). On a failed save, the creature has the Prone condition.</p>
			</div>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_WEAPON_PROFICIENCY_TRIDENT</set>
```suggestion
			<set name="category">Weapons</set>
			<set name="damage" type="piercing">1d8</set>
			<set name="range">20/60</set>
			<set name="versatile">1d10</set>
			<set name="weight" lb="4">4 lb.</set>
			<set name="cost" currency="gp">5</set>
			<set name="slot">onehand</set>
			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_WEAPON_PROFICIENCY_TRIDENT</set>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +	</element>
```suggestion
	</element>

```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +		<supports>ID_INTERNAL_WEAPON_CATEGORY_MARTIAL_MELEE, ID_INTERNAL_DAMAGE_TYPE_BLUDGEONING, ID_WOTC_PHB24_WEAPON_PROPERTY_VERSATILE, ID_INTERNAL_WEAPON_GROUP_HAMMERS, ID_WOTC_PHB24_WEAPON_PROPERTY_PU
```suggestion
		<supports>ID_INTERNAL_WEAPON_CATEGORY_MARTIAL_MELEE, ID_INTERNAL_DAMAGE_TYPE_BLUDGEONING, ID_INTERNAL_WEAPON_PROPERTY_VERSATILE, ID_INTERNAL_WEAPON_GROUP_HAMMERS, ID_WOTC_PHB24_WEAPON_PROPERTY_PUSH</supports>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +			<p></p>
```suggestion
			<div class="sidebar" style="margin-top:10px">
				<h5>MASTERY</h5>
				<p><b>Push.</b> If you hit a creature with this weapon, you can push the creature up to 10 feet straight away from yourself if it is Large or smaller.</p>
			</div>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_WEAPON_PROFICIENCY_WARHAMMER</set>
```suggestion
			<set name="category">Weapons</set>
			<set name="damage" type="bludgeoning">1d8</set>
			<set name="versatile">1d10</set>
			<set name="weight" lb="5">5 lb.</set>
			<set name="cost" currency="gp">15</set>
			<set name="slot">onehand</set>
			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_WEAPON_PROFICIENCY_WARHAMMER</set>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +	</element>
```suggestion
	</element>

```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +		<supports>ID_INTERNAL_WEAPON_CATEGORY_MARTIAL_MELEE, ID_INTERNAL_DAMAGE_TYPE_PIERCING,ID_WOTC_PHB24_WEAPON_PROPERTY_VERSATILE, ID_WOTC_PHB24_WEAPON_PROPERTY_SAP</supports>
```suggestion
		<supports>ID_INTERNAL_WEAPON_CATEGORY_MARTIAL_MELEE, ID_INTERNAL_DAMAGE_TYPE_PIERCING,ID_INTERNAL_WEAPON_PROPERTY_VERSATILE, ID_WOTC_PHB24_WEAPON_PROPERTY_SAP</supports>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +			<p></p>
```suggestion
			<div class="sidebar" style="margin-top:10px">
				<h5>MASTERY</h5>
				<p><b>Sap.</b> If you hit a creature with this weapon, that creature has Disadvantage on its next attack roll before the start of your next turn.</p>
			</div>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_WEAPON_PROFICIENCY_WAR_PICK</set>
```suggestion
			<set name="category">Weapons</set>
			<set name="damage" type="piercing">1d8</set>
			<set name="versatile">1d10</set>
			<set name="weight" lb="2">2 lb.</set>
			<set name="cost" currency="gp">5</set>
			<set name="slot">onehand</set>
			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_WEAPON_PROFICIENCY_WAR_PICK</set>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +	</element>
```suggestion
	</element>

```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +		<supports>ID_INTERNAL_WEAPON_CATEGORY_MARTIAL_MELEE, ID_INTERNAL_DAMAGE_TYPE_SLASHING, ID_WOTC_PHB24_WEAPON_PROPERTY_FINESSE, ID_WOTC_PHB24_WEAPON_PROPERTY_REACH, ID_WOTC_PHB24_WEAPON_PROPERTY_SLOW
```suggestion
		<supports>ID_INTERNAL_WEAPON_CATEGORY_MARTIAL_MELEE, ID_INTERNAL_DAMAGE_TYPE_SLASHING, ID_INTERNAL_WEAPON_PROPERTY_FINESSE, ID_INTERNAL_WEAPON_PROPERTY_REACH, ID_WOTC_PHB24_WEAPON_PROPERTY_SLOW</supports>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +			<p></p>
```suggestion
			<div class="sidebar" style="margin-top:10px">
				<h5>MASTERY</h5>
				<p><b>Slow.</b> If you hit a creature with this weapon and deal damage to it, you can reduce its Speed by 10 feet until the start of your next turn. If the creature is hit more than once by weapons that have this property, the Speed reduction doesn't exceed 10 feet.</p>
			</div>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_WEAPON_PROFICIENCY_WHIP</set>
```suggestion
			<set name="category">Weapons</set>
			<set name="damage" type="slashing">1d4</set>
			<set name="weight" lb="3">3 lb.</set>
			<set name="cost" currency="gp">2</set>
			<set name="slot">onehand</set>
			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_WEAPON_PROFICIENCY_WHIP</set>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +	</element>
```suggestion
	</element>

```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +		<supports>ID_INTERNAL_WEAPON_CATEGORY_MARTIAL_RANGED, ID_INTERNAL_DAMAGE_TYPE_PIERCING, ID_WOTC_PHB24_WEAPON_PROPERTY_AMMUNITION, ID_WOTC_PHB24_WEAPON_PROPERTY_LOADING, ID_WOTC_PHB24_WEAPON_PROPERT
```suggestion
		<supports>ID_INTERNAL_WEAPON_CATEGORY_MARTIAL_RANGED, ID_INTERNAL_DAMAGE_TYPE_PIERCING, ID_INTERNAL_WEAPON_PROPERTY_AMMUNITION, ID_INTERNAL_WEAPON_PROPERTY_LOADING, ID_WOTC_PHB24_WEAPON_PROPERTY_VEX</supports>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +			<p></p>
```suggestion
			<div class="sidebar" style="margin-top:10px">
				<h5>MASTERY</h5>
				<p><b>Vex.</b> If you hit a creature with this weapon and deal damage to the creature, you have Advantage on your next attack roll against that creature before the end of your next turn.</p>
			</div>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_WEAPON_PROFICIENCY_BLOWGUN</set>
```suggestion
			<set name="category">Weapons</set>
			<set name="damage" type="piercing">1</set>
			<set name="range">25/100; Needle</set>
			<set name="weight" lb="1">1 lb.</set>
			<set name="cost" currency="gp">10</set>
			<set name="slot">onehand</set>
			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_WEAPON_PROFICIENCY_BLOWGUN</set>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +	</element>
```suggestion
	</element>

```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +		<supports>ID_INTERNAL_WEAPON_CATEGORY_MARTIAL_RANGED,ID_INTERNAL_DAMAGE_TYPE_PIERCING,ID_WOTC_PHB24_WEAPON_PROPERTY_AMMUNITION,ID_WOTC_PHB24_WEAPON_PROPERTY_LIGHT,ID_WOTC_PHB24_WEAPON_PROPERTY_LOAD
```suggestion
		<supports>ID_INTERNAL_WEAPON_CATEGORY_MARTIAL_RANGED,ID_INTERNAL_DAMAGE_TYPE_PIERCING,ID_INTERNAL_WEAPON_PROPERTY_AMMUNITION,ID_INTERNAL_WEAPON_PROPERTY_LIGHT,ID_INTERNAL_WEAPON_PROPERTY_LOADING, ID_INTERNAL_WEAPON_GROUP_CROSSBOWS, ID_WOTC_PHB24_WEAPON_PROPERTY_VEX</supports>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +			<p></p>
```suggestion
			<div class="sidebar" style="margin-top:10px">
				<h5>MASTERY</h5>
				<p><b>Vex.</b> If you hit a creature with this weapon and deal damage to the creature, you have Advantage on your next attack roll against that creature before the end of your next turn.</p>
			</div>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_WEAPON_PROFICIENCY_CROSSBOW_HAND</set>
```suggestion
			<set name="category">Weapons</set>
			<set name="damage" type="piercing">1d6</set>
			<set name="range">30/120; Bolt</set>
			<set name="weight" lb="3">3 lb.</set>
			<set name="cost" currency="gp">75</set>
			<set name="slot">onehand</set>
			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_WEAPON_PROFICIENCY_CROSSBOW_HAND</set>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +	</element>
```suggestion
	</element>

```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +		<supports>ID_INTERNAL_WEAPON_CATEGORY_MARTIAL_RANGED, ID_INTERNAL_DAMAGE_TYPE_PIERCING, ID_WOTC_PHB24_WEAPON_PROPERTY_AMMUNITION, ID_WOTC_PHB24_WEAPON_PROPERTY_HEAVY, ID_WOTC_PHB24_WEAPON_PROPERTY_
```suggestion
		<supports>ID_INTERNAL_WEAPON_CATEGORY_MARTIAL_RANGED, ID_INTERNAL_DAMAGE_TYPE_PIERCING, ID_INTERNAL_WEAPON_PROPERTY_AMMUNITION, ID_INTERNAL_WEAPON_PROPERTY_HEAVY, ID_INTERNAL_WEAPON_PROPERTY_LOADING, ID_INTERNAL_WEAPON_PROPERTY_TWOHANDED, ID_INTERNAL_WEAPON_GROUP_CROSSBOWS, ID_WOTC_PHB24_WEAPON_PROPERTY_PUSH</supports>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +			<p></p>
```suggestion
			<div class="sidebar" style="margin-top:10px">
				<h5>MASTERY</h5>
				<p><b>Push.</b> If you hit a creature with this weapon, you can push the creature up to 10 feet straight away from yourself if it is Large or smaller.</p>
			</div>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_WEAPON_PROFICIENCY_CROSSBOW_HEAVY</set>
```suggestion
			<set name="category">Weapons</set>
			<set name="damage" type="piercing">1d10</set>
			<set name="range">100/400; Bolt</set>
			<set name="weight" lb="18">18 lb.</set>
			<set name="cost" currency="gp">50</set>
			<set name="slot">twohand</set>
			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_WEAPON_PROFICIENCY_CROSSBOW_HEAVY</set>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +	</element>
```suggestion
	</element>

```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +		<supports>ID_INTERNAL_WEAPON_CATEGORY_MARTIAL_RANGED, ID_INTERNAL_DAMAGE_TYPE_PIERCING, ID_WOTC_PHB24_WEAPON_PROPERTY_AMMUNITION, ID_WOTC_PHB24_WEAPON_PROPERTY_HEAVY, ID_WOTC_PHB24_WEAPON_PROPERTY_
```suggestion
		<supports>ID_INTERNAL_WEAPON_CATEGORY_MARTIAL_RANGED, ID_INTERNAL_DAMAGE_TYPE_PIERCING, ID_INTERNAL_WEAPON_PROPERTY_AMMUNITION, ID_INTERNAL_WEAPON_PROPERTY_HEAVY, ID_INTERNAL_WEAPON_PROPERTY_TWOHANDED, ID_INTERNAL_WEAPON_GROUP_BOWS, ID_WOTC_PHB24_WEAPON_PROPERTY_SLOW</supports>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +			<p></p>
```suggestion
			<div class="sidebar" style="margin-top:10px">
				<h5>MASTERY</h5>
				<p><b>Slow.</b> If you hit a creature with this weapon and deal damage to it, you can reduce its Speed by 10 feet until the start of your next turn. If the creature is hit more than once by weapons that have this property, the Speed reduction doesn't exceed 10 feet.</p>
			</div>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_WEAPON_PROFICIENCY_LONGBOW</set>
```suggestion
			<set name="category">Weapons</set>
			<set name="damage" type="piercing">1d8</set>
			<set name="range">150/600; Arrow</set>
			<set name="weight" lb="2">2 lb.</set>
			<set name="cost" currency="gp">50</set>
			<set name="slot">twohand</set>
			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_WEAPON_PROFICIENCY_LONGBOW</set>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +	</element>
```suggestion
	</element>

```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +		<description />
```suggestion
		<supports>ID_INTERNAL_WEAPON_CATEGORY_FIREARM, ID_INTERNAL_WEAPON_CATEGORY_MARTIAL_RANGED, ID_INTERNAL_DAMAGE_TYPE_PIERCING, ID_INTERNAL_WEAPON_PROPERTY_AMMUNITION, ID_INTERNAL_WEAPON_PROPERTY_LOADING, ID_INTERNAL_WEAPON_PROPERTY_TWOHANDED, ID_WOTC_PHB24_WEAPON_PROPERTY_SLOW</supports>
		<description>
			<div class="sidebar" style="margin-top:10px">
				<h5>MASTERY</h5>
				<p><b>Slow.</b> If you hit a creature with this weapon and deal damage to it, you can reduce its Speed by 10 feet until the start of your next turn. If the creature is hit more than once by weapons that have this property, the Speed reduction doesn't exceed 10 feet.</p>
			</div>
		</description>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_WEAPON_PROFICIENCY_MUSKET</set>
```suggestion
			<set name="category">Weapons</set>
			<set name="damage" type="piercing">1d12</set>
			<set name="range">40/120; Bullet</set>
			<set name="weight" lb="10">10 lb.</set>
			<set name="cost" currency="gp">500</set>
			<set name="slot">twohand</set>
			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_WEAPON_PROFICIENCY_MUSKET</set>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +	</element>
```suggestion
	</element>

```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +		<description />
```suggestion
		<supports>ID_INTERNAL_WEAPON_CATEGORY_FIREARM, ID_INTERNAL_WEAPON_CATEGORY_MARTIAL_RANGED, ID_INTERNAL_DAMAGE_TYPE_PIERCING, ID_INTERNAL_WEAPON_PROPERTY_AMMUNITION, ID_INTERNAL_WEAPON_PROPERTY_LOADING, ID_WOTC_PHB24_WEAPON_PROPERTY_VEX</supports>
		<description>
			<div class="sidebar" style="margin-top:10px">
				<h5>MASTERY</h5>
				<p><b>Vex.</b> If you hit a creature with this weapon and deal damage to the creature, you have Advantage on your next attack roll against that creature before the end of your next turn.</p>
			</div>
		</description>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/items/items-weapons.xml
> +			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_WEAPON_PROFICIENCY_PISTOL</set>
```suggestion
			<set name="category">Weapons</set>
			<set name="damage" type="piercing">1d10</set>
			<set name="range">30/90; Bullet</set>
			<set name="weight" lb="3">3 lb.</set>
			<set name="cost" currency="gp">250</set>
			<set name="slot">onehand</set>
			<set name="proficiency">ID_WOTC_PHB24_PROFICIENCY_WEAPON_PROFICIENCY_PISTOL</set>
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/misc/alignments.xml
this file can be deleted. Already existing alignments will be updated to be Internal source.

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/misc/weapon-mastery-properties.xml
> +		<author url="http://dnd.wizards.com/products/tabletop-games/rpg-products/rpg_playershandbook">Wizards of the Coast</author>
```suggestion
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/misc/weapon-mastery-properties.xml
> +	<element name="Greataxe (Cleave)" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_WPM_GREATAXE_CLEAVE">
```suggestion
	<element name="Greataxe (Cleave)" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_MASTERY_PROPERTY_GREATAXE_CLEAVE">
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/misc/weapon-mastery-properties.xml
> +	<element name="Halberd (Cleave)" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_WPM_HALBERD_CLEAVE">
```suggestion
	<element name="Halberd (Cleave)" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_MASTERY_PROPERTY_HALBERD_CLEAVE">
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/misc/weapon-mastery-properties.xml
> +	<element name="Glaive (Graze)" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_WPM_GLAIVE_GRAZE">
```suggestion
	<element name="Glaive (Graze)" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_MASTERY_PROPERTY_GLAIVE_GRAZE">
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/misc/weapon-mastery-properties.xml
> +	<element name="Greatsword (Graze)" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_WPM_GREATSWORD_GRAZE">
```suggestion
	<element name="Greatsword (Graze)" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_MASTERY_PROPERTY_GREATSWORD_GRAZE">
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/misc/weapon-mastery-properties.xml
> +	<element name="Dagger (Nick)" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_WPM_DAGGER_NICK">
```suggestion
	<element name="Dagger (Nick)" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_MASTERY_PROPERTY_DAGGER_NICK">
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/misc/weapon-mastery-properties.xml
> +	<element name="Light Hammer (Nick)" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_WPM_LIGHT_HAMMER_NICK">
```suggestion
	<element name="Light Hammer (Nick)" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_MASTERY_PROPERTY_LIGHT_HAMMER_NICK">
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/misc/weapon-mastery-properties.xml
> +	<element name="Sickle (Nick)" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_WPM_SICKLE_NICK">
```suggestion
	<element name="Sickle (Nick)" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_MASTERY_PROPERTY_SICKLE_NICK">
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/misc/weapon-mastery-properties.xml
> +	<element name="Scimitar (Nick)" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_WPM_SCIMITAR_NICK">
```suggestion
	<element name="Scimitar (Nick)" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_MASTERY_PROPERTY_SCIMITAR_NICK">
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/misc/weapon-mastery-properties.xml
> +	<element name="Greatclub (Push)" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_WPM_PUSH">
```suggestion
	<element name="Greatclub (Push)" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_MASTERY_PROPERTY_PUSH">
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/misc/weapon-mastery-properties.xml
> +	<element name="Pike (Push)" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_WPM_PIKE_PUSH">
```suggestion
	<element name="Pike (Push)" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_MASTERY_PROPERTY_PIKE_PUSH">
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/misc/weapon-mastery-properties.xml
> +	<element name="Warhammer (Push)" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_WPM_WARHAMMER_PUSH">
```suggestion
	<element name="Warhammer (Push)" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_MASTERY_PROPERTY_WARHAMMER_PUSH">
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/misc/weapon-mastery-properties.xml
> +	<element name="Crossbow, Heavy (Push)" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_WPM_CROSSBOW_HEAVY_PUSH">
```suggestion
	<element name="Crossbow, Heavy (Push)" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_MASTERY_PROPERTY_CROSSBOW_HEAVY_PUSH">
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/misc/weapon-mastery-properties.xml
> +	<element name="Mace (Sap)" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_WPM_MACE_SAP">
```suggestion
	<element name="Mace (Sap)" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_MASTERY_PROPERTY_MACE_SAP">
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/misc/weapon-mastery-properties.xml
> +	<element name="Spear (Sap)" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_WPM_SPEAR_SAP">
```suggestion
	<element name="Spear (Sap)" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_MASTERY_PROPERTY_SPEAR_SAP">
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/misc/weapon-mastery-properties.xml
> +	<element name="Flail (Sap)" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_WPM_FLAIL_SAP">
```suggestion
	<element name="Flail (Sap)" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_MASTERY_PROPERTY_FLAIL_SAP">
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/misc/weapon-mastery-properties.xml
> +	<element name="Longsword (Sap)" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_WPM_LONGSWORD_SAP">
```suggestion
	<element name="Longsword (Sap)" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_MASTERY_PROPERTY_LONGSWORD_SAP">
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/misc/weapon-mastery-properties.xml
> +	<element name="Morningstar (Sap)" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_WPM_MORNINGSTAR_SAP">
```suggestion
	<element name="Morningstar (Sap)" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_MASTERY_PROPERTY_MORNINGSTAR_SAP">
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/misc/weapon-mastery-properties.xml
> +	<element name="War Pick (Sap)" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_WPM_WAR_PICK_SAP">
```suggestion
	<element name="War Pick (Sap)" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_MASTERY_PROPERTY_WAR_PICK_SAP">
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/misc/weapon-mastery-properties.xml
> +	<element name="Club (Slow)" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_WPM_CLUB_SLOW">
```suggestion
	<element name="Club (Slow)" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_MASTERY_PROPERTY_CLUB_SLOW">
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/misc/weapon-mastery-properties.xml
> +	<element name="Javelin (Slow)" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_WPM_JAVELIN_SLOW">
```suggestion
	<element name="Javelin (Slow)" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_MASTERY_PROPERTY_JAVELIN_SLOW">
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/misc/weapon-mastery-properties.xml
> +	<element name="Crossbow, Light (Slow)" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_WPM_CROSSBOW_LIGHT_SLOW">
```suggestion
	<element name="Crossbow, Light (Slow)" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_MASTERY_PROPERTY_CROSSBOW_LIGHT_SLOW">
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/misc/weapon-mastery-properties.xml
> +	<element name="Sling (Slow)" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_WPM_SLING_SLOW">
```suggestion
	<element name="Sling (Slow)" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_MASTERY_PROPERTY_SLING_SLOW">
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/misc/weapon-mastery-properties.xml
> +	<element name="Whip (Slow)" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_WPM_WHIP_SLOW">
```suggestion
	<element name="Whip (Slow)" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_MASTERY_PROPERTY_WHIP_SLOW">
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/misc/weapon-mastery-properties.xml
> +	<element name="Longbow (Slow)" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_WPM_LONGBOW_SLOW">
```suggestion
	<element name="Longbow (Slow)" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_MASTERY_PROPERTY_LONGBOW_SLOW">
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/misc/weapon-mastery-properties.xml
> +	<element name="Musket (Slow)" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_WPM_MUSKET_SLOW">
```suggestion
	<element name="Musket (Slow)" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_MASTERY_PROPERTY_MUSKET_SLOW">
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/misc/weapon-mastery-properties.xml
> +	<element name="Quarterstaff (Topple)" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_WPM_QUARTERSTAFF_TOPPLE">
```suggestion
	<element name="Quarterstaff (Topple)" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_MASTERY_PROPERTY_QUARTERSTAFF_TOPPLE">
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/misc/weapon-mastery-properties.xml
> +	<element name="Battleaxe (Topple)" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_WPM_BATTLEAXE_TOPPLE">
```suggestion
	<element name="Battleaxe (Topple)" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_MASTERY_PROPERTY_BATTLEAXE_TOPPLE">
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/misc/weapon-mastery-properties.xml
> +	<element name="Lance (Topple)" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_WPM_LANCE_TOPPLE">
```suggestion
	<element name="Lance (Topple)" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_MASTERY_PROPERTY_LANCE_TOPPLE">
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/misc/weapon-mastery-properties.xml
> +	<element name="Maul (Topple)" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_WPM_MAUL_TOPPLE">
```suggestion
	<element name="Maul (Topple)" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_MASTERY_PROPERTY_MAUL_TOPPLE">
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/misc/weapon-mastery-properties.xml
> +	<element name="Trident (Topple)" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_WPM_TRIDENT_TOPPLE">
```suggestion
	<element name="Trident (Topple)" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_MASTERY_PROPERTY_TRIDENT_TOPPLE">
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/misc/weapon-mastery-properties.xml
> +	<element name="Handaxe (Vex)" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_WPM_HANDAXE_VEX">
```suggestion
	<element name="Handaxe (Vex)" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_MASTERY_PROPERTY_HANDAXE_VEX">
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/misc/weapon-mastery-properties.xml
> +	<element name="Dart (Vex)" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_WPM_DART_VEX">
```suggestion
	<element name="Dart (Vex)" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_MASTERY_PROPERTY_DART_VEX">
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/misc/weapon-mastery-properties.xml
> +	<element name="Shortbow (Vex)" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_WPM_SHORTBOW_VEX">
```suggestion
	<element name="Shortbow (Vex)" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_MASTERY_PROPERTY_SHORTBOW_VEX">
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/misc/weapon-mastery-properties.xml
> +	<element name="Rapier (Vex)" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_WPM_RAPIER_VEX">
```suggestion
	<element name="Rapier (Vex)" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_MASTERY_PROPERTY_RAPIER_VEX">
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/misc/weapon-mastery-properties.xml
> +	<element name="Shortsword (Vex)" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_WPM_SHORTSWORD_VEX">
```suggestion
	<element name="Shortsword (Vex)" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_MASTERY_PROPERTY_SHORTSWORD_VEX">
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/misc/weapon-mastery-properties.xml
> +	<element name="Blowgun (Vex)" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_WPM_BLOWGUN_VEX">
```suggestion
	<element name="Blowgun (Vex)" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_MASTERY_PROPERTY_BLOWGUN_VEX">
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/misc/weapon-mastery-properties.xml
> +	<element name="Crossbow, Hand (Vex)" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_WPM_CROSSBOW_HAND_VEX">
```suggestion
	<element name="Crossbow, Hand (Vex)" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_MASTERY_PROPERTY_CROSSBOW_HAND_VEX">
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/misc/weapon-mastery-properties.xml
> +	<element name="Pistol (Vex)" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_WPM_PISTOL_VEX">
```suggestion
	<element name="Pistol (Vex)" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_MASTERY_PROPERTY_PISTOL_VEX">
```

2025-12-12 14:49 UTC, NickVendel commented on core/players-handbook-2024/misc/properties-weapons.xml
this file can be deleted. Properties seems to be hardcodded, and since they're already part of the Internal source, there's no need to do anything with them.

2025-12-19 22:25 UTC, NickVendel requested changes
Hate these typos, only noticed them when working on spells file and encountering similar issue

2025-12-19 22:25 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +			<p>When you take the Attack action, you can replace one of your attacks with throwing a flask of Alchemist's Fire. Target one creature or object you can see within 20 feet of yourself. The target
```suggestion
			<p>When you take the Attack action, you can replace one of your attacks with throwing a flask of Alchemist's Fire. Target one creature or object you can see within 20 feet of yourself. The target must succeed on a Dexterity saving throw (DC 8 plus your Dexterity modifier and Proficiency Bonus) or take 1d4 Fire damage and start burning.</p>
```

2025-12-19 22:25 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +			<p>As a Utilize action, you can set a Hunting Trap, which is a sawtooth steel ring that snaps shut when a creature steps on a pressure plate in the center. The trap is affixed by a heavy chain to
```suggestion
			<p>As a Utilize action, you can set a Hunting Trap, which is a sawtooth steel ring that snaps shut when a creature steps on a pressure plate in the center. The trap is affixed by a heavy chain to an immobile object, such as a tree or a spike driven into the ground. A creature that steps on the plate must succeed on a DC 13 Dexterity saving throw or take 1d4 Piercing damage and have its Speed reduced to 0 until the start of its next turn. Thereafter, until the creature breaks free of the trap, its movement is limited by the length of the chain (typically 3 feet). A creature can use its action to make a DC 13 Strength (Athletics) check, freeing itself or another creature within its reach on a success. Each failed check deals 1 Piercing damage to the trapped creature.</p>
```

2025-12-19 22:25 UTC, NickVendel commented on core/players-handbook-2024/items/items-gear.xml
> +			<p>As a Bonus Action, you can use a vial of Basic Poison to coat one weapon or up to three pieces of ammunition. A creature that takes Piercing or Slashing damage from the poisoned weapon or ammun
```suggestion
			<p>As a Bonus Action, you can use a vial of Basic Poison to coat one weapon or up to three pieces of ammunition. A creature that takes Piercing or Slashing damage from the poisoned weapon or ammunition takes an extra 1d4 Poison damage. Once applied, the poison retains potency for 1 minute or until its damage is dealt, whichever comes first.</p>
```

2025-12-19 22:25 UTC, NickVendel commented on core/players-handbook-2024/misc/properties-weapons.xml
> +			<p class="indent"><i>Damage.</i> On a hit, the weapon deals ld4 damage of a type the DM thinks is appropriate for the object.</p>
```suggestion
			<p class="indent"><i>Damage.</i> On a hit, the weapon deals 1d4 damage of a type the DM thinks is appropriate for the object.</p>
```

2025-12-21 21:44 UTC, Tel0k commented on core/players-handbook-2024/misc/properties-weapons.xml
I don't think it would be ok to delete it.. even if properties are hardcoded, we should keep these at least for compendium purposes, as phb24 ones have differences in wording compared to old phb14 ones..

2025-12-21 21:54 UTC, Tel0k commented on core/players-handbook-2024/misc/properties-weapons.xml
or at least change them to type="Rule"?

2026-01-14 07:34 UTC, FreshRoyal commented on core/players-handbook-2024/misc/weapon-mastery-properties.xml
Would it be possible to add specific supports for whether a weapon is melee or ranged and also for if it's simple or martial? I feel like that would be a good quality-of-life addition for homebrewers.

2026-01-16 21:55 UTC, FreshRoyal reviewed
Other than what Nick already suggested changes for, I see no issues. We're still planning on adding all of the proficiencies and languages that overlap with the 2014 PHB to a standalone "SRD" source, right?

2026-02-01 23:39 UTC, merged