[PHB24] Backgrounds and Feats
AuroraLegacy/elements pull request #276
Opened 2024-09-16 14:30 UTC by Tel0k

2024-09-16 22:53 UTC, FreshRoyal commented
I haven't look at all the way through these yet, but the background ASI grant comes from the background so that it can replace the racial ASIs. With how the backgrounds are implemented now, the background ASIs are removed when the grant is given.

2024-09-16 23:21 UTC, Tel0k commented
No, the background ASIs are not removed when the grant is given, it's the contrary. When the grant is given, each background uses its own +2,+1/+1,+1,+1 ASIs (that is restricted to only 3 predetermined abilities) appended at the end of each file. When the grant is not given (using any other backgrounds than phb2024 ones) it uses the racial ASIs..

2024-09-17 00:17 UTC, FreshRoyal commented
Ah, alright, my mistake

2024-11-20 14:09 UTC, tregolani commented
Do we want to add setters for the short description in Aurora? Currently they're just blanks, which looks a bit strange when compared to backgrounds from other sources. 
![image](https://github.com/user-attachments/assets/9eceb289-f8db-4b21-99e6-2a7624bb72fa)

2024-11-20 14:31 UTC, tregolani requested changes
Noticed a few corrections needed during my app testing. Two instances of PHB14 proficiency grants, a few typos, and a couple incorrect skill prof grants.

2024-11-20 14:31 UTC, tregolani commented on core/players-handbook-2024/backgrounds/background-acolyte.xml
> +			<grant type="Proficiency" id="ID_PROFICIENCY_SKILL_RELIGION" />
```suggestion
			<grant type="Proficiency" id="ID_WOTC_PHB24_PROFICIENCY_SKILL_INSIGHT" />
			<grant type="Proficiency" id="ID_WOTC_PHB24_PROFICIENCY_SKILL_RELIGION" /> 
```

2024-11-20 14:31 UTC, tregolani commented on core/players-handbook-2024/backgrounds/background-farmer.xml
> +			<grant type="Proficiency" id="ID_WOTC_PHB24_PROFICIENCY_SKILL_STEALTH" />
Incorrect skill proficiency grants
```suggestion
			<grant type="Proficiency" id="ID_WOTC_PHB24_PROFICIENCY_SKILL_ANIMALHANDLING" /> 
			<grant type="Proficiency" id="ID_WOTC_PHB24_PROFICIENCY_SKILL_NATURE" />
```

2024-11-20 14:31 UTC, tregolani commented on core/players-handbook-2024/backgrounds/background-sailor.xml
> +				<tr><td><b>Skill Proficiencies:</b></td><td> : Acrobatics and Perception</td></tr>
```suggestion
				<tr><td><b>Skill Proficiencies:</b></td><td> Acrobatics and Perception</td></tr>
```

2024-11-20 14:31 UTC, tregolani commented on core/players-handbook-2024/backgrounds/background-scribe.xml
> +				<tr><td><b>Skill Proficiencies:</b></td><td> : Investigation and Perception</td></tr>
```suggestion
				<tr><td><b>Skill Proficiencies:</b></td><td> Investigation and Perception</td></tr>
```

2024-11-20 14:31 UTC, tregolani commented on core/players-handbook-2024/backgrounds/background-soldier.xml
> +			<grant type="Proficiency" id="ID_WOTC_PHB24_PROFICIENCY_SKILL_PERCEPTION" />
Wrong skill proficiency grant
```suggestion
			<grant type="Proficiency" id="ID_WOTC_PHB24_PROFICIENCY_SKILL_INTIMIDATION" />
```

2024-11-20 14:31 UTC, tregolani commented on core/players-handbook-2024/backgrounds/background-wayfarer.xml
> +				<tr><td><b>Skill Proficiencies:</b></td><td> : Insight and Stealth</td></tr>
```suggestion
				<tr><td><b>Skill Proficiencies:</b></td><td> Insight and Stealth</td></tr>
```

2024-12-03 03:57 UTC, tregolani reviewed
Some typos and corrections I found when testing the latest pulls.

2024-12-03 03:57 UTC, tregolani commented on core/players-handbook-2024/feats/feats-fighting-styles.xml
> +		<requirements>ID_WOTC_PHB24_CLASS_FEATURE_RANGER_FIGHTING_STYLE||ID_WOTC_PHB24_CLASS_FEATURE_PALADIN_FIGHTING_STYLE</requirements>
```suggestion
		<requirements>ID_WOTC_PHB24_CLASS_FEATURE_FIGHTER_FIGHTING_STYLE||ID_WOTC_PHB24_CLASS_FEATURE_RANGER_FIGHTING_STYLE||ID_WOTC_PHB24_CLASS_FEATURE_PALADIN_FIGHTING_STYLE</requirements>
```

2024-12-03 03:57 UTC, tregolani commented on core/players-handbook-2024/feats/feats-fighting-styles.xml
> +		<requirements>ID_WOTC_PHB24_CLASS_FEATURE_RANGER_FIGHTING_STYLE||ID_WOTC_PHB24_CLASS_FEATURE_PALADIN_FIGHTING_STYLE</requirements>
```suggestion
		<requirements>ID_WOTC_PHB24_CLASS_FEATURE_FIGHTER_FIGHTING_STYLE||ID_WOTC_PHB24_CLASS_FEATURE_RANGER_FIGHTING_STYLE||ID_WOTC_PHB24_CLASS_FEATURE_PALADIN_FIGHTING_STYLE</requirements>
```

2024-12-03 03:57 UTC, tregolani commented on core/players-handbook-2024/feats/feats-fighting-styles.xml
> +		<requirements>ID_WOTC_PHB24_CLASS_FEATURE_RANGER_FIGHTING_STYLE||ID_WOTC_PHB24_CLASS_FEATURE_PALADIN_FIGHTING_STYLE</requirements>
```suggestion
		<requirements>ID_WOTC_PHB24_CLASS_FEATURE_FIGHTER_FIGHTING_STYLE||ID_WOTC_PHB24_CLASS_FEATURE_RANGER_FIGHTING_STYLE||ID_WOTC_PHB24_CLASS_FEATURE_PALADIN_FIGHTING_STYLE</requirements>
```

2024-12-03 03:57 UTC, tregolani commented on core/players-handbook-2024/feats/feats-fighting-styles.xml
> +		<requirements>ID_WOTC_PHB24_CLASS_FEATURE_RANGER_FIGHTING_STYLE||ID_WOTC_PHB24_CLASS_FEATURE_PALADIN_FIGHTING_STYLE</requirements>
```suggestion
		<requirements>ID_WOTC_PHB24_CLASS_FEATURE_FIGHTER_FIGHTING_STYLE||ID_WOTC_PHB24_CLASS_FEATURE_RANGER_FIGHTING_STYLE||ID_WOTC_PHB24_CLASS_FEATURE_PALADIN_FIGHTING_STYLE</requirements>
```

2024-12-03 03:57 UTC, tregolani commented on core/players-handbook-2024/feats/feats-fighting-styles.xml
> +		<requirements>ID_WOTC_PHB24_CLASS_FEATURE_RANGER_FIGHTING_STYLE||ID_WOTC_PHB24_CLASS_FEATURE_PALADIN_FIGHTING_STYLE</requirements>
```suggestion
		<requirements>ID_WOTC_PHB24_CLASS_FEATURE_FIGHTER_FIGHTING_STYLE||ID_WOTC_PHB24_CLASS_FEATURE_RANGER_FIGHTING_STYLE||ID_WOTC_PHB24_CLASS_FEATURE_PALADIN_FIGHTING_STYLE</requirements>
```

2024-12-03 03:57 UTC, tregolani commented on core/players-handbook-2024/feats/feats-fighting-styles.xml
> +		<requirements>ID_WOTC_PHB24_CLASS_FEATURE_RANGER_FIGHTING_STYLE||ID_WOTC_PHB24_CLASS_FEATURE_PALADIN_FIGHTING_STYLE</requirements>
```suggestion
		<requirements>ID_WOTC_PHB24_CLASS_FEATURE_FIGHTER_FIGHTING_STYLE||ID_WOTC_PHB24_CLASS_FEATURE_RANGER_FIGHTING_STYLE||ID_WOTC_PHB24_CLASS_FEATURE_PALADIN_FIGHTING_STYLE</requirements>
```

2024-12-03 03:57 UTC, tregolani commented on core/players-handbook-2024/feats/feats-fighting-styles.xml
> +		<requirements>ID_WOTC_PHB24_CLASS_FEATURE_RANGER_FIGHTING_STYLE||ID_WOTC_PHB24_CLASS_FEATURE_PALADIN_FIGHTING_STYLE</requirements>
```suggestion
		<requirements>ID_WOTC_PHB24_CLASS_FEATURE_FIGHTER_FIGHTING_STYLE||ID_WOTC_PHB24_CLASS_FEATURE_RANGER_FIGHTING_STYLE||ID_WOTC_PHB24_CLASS_FEATURE_PALADIN_FIGHTING_STYLE</requirements>
```

2024-12-03 03:57 UTC, tregolani commented on core/players-handbook-2024/feats/feats-fighting-styles.xml
> +		<requirements>ID_WOTC_PHB24_CLASS_FEATURE_RANGER_FIGHTING_STYLE||ID_WOTC_PHB24_CLASS_FEATURE_PALADIN_FIGHTING_STYLE</requirements>
```suggestion
		<requirements>ID_WOTC_PHB24_CLASS_FEATURE_FIGHTER_FIGHTING_STYLE||ID_WOTC_PHB24_CLASS_FEATURE_RANGER_FIGHTING_STYLE||ID_WOTC_PHB24_CLASS_FEATURE_PALADIN_FIGHTING_STYLE</requirements>
```

2024-12-03 03:57 UTC, tregolani commented on core/players-handbook-2024/feats/feats-fighting-styles.xml
> +		<requirements>ID_WOTC_PHB24_CLASS_FEATURE_RANGER_FIGHTING_STYLE||ID_WOTC_PHB24_CLASS_FEATURE_PALADIN_FIGHTING_STYLE</requirements>
```suggestion
		<requirements>ID_WOTC_PHB24_CLASS_FEATURE_FIGHTER_FIGHTING_STYLE||ID_WOTC_PHB24_CLASS_FEATURE_RANGER_FIGHTING_STYLE||ID_WOTC_PHB24_CLASS_FEATURE_PALADIN_FIGHTING_STYLE</requirements>
```

2024-12-03 03:57 UTC, tregolani commented on core/players-handbook-2024/feats/feats-fighting-styles.xml
> +        <requirements>ID_WOTC_PHB24_CLASS_FEATURE_RANGER_FIGHTING_STYLE||ID_WOTC_PHB24_CLASS_FEATURE_PALADIN_FIGHTING_STYLE</requirements>
```suggestion
        <requirements>ID_WOTC_PHB24_CLASS_FEATURE_FIGHTER_FIGHTING_STYLE||ID_WOTC_PHB24_CLASS_FEATURE_RANGER_FIGHTING_STYLE||ID_WOTC_PHB24_CLASS_FEATURE_PALADIN_FIGHTING_STYLE</requirements>
```

2024-12-03 03:57 UTC, tregolani commented on core/players-handbook-2024/feats/feats-fighting-styles.xml
> +			<p>When you hit with your Unarmed Strike and deal damage, you can deal Bludgeoning damage equal to ld6 plus your Strength modifier instead of the normal damage of an Unarmed Strike. If you aren't
```suggestion
			<p>When you hit with your Unarmed Strike and deal damage, you can deal Bludgeoning damage equal to 1d6 plus your Strength modifier instead of the normal damage of an Unarmed Strike. If you aren't holding any weapons or a Shield when you make the attack roll, the d6 becomes a d8.</p>
```

2024-12-03 03:57 UTC, tregolani commented on core/players-handbook-2024/feats/feats-fighting-styles.xml
> +            At the start of each of your turns, you can deal ld4 Bludgeoning damage to one creature Grappled by you.</description>
```suggestion
			<description>When you hit with your Unarmed Strike and deal damage, you can deal 1d{{unarmed strike:dice}}+{{strength:modifier}} Bludgeoning damage instead of the normal damage of an Unarmed Strike.&#13;
            At the start of each of your turns, you can deal 1d4 Bludgeoning damage to one creature Grappled by you.</description>
```

2024-12-03 03:57 UTC, tregolani commented on core/players-handbook-2024/feats/feats-fighting-styles.xml
> +			<description>When a creature you can see hits another creature within 5feet of you with an attack roll, you can take a Reaction to reduce the damage dealt to the target by 1dlO+{{proficiency}}. Yo
```suggestion
			<p>When a creature you can see hits another creature within 5feet of you with an attack roll, you can take a Reaction to reduce the damage dealt to the target by 1d10 plus your Proficiency Bonus. You must be holding a Shield or a Simple or Martial weapon to use this Reaction.</p>
		</description>
		<sheet>
			<description>When a creature you can see hits another creature within 5feet of you with an attack roll, you can take a Reaction to reduce the damage dealt to the target by 1d10+{{proficiency}}. You must be holding a Shield or a Simple or Martial weapon.</description>
```

2024-12-03 03:57 UTC, tregolani commented on core/players-handbook-2024/feats/feats-fighting-styles.xml
> +            <p class="indent">At the start of each of your turns, you can deal ld4 Bludgeoning damage to one creature Grappled by you.</p>
```suggestion
            <p class="indent">At the start of each of your turns, you can deal 1d4 Bludgeoning damage to one creature Grappled by you.</p>
```

2024-12-03 03:57 UTC, tregolani commented on core/players-handbook-2024/feats/feats-general.xml
> +			<description>As part of a Short Rest, if you have ingredients and Cook's Utensils on hand, you can prepare enough of food for {{chef:meal}} creatures. At the end of the Short Rest, any creature wh
```suggestion
			<description>As part of a Short Rest, if you have ingredients and Cook's Utensils on hand, you can prepare enough of food for {{chef:meal}} creatures. At the end of the Short Rest, any creature who eat the food and spends one or more Hit Dice to regain HP regains an extra 1d8 HP. 
```

2024-12-03 03:57 UTC, tregolani commented on core/players-handbook-2024/feats/feats-general.xml
> +			<p class="indent"><b><i>Replenishing Meal.</i></b> As part of a Short Rest, you can cook special food if you have ingredients and Cook's Utensils on hand. You can prepare enough of this food for a
```suggestion
			<p class="indent"><b><i>Replenishing Meal.</i></b> As part of a Short Rest, you can cook special food if you have ingredients and Cook's Utensils on hand. You can prepare enough of this food for a number of creatures equal to 4 plus your Proficiency Bonus. At the end of the Short Rest, any creature who eat the food and spends one or more Hit Dice to regain Hit Points regains an extra 1d8 Hit Points.</p>
```

2024-12-03 03:57 UTC, tregolani commented on core/players-handbook-2024/feats/feats-general.xml
> +			<description>As part of a Short Rest, if you have ingredients and Cook's Utensils on hand, you can prepare enough of food for {{chef:meal}} creatures. At the end of the Short Rest, any creature wh
```suggestion
			<description>As part of a Short Rest, if you have ingredients and Cook's Utensils on hand, you can prepare enough of food for {{chef:meal}} creatures. At the end of the Short Rest, any creature who eat the food and spends one or more Hit Dice to regain HP regains an extra 1d8 HP. 
```

2024-12-03 03:57 UTC, tregolani commented on core/players-handbook-2024/feats/feats-origin.xml
> +			<stat name="initiative" value="{{proficiency}}" />
```suggestion
			<stat name="initiative" value="proficiency" />			
```

2024-12-03 03:57 UTC, tregolani commented on core/players-handbook-2024/feats/feats-origin.xml
> +			<p class="indent"><b><i>Enhanced Unarmed Strike.</i></b> When you hit with your Unarmed Strike and deal damage, you can deal Bludgeoning damage equal to ld4 plus your Strength modifier instead of
```suggestion
			<p class="indent"><b><i>Enhanced Unarmed Strike.</i></b> When you hit with your Unarmed Strike and deal damage, you can deal Bludgeoning damage equal to 1d4 plus your Strength modifier instead of the normal damage of an Unarmed Strike.</p> 
```

2024-12-03 03:57 UTC, tregolani commented on core/players-handbook-2024/feats/feats-origin.xml
> +			<description>When you hit with your Unarmed Strike and deal damage, you can deal ld4+{{strength:modifier}} Bludgeoning damage and, once per turn you can also push it 5ft away from you. Whenever yo
```suggestion
			<description>When you hit with your Unarmed Strike and deal damage, you can deal 1d4+{{strength:modifier}} Bludgeoning damage and, once per turn you can also push it 5ft away from you. Whenever you roll a 1 for damage for your Unarmed Strike, you can reroll the die, and you must use the new roll. You have proficiency with improvised weapons.</description>
```

2024-12-03 03:57 UTC, tregolani commented on core/players-handbook-2024/feats/feats-origin.xml
> +			<select type="Feat Feature" name="Magic Initiate" supports="Magic Initiate" requirements="!(ID_WOTC_PHB24_FEAT_MAGIC_INITIATE_CLERIC||ID_WOTC_PHB24_FEAT_MAGIC_INITIATE_DRUID||ID_WOTC_PHB24_FEAT_MA
Something about the way this is implemented was causing the app to reset my choice of magic initiate type if I didn't have one of Acolyte/Guide/Sage backgrounds. I need to do a bit more testing, but I think we can just remove the top three selects and just have those specific backgrounds assign the Feat Feature (i.e. `ID_WOTC_PHB24_FEAT_MAGIC_INITIATE_CLERIC` instead of `ID_WOTC_PHB24_FEAT_MAGIC_INITIATE`)instead of the full feat itself? Just brainstorming here

**_Edit_** - did some more testing, and I think I've got a way to implement this. I'll make a review comment with my suggestion.
```suggestion
			<select type="Feat Feature" name="Magic Initiate" supports="Origin Magic Initiate" />
```

2024-12-03 03:57 UTC, tregolani commented on core/players-handbook-2024/backgrounds/background-acolyte.xml
> +			<grant type="Feat" id="ID_WOTC_PHB24_FEAT_MAGIC_INITIATE" />
No need to give them the "top level selectable feat". Just grant the Feat Feature.
```suggestion
			<grant type="Feat Feature" id="ID_WOTC_PHB24_FEAT_MAGIC_INITIATE_CLERIC" />
```

2024-12-03 03:57 UTC, tregolani commented on core/players-handbook-2024/backgrounds/background-guide.xml
> +			<grant type="Feat" id="ID_WOTC_PHB24_FEAT_MAGIC_INITIATE" />
```suggestion
			<grant type="Feat Feature" id="ID_WOTC_PHB24_FEAT_MAGIC_INITIATE_DRUID" />
```

2024-12-03 03:57 UTC, tregolani commented on core/players-handbook-2024/backgrounds/background-sage.xml
> +			<grant type="Feat" id="ID_WOTC_PHB24_FEAT_MAGIC_INITIATE" />
```suggestion
			<grant type="Feat Feature" id="ID_WOTC_PHB24_FEAT_MAGIC_INITIATE_WIZARD" />
```

2024-12-03 03:57 UTC, tregolani commented on core/players-handbook-2024/feats/feats-origin.xml
> +			<select type="Feat Feature" name="Magic Initiate" supports="Magic Initiate" />
```suggestion
			<select type="Feat Feature" name="Magic Initiate" supports="Origin Magic Initiate" />
```

2024-12-03 03:57 UTC, tregolani commented on core/players-handbook-2024/feats/feats-origin.xml
> +			<select type="Feat Feature" name="Magic Initiate" supports="Magic Initiate" />
```suggestion
			<select type="Feat Feature" name="Magic Initiate" supports="Origin Magic Initiate" />
```

2024-12-03 03:57 UTC, tregolani commented on core/players-handbook-2024/feats/feats-origin.xml
> +		</setters>
```suggestion
	<element name="Cleric" type="Feat Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_FEAT_MAGIC_INITIATE_CLERIC">
		<supports>Origin Magic Initiate</supports>
		<compendium display="false" />
		<description>
			<p>You learn two cantrips of your choice from the cleric's spell list.</p>
			<p class="indent">Choose a level 1 spell from the same list. You always have that spell prepared. You can cast it once without a spell slot, and you regain the ability to cast it in that way when you finish a Long Rest. You can also cast the spell using any spell slots you have.</p>
			<p class="indent">Whenever you gain a new level, you can replace one of the spells you chose for this feat with a different spell of the same level from the chosen spell list.</p>
		</description>
		<setters>
			<set name="allow duplicate">false</set>
		</setters>
```

2024-12-03 03:57 UTC, tregolani commented on core/players-handbook-2024/feats/feats-origin.xml
> +		</setters>
```suggestion
	<element name="Druid" type="Feat Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_FEAT_MAGIC_INITIATE_DRUID">
		<supports>Origin Magic Initiate</supports>
		<compendium display="false" />
		<description>
			<p>You learn two cantrips of your choice from the druid's spell list.</p>
			<p class="indent">Choose a level 1 spell from the same list. You always have that spell prepared. You can cast it once without a spell slot, and you regain the ability to cast it in that way when you finish a Long Rest. You can also cast the spell using any spell slots you have.</p>
			<p class="indent">Whenever you gain a new level, you can replace one of the spells you chose for this feat with a different spell of the same level from the chosen spell list.</p>
		</description>
		<setters>
			<set name="allow duplicate">false</set>
		</setters>
```

2024-12-03 03:57 UTC, tregolani commented on core/players-handbook-2024/feats/feats-origin.xml
> +		</setters>
```suggestion
	<element name="Wizard" type="Feat Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_FEAT_MAGIC_INITIATE_WIZARD">
		<supports>Origin Magic Initiate</supports>
		<compendium display="false" />
		<description>
			<p>You learn two cantrips of your choice from the wizard's spell list.</p>
			<p class="indent">Choose a level 1 spell from the same list. You always have that spell prepared. You can cast it once without a spell slot, and you regain the ability to cast it in that way when you finish a Long Rest. You can also cast the spell using any spell slots you have.</p>
			<p class="indent">Whenever you gain a new level, you can replace one of the spells you chose for this feat with a different spell of the same level from the chosen spell list.</p>
		</description>
		<setters>
			<set name="allow duplicate">false</set>
		</setters>
```

2024-12-03 03:57 UTC, tregolani commented on core/players-handbook-2024/feats/feats-origin.xml
> +				<tr><td>Woodcarver's Tools</td><td>Club, Greatclub, Quarterstaf</td></tr>
```suggestion
				<tr><td>Woodcarver's Tools</td><td>Club, Greatclub, Quarterstaff</td></tr>
```

2024-12-03 03:57 UTC, tregolani commented on core/players-handbook-2024/feats/feats-general.xml
> +			<p class="indent"><b><i>Dash over Difficult Terrain.</i></b> When you take the Dash action on your turn, Difficult Terrain doesn't cost you extra movement for the rest ofthat turn.</p>
```suggestion
			<p class="indent"><b><i>Dash over Difficult Terrain.</i></b> When you take the Dash action on your turn, Difficult Terrain doesn't cost you extra movement for the rest of that turn.</p>
```

2024-12-03 03:57 UTC, tregolani commented on core/players-handbook-2024/feats/feats-general.xml
> +			<description>When you take the Dash action on your turn, Difficult Terrain doesn't cost you extra movement for the rest ofthat turn. Opportunity Attacks have Disadvantage against you.</description
```suggestion
			<description>When you take the Dash action on your turn, Difficult Terrain doesn't cost you extra movement for the rest of that turn. Opportunity Attacks have Disadvantage against you.</description>
```

2024-12-03 03:57 UTC, tregolani commented on core/players-handbook-2024/feats/feats-general.xml
> +			<description>When you take the Dash action on your turn, Difficult Terrain doesn't cost you extra movement for the rest ofthat turn. Opportunity Attacks have Disadvantage against you.</description
```suggestion
			<description>When you take the Dash action on your turn, Difficult Terrain doesn't cost you extra movement for the rest of that turn. Opportunity Attacks have Disadvantage against you.</description>
```

2024-12-03 03:57 UTC, tregolani commented on core/players-handbook-2024/feats/feats-epic-boons.xml
> +			<p class="indent"><b><i>Fortified Health.</i></b> Your Hit Point maximum increases by 40. In addition, whenever you regain Hit Points, you can regain additional Hit Points equal to your Constituti
```suggestion
			<p class="indent"><b><i>Fortified Health.</i></b> Your Hit Point maximum increases by 40. In addition, whenever you regain Hit Points, you can regain additional Hit Points equal to your Constitution modifier. Once you've regained these additional Hit Points, you can't do so again until the start of your next turn.</p>
```

2024-12-03 03:57 UTC, tregolani commented on core/players-handbook-2024/feats/feats-epic-boons.xml
> +			<p class="indent"><b><i>Merge with Shadows.</i></b> While within Dim Light or Darkness, you can give yourself the invisible condition as a Bonus Action. The condition ends on you immediately after
```suggestion
			<p class="indent"><b><i>Merge with Shadows.</i></b> While within Dim Light or Darkness, you can give yourself the invisible condition as a Bonus Action. The condition ends on you immediately after you take an action, a Bonus Action, or a Reaction.</p>
```

2024-12-03 03:57 UTC, tregolani commented on core/players-handbook-2024/feats/feats-fighting-styles.xml
> +		</rules>
```suggestion
```

2024-12-03 05:04 UTC, Tel0k commented on core/players-handbook-2024/feats/feats-origin.xml
> +			<select type="Feat Feature" name="Magic Initiate" supports="Magic Initiate" requirements="!(ID_WOTC_PHB24_FEAT_MAGIC_INITIATE_CLERIC||ID_WOTC_PHB24_FEAT_MAGIC_INITIATE_DRUID||ID_WOTC_PHB24_FEAT_MA
And what's wrong with that? If you have the background you get the appropriate one, if you don't you get to select the one you want.. if you change your background you don't keep the feat associated to it.. if it works as intended why bother changing it?

2024-12-25 22:16 UTC, Tel0k commented
Added the fix for Resilient feat, for now it works exclusively for PHB24 content. It needs further work for compatibility with older supplements giving PHB14 Saving Throws proficiencies.

2025-01-27 21:57 UTC, tregolani reviewed
Some small changes to Backgrounds granting Origin Feats that are repeatable to hopefully force the app to not give duplicates of something. Haven't had a chance to test it myself, so it might not even work...

2025-01-27 21:57 UTC, tregolani commented on core/players-handbook-2024/backgrounds/background-charlatan.xml
> +			<grant type="Feat" id="ID_WOTC_PHB24_FEAT_SKILLED" />
I think doing it this way will avoid two features both granting the first version of Skilled? Laser saw a slight bug where selecting a human origin feat (Skilled) before selecting background could cause ID overlap instead of incrementation, and thus only grant a single instance of the Skilled feat instead of two separate ones.

```suggestion
			<select type="Feat" name="Charlatan Origin Feat" supports="ID_WOTC_PHB24_FEAT_SKILLED,ID_WOTC_PHB24_FEAT_SKILLED_2" default="ID_WOTC_PHB24_FEAT_SKILLED" />
```

2025-01-27 21:57 UTC, tregolani commented on core/players-handbook-2024/backgrounds/background-noble.xml
> +			<grant type="Feat" id="ID_WOTC_PHB24_FEAT_SKILLED" />
Same as Charlatan
```suggestion
			<select type="Feat" name="Noble Origin Feat" supports="ID_WOTC_PHB24_FEAT_SKILLED,ID_WOTC_PHB24_FEAT_SKILLED_2" default="ID_WOTC_PHB24_FEAT_SKILLED" />
```

2025-01-27 21:57 UTC, tregolani commented on core/players-handbook-2024/backgrounds/background-scribe.xml
> +			<grant type="Feat" id="ID_WOTC_PHB24_FEAT_SKILLED" />
Same as Charlatan
```suggestion
			<select type="Feat" name="Scribe Origin Feat" supports="ID_WOTC_PHB24_FEAT_SKILLED,ID_WOTC_PHB24_FEAT_SKILLED_2" default="ID_WOTC_PHB24_FEAT_SKILLED" />
```

2025-01-27 21:57 UTC, tregolani commented on core/players-handbook-2024/backgrounds/background-acolyte.xml
> +			<grant type="Feat" id="ID_WOTC_PHB24_FEAT_MAGIC_INITIATE" />
I think doing it this way will avoid two features both granting the first version of Magic Initiate. Laser saw a slight bug where selecting a human origin feat (Magic Initiate) before selecting background could cause ID overlap instead of incrementation, and thus only grant a single instance of the Magic Initiate feat instead of two separate ones.
```suggestion
			<select type="Feat" name="Acolyte Origin Feat" supports="ID_WOTC_PHB24_FEAT_MAGIC_INITIATE,ID_WOTC_PHB24_FEAT_MAGIC_INITIATE_2" default="ID_WOTC_PHB24_FEAT_MAGIC_INITIATE" />
```

2025-01-27 21:57 UTC, tregolani commented on core/players-handbook-2024/backgrounds/background-guide.xml
> +			<grant type="Feat" id="ID_WOTC_PHB24_FEAT_MAGIC_INITIATE" />
Same as Acolyte
```suggestion
			<select type="Feat" name="Guide Origin Feat" supports="ID_WOTC_PHB24_FEAT_MAGIC_INITIATE,ID_WOTC_PHB24_FEAT_MAGIC_INITIATE_2" default="ID_WOTC_PHB24_FEAT_MAGIC_INITIATE" />
```

2025-01-27 21:57 UTC, tregolani commented on core/players-handbook-2024/backgrounds/background-sage.xml
> +			<grant type="Feat" id="ID_WOTC_PHB24_FEAT_MAGIC_INITIATE" />
Same as Acolyte
```suggestion
			<select type="Feat" name="Sage Origin Feat" supports="ID_WOTC_PHB24_FEAT_MAGIC_INITIATE,ID_WOTC_PHB24_FEAT_MAGIC_INITIATE_2" default="ID_WOTC_PHB24_FEAT_MAGIC_INITIATE" />
```

2025-01-27 23:44 UTC, Tel0k commented
please test things before making suggestions.. I will try to do something about this tomorrow, but I can already see that all the selections' supports are messed up and wont work properly.. if you use an ID collection you must use `|` not `,` to separate them, otherwise you are telling app to look for elements with both IDs as supports instead of two separate elements..
this will probably need the addition of an instance of both Magic Initiate and Skilled to compensate the Human trait feat selection, as I didn't take it into account when I made the feats..

2025-05-27 13:56 UTC, NickVendel requested changes
I've been a bit lazy with this review, just copied the contents of my files. So it might require some checking before applying the changes.

2025-05-27 13:56 UTC, NickVendel commented on core/internal.xml
> +
```suggestion
	<!-- 5e 2024: ASI Combinations elements for Backgrounds -->
	<element name="Strength, Dexterity, Constitution" type="Ability Score Improvement" source="Internal" id="ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_COMBINATION_STR_DEX_CON">
		<supports>Custom Background Ability Score Combination</supports>
		<compendium display="false" />
		<description>
			<p>You can increase Strength, Dexterity, or Constitution score by 2 and another one by 1, or increase all three by 1. None of these increases can raise a score above 20.</p>
		</description>
		<sheet display="false" />
		<rules>
			<select type="Ability Score Improvement" name="Ability Score Improvement Option" supports="ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_COMBINATION_STR_DEX_CON_1|ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_COMBINATION_STR_DEX_CON_2" />
		</rules>
	</element>
	<element name="Ability Score Improvement +2, +1" type="Ability Score Improvement" source="Internal" id="ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_COMBINATION_STR_DEX_CON_1">
		<compendium display="false" />
		<description>
			<p>You can increase Strength, Dexterity, or Constitution score by 2 and increase a different score by 1.</p>
		</description>
		<sheet display="false" />
		<rules>
			<select type="Ability Score Improvement" name="Custom Ability Score Improvement +2" supports="ID_WOTC_TCOE_OPTION_CUSTOMIZED_ASI_STRENGTH_INCREASE_2|ID_WOTC_TCOE_OPTION_CUSTOMIZED_ASI_DEXTERITY_INCREASE_2|ID_WOTC_TCOE_OPTION_CUSTOMIZED_ASI_CONSTITUTION_INCREASE_2" />
			<select type="Ability Score Improvement" name="Custom Ability Score Improvement +1" supports="ID_WOTC_TCOE_OPTION_CUSTOMIZED_ASI_STRENGTH_INCREASE_1|ID_WOTC_TCOE_OPTION_CUSTOMIZED_ASI_DEXTERITY_INCREASE_1|ID_WOTC_TCOE_OPTION_CUSTOMIZED_ASI_CONSTITUTION_INCREASE_1" />
		</rules>
	</element>
	<element name="Ability Score Improvement +1, +1, +1" type="Ability Score Improvement" source="Internal" id="ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_COMBINATION_STR_DEX_CON_2">
		<compendium display="false" />
		<description>
			<p>You increase Strength, Dexterity, and Constitution score by 1.</p>
		</description>
		<sheet display="false" />
		<rules>
			<stat name="strength" value="1" alt="Ability Score Increase (Background)" />
			<stat name="dexterity" value="1" alt="Ability Score Increase (Background)" />
			<stat name="constitution" value="1" alt="Ability Score Increase (Background)" />
		</rules>
	</element>

	<element name="Strength, Dexterity, Intelligence" type="Ability Score Improvement" source="Internal" id="ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_COMBINATION_STR_DEX_INT">
		<supports>Custom Background Ability Score Combination</supports>
		<compendium display="false" />
		<description>
			<p>You can increase Strength, Dexterity, or Intelligence score by 2 and another one by 1, or increase all three by 1. None of these increases can raise a score above 20.</p>
		</description>
		<sheet display="false" />
		<rules>
			<select type="Ability Score Improvement" name="Ability Score Improvement Option" supports="ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_COMBINATION_STR_DEX_INT_1|ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_COMBINATION_STR_DEX_INT_2" />
		</rules>
	</element>
	<element name="Ability Score Improvement +2, +1" type="Ability Score Improvement" source="Internal" id="ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_COMBINATION_STR_DEX_INT_1">
		<compendium display="false" />
		<description>
			<p>You can increase Strength, Dexterity, or Intelligence score by 2 and increase a different score by 1.</p>
		</description>
		<sheet display="false" />
		<rules>
			<select type="Ability Score Improvement" name="Custom Ability Score Improvement +2" supports="ID_WOTC_TCOE_OPTION_CUSTOMIZED_ASI_STRENGTH_INCREASE_2|ID_WOTC_TCOE_OPTION_CUSTOMIZED_ASI_DEXTERITY_INCREASE_2|ID_WOTC_TCOE_OPTION_CUSTOMIZED_ASI_INTELLIGENCE_INCREASE_2" />
			<select type="Ability Score Improvement" name="Custom Ability Score Improvement +1" supports="ID_WOTC_TCOE_OPTION_CUSTOMIZED_ASI_STRENGTH_INCREASE_1|ID_WOTC_TCOE_OPTION_CUSTOMIZED_ASI_DEXTERITY_INCREASE_1|ID_WOTC_TCOE_OPTION_CUSTOMIZED_ASI_INTELLIGENCE_INCREASE_1" />
		</rules>
	</element>
	<element name="Ability Score Improvement +1, +1, +1" type="Ability Score Improvement" source="Internal" id="ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_COMBINATION_STR_DEX_INT_2">
		<compendium display="false" />
		<description>
			<p>You increase Strength, Dexterity, and Intelligence score by 1.</p>
		</description>
		<sheet display="false" />
		<rules>
			<stat name="strength" value="1" alt="Ability Score Increase (Background)" />
			<stat name="dexterity" value="1" alt="Ability Score Increase (Background)" />
			<stat name="intelligence" value="1" alt="Ability Score Increase (Background)" />
		</rules>
	</element>

	<element name="Strength, Dexterity, Wisdom" type="Ability Score Improvement" source="Internal" id="ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_COMBINATION_STR_DEX_WIS">
		<supports>Custom Background Ability Score Combination</supports>
		<compendium display="false" />
		<description>
			<p>You can increase Strength, Dexterity, or Wisdom score by 2 and another one by 1, or increase all three by 1. None of these increases can raise a score above 20.</p>
		</description>
		<sheet display="false" />
		<rules>
			<select type="Ability Score Improvement" name="Ability Score Improvement Option" supports="ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_COMBINATION_STR_DEX_WIS_1|ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_COMBINATION_STR_DEX_WIS_2" />
		</rules>
	</element>
	<element name="Ability Score Improvement +2, +1" type="Ability Score Improvement" source="Internal" id="ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_COMBINATION_STR_DEX_WIS_1">
		<compendium display="false" />
		<description>
			<p>You can increase Strength, Dexterity, or Wisdom score by 2 and increase a different score by 1.</p>
		</description>
		<sheet display="false" />
		<rules>
			<select type="Ability Score Improvement" name="Custom Ability Score Improvement +2" supports="ID_WOTC_TCOE_OPTION_CUSTOMIZED_ASI_STRENGTH_INCREASE_2|ID_WOTC_TCOE_OPTION_CUSTOMIZED_ASI_DEXTERITY_INCREASE_2|ID_WOTC_TCOE_OPTION_CUSTOMIZED_ASI_WISDOM_INCREASE_2" />
			<select type="Ability Score Improvement" name="Custom Ability Score Improvement +1" supports="ID_WOTC_TCOE_OPTION_CUSTOMIZED_ASI_STRENGTH_INCREASE_1|ID_WOTC_TCOE_OPTION_CUSTOMIZED_ASI_DEXTERITY_INCREASE_1|ID_WOTC_TCOE_OPTION_CUSTOMIZED_ASI_WISDOM_INCREASE_1" />
		</rules>
	</element>
	<element name="Ability Score Improvement +1, +1, +1" type="Ability Score Improvement" source="Internal" id="ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_COMBINATION_STR_DEX_WIS_2">
		<compendium display="false" />
		<description>
			<p>You increase Strength, Dexterity, and Wisdom score by 1.</p>
		</description>
		<sheet display="false" />
		<rules>
			<stat name="strength" value="1" alt="Ability Score Increase (Background)" />
			<stat name="dexterity" value="1" alt="Ability Score Increase (Background)" />
			<stat name="wisdom" value="1" alt="Ability Score Increase (Background)" />
		</rules>
	</element>

	<element name="Strength, Dexterity, Charisma" type="Ability Score Improvement" source="Internal" id="ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_COMBINATION_STR_DEX_CHA">
		<supports>Custom Background Ability Score Combination</supports>
		<compendium display="false" />
		<description>
			<p>You can increase Strength, Dexterity, or Charisma score by 2 and another one by 1, or increase all three by 1. None of these increases can raise a score above 20.</p>
		</description>
		<sheet display="false" />
		<rules>
			<select type="Ability Score Improvement" name="Ability Score Improvement Option" supports="ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_COMBINATION_STR_DEX_CHA_1|ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_COMBINATION_STR_DEX_CHA_2" />
		</rules>
	</element>
	<element name="Ability Score Improvement +2, +1" type="Ability Score Improvement" source="Internal" id="ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_COMBINATION_STR_DEX_CHA_1">
		<compendium dis [...]

2025-05-27 13:56 UTC, NickVendel commented on core/players-handbook-2024/backgrounds/background-acolyte.xml
> +	</element>
```suggestion
		<description>The Acolyte background from the Player’s Handbook 2024.</description>
		<author url="https://dndstore.wizards.com/us/en/product/1001494/2024-player-s-handbook-digital-plus-physical-bundle">Wizards of the Coast</author>
		<update version="0.0.1">
			<file name="background-acolyte.xml" url="https://raw.githubusercontent.com/AuroraLegacy/elements/master/core/players-handbook-2024/backgrounds/background-acolyte.xml" />
		</update>
	</info>

	<element name="Acolyte" type="Background" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_BACKGROUND_ACOLYTE">
		<description>
			<ul class="unstyled" style="text-indent:-1em; margin-left:1em; margin-bottom:5px">
				<li><strong>Ability Scores:</strong> Intelligence, Wisdom, Charisma</li>
				<li><strong>Feat:</strong> Magic Initiate (Cleric)</li>
				<li><strong>Skill Proficiencies:</strong> Insight and Religion</li>
				<li><strong>Tool Proficiency:</strong> Calligrapher’s Supplies</li>
				<li><strong>Equipment:</strong><i> Choose A or B:</i> (A) Calligrapher’s Supplies, Book (prayers), Holy Symbol, Parchment (10 sheets), Robe, 8 GP; or (B) 50 GP</li>
			</ul>
			<p>You devoted yourself to service in a temple, either nestled in a town or secluded in a sacred grove. There you performed rites in honor of a god or pantheon. You served under a priest and studied religion. Thanks to your priest’s instruction and your own devotion, you also learned how to channel a modicum of divine power in service to your place of worship and the people who prayed there.</p>
		</description>
		<setters>
			<set name="short">Intelligence, Wisdom, Charisma, Magic Initiate (Cleric) Feat, Insight and Religion Skills, and Calligrapher’s Supplies</set>
		</setters>
		<rules>
			<grant type="Ability Score Improvement" id="ID_WOTC_INTERNAL_ABILITY_SCORE_IMPROVEMENT_COMBINATION_INT_WIS_CHA" />
			<grant type="Feat" id="ID_WOTC_PHB24_FEAT_MAGIC_INITIATE_CLERIC" />
			<grant type="Proficiency" id="ID_WOTC_PHB24_PROFICIENCY_SKILL_INSIGHT" />
			<grant type="Proficiency" id="ID_WOTC_PHB24_PROFICIENCY_SKILL_RELIGION" />
			<grant type="Grants" id="ID_INTERNAL_GRANTS_BACKGROUND_ASI" />
			<grant type="Proficiency" id="ID_PROFICIENCY_TOOL_PROFICIENCY_CALLIGRAPHERS_SUPPLIES" />
		</rules>
	</element>

	<!-- Placeholder: Equipment Pack for Backgrounds. Will be populated with correct IDs later -->
	<!-- <element name="Background Equipment Pack (Acolyte)" type="Item" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ITEM_BACKGROUND_EQUIPMENT_PACK_ACOLYTE">
		<description>
			<p style="margin-bottom:5px">This pack contains items that are given to a character of Acolyte Background, if they chose option A.</p>
			<p>You will receive following items by extracting contents of this pack:</p>
			<p class="indent">• Calligrapher’s Supplies</p>
			<p class="indent">• Book (prayers)</p>
			<p class="indent">• Holy Symbol</p>
			<p class="indent">• Parchment (10 sheets)</p>
			<p class="indent" style="margin-bottom:5px">• Robe</p>
			<p><b>Note:</b> This pack doesn't include 8 GP.</p>
		</description>
		<setters>
			<set name="category">Equipment Packs</set>
			<set name="cost">—</set>
			<set name="weight">—</set>
		</setters>
		<extract>
			<item>Calligrapher’s Supplies</item>
			<item>Book (prayers)</item>
			<item>Holy Symbol</item>
			<item amount="10">Parchment (10 sheets)</item>
			<item>Robe</item>
		</extract>
	</element> -->
```

2025-05-27 13:56 UTC, NickVendel commented on core/players-handbook-2024/backgrounds/background-artisan.xml
> +
```suggestion
		<description>Artisan background from the Player’s Handbook 2024.</description>
		<author url="https://dndstore.wizards.com/us/en/product/1001494/2024-player-s-handbook-digital-plus-physical-bundle">Wizards of the Coast</author>
		<update version="0.0.1">
			<file name="background-artisan.xml" url="https://raw.githubusercontent.com/AuroraLegacy/elements/master/core/players-handbook-2024/backgrounds/background-artisan.xml" />
		</update>
	</info>

	<element name="Artisan" type="Background" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_BACKGROUND_ARTISAN">
		<description>
			<ul class="unstyled" style="text-indent:-1em; margin-left:1em; margin-bottom:5px">
				<li><strong>Ability Scores:</strong> Strength, Dexterity, Intelligence</li>
				<li><strong>Feat:</strong> Crafter</li>
				<li><strong>Skill Proficiencies:</strong> Investigation and Persuasion</li>
				<li><strong>Tool Proficiency:</strong><i> Choose one kind of Artisan's Tools</i></li>
				<li><strong>Equipment:</strong><i> Choose A or B:</i> (A) Artisan’s Tools (same as above), 2 Pouches, Traveler's Clothes, 32 GP; or (B) 50 GP</li>
			</ul>
			<p>You began mopping floors and scrubbing counters in an artisan's workshop for a few coppers per day as soon as you were strong enough to carry a bucket. When you were old enough to apprentice, you learned to create basic crafts of your own, as well as how to sweet-talk the occasional demanding customer. Your trade has also given you a keen eye for detail.</p>
		</description>
		<setters>
			<set name="short">Strength, Dexterity, Intelligence, Crafter Feat, Investigation and Persuasion Skills, an Artisan's Tool</set>
		</setters>
		<rules>
			<grant type="Ability Score Improvement" id="ID_WOTC_INTERNAL_ABILITY_SCORE_IMPROVEMENT_COMBINATION_STR_DEX_INT" />
			<grant type="Feat" id="ID_WOTC_PHB24_FEAT_CRAFTER" />
			<grant type="Proficiency" id="ID_WOTC_PHB24_PROFICIENCY_SKILL_INVESTIGATION" />
			<grant type="Proficiency" id="ID_WOTC_PHB24_PROFICIENCY_SKILL_PERSUASION" />
			<grant type="Grants" id="ID_INTERNAL_GRANTS_BACKGROUND_ASI" />
			<select type="Proficiency" name="Tool Proficiency (Artisan)" supports="Tool, Artisan tools" />
		</rules>
	</element>

	<!-- Todo: Add Equipment Pack for this Background. Example element is in the Acolyte Background. -->
```

2025-05-27 13:56 UTC, NickVendel commented on core/players-handbook-2024/backgrounds/background-charlatan.xml
> +
```suggestion
		<description>Charlatan background from the Player’s Handbook 2024.</description>
		<author url="https://dndstore.wizards.com/us/en/product/1001494/2024-player-s-handbook-digital-plus-physical-bundle">Wizards of the Coast</author>
		<update version="0.0.1">
			<file name="background-charlatan.xml" url="https://raw.githubusercontent.com/AuroraLegacy/elements/master/core/players-handbook-2024/backgrounds/background-charlatan.xml" />
		</update>
	</info>

	<element name="Charlatan" type="Background" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_BACKGROUND_CHARLATAN">
		<description>
			<ul class="unstyled" style="text-indent:-1em; margin-left:1em; margin-bottom:5px">
				<li><strong>Ability Scores:</strong> Dexterity, Constitution, Charisma</li>
				<li><strong>Feat:</strong> Skilled</li>
				<li><strong>Skill Proficiencies:</strong> Deception and Sleight of Hand</li>
				<li><strong>Tool Proficiency:</strong> Forgery Kit</li>
				<li><strong>Equipment:</strong><i> Choose A or B:</i> (A) Forgery Kit, Costume, Fine Clothes, 15 CP; or (B) 50 GP</li>
			</ul>
			<p>Once you were old enough to order an ale, you soon had a favorite stool in every tavern within ten miles of where you were born. As you traveled the circuit from public house to watering hole, you learned to prey on unfortunates who were in the market for a comforting lie or two-perhaps a sham potion or forged ancestry records.</p>
		</description>
		<setters>
			<set name="short">Dexterity, Constitution, Charisma, Skilled Feat, Deception and Sleight of Hand Skills, Forgery Kit</set>
		</setters>
		<rules>
			<grant type="Ability Score Improvement" id="ID_WOTC_INTERNAL_ABILITY_SCORE_IMPROVEMENT_COMBINATION_DEX_CON_CHA" />
			<select type="Feat" name="Origin Feat (Charlatan)" supports="ID_WOTC_PHB24_FEAT_SKILLED|ID_WOTC_PHB24_FEAT_SKILLED_2" default="ID_WOTC_PHB24_FEAT_SKILLED" />
			<grant type="Proficiency" id="ID_WOTC_PHB24_PROFICIENCY_SKILL_DECEPTION" />
			<grant type="Proficiency" id="ID_WOTC_PHB24_PROFICIENCY_SKILL_SLEIGHTOFHAND" />
			<grant type="Grants" id="ID_INTERNAL_GRANTS_BACKGROUND_ASI" />
			<grant type="Proficiency" id="ID_WOTC_PHB24_PROFICIENCY_TOOL_PROFICIENCY_FORGERY_KIT" />
		</rules>
	</element>

	<!-- Todo: Add Equipment Pack for this Background. Example element is in the Acolyte Background. -->
```

2025-05-27 13:56 UTC, NickVendel commented on core/players-handbook-2024/backgrounds/background-criminal.xml
> +
```suggestion
		<description>Criminal background from the Player’s Handbook 2024.</description>
		<author url="https://dndstore.wizards.com/us/en/product/1001494/2024-player-s-handbook-digital-plus-physical-bundle">Wizards of the Coast</author>
		<update version="0.0.1">
			<file name="background-criminal.xml" url="https://raw.githubusercontent.com/AuroraLegacy/elements/master/core/players-handbook-2024/backgrounds/background-criminal.xml" />
		</update>
	</info>

	<element name="Criminal" type="Background" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_BACKGROUND_CRIMINAL">
		<description>
			<ul class="unstyled" style="text-indent:-1em; margin-left:1em; margin-bottom:5px">
				<li><strong>Ability Scores:</strong> Dexterity, Constitution, Intelligence</li>
				<li><strong>Feat:</strong> Alert</li>
				<li><strong>Skill Proficiencies:</strong> Sleight of Hand and Stealth</li>
				<li><strong>Tool Proficiency:</strong> Thieves' Tools</li>
				<li><strong>Equipment:</strong><i> Choose A or B:</i> (A) 2 Daggers, Thieves' Tools, Crowbar, 2 Pouches, Traveler's Clothes, 16 CP; or (B) 50 GP</li>
			</ul>
			<p>You eked out a living in dark alleyways, cutting purses or burgling shops. Perhaps you were part of a small gang of like-minded wrongdoers who looked out for each other. Or maybe you were a lone wolf, fending for yourself against the local thieves' guild and more fearsome lawbreakers.</p>
		</description>
		<setters>
			<set name="short">Dexterity, Constitution, Intelligence, Alert Feat, Sleight of Hand and Stealth Skills, Thieves' Tools</set>
		</setters>
		<rules>
			<grant type="Ability Score Improvement" id="ID_WOTC_INTERNAL_ABILITY_SCORE_IMPROVEMENT_COMBINATION_DEX_CON_INT" />
			<grant type="Feat" id="ID_WOTC_PHB24_FEAT_ALERT" />
			<grant type="Proficiency" id="ID_WOTC_PHB24_PROFICIENCY_SKILL_SLEIGHTOFHAND" />
			<grant type="Proficiency" id="ID_WOTC_PHB24_PROFICIENCY_SKILL_STEALTH" />
			<grant type="Grants" id="ID_INTERNAL_GRANTS_BACKGROUND_ASI" />
			<grant type="Proficiency" id="ID_WOTC_PHB24_PROFICIENCY_TOOL_PROFICIENCY_THIEVES_TOOLS" />
		</rules>
	</element>

	<!-- Todo: Add Equipment Pack for this Background. Example element is in the Acolyte Background. -->
```

2025-05-27 13:56 UTC, NickVendel commented on core/players-handbook-2024/backgrounds/background-entertainer.xml
> +
```suggestion
		<description>Entertainer background from the Player’s Handbook 2024.</description>
		<author url="https://dndstore.wizards.com/us/en/product/1001494/2024-player-s-handbook-digital-plus-physical-bundle">Wizards of the Coast</author>
		<update version="0.0.1">
			<file name="background-entertainer.xml" url="https://raw.githubusercontent.com/AuroraLegacy/elements/master/core/players-handbook-2024/backgrounds/background-entertainer.xml" />
		</update>
	</info>

	<element name="Entertainer" type="Background" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_BACKGROUND_ENTERTAINER">
		<description>
			<ul class="unstyled" style="text-indent:-1em; margin-left:1em; margin-bottom:5px">
				<li><strong>Ability Scores:</strong> Strength, Dexterity, Charisma</li>
				<li><strong>Feat:</strong> Musician</li>
				<li><strong>Skill Proficiencies:</strong> Acrobatics and Performance</li>
				<li><strong>Tool Proficiency:</strong><i> Choose one kind of Musical Instrument</i></li>
				<li><strong>Equipment:</strong><i> Choose A or B:</i> (A) Musical Instrument (same as above), 2 Costumes, Mirror, Perfume, Traveler's Clothes, 11 GP; or (B) 50 GP</li>
			</ul>
			<p>You spent much of your youth following roving fairs and carnivals, performing odd jobs for musicians and acrobats in exchange for lessons. You may have learned how to walk a tightrope, how to play a lute in a distinct style, or how to recite poetry with impeccable diction. To this day, you thrive on applause and long for the stage.</p>
		</description>
		<setters>
			<set name="short">Strength, Dexterity, Charisma, Musician Feat, Acrobatics and Performance Skills, a Musical Instrument</set>
		</setters>
		<rules>
			<grant type="Ability Score Improvement" id="ID_WOTC_INTERNAL_ABILITY_SCORE_IMPROVEMENT_COMBINATION_STR_DEX_CHA" />
			<grant type="Feat" id="ID_WOTC_PHB24_FEAT_MUSICIAN" />
			<grant type="Proficiency" id="ID_WOTC_PHB24_PROFICIENCY_SKILL_ACROBATICS" />
			<grant type="Proficiency" id="ID_WOTC_PHB24_PROFICIENCY_SKILL_PERFORMANCE" />
			<grant type="Grants" id="ID_INTERNAL_GRANTS_BACKGROUND_ASI" />
			<select type="Proficiency" name="Musical Instrument (Entertainer)" supports="Musical Instrument" />
		</rules>
	</element>

	<!-- Todo: Add Equipment Pack for this Background. Example element is in the Acolyte Background. -->
```

2025-05-27 13:56 UTC, NickVendel commented on core/players-handbook-2024/backgrounds/background-farmer.xml
> +
```suggestion
		<description>Farmer background from the Player’s Handbook 2024.</description>
		<author url="https://dndstore.wizards.com/us/en/product/1001494/2024-player-s-handbook-digital-plus-physical-bundle">Wizards of the Coast</author>
		<update version="0.0.1">
			<file name="background-farmer.xml" url="https://raw.githubusercontent.com/AuroraLegacy/elements/master/core/players-handbook-2024/backgrounds/background-farmer.xml" />
		</update>
	</info>

	<element name="Farmer" type="Background" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_BACKGROUND_FARMER">
		<description>
			<ul class="unstyled" style="text-indent:-1em; margin-left:1em; margin-bottom:5px">
				<li><strong>Ability Scores:</strong> Strength, Constitution, Wisdom</li>
				<li><strong>Feat:</strong> Tough</li>
				<li><strong>Skill Proficiencies:</strong> Animal Handling and Nature</li>
				<li><strong>Tool Proficiency:</strong> Carpenter's Tools</li>
				<li><strong>Equipment:</strong><i> Choose A or B:</i> (A) Sickle, Carpenter's Tools, Healer's Kit, Iron Pot, Shovel, Traveler's Clothes, 30GP; or (B) 50 GP</li>
			</ul>
			<p>You grew up close to the land. Years tending animals and cultivating the earth rewarded you with patience and good health. You have a keen appreciation for nature's bounty alongside a healthy respect for nature's wrath.</p>
		</description>
		<setters>
			<set name="short">Strength, Constitution, Wisdom, Tough Feat, Animal Handling and Nature Skills, Carpenter's Tools</set>
		</setters>
		<rules>
			<grant type="Ability Score Improvement" id="ID_WOTC_INTERNAL_ABILITY_SCORE_IMPROVEMENT_COMBINATION_STR_CON_WIS" />
			<grant type="Feat" id="ID_WOTC_PHB24_FEAT_TOUGH" />
			<grant type="Proficiency" id="ID_WOTC_PHB24_PROFICIENCY_SKILL_ANIMALHANDLING" />
			<grant type="Proficiency" id="ID_WOTC_PHB24_PROFICIENCY_SKILL_NATURE" />
			<grant type="Grants" id="ID_INTERNAL_GRANTS_BACKGROUND_ASI" />
			<grant type="Proficiency" id="ID_WOTC_PHB24_PROFICIENCY_TOOL_PROFICIENCY_CARPENTERS_TOOLS" />
		</rules>
	</element>

	<!-- Todo: Add Equipment Pack for this Background. Example element is in the Acolyte Background. -->
```

2025-05-27 13:56 UTC, NickVendel commented on core/players-handbook-2024/backgrounds/background-guard.xml
> +
```suggestion
		<description>Guard background from the Player’s Handbook 2024.</description>
		<author url="https://dndstore.wizards.com/us/en/product/1001494/2024-player-s-handbook-digital-plus-physical-bundle">Wizards of the Coast</author>
		<update version="0.0.1">
			<file name="background-guard.xml" url="https://raw.githubusercontent.com/AuroraLegacy/elements/master/core/players-handbook-2024/backgrounds/background-guard.xml" />
		</update>
	</info>

	<element name="Guard" type="Background" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_BACKGROUND_GUARD">
		<description>
			<ul class="unstyled" style="text-indent:-1em; margin-left:1em; margin-bottom:5px">
				<li><strong>Ability Scores:</strong> Strength, Intelligence, Wisdom</li>
				<li><strong>Feat:</strong> Alert</li>
				<li><strong>Skill Proficiencies:</strong> Athletics and Perception</li>
				<li><strong>Tool Proficiency:</strong><i> Choose one kind of Gaming Set</i></li>
				<li><strong>Equipment:</strong><i> Choose A or B:</i> (A) Spear, Light Crossbow, 20 Bolts, Gaming Set (same as above). Hooded Lantern, Manacles, Quiver, Traveler's Clothes, 12 GP; or (B) 50 GP</li>
			</ul>
			<p>Your feet ache when you remember the countless hours you spent at your post in the tower. You were trained to keep one eye looking outside the wall, watching for marauders sweeping from the nearby forest, and your other eye looking inside the wall, searching for cutpurses and troublemakers.</p>
		</description>
		<setters>
			<set name="short">Strength, Intelligence, Wisdom, Alert Feat, Athletics and Perception Skills, a Gaming Set</set>
		</setters>
		<rules>
			<grant type="Ability Score Improvement" id="ID_WOTC_INTERNAL_ABILITY_SCORE_IMPROVEMENT_COMBINATION_STR_INT_WIS" />
			<grant type="Feat" id="ID_WOTC_PHB24_FEAT_ALERT" />
			<grant type="Proficiency" id="ID_WOTC_PHB24_PROFICIENCY_SKILL_ATHLETICS" />
			<grant type="Proficiency" id="ID_WOTC_PHB24_PROFICIENCY_SKILL_PERCEPTION" />
			<grant type="Grants" id="ID_INTERNAL_GRANTS_BACKGROUND_ASI" />
			<select type="Proficiency" name="Gaming Set (Guard)" supports="Gaming Set" />
		</rules>
	</element>

	<!-- Todo: Add Equipment Pack for this Background. Example element is in the Acolyte Background. -->
```

2025-05-27 13:56 UTC, NickVendel commented on core/players-handbook-2024/backgrounds/background-guide.xml
> +
```suggestion
		<description>Guide background from the Player’s Handbook 2024.</description>
		<author url="https://dndstore.wizards.com/us/en/product/1001494/2024-player-s-handbook-digital-plus-physical-bundle">Wizards of the Coast</author>
		<update version="0.0.1">
			<file name="background-guide.xml" url="https://raw.githubusercontent.com/AuroraLegacy/elements/master/core/players-handbook-2024/backgrounds/background-guide.xml" />
		</update>
	</info>

	<element name="Guide" type="Background" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_BACKGROUND_GUIDE">
		<description>
			<ul class="unstyled" style="text-indent:-1em; margin-left:1em; margin-bottom:5px">
				<li><strong>Ability Scores:</strong> Dexterity, Constitution, Wisdom</li>
				<li><strong>Feat:</strong> Magic Initiate (Druid)</li>
				<li><strong>Skill Proficiencies:</strong> Stealth and Survival</li>
				<li><strong>Tool Proficiency:</strong> Cartographer's Tools</li>
				<li><strong>Equipment:</strong><i> Choose A or B:</i> (A) Shortbow, 20 Arrows, Cartographer's Tools, Bedroll, Quiver, Tent, Traveler's Clothes, 3 GP; or (B) 50 GP</li>
			</ul>
			<p>You came of age outdoors, far from settled lands. Your home was anywhere you chose to spread your bedroll. There are wonders in the wilderness—strange monsters, pristine forests and streams, overgrown ruins of great halls once trod by giants—and you learned to fend for yourself as you explored them. From time to time, you guided friendly nature priests who instructed you in the fundamentals of channeling the magic of the wild.</p>
		</description>
		<setters>
			<set name="short">Dexterity, Constitution, Wisdom, Magic Initiate (Druid) Feat, Stealth and Survival Skills, Cartographer's Tools</set>
		</setters>
		<rules>
			<grant type="Ability Score Improvement" id="ID_WOTC_INTERNAL_ABILITY_SCORE_IMPROVEMENT_COMBINATION_DEX_CON_WIS" />
			<grant type="Feat" id="ID_WOTC_PHB24_FEAT_MAGIC_INITIATE_DRUID" />
			<grant type="Proficiency" id="ID_WOTC_PHB24_PROFICIENCY_SKILL_STEALTH" />
			<grant type="Proficiency" id="ID_WOTC_PHB24_PROFICIENCY_SKILL_SURVIVAL" />
			<grant type="Grants" id="ID_INTERNAL_GRANTS_BACKGROUND_ASI" />
			<grant type="Proficiency" id="ID_WOTC_PHB24_PROFICIENCY_TOOL_PROFICIENCY_CARPENTERS_TOOLS" />
		</rules>
	</element>

	<!-- Todo: Add Equipment Pack for this Background. Example element is in the Acolyte Background. -->
```

2025-05-27 13:56 UTC, NickVendel commented on core/players-handbook-2024/backgrounds/background-hermit.xml
> +
```suggestion
		<description>Hermit background from the Player’s Handbook 2024.</description>
		<author url="https://dndstore.wizards.com/us/en/product/1001494/2024-player-s-handbook-digital-plus-physical-bundle">Wizards of the Coast</author>
		<update version="0.0.1">
			<file name="background-hermit.xml" url="https://raw.githubusercontent.com/AuroraLegacy/elements/master/core/players-handbook-2024/backgrounds/background-hermit.xml" />
		</update>
	</info>

	<element name="Hermit" type="Background" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_BACKGROUND_HERMIT">
		<description>
			<ul class="unstyled" style="text-indent:-1em; margin-left:1em; margin-bottom:5px">
				<li><strong>Ability Scores:</strong> Constitution, Wisdom, Charisma</li>
				<li><strong>Feat:</strong> Healer</li>
				<li><strong>Skill Proficiencies:</strong> Medicine and Religion</li>
				<li><strong>Tool Proficiency:</strong> Herbalism Kit</li>
				<li><strong>Equipment:</strong><i> Choose A or B:</i> (A) Quarterstaff, Herbalism Kit, Bedroll, Book (philosophy), Lamp, Oil (3 flasks), Traveler's Clothes, 16 CP; or (B) 50 GP</li>
			</ul>
			<p>You spent your early years secluded in a hut or monastery located well beyond the outskirts of the nearest settlement. In those days, your only companions were the creatures of the forest and those who would occasionally visit to bring news of the outside world and supplies. The solitude allowed you to spend many hours pondering the mysteries of creation.</p>
		</description>
		<setters>
			<set name="short">Constitution, Wisdom, Charisma, Healer Feat, Medicine and Religion Skills, Herbalism Kit</set>
		</setters>
		<rules>
			<grant type="Ability Score Improvement" id="ID_WOTC_INTERNAL_ABILITY_SCORE_IMPROVEMENT_COMBINATION_CON_WIS_CHA" />
			<grant type="Feat" id="ID_WOTC_PHB24_FEAT_HEALER" />
			<grant type="Proficiency" id="ID_WOTC_PHB24_PROFICIENCY_SKILL_MEDICINE" />
			<grant type="Proficiency" id="ID_WOTC_PHB24_PROFICIENCY_SKILL_RELIGION" />
			<grant type="Grants" id="ID_INTERNAL_GRANTS_BACKGROUND_ASI" />
			<grant type="Proficiency" id="ID_WOTC_PHB24_PROFICIENCY_TOOL_PROFICIENCY_HERBALISM_KIT" />
		</rules>
	</element>

	<!-- Todo: Add Equipment Pack for this Background. Example element is in the Acolyte Background. -->
```

2025-05-27 13:56 UTC, NickVendel commented on core/players-handbook-2024/backgrounds/background-merchant.xml
> +
```suggestion
		<description>Merchant background from the Player’s Handbook 2024.</description>
		<author url="https://dndstore.wizards.com/us/en/product/1001494/2024-player-s-handbook-digital-plus-physical-bundle">Wizards of the Coast</author>
		<update version="0.0.1">
			<file name="background-merchant.xml" url="https://raw.githubusercontent.com/AuroraLegacy/elements/master/core/players-handbook-2024/backgrounds/background-merchant.xml" />
		</update>
	</info>

	<element name="Merchant" type="Background" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_BACKGROUND_MERCHANT">
		<description>
			<ul class="unstyled" style="text-indent:-1em; margin-left:1em; margin-bottom:5px">
				<li><strong>Ability Scores:</strong> Constitution, Intelligence, Charisma</li>
				<li><strong>Feat:</strong> Lucky</li>
				<li><strong>Skill Proficiencies:</strong> Animal Handling and Persuasion</li>
				<li><strong>Tool Proficiency:</strong> Navigator's Tools</li>
				<li><strong>Equipment:</strong><i> Choose A or B:</i> (A) Navigator's Tools, 2 Pouches, Traveler's Clothes, 22 CP; or (B) 50 GP</li>
			</ul>
			<p>You were apprenticed to a trader, caravan master, or shopkeeper, learning the fundamentals of commerce. You traveled broadly, and you earned a living by buying and selling the raw materials artisans need to practice their craft or finished works from such crafters. You might have transported goods from one place to another (by ship, wagon, or caravan) or bought them from traveling traders and sold them in your own shop.</p>
		</description>
		<setters>
			<set name="short">Constitution, Intelligence, Charisma, Lucky Feat, Animal Handling and Persuasion Skills, Navigator's Tools</set>
		</setters>
		<rules>
			<grant type="Ability Score Improvement" id="ID_WOTC_INTERNAL_ABILITY_SCORE_IMPROVEMENT_COMBINATION_CON_INT_CHA" />
			<grant type="Feat" id="ID_WOTC_PHB24_FEAT_LUCKY" />
			<grant type="Proficiency" id="ID_WOTC_PHB24_PROFICIENCY_SKILL_ANIMALHANDLING" />
			<grant type="Proficiency" id="ID_WOTC_PHB24_PROFICIENCY_SKILL_PERSUASION" />
			<grant type="Grants" id="ID_INTERNAL_GRANTS_BACKGROUND_ASI" />
			<grant type="Proficiency" id="ID_WOTC_PHB24_PROFICIENCY_TOOL_PROFICIENCY_NAVIGATORS_TOOLS" />
		</rules>
	</element>

	<!-- Todo: Add Equipment Pack for this Background. Example element is in the Acolyte Background. -->
```

2025-05-27 13:56 UTC, NickVendel commented on core/players-handbook-2024/backgrounds/background-noble.xml
> +
```suggestion
		<description>Noble background from the Player’s Handbook 2024.</description>
		<author url="https://dndstore.wizards.com/us/en/product/1001494/2024-player-s-handbook-digital-plus-physical-bundle">Wizards of the Coast</author>
		<update version="0.0.1">
			<file name="background-noble.xml" url="https://raw.githubusercontent.com/AuroraLegacy/elements/master/core/players-handbook-2024/backgrounds/background-noble.xml" />
		</update>
	</info>

	<element name="Noble" type="Background" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_BACKGROUND_NOBLE">
		<description>
			<ul class="unstyled" style="text-indent:-1em; margin-left:1em; margin-bottom:5px">
				<li><strong>Ability Scores:</strong> Strength, Intelligence, Charisma</li>
				<li><strong>Feat:</strong> Skilled</li>
				<li><strong>Skill Proficiencies:</strong> History and Persuasion</li>
				<li><strong>Tool Proficiency:</strong><i> Choose one kind of Gaming Set</i></li>
				<li><strong>Equipment:</strong><i> Choose A or B:</i> (A) Gaming Set (same as above). Fine Clothes, Perfume, 29 CP; or (B) 50 GP</li>
			</ul>
			<p>You were raised in a castle, surrounded by wealth, power, and privilege. Your family of minor aristocrats ensured that you received a first-class education, some of which you appreciated and some of which you resented. Your time in the castle, especially the many hours you spent observing your family at court, also taught you a great deal about leadership.</p>
		</description>
		<setters>
			<set name="short">Strength, Intelligence, Charisma, Skilled Feat, History and Persuasion Skills, a Gaming Set</set>
		</setters>
		<rules>
			<grant type="Ability Score Improvement" id="ID_WOTC_INTERNAL_ABILITY_SCORE_IMPROVEMENT_COMBINATION_STR_INT_CHA" />
			<select type="Feat" name="Origin Feat (Noble)" supports="ID_WOTC_PHB24_FEAT_SKILLED|ID_WOTC_PHB24_FEAT_SKILLED_2" default="ID_WOTC_PHB24_FEAT_SKILLED" />
			<grant type="Proficiency" id="ID_WOTC_PHB24_PROFICIENCY_SKILL_HISTORY" /> 
			<grant type="Proficiency" id="ID_WOTC_PHB24_PROFICIENCY_SKILL_PERSUASION" />
			<grant type="Grants" id="ID_INTERNAL_GRANTS_BACKGROUND_ASI" />
			<select type="Proficiency" name="Gaming Set (Noble)" supports="Gaming Set" />
		</rules>
	</element>

	<!-- Todo: Add Equipment Pack for this Background. Example element is in the Acolyte Background. -->
```

2025-05-27 13:56 UTC, NickVendel commented on core/players-handbook-2024/backgrounds/background-sage.xml
> +
```suggestion
		<description>Sage background from the Player’s Handbook 2024.</description>
		<author url="https://dndstore.wizards.com/us/en/product/1001494/2024-player-s-handbook-digital-plus-physical-bundle">Wizards of the Coast</author>
		<update version="0.0.1">
			<file name="background-sage.xml" url="https://raw.githubusercontent.com/AuroraLegacy/elements/master/core/players-handbook-2024/backgrounds/background-sage.xml" />
		</update>
	</info>

	<element name="Sage" type="Background" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_BACKGROUND_SAGE">
		<description>
			<ul class="unstyled" style="text-indent:-1em; margin-left:1em; margin-bottom:5px">
				<li><strong>Ability Scores:</strong> Constitution, Intelligence, Wisdom</li>
				<li><strong>Feat:</strong> Magic Initiate (Wizard)</li>
				<li><strong>Skill Proficiencies:</strong> Arcana and History</li>
				<li><strong>Tool Proficiency:</strong> Calligrapher’s Supplies</li>
				<li><strong>Equipment:</strong><i> Choose A or B:</i> (A) Quarterstaff, Calligrapher's Supplies, Book (history), Parchment (8 sheets), Robe. 8 GP; or (B) 50 GP</li>
			</ul>
			<p>You spent your formative years traveling between manors and monasteries, performing various odd jobs and services in exchange for access to their libraries. You whiled away many a long evening studying books and scrolls, learning the lore of the multiverse—even the rudiments of magic—and your mind yearns for more.</p>
		</description>
		<setters>
			<set name="short">Constitution, Intelligence, Wisdom, Magic Initiate (Wizard) Feat, Arcana and History Skills, Calligrapher’s Supplies</set>
		</setters>
		<rules>
			<grant type="Ability Score Improvement" id="ID_WOTC_INTERNAL_ABILITY_SCORE_IMPROVEMENT_COMBINATION_CON_INT_WIS" />
			<grant type="Feat" id="ID_WOTC_PHB24_FEAT_MAGIC_INITIATE_WIZARD" />
			<grant type="Proficiency" id="ID_WOTC_PHB24_PROFICIENCY_SKILL_ARCANA" />
			<grant type="Proficiency" id="ID_WOTC_PHB24_PROFICIENCY_SKILL_HISTORY" /> 
			<grant type="Grants" id="ID_INTERNAL_GRANTS_BACKGROUND_ASI" />
			<grant type="Proficiency" id="ID_WOTC_PHB24_PROFICIENCY_TOOL_PROFICIENCY_CALLIGRAPHERS_SUPPLIES" />	
		</rules>
	</element>

	<!-- Todo: Add Equipment Pack for this Background. Example element is in the Acolyte Background. -->
```

2025-05-27 13:56 UTC, NickVendel commented on core/players-handbook-2024/backgrounds/background-sailor.xml
> +
```suggestion
		<description>Sailor background from the Player’s Handbook 2024.</description>
		<author url="https://dndstore.wizards.com/us/en/product/1001494/2024-player-s-handbook-digital-plus-physical-bundle">Wizards of the Coast</author>
		<update version="0.0.1">
			<file name="background-sailor.xml" url="https://raw.githubusercontent.com/AuroraLegacy/elements/master/core/players-handbook-2024/backgrounds/background-sailor.xml" />
		</update>
	</info>

	<element name="Sailor" type="Background" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_BACKGROUND_SAILOR">
		<description>
			<ul class="unstyled" style="text-indent:-1em; margin-left:1em; margin-bottom:5px">
				<li><strong>Ability Scores:</strong> Strength, Dexterity, Wisdom</li>
				<li><strong>Feat:</strong> Tavern Brawler</li>
				<li><strong>Skill Proficiencies:</strong> Acrobatics and Perception</li>
				<li><strong>Tool Proficiency:</strong> Navigator's Tools</li>
				<li><strong>Equipment:</strong><i> Choose A or B:</i> (A) Dagger, Navigator's Tools, Rope, Traveler’s Clothes, 20 GP; or (B) 50 GP</li>
			</ul>
			<p>You lived as a seafarer, wind at your back and decks swaying beneath your feet. You've perched on barstools in more ports of call than you can remember, faced mighty storms, and swapped stories with folk who live beneath the waves.</p>
		</description>
		<setters>
			<set name="short">Strength, Dexterity, Wisdom, Tavern Brawler Feat, Acrobatics and Perception Skills, Navigator's Tools</set>
		</setters>
		<rules>
			<grant type="Ability Score Improvement" id="ID_WOTC_INTERNAL_ABILITY_SCORE_IMPROVEMENT_COMBINATION_STR_DEX_WIS" />
			<grant type="Feat" id="ID_WOTC_PHB24_FEAT_TAVERN_BRAWLER" />
			<grant type="Proficiency" id="ID_WOTC_PHB24_PROFICIENCY_SKILL_ACROBATICS" />
			<grant type="Proficiency" id="ID_WOTC_PHB24_PROFICIENCY_SKILL_PERCEPTION" /> 
			<grant type="Grants" id="ID_INTERNAL_GRANTS_BACKGROUND_ASI" />
			<grant type="Proficiency" id="ID_WOTC_PHB24_PROFICIENCY_TOOL_PROFICIENCY_NAVIGATORS_TOOLS" />	
		</rules>
	</element>

	<!-- Todo: Add Equipment Pack for this Background. Example element is in the Acolyte Background. -->
```

2025-05-27 13:56 UTC, NickVendel commented on core/players-handbook-2024/backgrounds/background-scribe.xml
> +
```suggestion
		<description>Scribe background from the Player’s Handbook 2024.</description>
		<author url="https://dndstore.wizards.com/us/en/product/1001494/2024-player-s-handbook-digital-plus-physical-bundle">Wizards of the Coast</author>
		<update version="0.0.1">
			<file name="background-scribe.xml" url="https://raw.githubusercontent.com/AuroraLegacy/elements/master/core/players-handbook-2024/backgrounds/background-scribe.xml" />
		</update>
	</info>

	<element name="Scribe" type="Background" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_BACKGROUND_SCRIBE">
		<description>
			<ul class="unstyled" style="text-indent:-1em; margin-left:1em; margin-bottom:5px">
				<li><strong>Ability Scores:</strong> Dexterity, Intelligence, Wisdom</li>
				<li><strong>Feat:</strong> Skilled</li>
				<li><strong>Skill Proficiencies:</strong> Investigation and Perception</li>
				<li><strong>Tool Proficiency:</strong> Calligrapher’s Supplies</li>
				<li><strong>Equipment:</strong><i> Choose A or B:</i> (A) Calligrapher's Supplies, Fine Clothes, Lamp, Oil (3 flasks). Parchment (12 sheets), 23 GP; or (B) 50 GP</li>
			</ul>
			<p>You spent your formative years in a scriptorium, a monastery dedicated to the preservation of knowledge, or a government agency, where you learned to write with a clear hand and produce finely written texts. Perhaps you scribed government documents or copied tomes of literature. You might have some skill as a writer of poetry, narrative, or scholarly research. Above all, you have a careful attention to detail, helping you avoid introducing mistakes to the documents you copy and create.</p>
		</description>
		<setters>
			<set name="short">Dexterity, Intelligence, Wisdom, Skilled Feat, Investigation and Perception Skills, Calligrapher’s Supplies</set>
		</setters>
		<rules>
			<grant type="Ability Score Improvement" id="ID_WOTC_INTERNAL_ABILITY_SCORE_IMPROVEMENT_COMBINATION_DEX_INT_WIS" />
			<select type="Feat" name="Origin Feat (Scribe)" supports="ID_WOTC_PHB24_FEAT_SKILLED|ID_WOTC_PHB24_FEAT_SKILLED_2" default="ID_WOTC_PHB24_FEAT_SKILLED" />
			<grant type="Proficiency" id="ID_WOTC_PHB24_PROFICIENCY_SKILL_INVESTIGATION" />
			<grant type="Proficiency" id="ID_WOTC_PHB24_PROFICIENCY_SKILL_PERCEPTION" /> 
			<grant type="Grants" id="ID_INTERNAL_GRANTS_BACKGROUND_ASI" />
			<grant type="Proficiency" id="ID_WOTC_PHB24_PROFICIENCY_TOOL_PROFICIENCY_CALLIGRAPHERS_SUPPLIES" />	
		</rules>
	</element>

	<!-- Todo: Add Equipment Pack for this Background. Example element is in the Acolyte Background. -->
```

2025-05-27 13:56 UTC, NickVendel commented on core/players-handbook-2024/backgrounds/background-soldier.xml
> +
```suggestion
		<description>Soldier background from the Player’s Handbook 2024.</description>
		<author url="https://dndstore.wizards.com/us/en/product/1001494/2024-player-s-handbook-digital-plus-physical-bundle">Wizards of the Coast</author>
		<update version="0.0.1">
			<file name="background-soldier.xml" url="https://raw.githubusercontent.com/AuroraLegacy/elements/master/core/players-handbook-2024/backgrounds/background-soldier.xml" />
		</update>
	</info>

	<element name="Soldier" type="Background" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_BACKGROUND_SOLDIER">
		<description>
			<ul class="unstyled" style="text-indent:-1em; margin-left:1em; margin-bottom:5px">
				<li><strong>Ability Scores:</strong> Strength, Dexterity, Constitution</li>
				<li><strong>Feat:</strong> Savage Attacker</li>
				<li><strong>Skill Proficiencies:</strong> Athletics and Intimidation</li>
				<li><strong>Tool Proficiency:</strong><i> Choose one kind of Gaming Set</i></li>
				<li><strong>Equipment:</strong><i> Choose A or B:</i> (A) Spear, Shortbow, 20 Arrows, Gaming Set (same as above), Healer's Kit, Quiver, Traveler’s Clothes, 14 GP; or (B) 50 GP</li>
			</ul>
			<p>You began training for war as soon as you reached adulthood and carry precious few memories of life before you took up arms. Battle is in your blood. Sometimes you catch yourself reflexively performing the basic fighting exercises you learned first. Eventually, you put that training to use on the battlefield, protecting the realm by waging war</p>
		</description>
		<setters>
			<set name="short">Strength, Dexterity, Constitution, Savage Attacker Feat, Athletics and Intimidation Skills, a Gaming Set</set>
		</setters>
		<rules>
			<grant type="Ability Score Improvement" id="ID_WOTC_INTERNAL_ABILITY_SCORE_IMPROVEMENT_COMBINATION_STR_DEX_CON" />
			<grant type="Feat" id="ID_WOTC_PHB24_FEAT_SAVAGE_ATTACKER" />
			<grant type="Proficiency" id="ID_WOTC_PHB24_PROFICIENCY_SKILL_ATHLETICS" /> 
			<grant type="Proficiency" id="ID_WOTC_PHB24_PROFICIENCY_SKILL_INTIMIDATION" />
			<grant type="Grants" id="ID_INTERNAL_GRANTS_BACKGROUND_ASI" />
			<select type="Proficiency" name="Gaming Set (Soldier)" supports="Gaming Set" />
		</rules>
	</element>

	<!-- Todo: Add Equipment Pack for this Background. Example element is in the Acolyte Background. -->
```

2025-05-27 13:56 UTC, NickVendel commented on core/players-handbook-2024/backgrounds/background-wayfarer.xml
> +
```suggestion
		<description>Wayfarer background from the Player’s Handbook 2024.</description>
		<author url="https://dndstore.wizards.com/us/en/product/1001494/2024-player-s-handbook-digital-plus-physical-bundle">Wizards of the Coast</author>
		<update version="0.0.1">
			<file name="background-wayfarer.xml" url="https://raw.githubusercontent.com/AuroraLegacy/elements/master/core/players-handbook-2024/backgrounds/background-wayfarer.xml" />
		</update>
	</info>

	<element name="Wayfarer" type="Background" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_BACKGROUND_WAYFARER">
		<description>
			<ul class="unstyled" style="text-indent:-1em; margin-left:1em; margin-bottom:5px">
				<li><strong>Ability Scores:</strong> Dexterity, Wisdom, Charisma</li>
				<li><strong>Feat:</strong> Lucky</li>
				<li><strong>Skill Proficiencies:</strong> Insight and Stealth</li>
				<li><strong>Tool Proficiency:</strong> Thieves' Tools</li>
				<li><strong>Equipment:</strong><i> Choose A or B:</i> (A) 2 Daggers, Thieves' Tools, Gaming Set (any), Bedroll, 2 Pouches, Traveler's Clothes, 16 GP; or (B) 50 GP</li>
			</ul>
			<p>You grew up on the streets surrounded by similarly ill-fated castoffs, a few of them friends and a few of them rivals. You slept where you could and did odd jobs for food. At times, when the hunger became unbearable, you resorted to theft. Still, you never lost your pride and never abandoned hope. Fate is not yet finished with you.</p>
		</description>
		<setters>
			<set name="short">Dexterity, Wisdom, Charisma, Lucky Feat, Insight and Stealth Skills, Thieves' Tools</set>
		</setters>
		<rules>
			<grant type="Ability Score Improvement" id="ID_WOTC_INTERNAL_ABILITY_SCORE_IMPROVEMENT_COMBINATION_DEX_WIS_CHA" />
			<grant type="Feat" id="ID_WOTC_PHB24_FEAT_LUCKY" />
			<grant type="Proficiency" id="ID_WOTC_PHB24_PROFICIENCY_SKILL_INSIGHT" />
			<grant type="Proficiency" id="ID_WOTC_PHB24_PROFICIENCY_SKILL_STEALTH" /> 
			<grant type="Grants" id="ID_INTERNAL_GRANTS_BACKGROUND_ASI" />
			<grant type="Proficiency" id="ID_WOTC_PHB24_PROFICIENCY_TOOL_PROFICIENCY_THIEVES_TOOLS" />	
		</rules>
	</element>

	<!-- Todo: Add Equipment Pack for this Background. Example element is in the Acolyte Background. -->
```

2025-07-03 04:12 UTC, FreshRoyal commented
I feel like we need to make a grant for "Fighting Style Class Feature" and make that the requirement for the Fighting Style feats instead of each individual class' feature. It'll make it a lot more convenient for homebrew and would be useful in case WotC actually makes a new martial class.

2025-10-01 14:02 UTC, NickVendel requested changes
Review got quite long, so here's part 1 for now.

2025-10-01 14:02 UTC, NickVendel commented on core/internal.xml
> +	</element>
Removing "+2 Feat ASI" and replacing old formatting with new (including change in the IDs)
```suggestion
	<!-- Generic Ability Score Increases for Feats from PHB24 and onward -->
	<element name="Strength +1" type="Ability Score Improvement" source="Internal" id="ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_FEAT_STRENGTH">
		<compendium display="false" />
		<supports>Feat Ability Score Increase</supports>
		<description>
			<p>Your Strength increases by 1.</p>
		</description>
		<setters>
			<set name="allow duplicate">true</set>
		</setters>
		<rules>
			<stat name="strength" value="1" alt="Ability Score Increase" />
		</rules>
	</element>
	<element name="Dexterity +1" type="Ability Score Improvement" source="Internal" id="ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_FEAT_DEXTERITY">
		<compendium display="false" />
		<supports>Feat Ability Score Increase</supports>
		<description>
			<p>Your Dexterity increases by 1.</p>
		</description>
		<setters>
			<set name="allow duplicate">true</set>
		</setters>
		<rules>
			<stat name="dexterity" value="1" alt="Ability Score Increase" />
		</rules>
	</element>
	<element name="Constitution +1" type="Ability Score Improvement" source="Internal" id="ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_FEAT_CONSTITUTION">
		<compendium display="false" />
		<supports>Feat Ability Score Increase</supports>
		<description>
			<p>Your Constitution increases by 1.</p>
		</description>
		<setters>
			<set name="allow duplicate">true</set>
		</setters>
		<rules>
			<stat name="constitution" value="1" alt="Ability Score Increase" />
		</rules>
	</element>
	<element name="Intelligence +1" type="Ability Score Improvement" source="Internal" id="ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_FEAT_INTELLIGENCE">
		<compendium display="false" />
		<supports>Feat Ability Score Increase</supports>
		<description>
			<p>Your Intelligence increases by 1.</p>
		</description>
		<setters>
			<set name="allow duplicate">true</set>
		</setters>
		<rules>
			<stat name="intelligence" value="1" alt="Ability Score Increase" />
		</rules>
	</element>
	<element name="Wisdom +1" type="Ability Score Improvement" source="Internal" id="ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_FEAT_WISDOM">
		<compendium display="false" />
		<supports>Feat Ability Score Increase</supports>
		<description>
			<p>Your Wisdom increases by 1.</p>
		</description>
		<setters>
			<set name="allow duplicate">true</set>
		</setters>
		<rules>
			<stat name="wisdom" value="1" alt="Ability Score Increase" />
		</rules>
	</element>
	<element name="Charisma +1" type="Ability Score Improvement" source="Internal" id="ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_FEAT_CHARISMA">
		<compendium display="false" />
		<supports>Feat Ability Score Increase</supports>
		<description>
			<p>Your Charisma increases by 1.</p>
		</description>
		<setters>
			<set name="allow duplicate">true</set>
		</setters>
		<rules>
			<stat name="charisma" value="1" alt="Ability Score Increase" />
		</rules>
	</element>
```

2025-10-01 14:02 UTC, NickVendel commented on core/internal.xml
> +	</element>
same thing as above, but for Boon-specific ASIs.
```suggestion
	<!-- Generic Ability Score Increase for Boons from PHB24 and onward -->-->
	<element name="Strength +1" type="Ability Score Improvement" source="Internal" id="ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_BOON_STRENGTH">
		<compendium display="false" />
		<supports>Boon Ability Score Increase</supports>
		<requirements>[level:19]</requirements>
		<description>
			<p>Your Strength increases by 1, to a maximum of 30.</p>
		</description>
		<setters>
			<set name="allow duplicate">true</set>
		</setters>
		<rules>
			<stat name="strength" value="1" alt="Ability Score Increase" />
			<stat name="strength:max" value="10" bonus="ability"/>
		</rules>
	</element>
	<element name="Dexterity +1" type="Ability Score Improvement" source="Internal" id="ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_BOON_DEXTERITY">
		<compendium display="false" />
		<supports>Boon Ability Score Increase</supports>
		<requirements>[level:19]</requirements>
		<description>
			<p>Your Dexterity increases by 1, to a maximum of 30.</p>
		</description>
		<setters>
			<set name="allow duplicate">true</set>
		</setters>
		<rules>
			<stat name="dexterity" value="1" alt="Ability Score Increase" />
			<stat name="dexterity:max" value="10" bonus="ability"/>
		</rules>
	</element>
	<element name="Constitution +1" type="Ability Score Improvement" source="Internal" id="ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_BOON_CONSTITUTION">
		<compendium display="false" />
		<supports>Boon Ability Score Increase</supports>
		<description>
			<p>Your Constitution increases by 1, to a maximum of 30.</p>
		</description>
		<setters>
			<set name="allow duplicate">true</set>
		</setters>
		<rules>
			<stat name="constitution" value="1" alt="Ability Score Increase" />
			<stat name="constitution:max" value="10" bonus="ability"/>
		</rules>
	</element>
	<element name="Intelligence +1" type="Ability Score Improvement" source="Internal" id="ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_BOON_INTELLIGENCE">
		<compendium display="false" />
		<supports>Boon Ability Score Increase</supports>
		<description>
			<p>Your Intelligence increases by 1, to a maximum of 30.</p>
		</description>
		<setters>
			<set name="allow duplicate">true</set>
		</setters>
		<rules>
			<stat name="intelligence" value="1" alt="Ability Score Increase" />
			<stat name="intelligence:max" value="10" bonus="ability"/>
		</rules>
	</element>
	<element name="Wisdom +1" type="Ability Score Improvement" source="Internal" id="ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_BOON_WISDOM">
		<compendium display="false" />
		<supports>Boon Ability Score Increase</supports>
		<description>
			<p>Your Wisdom increases by 1, to a maximum of 30.</p>
		</description>
		<setters>
			<set name="allow duplicate">true</set>
		</setters>
		<rules>
			<stat name="wisdom" value="1" alt="Ability Score Increase" />
			<stat name="wisdom:max" value="10" bonus="ability"/>
		</rules>
	</element>
	<element name="Charisma +1" type="Ability Score Improvement" source="Internal" id="ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_BOON_CHARISMA">
		<compendium display="false" />
		<supports>Boon Ability Score Increase</supports>
		<description>
			<p>Your Charisma increases by 1.</p>
		</description>
		<setters>
			<set name="allow duplicate">true</set>
		</setters>
		<rules>
			<stat name="charisma" value="1" alt="Ability Score Increase" />
			<stat name="charisma:max" value="10" bonus="ability"/>
		</rules>
	</element>
```

2025-10-01 14:02 UTC, NickVendel commented on core/internal.xml
> +
all of the new Grants, including Background ASI from #272
```suggestion

	<element name="Background Ability Score Improvement" type="Grants" source="Internal" id="ID_INTERNAL_GRANTS_BACKGROUND_ASI" />

	<element name="Fighting Style Feature" type="Grants" source="Internal" id="ID_INTERNAL_GRANTS_FIGHTING_STYLE_FEATURE" />

	<element name="Spellcasting Feature Grants" type="Grants" source="Internal" id="ID_INTERNAL_GRANTS_SPELLCASTING_FEATURE" />

	<element name="Pact Magic Feature Grants" type="Grants" source="Internal" id="ID_INTERNAL_GRANTS_PACT_MAGIC_FEATURE" />

```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-origin.xml
> +	</element>
```suggestion
	<element name="Alert" type="Feat" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_FEAT_ALERT">
		<supports>Origin</supports>
		<description>
			<p class="flavor">Origin Feat</p>
			<p>You gain the following benefits.</p>
			<p class="indent"><b><i>Initiative Proficiency.</i></b> When you roll Initiative, you can add your Proficiency Bonus to the roll.</p>
			<p class="indent"><b><i>Initiative Swap.</i></b> Immediately after you roll Initiative, you can swap your Initiative with the Initiative of one willing ally in the same combat. You can't make this swap if you or the ally has the Incapacitated condition.</p>
		</description>
		<sheet>
			<description>Immediately after you roll Initiative, you can swap yours with that of one willing ally in the same combat. You can't make this swap if you or the ally has the Incapacitated condition.</description>
		</sheet>
		<rules>
			<stat name="initiative" value="proficiency" bonus="proficiency" />			
		</rules>
	</element>

```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-origin.xml
> +		<prerequisite>Origin Feat</prerequisite>
```suggestion
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-origin.xml
> +					<tr><td>column1</td><td>column2</td></tr>
```suggestion
			<h5>FAST CRAFTING</h5>
			<table>
				<thead>
					<tr><td>Artisan's Tools</td><td>Crafted Gear</td></tr>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-origin.xml
> +		<sheet>
```suggestion
		<setters>
			<set name="keywords">fast crafting</set>
		</setters>
		<sheet>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-origin.xml
> +			<select type="Proficiency" name="Tool Proficiency (Crafter)" supports="(ID_WOTC_PHB24_PROFICIENCY_TOOL_PROFICIENCY_CARPENTERS_TOOLS|ID_WOTC_PHB24_PROFICIENCY_TOOL_PROFICIENCY_LEATHERWORKERS_TOOLS|
```suggestion
			<select type="Proficiency" name="Tool Proficiency (Crafter)" supports="ID_WOTC_PHB24_PROFICIENCY_TOOL_PROFICIENCY_CARPENTERS_TOOLS|ID_WOTC_PHB24_PROFICIENCY_TOOL_PROFICIENCY_LEATHERWORKERS_TOOLS|ID_WOTC_PHB24_PROFICIENCY_TOOL_PROFICIENCY_MASONS_TOOLS|ID_WOTC_PHB24_PROFICIENCY_TOOL_PROFICIENCY_POTTERS_TOOLS|ID_WOTC_PHB24_PROFICIENCY_TOOL_PROFICIENCY_SMITHS_TOOLS|ID_WOTC_PHB24_PROFICIENCY_TOOL_PROFICIENCY_TINKERS_TOOLS|ID_WOTC_PHB24_PROFICIENCY_TOOL_PROFICIENCY_WEAVERS_TOOLS|ID_WOTC_PHB24_PROFICIENCY_TOOL_PROFICIENCY_WOODCARVERS_TOOLS" number="3"/>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-origin.xml
> +		<description>
```suggestion

	<element name="Healer" type="Feat" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_FEAT_HEALER">
		<supports>Origin</supports>
		<description>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-origin.xml
> +			Whenever you roll a 1 on a die to restore HP with a spell or Battle Medic's benefit, you can reroll it, and you must use the new result.</description>
```suggestion
			<description>You gain the following benefits: &#13;
			• You can spend one use of a Healer's Kit to tend to a creature within 5ft. of yourself. That creature can expend one of its Hit Point Dice, and you then roll that die. It regains a number of HP equal to the roll + {{proficiency}}. &#13;
			• Whenever you roll a 1 on a die to restore HP with a spell or the benefit above, you can reroll it, you must use the new result.</description>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-origin.xml
> +		<description>
```suggestion
	</element>

	<element name="Lucky" type="Feat" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_FEAT_LUCKY">
		<supports>Origin</supports>
		<description>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-origin.xml
> +			When a creature rolls a d20 for an attack roll against you, you can spend 1 Luck Point to impose Disadvantage on that roll.</description>
```suggestion
		<sheet usage="{{proficiency}}/Long Rest">
			<description>When you roll a d20 for a D20 Test, you can give yourself Advantage on the roll.&#13;
			Alternatively, when a creature rolls a d20 for an attack roll against you, you can impose Disadvantage on that roll.</description>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-origin.xml
> +		<description>
```suggestion
	</element>

	<element name="Magic Initiate" type="Feat" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_FEAT_MAGIC_INITIATE">
		<supports>Origin</supports>
		<description>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-origin.xml
> +		</rules>
```suggestion
		<rules>
			<select type="Feat Feature" name="Spell List (Magic Initiate)" supports="ID_WOTC_PHB24_FEAT_MAGIC_INITIATE_CLERIC|ID_WOTC_PHB24_FEAT_MAGIC_INITIATE_DRUID|ID_WOTC_PHB24_FEAT_MAGIC_INITIATE_WIZARD"/>
		</rules>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-origin.xml
> +		<prerequisite>Origin Feat</prerequisite>
```suggestion
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-origin.xml
> +		</rules>
```suggestion
		<rules>
			<select type="Feat Feature" name="Spell List (Magic Initiate)" supports="ID_WOTC_PHB24_FEAT_MAGIC_INITIATE_CLERIC|ID_WOTC_PHB24_FEAT_MAGIC_INITIATE_DRUID|ID_WOTC_PHB24_FEAT_MAGIC_INITIATE_WIZARD"/>
		</rules>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-origin.xml
> +		<prerequisite>Origin Feat</prerequisite>
```suggestion
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-origin.xml
> +		</rules>
```suggestion
		<rules>
			<select type="Feat Feature" name="Spell List (Magic Initiate)" supports="ID_WOTC_PHB24_FEAT_MAGIC_INITIATE_CLERIC|ID_WOTC_PHB24_FEAT_MAGIC_INITIATE_DRUID|ID_WOTC_PHB24_FEAT_MAGIC_INITIATE_WIZARD"/>
		</rules>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-origin.xml
> +		<supports>Magic Initiate 24</supports>
```suggestion
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-origin.xml
> +			<p>You learn two cantrips of your choice from the cleric's spell list.</p>
```suggestion
			<p>You learn two cantrips of your choice from the Cleric's spell list.</p>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-origin.xml
> +			<select type="Spell" name="1st-level Spell (Magic Initiate)" supports="1,Cleric" />
```suggestion
			<select type="Spell" name="Level 1 Spell (Magic Initiate)" supports="1,Cleric" />
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-origin.xml
> +			<description>You can cast the chosen 1st-level spell without a spell slot. You can also cast the spell using any spell slots you have. Your spellcasting ability for this feat's spells is Intellige
```suggestion
			<p>Your spellcasting ability for this feat's spells is Intelligence.</p>
		</description>
		<sheet alt="Magic Initiate (Cleric)">
			<description>You can cast the chosen level 1 spell without a spell slot. You can also cast the spell using any spell slots you have. Your spellcasting ability for this feat's spells is Intelligence. &#13;
			Whenever you gain a new level, you can replace one of the spells you chose for this feat with a different spell of the same level from the chosen spell list.</description>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-origin.xml
> +			<description>You can cast the chosen 1st-level spell without a spell slot. You can also cast the spell using any spell slots you have. Your spellcasting ability for this feat's spells is Wisdom.</
```suggestion
			<p>Your spellcasting ability for this feat's spells is Wisdom.</p>
		</description>
		<sheet alt="Magic Initiate (Cleric)">
			<description>You can cast the chosen level 1 spell without a spell slot. You can also cast the spell using any spell slots you have. Your spellcasting ability for this feat's spells is Wisdom. &#13;
			Whenever you gain a new level, you can replace one of the spells you chose for this feat with a different spell of the same level from the chosen spell list.</description>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-origin.xml
> +			<description>You can cast the chosen 1st-level spell without a spell slot. You can also cast the spell using any spell slots you have. Your spellcasting ability for this feat's spells is Charisma.
```suggestion
			<p>Your spellcasting ability for this feat's spells is Charisma.</p>
		</description>
		<sheet alt="Magic Initiate (Cleric)">
			<description>You can cast the chosen level 1 spell without a spell slot. You can also cast the spell using any spell slots you have. Your spellcasting ability for this feat's spells is Charisma. &#13;
			Whenever you gain a new level, you can replace one of the spells you chose for this feat with a different spell of the same level from the chosen spell list.</description>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-origin.xml
> +		<supports>Magic Initiate 24</supports>
```suggestion
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-origin.xml
> +			<p>You learn two cantrips of your choice from the druid's spell list.</p>
```suggestion
			<p>You learn two cantrips of your choice from the Druid's spell list.</p>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-origin.xml
> +			<select type="Spell" name="1st-level Spell (Magic Initiate)" supports="1,Druid" />
```suggestion
			<select type="Spell" name="Level 1 Spell (Magic Initiate)" supports="1,Druid" />
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-origin.xml
> +			<description>You can cast the chosen 1st-level spell without a spell slot. You can also cast the spell using any spell slots you have. Your spellcasting ability for this feat's spells is Intellige
```suggestion
			<p>Your spellcasting ability for this feat's spells is Intelligence.</p>
		</description>
		<sheet alt="Magic Initiate (Druid)">
			<description>You can cast the chosen level 1 spell without a spell slot. You can also cast the spell using any spell slots you have. Your spellcasting ability for this feat's spells is Intelligence. &#13;
			Whenever you gain a new level, you can replace one of the spells you chose for this feat with a different spell of the same level from the chosen spell list.</description>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-origin.xml
> +			<description>You can cast the chosen 1st-level spell without a spell slot. You can also cast the spell using any spell slots you have. Your spellcasting ability for this feat's spells is Wisdom.</
```suggestion
			<p>Your spellcasting ability for this feat's spells is Wisdom.</p>
		</description>
		<sheet alt="Magic Initiate (Druid)">
			<description>You can cast the chosen level 1 spell without a spell slot. You can also cast the spell using any spell slots you have. Your spellcasting ability for this feat's spells is Wisdom. &#13;
			Whenever you gain a new level, you can replace one of the spells you chose for this feat with a different spell of the same level from the chosen spell list.</description>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-origin.xml
> +			<description>You can cast the chosen 1st-level spell without a spell slot. You can also cast the spell using any spell slots you have. Your spellcasting ability for this feat's spells is Charisma.
```suggestion
			<p>Your spellcasting ability for this feat's spells is Charisma.</p>
		</description>
		<sheet alt="Magic Initiate (Druid)">
			<description>You can cast the chosen level 1 spell without a spell slot. You can also cast the spell using any spell slots you have. Your spellcasting ability for this feat's spells is Charisma. &#13;
			Whenever you gain a new level, you can replace one of the spells you chose for this feat with a different spell of the same level from the chosen spell list.</description>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-origin.xml
> +		<supports>Magic Initiate 24</supports>
```suggestion
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-origin.xml
> +			<p>You learn two cantrips of your choice from the wizard's spell list.</p>
```suggestion
			<p>You learn two cantrips of your choice from the Wizard's spell list.</p>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-origin.xml
> +			<select type="Spell" name="1st-level Spell (Magic Initiate)" supports="1,Wizard" />
```suggestion
			<select type="Spell" name="Level 1 Spell (Magic Initiate)" supports="1,Wizard" />
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-origin.xml
> +			<description>You can cast the chosen 1st-level spell without a spell slot. You can also cast the spell using any spell slots you have. Your spellcasting ability for this feat's spells is Intellige
```suggestion
			<p>Your spellcasting ability for this feat's spells is Intelligence.</p>
		</description>
		<sheet alt="Magic Initiate (Wizard)">
			<description>You can cast the chosen level 1 spell without a spell slot. You can also cast the spell using any spell slots you have. Your spellcasting ability for this feat's spells is Intelligence. &#13;
			Whenever you gain a new level, you can replace one of the spells you chose for this feat with a different spell of the same level from the chosen spell list.</description>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-origin.xml
> +			<description>You can cast the chosen 1st-level spell without a spell slot. You can also cast the spell using any spell slots you have. Your spellcasting ability for this feat's spells is Wisdom.</
```suggestion
			<p>Your spellcasting ability for this feat's spells is Wisdom.</p>
		</description>
		<sheet alt="Magic Initiate (Wizard)">
			<description>You can cast the chosen level 1 spell without a spell slot. You can also cast the spell using any spell slots you have. Your spellcasting ability for this feat's spells is Wisdom. &#13;
			Whenever you gain a new level, you can replace one of the spells you chose for this feat with a different spell of the same level from the chosen spell list.</description>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-origin.xml
> +			<description>You can cast the chosen 1st-level spell without a spell slot. You can also cast the spell using any spell slots you have. Your spellcasting ability for this feat's spells is Charisma.
```suggestion
			<p>Your spellcasting ability for this feat's spells is Charisma.</p>
		</description>
		<sheet alt="Magic Initiate (Wizard)">
			<description>You can cast the chosen level 1 spell without a spell slot. You can also cast the spell using any spell slots you have. Your spellcasting ability for this feat's spells is Charisma. &#13;
			Whenever you gain a new level, you can replace one of the spells you chose for this feat with a different spell of the same level from the chosen spell list.</description>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-origin.xml
> +		<description>
```suggestion

	<element name="Musician" type="Feat" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_FEAT_MUSICIAN">
		<supports>Origin</supports>
		<description>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-origin.xml
> +			<p class="indent"><b><i>Instrument Training.</i></b> You gain proficiency with three Musical Instruments of your choice</p>
```suggestion
			<p class="indent"><b><i>Instrument Training.</i></b> You gain proficiency with three Musical Instruments of your choice.</p>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-origin.xml
> +			<select type="Proficiency" name="Tool Proficiency (Musician)" supports="Musical Instrument" number="3" />
```suggestion
		<sheet>
			<description>As you finish a Short or Long Rest, you can play a song on a Musical Instrument you are proficient with and give Heroic Inspiration to up to {{proficiency}} allies who hear the song.</description>
		</sheet>
		<rules>
			<select type="Proficiency" name="Musical Instrument (Musician)" supports="Musical Instrument" number="3" />
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-origin.xml
> +		<description>
```suggestion
	</element>

	<element name="Savage Attacker" type="Feat" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_FEAT_SAVAGE_ATTACKER">
		<supports>Origin</supports>
		<description>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-origin.xml
> +		<description>
```suggestion
	</element>

	<element name="Skilled" type="Feat" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_FEAT_SKILLED">
		<supports>Origin</supports>
		<description>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-origin.xml
> +			<select type="Proficiency" name="Skill Proficiency (Skilled)" supports="(Skill||Tool),!Expertise,!Musical Instrument" number="3" />
```suggestion
			<select type="Proficiency" name="Skill or Tool Proficiency (Skilled)" supports="Skill||Tool" number="3" />
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-origin.xml
> +		<description />
```suggestion
		<description>
			<p class="flavor">Origin Feat</p>
			<p>You gain proficiency in any combination of three skills or tools of your choice.</p>
			<p class="indent"><b><i>Repeatable.</i></b> You can take this feat more than once.</p>
		</description>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-origin.xml
> +			<select type="Proficiency" name="Skill Proficiency (Skilled)" supports="(Skill||Tool),!Expertise,!Musical Instrument" number="3" />
```suggestion
			<select type="Proficiency" name="Skill or Tool Proficiency (Skilled)" supports="Skill||Tool" number="3" />
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-origin.xml
> +		<description />
```suggestion
		<description>
			<p class="flavor">Origin Feat</p>
			<p>You gain proficiency in any combination of three skills or tools of your choice.</p>
			<p class="indent"><b><i>Repeatable.</i></b> You can take this feat more than once.</p>
		</description>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-origin.xml
> +			<select type="Proficiency" name="Skill Proficiency (Skilled)" supports="(Skill||Tool),!Expertise,!Musical Instrument" number="3" />
```suggestion
			<select type="Proficiency" name="Skill or Tool Proficiency (Skilled)" supports="Skill||Tool" number="3" />
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-origin.xml
> +		<description />
```suggestion
		<description>
			<p class="flavor">Origin Feat</p>
			<p>You gain proficiency in any combination of three skills or tools of your choice.</p>
			<p class="indent"><b><i>Repeatable.</i></b> You can take this feat more than once.</p>
		</description>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-origin.xml
> +			<select type="Proficiency" name="Skill Proficiency (Skilled)" supports="(Skill||Tool),!Expertise,!Musical Instrument" number="3" />
```suggestion
			<select type="Proficiency" name="Skill or Tool Proficiency (Skilled)" supports="Skill||Tool" number="3" />
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-origin.xml
> +		<description />
```suggestion
		<description>
			<p class="flavor">Origin Feat</p>
			<p>You gain proficiency in any combination of three skills or tools of your choice.</p>
			<p class="indent"><b><i>Repeatable.</i></b> You can take this feat more than once.</p>
		</description>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-origin.xml
> +			<select type="Proficiency" name="Skill Proficiency (Skilled)" supports="(Skill||Tool),!Expertise,!Musical Instrument" number="3" />
```suggestion
			<select type="Proficiency" name="Skill or Tool Proficiency (Skilled)" supports="Skill||Tool" number="3" />
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-origin.xml
> +		<description />
```suggestion
		<description>
			<p class="flavor">Origin Feat</p>
			<p>You gain proficiency in any combination of three skills or tools of your choice.</p>
			<p class="indent"><b><i>Repeatable.</i></b> You can take this feat more than once.</p>
		</description>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-origin.xml
> +			<select type="Proficiency" name="Skill Proficiency (Skilled)" supports="(Skill||Tool),!Expertise,!Musical Instrument" number="3" />
```suggestion
			<select type="Proficiency" name="Skill or Tool Proficiency (Skilled)" supports="Skill||Tool" number="3" />
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-origin.xml
> +		<description />
```suggestion
		<description>
			<p class="flavor">Origin Feat</p>
			<p>You gain proficiency in any combination of three skills or tools of your choice.</p>
			<p class="indent"><b><i>Repeatable.</i></b> You can take this feat more than once.</p>
		</description>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-origin.xml
> +			<select type="Proficiency" name="Skill Proficiency (Skilled)" supports="(Skill||Tool),!Expertise,!Musical Instrument" number="3" />
```suggestion
			<select type="Proficiency" name="Skill or Tool Proficiency (Skilled)" supports="Skill||Tool" number="3" />
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-origin.xml
> +		<description />
```suggestion
		<description>
			<p class="flavor">Origin Feat</p>
			<p>You gain proficiency in any combination of three skills or tools of your choice.</p>
			<p class="indent"><b><i>Repeatable.</i></b> You can take this feat more than once.</p>
		</description>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-origin.xml
> +			<select type="Proficiency" name="Skill Proficiency (Skilled)" supports="(Skill||Tool),!Expertise,!Musical Instrument" number="3" />
```suggestion
			<select type="Proficiency" name="Skill or Tool Proficiency (Skilled)" supports="Skill||Tool" number="3" />
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-origin.xml
> +		<description />
```suggestion
		<description>
			<p class="flavor">Origin Feat</p>
			<p>You gain proficiency in any combination of three skills or tools of your choice.</p>
			<p class="indent"><b><i>Repeatable.</i></b> You can take this feat more than once.</p>
		</description>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-origin.xml
> +			<select type="Proficiency" name="Skill Proficiency (Skilled)" supports="(Skill||Tool),!Expertise,!Musical Instrument" number="3" />
```suggestion
			<select type="Proficiency" name="Skill or Tool Proficiency (Skilled)" supports="Skill||Tool" number="3" />
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-origin.xml
> +		<description>
```suggestion
	</element>

	<element name="Tavern Brawler" type="Feat" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_FEAT_TAVERN_BRAWLER">
		<supports>Origin</supports>
		<description>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-origin.xml
> +			<description>When you hit with your Unarmed Strike and deal damage, you can deal 1d4+{{strength:modifier}} Bludgeoning damage and, once per turn you can also push it 5ft away from you. Whenever yo
```suggestion
			<description>You gain following benefits: &#13;
			• When you hit with your Unarmed Strike and deal damage, you can deal 1d4+{{strength:modifier}} Bludgeoning damage, and once per turn you can also push the target of that attack 5ft. away from you. &#13;
			• Whenever you roll a 1 for damage for your Unarmed Strike, you can reroll the die, and you must use the new roll. &#13;
			• You have proficiency with improvised weapons.</description>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-origin.xml
> +		<description>
```suggestion
	</element>

	<element name="Tough" type="Feat" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_FEAT_TOUGH">
		<supports>Origin</supports>
		<description>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-origin.xml
> +</elements>
```suggestion
		<sheet display="false" />
		<rules>
			<stat name="tough:hp" value="level" />
			<stat name="tough:hp" value="level" />
			<stat name="hp" value="tough:hp" bonus="tough" />
		</rules>
	</element>

</elements>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<select type="Ability Score Improvement" name="Ability Score Improvement (4th LV)" supports="ID_WOTC_PHB24_FEAT_FEATURE_ASI_OPTION2_1|ID_WOTC_PHB24_FEAT_FEATURE_ASI_OPTION1_1" />
```suggestion
		<prerequisite>Level 4+</prerequisite>
		<description>
			<p class="flavor">General Feat (Prerequisite: Level 4+)</p>
			<p>Increase one ability score of your choice by 2, or increase two ability scores of your choice by 1. This feat can't increase an ability score above 20.</p>
			<p class="indent"><b><i>Repeatable.</i></b> You can take this feat more than once.</p>
		</description>
		<sheet display="false" />
		<rules>
			<select type="Ability Score Improvement" name="Ability Score Improvement Feat" supports="Feat Ability Score Increase" number="2" />
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<select type="Ability Score Improvement" name="Ability Score Improvement (8th LV)" supports="ID_WOTC_PHB24_FEAT_FEATURE_ASI_OPTION2_2|ID_WOTC_PHB24_FEAT_FEATURE_ASI_OPTION1_2" />
```suggestion
		<prerequisite>Level 4+</prerequisite>
		<description>
			<p class="flavor">General Feat (Prerequisite: Level 4+)</p>
			<p>Increase one ability score of your choice by 2, or increase two ability scores of your choice by 1. This feat can't increase an ability score above 20.</p>
			<p class="indent"><b><i>Repeatable.</i></b> You can take this feat more than once.</p>
		</description>
		<sheet display="false" />
		<rules>
			<select type="Ability Score Improvement" name="Ability Score Improvement Feat" supports="Feat Ability Score Increase" number="2" />
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<select type="Ability Score Improvement" name="Ability Score Improvement (12th LV)" supports="ID_WOTC_PHB24_FEAT_FEATURE_ASI_OPTION2_3|ID_WOTC_PHB24_FEAT_FEATURE_ASI_OPTION1_3" />
```suggestion
		<prerequisite>Level 4+</prerequisite>
		<description>
			<p class="flavor">General Feat (Prerequisite: Level 4+)</p>
			<p>Increase one ability score of your choice by 2, or increase two ability scores of your choice by 1. This feat can't increase an ability score above 20.</p>
			<p class="indent"><b><i>Repeatable.</i></b> You can take this feat more than once.</p>
		</description>
		<sheet display="false" />
		<rules>
			<select type="Ability Score Improvement" name="Ability Score Improvement Feat" supports="Feat Ability Score Increase" number="2" />
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<select type="Ability Score Improvement" name="Ability Score Improvement (16th LV)" supports="ID_WOTC_PHB24_FEAT_FEATURE_ASI_OPTION2_4|ID_WOTC_PHB24_FEAT_FEATURE_ASI_OPTION1_4" />
```suggestion
		<prerequisite>Level 4+</prerequisite>
		<description>
			<p class="flavor">General Feat (Prerequisite: Level 4+)</p>
			<p>Increase one ability score of your choice by 2, or increase two ability scores of your choice by 1. This feat can't increase an ability score above 20.</p>
			<p class="indent"><b><i>Repeatable.</i></b> You can take this feat more than once.</p>
		</description>
		<sheet display="false" />
		<rules>
			<select type="Ability Score Improvement" name="Ability Score Improvement Feat" supports="Feat Ability Score Increase" number="2" />
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +	</element>
```suggestion
	<element name="Ability Score Improvement" type="Feat" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_FEAT_ABILITY_SCORE_IMPROVEMENT_5">
		<compendium display="false" />
		<supports>General</supports>
		<requirements>ID_WOTC_PHB24_FEAT_ABILITY_SCORE_IMPROVEMENT_4</requirements>
		<prerequisite>Level 4+</prerequisite>
		<description>
			<p class="flavor">General Feat (Prerequisite: Level 4+)</p>
			<p>Increase one ability score of your choice by 2, or increase two ability scores of your choice by 1. This feat can't increase an ability score above 20.</p>
			<p class="indent"><b><i>Repeatable.</i></b> You can take this feat more than once.</p>
		</description>
		<sheet display="false" />
		<rules>
			<select type="Ability Score Improvement" name="Ability Score Improvement Feat" supports="Feat Ability Score Increase" number="2" />
		</rules>
	</element>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +	</element>
```suggestion
	<element name="Ability Score Improvement" type="Feat" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_FEAT_ABILITY_SCORE_IMPROVEMENT_6">
		<compendium display="false" />
		<supports>General</supports>
		<requirements>ID_WOTC_PHB24_FEAT_ABILITY_SCORE_IMPROVEMENT_5</requirements>
		<prerequisite>Level 4+</prerequisite>
		<description>
			<p class="flavor">General Feat (Prerequisite: Level 4+)</p>
			<p>Increase one ability score of your choice by 2, or increase two ability scores of your choice by 1. This feat can't increase an ability score above 20.</p>
			<p class="indent"><b><i>Repeatable.</i></b> You can take this feat more than once.</p>
		</description>
		<sheet display="false" />
		<rules>
			<select type="Ability Score Improvement" name="Ability Score Improvement Feat" supports="Feat Ability Score Increase" number="2" />
		</rules>
	</element>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +	</element>
```suggestion
	<element name="Ability Score Improvement" type="Feat" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_FEAT_ABILITY_SCORE_IMPROVEMENT_7">
		<compendium display="false" />
		<supports>General</supports>
		<requirements>ID_WOTC_PHB24_FEAT_ABILITY_SCORE_IMPROVEMENT_6</requirements>
		<prerequisite>Level 4+</prerequisite>
		<description>
			<p class="flavor">General Feat (Prerequisite: Level 4+)</p>
			<p>Increase one ability score of your choice by 2, or increase two ability scores of your choice by 1. This feat can't increase an ability score above 20.</p>
			<p class="indent"><b><i>Repeatable.</i></b> You can take this feat more than once.</p>
		</description>
		<sheet display="false" />
		<rules>
			<select type="Ability Score Improvement" name="Ability Score Improvement Feat" supports="Feat Ability Score Increase" number="2" />
		</rules>
	</element>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +	</element>
```suggestion
	<element name="Ability Score Improvement" type="Feat" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_FEAT_ABILITY_SCORE_IMPROVEMENT_8">
		<compendium display="false" />
		<supports>General</supports>
		<requirements>ID_WOTC_PHB24_FEAT_ABILITY_SCORE_IMPROVEMENT_7</requirements>
		<prerequisite>Level 4+</prerequisite>
		<description>
			<p class="flavor">General Feat (Prerequisite: Level 4+)</p>
			<p>Increase one ability score of your choice by 2, or increase two ability scores of your choice by 1. This feat can't increase an ability score above 20.</p>
			<p class="indent"><b><i>Repeatable.</i></b> You can take this feat more than once.</p>
		</description>
		<sheet display="false" />
		<rules>
			<select type="Ability Score Improvement" name="Ability Score Improvement Feat" supports="Feat Ability Score Increase" number="2" />
		</rules>
	</element>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +	</element>
removal of unnecessary elements.
```suggestion
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<p><em>General Feat (Prerequisite: Level 4+, Charisma 13+)</em></p>
```suggestion
		<prerequisite>Level 4+, Charisma 13+</prerequisite>
		<description>
			<p class="flavor">General Feat (Prerequisite: Level 4+, Charisma 13+)</p>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<stat name="actor:mimicry:dc" value="charisma:modifier" />
```suggestion
			<description>While you're disguised as a real or fictional person, you have Advantage on Charisma (Deception or Performance) checks to convince others that you are that person. &#13;
			Additionally, you can mimic the sounds of other creatures, including speech. A creature that hears the mimicry must succeed on a Wisdom (Insight) check against DC{{actor:dc}} to determine the effect is faked.</description>
		</sheet>
		<rules>
			<stat name="charisma" value="1" alt="Actor" />
			<stat name="actor:dc" value="8" bonus="base" />
			<stat name="actor:dc" value="proficiency" bonus="proficiency" />
			<stat name="actor:dc" value="charisma:modifier" bonus="ability" />
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<p><em>General Feat (Prerequisite: Level 4+, Strength or Dexterity 13+)</em></p>
```suggestion
		<prerequisite>Level 4+, Strength or Dexterity 13+</prerequisite>
		<description>
			<p class="flavor">General Feat (Prerequisite: Level 4+, Strength or Dexterity 13+)</p>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +	</element>
```suggestion
		<sheet>
			<description>When you have the Prone condition, you can right yourself with only 5 feet of movement. You can make a running Long or High Jump after moving only 5 feet.</description>
		</sheet>
		<rules>
			<select type="Ability Score Improvement" name="Ability Score Increase (Athlete)" supports="ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_FEAT_STRENGTH|ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_FEAT_DEXTERITY" />
			<stat name="speed:climb" value="speed" bonus="base" />
		</rules>
	</element>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +	</element>
```suggestion
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<p><em>General Feat (Prerequisite: Level 4+, Strength or Dexterity 13+)</em></p>
```suggestion
		<prerequisite>Level 4+, Strength or Dexterity 13+</prerequisite>
		<description>
			<p class="flavor">General Feat (Prerequisite: Level 4+, Strength or Dexterity 13+)</p>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<stat name="speed:climb" value="speed" bonus="base" />
```suggestion
		<sheet usage="1/Turn">
			<description>If you move at least 10ft. in a straight line toward a target immediately before hitting it with a melee attack roll as part of the Attack action, choose one of the following effects: gain a 1d8 bonus to the attack's damage roll, or push the target up to 10ft. away if it is no more than one size larger than you. &#13;
			Additionally, when you take the Dash action, your Speed increases by 10 feet for that action.</description>
		</sheet>
		<rules>
			<select type="Ability Score Improvement" name="Ability Score Increase (Charger)" supports="ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_FEAT_STRENGTH|ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_FEAT_DEXTERITY" />
			<stat name="speed:climb" value="speed" bonus="base" />
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +	</element>
```suggestion
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<p><em>General Feat (Prerequisite: Level 4+)</em></p>
```suggestion
		<prerequisite>Level 4+</prerequisite>
		<description>
			<p class="flavor">General Feat (Prerequisite: Level 4+)</p>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<stat name="chef:meal" value="proficiency" />
```suggestion
		<sheet>
			<description>As part of a Short Rest, if you have ingredients and Cook's Utensils on hand, you can prepare enough of food for {{chef:amount}} creatures. Creature who eats the food and spends one or more Hit Dice to regain HP regains an extra 1d8 HP. &#13;
			Additionally, with 1 hour of work or when you finish a Long Rest, you can cook {{proficiency}} treats if you have ingredients and Cook's Utensils on hand. These special treats last 8 hours. A creature can use a Bonus Action to eat one of those treats to gain {{proficiency}} Temporary HP.</description>
		</sheet>
		<rules>
			<select type="Ability Score Improvement" name="Ability Score Increase (Chef)" supports="ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_FEAT_CONSTITUTION|ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_FEAT_WISDOM" />
			<grant type="Proficiency" id="ID_WOTC_PHB24_PROFICIENCY_TOOL_PROFICIENCY_COOKS_UTENSILS" />
			<stat name="chef:amount" value="4" />
			<stat name="chef:amount" value="proficiency" />
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +	</element>
```suggestion
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<p><em>General Feat (Prerequisite: Level 4+, Dexterity 13+)</em></p>
```suggestion
		<prerequisite>Level 4+, Dexterity 13+</prerequisite>
		<description>
			<p class="flavor">General Feat (Prerequisite: Level 4+, Dexterity 13+)</p>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<p class="indent"><b><i>Ignore Loading.</i></b> You ignore the Loading property of the Hand Crossbow. Heavy Crossbow, and Light Crossbow (all called crossbows elsewhere in this feat). If you're ho
```suggestion
			<p class="indent"><b><i>Ignore Loading.</i></b> You ignore the Loading property of the Hand Crossbow, Heavy Crossbow, and Light Crossbow (all called crossbows elsewhere in this feat). If you're holding one of them, you can load a piece of ammunition into it even if you lack a free hand.</p>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<description> You ignore the Loading property of crossbows. If you're holding one of them, you can load a piece of ammunition into it even if you lack a free hand. Being within 5 feet of an enemy
```suggestion
			<description>You ignore the Loading property of crossbows. If you're holding one of them, you can load a piece of ammunition into it even if you lack a free hand. Being within 5ft. of an enemy doesn't impose Disadvantage on your attack rolls with crossbows. When you make the extra attack with a crossbow that has the Light property, you can add your ability modifier to the damage of the extra attack if you aren't already adding that modifier to the damage.</description>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<p><em>General Feat (Prerequisite: Level 4+)</em></p>
```suggestion
		<prerequisite>Level 4+</prerequisite>
		<description>
			<p class="flavor">General Feat (Prerequisite: Level 4+)</p>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +	</element>
```suggestion
		<sheet usage="1/Turn">
			<description>When you hit a creature with an attack that deals Bludgeoning damage, you can move it 5ft. to an unoccupied space if the target is no more than one size larger than you. &#13;
			Additionally, whenever you score a Critical Hit that deals Bludgeoning damage to a creature, attack rolls against that creature have Advantage until the start of your next turn.</description>
		</sheet>
		<rules>
			<select type="Ability Score Improvement" name="Ability Score Increase (Crusher)" supports="ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_FEAT_STRENGTH|ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_FEAT_CONSTITUTION" />
		</rules>
	</element>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +	</element>
```suggestion
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<p><em>General Feat (Prerequisite: Level 4+, Dexterity 13+)</em></p>
```suggestion
		<prerequisite>Level 4+, Dexterity 13+</prerequisite>
		<description>
			<p class="flavor">General Feat (Prerequisite: Level 4+, Dexterity 13+)</p>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<description>If you're holding a Finesse weapon and another creature hits you with a melee attack, you can add +{{proficiency}} to your AC, potentially causing the attack to miss you. You gain thi
```suggestion
			<description>If you're holding a Finesse weapon and another creature hits you with a melee attack, you can add {{proficiency}} to your AC, potentially causing the attack to miss you. This bonus to AC lasts until the start of your next turn.</description>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<p><em>General Feat (Prerequisite: Level 4+, Strength or Dexterity 13+)</em></p>
```suggestion
		<prerequisite>Level 4+, Strength or Dexterity 13+</prerequisite>
		<description>
			<p class="flavor">General Feat (Prerequisite: Level 4+, Strength or Dexterity 13+)</p>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +	</element>
```suggestion
		<sheet>
			<description>When you attack with a weapon that has the Light property, you can make one extra attack as a Bonus Action with a different Melee weapon that lacks the Two-Handed property. You don't add your ability modifier to the extra attack's damage unless that modifier is negative. &#13;
			Whenever you draw or stow your weapons that lack the Two-handed property, you can do so with two weapons instead of only one.</description>
		</sheet>
		<rules>
			<select type="Ability Score Improvement" name="Ability Score Increase (Dual Wielder)" supports="ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_FEAT_STRENGTH|ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_FEAT_DEXTERITY" />
		</rules>
	</element>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +	</element>
```suggestion
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<p><em>General Feat (Prerequisite: Level 4+)</em></p>
```suggestion
		<prerequisite>Level 4+</prerequisite>
		<description>
			<p class="flavor">General Feat (Prerequisite: Level 4+)</p>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<description>You have Advantage on Death Saving Throws. As a Bonus Action, you can expend one of your Hit Point Dice, roll the die, and regain a number of HP equal to the roll.</description>
```suggestion
		<sheet action="Bonus Action">
			<description>You can expend one of your Hit Point Dice, roll the die, and regain a number of HP equal to the roll. &#13;
			Additionally, you have Advantage on Death Saving Throws.</description>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<p><em>General Feat (Prerequisite: Level 4+, Spellcasting or Pact Magic Feature)</em></p>
```suggestion
		<requirements>[level:4],(ID_INTERNAL_GRANTS_SPELLCASTING_FEATURE||ID_INTERNAL_GRANTS_PACT_MAGIC_FEATURE)</requirements>
		<supports>General</supports>
		<prerequisite>Level 4+, Spellcasting or Pact Magic Feature</prerequisite>
		<description>
			<p class="flavor">General Feat (Prerequisite: Level 4+, Spellcasting or Pact Magic Feature)</p>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<select type="Feat Feature" name="Energy Mastery" supports="Energy Mastery" />
```suggestion
			<select type="Ability Score Improvement" name="Ability Score Increase (Elemental Adept)" supports="ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_FEAT_INTELLIGENCE|ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_FEAT_WISDOM|ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_FEAT_CHARISMA" />
			<select type="Feat Feature" name="Damage Type (Elemental Adept)" supports="Elemental Adept 24" />
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +	</element>
```suggestion
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<description>Spells you cast ignore Acid Resistance. Treat any 1 on a damage die as a 2 with Acid spells.</description>
```suggestion
		<supports>Elemental Adept 24</supports>
		<description>
			<p>Spells you cast ignore Acid Resistance. In addition, when you roll damage for a spell you cast that deals Acid damage, you can treat any 1 on a damage die as a 2.</p>
		</description>
		<sheet alt="Elemental Adept: Acid">
			<description>Spells you cast ignore Acid Resistance. Treat any 1 on a damage die as a 2 when using spells that deal Acid damage.</description>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<description>Spells you cast ignore Cold Resistance. Treat any 1 on a damage die as a 2 with Cold spells.</description>
```suggestion
		<supports>Elemental Adept 24</supports>
		<description>
			<p>Spells you cast ignore Cold Resistance. In addition, when you roll damage for a spell you cast that deals Cold damage, you can treat any 1 on a damage die as a 2.</p>
		</description>
		<sheet alt="Elemental Adept: Cold">
			<description>Spells you cast ignore Cold Resistance. Treat any 1 on a damage die as a 2 when using spells that deal Cold damage.</description>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<description>Spells you cast ignore Fire Resistance. Treat any 1 on a damage die as a 2 with Fire spells.</description>
```suggestion
		<supports>Elemental Adept 24</supports>
		<description>
			<p>Spells you cast ignore Fire Resistance. In addition, when you roll damage for a spell you cast that deals Fire damage, you can treat any 1 on a damage die as a 2.</p>
		</description>
		<sheet alt="Elemental Adept: Fire">
			<description>Spells you cast ignore Fire Resistance. Treat any 1 on a damage die as a 2 when using spells that deal Fire damage.</description>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<description>Spells you cast ignore Lightning Resistance. Treat any 1 on a damage die as a 2 with Lightning spells.</description>
```suggestion
		<supports>Elemental Adept 24</supports>
		<description>
			<p>Spells you cast ignore Lightning Resistance. In addition, when you roll damage for a spell you cast that deals Lightning damage, you can treat any 1 on a damage die as a 2.</p>
		</description>
		<sheet alt="Elemental Adept: Lightning">
			<description>Spells you cast ignore Lightning Resistance. Treat any 1 on a damage die as a 2 when using spells that deal Lightning damage.</description>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<description>Spells you cast ignore Thunder Resistance. Treat any 1 on a damage die as a 2 with Thunder spells.</description>
```suggestion
		<supports>Elemental Adept 24</supports>
		<description>
			<p>Spells you cast ignore Thunder Resistance. In addition, when you roll damage for a spell you cast that deals Thunder damage, you can treat any 1 on a damage die as a 2.</p>
		</description>
		<sheet alt="Elemental Adept: Thunder">
			<description>Spells you cast ignore Thunder Resistance. Treat any 1 on a damage die as a 2 when using spells that deal Thunder damage.</description>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +		<description />
```suggestion
		<requirements>ID_WOTC_PHB24_FEAT_ELEMENTAL_ADEPT</requirements>
		<prerequisite>Level 4+, Spellcasting or Pact Magic Feature</prerequisite>
		<description>
			<p class="flavor">General Feat (Prerequisite: Level 4+, Spellcasting or Pact Magic Feature)</p>
			<p>You gain the following benefits.</p>
			<p class="indent"><b><i>Ability Score Increase.</i></b> Increase your Intelligence, Wisdom, or Charisma score by 1, to a maximum of 20.</p>
			<p class="indent"><b><i>Energy Mastery.</i></b> Choose one of the following damage types: Acid, Cold, Fire, Lightning, or Thunder. Spells you cast ignore Resistance to damage of the chosen type. In addition, when you roll damage for a spell you cast that deals damage of that type, you can treat any 1 on a damage die as a 2.</p>
			<p class="indent"><b><i>Repeatable.</i></b> You can take this feat more than once, but you must choose a different damage type each time for Energy Mastery.</p>
		</description>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<select type="Feat Feature" name="Energy Mastery" supports="Energy Mastery" />
```suggestion
			<select type="Ability Score Improvement" name="Ability Score Increase (Elemental Adept)" supports="ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_FEAT_INTELLIGENCE|ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_FEAT_WISDOM|ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_FEAT_CHARISMA" />
			<select type="Feat Feature" name="Damage Type (Elemental Adept)" supports="Elemental Adept 24" />
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +		<description />
```suggestion
		<requirements>ID_WOTC_PHB24_FEAT_ELEMENTAL_ADEPT_2</requirements>
		<prerequisite>Level 4+, Spellcasting or Pact Magic Feature</prerequisite>
		<description>
			<p class="flavor">General Feat (Prerequisite: Level 4+, Spellcasting or Pact Magic Feature)</p>
			<p>You gain the following benefits.</p>
			<p class="indent"><b><i>Ability Score Increase.</i></b> Increase your Intelligence, Wisdom, or Charisma score by 1, to a maximum of 20.</p>
			<p class="indent"><b><i>Energy Mastery.</i></b> Choose one of the following damage types: Acid, Cold, Fire, Lightning, or Thunder. Spells you cast ignore Resistance to damage of the chosen type. In addition, when you roll damage for a spell you cast that deals damage of that type, you can treat any 1 on a damage die as a 2.</p>
			<p class="indent"><b><i>Repeatable.</i></b> You can take this feat more than once, but you must choose a different damage type each time for Energy Mastery.</p>
		</description>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<select type="Feat Feature" name="Energy Mastery" supports="Energy Mastery" />
```suggestion
			<select type="Ability Score Improvement" name="Ability Score Increase (Elemental Adept)" supports="ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_FEAT_INTELLIGENCE|ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_FEAT_WISDOM|ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_FEAT_CHARISMA" />
			<select type="Feat Feature" name="Damage Type (Elemental Adept)" supports="Elemental Adept 24" />
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +		<description />
```suggestion
		<requirements>ID_WOTC_PHB24_FEAT_ELEMENTAL_ADEPT_3</requirements>
		<prerequisite>Level 4+, Spellcasting or Pact Magic Feature</prerequisite>
		<description>
			<p class="flavor">General Feat (Prerequisite: Level 4+, Spellcasting or Pact Magic Feature)</p>
			<p>You gain the following benefits.</p>
			<p class="indent"><b><i>Ability Score Increase.</i></b> Increase your Intelligence, Wisdom, or Charisma score by 1, to a maximum of 20.</p>
			<p class="indent"><b><i>Energy Mastery.</i></b> Choose one of the following damage types: Acid, Cold, Fire, Lightning, or Thunder. Spells you cast ignore Resistance to damage of the chosen type. In addition, when you roll damage for a spell you cast that deals damage of that type, you can treat any 1 on a damage die as a 2.</p>
			<p class="indent"><b><i>Repeatable.</i></b> You can take this feat more than once, but you must choose a different damage type each time for Energy Mastery.</p>
		</description>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<select type="Feat Feature" name="Energy Mastery" supports="Energy Mastery" />
```suggestion
			<select type="Ability Score Improvement" name="Ability Score Increase (Elemental Adept)" supports="ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_FEAT_INTELLIGENCE|ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_FEAT_WISDOM|ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_FEAT_CHARISMA" />
			<select type="Feat Feature" name="Damage Type (Elemental Adept)" supports="Elemental Adept 24" />
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +		<description />
```suggestion
		<requirements>ID_WOTC_PHB24_FEAT_ELEMENTAL_ADEPT_4</requirements>
		<prerequisite>Level 4+, Spellcasting or Pact Magic Feature</prerequisite>
		<description>
			<p class="flavor">General Feat (Prerequisite: Level 4+, Spellcasting or Pact Magic Feature)</p>
			<p>You gain the following benefits.</p>
			<p class="indent"><b><i>Ability Score Increase.</i></b> Increase your Intelligence, Wisdom, or Charisma score by 1, to a maximum of 20.</p>
			<p class="indent"><b><i>Energy Mastery.</i></b> Choose one of the following damage types: Acid, Cold, Fire, Lightning, or Thunder. Spells you cast ignore Resistance to damage of the chosen type. In addition, when you roll damage for a spell you cast that deals damage of that type, you can treat any 1 on a damage die as a 2.</p>
			<p class="indent"><b><i>Repeatable.</i></b> You can take this feat more than once, but you must choose a different damage type each time for Energy Mastery.</p>
		</description>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<select type="Feat Feature" name="Energy Mastery" supports="Energy Mastery" />
```suggestion
			<select type="Ability Score Improvement" name="Ability Score Increase (Elemental Adept)" supports="ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_FEAT_INTELLIGENCE|ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_FEAT_WISDOM|ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_FEAT_CHARISMA" />
			<select type="Feat Feature" name="Damage Type (Elemental Adept)" supports="Elemental Adept 24" />
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<p><em>General Feat (Prerequisite: Level 4+)</em></p>
```suggestion
		<prerequisite>Level 4+</prerequisite>
		<description>
			<p class="flavor">General Feat (Prerequisite: Level 4+)</p>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<p class="indent"><b><i>Fey Magic.</i></b> Choose one level 1 spell from the Divination or Enchantment school of magic. You always have that spell and the Misty Step spell prepared. You can cast e
```suggestion
			<p class="indent"><b><i>Fey Magic.</i></b> Choose one level 1 spell from the Divination or Enchantment school of magic. You always have that spell and the <i>Misty Step</i> spell prepared. You can cast each of these spells without expending a spell slot. Once you cast either spell in this way, you can't cast that spell in this way again until you finish a Long Rest. You can also cast these spells using spell slots you have of the appropriate level. The spells' spellcasting ability is the ability increased by this feat.</p>
			<div class="reference">
				<div element="ID_WOTC_PHB24_SPELL_MISTY_STEP" />
			</div>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<select type="Spell" name="Spell, Fey Touched" supports="1,(Divination||Enchantment)" />
```suggestion
			<select type="Feat Feature" name="Ability Score Increase (Fey-Touched)" supports="Fey-Touched 24" />
			<select type="Spell" name="Spell (Fey-Touched)" supports="1,(Divination||Enchantment)" />
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +		<supports>Fey-Touched</supports>
```suggestion
		<supports>Fey-Touched 24</supports>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<description>Choose one level 1 spell from the Divination or Enchantment school of magic. You always have that spell and the Misty Step spell prepared. You can cast each of these spells without ex
```suggestion
			<description>You can cast each of this feat’s spells without a spell slot once per Long Rest. You can also cast these spells using spell slots you have of the appropriate level. Your spellcasting ability for these spells is Intelligence.</description>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +		<supports>Fey-Touched</supports>
```suggestion
		<supports>Fey-Touched 24</supports>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<description>Choose one level 1 spell from the Divination or Enchantment school of magic. You always have that spell and the Misty Step spell prepared. You can cast each of these spells without ex
```suggestion
			<description>You can cast each of this feat’s spells without a spell slot once per Long Rest. You can also cast these spells using spell slots you have of the appropriate level. Your spellcasting ability for these spells is Wisdom.</description>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +		<supports>Fey-Touched</supports>
```suggestion
		<supports>Fey-Touched 24</supports>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<description>Choose one level 1 spell from the Divination or Enchantment school of magic. You always have that spell and the Misty Step spell prepared. You can cast each of these spells without ex
```suggestion
			<description>You can cast each of this feat’s spells without a spell slot once per Long Rest. You can also cast these spells using spell slots you have of the appropriate level. Your spellcasting ability for these spells is Charisma.</description>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<p><em>General Feat (Prerequisite: Level 4+, Strength or Dexterity 13+)</em></p>
```suggestion
		<prerequisite>Level 4+, Strength or Dexterity 13+</prerequisite>
		<description>
			<p class="flavor">General Feat (Prerequisite: Level 4+, Strength or Dexterity 13+)</p>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +		<sheet display="false" />
```suggestion
			<p class="indent"><b><i>Fast Wrestler.</i></b> You don’t have to spend extra movement to move a creature Grappled by you if the creature is your size or smaller.</p>
		</description>
		<sheet>
			<description>You gain following benefits: &#13;
			• Once per turn, when you hit a creature with an Unarmed Strike as part of the Attack action on your turn, you can use both the Damage and the Grapple option. &#13;
			• You have Advantage on attack rolls against a creature Grappled by you. &#13;
			• You don’t have to spend extra movement to move a creature Grappled by you if the creature is your size or smaller.</description>
		</sheet>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<select type="Feat Feature" name="Ability Score Increase (Grappler)" supports="Grappler" />
```suggestion
			<select type="Ability Score Improvement" name="Ability Score Increase (Grappler)" supports="ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_FEAT_STRENGTH|ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_FEAT_DEXTERITY" />
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +	</element>
```suggestion
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<p><em>General Feat (Prerequisite: Level 4+, Strength 13+)</em></p>
```suggestion
		<prerequisite>Level 4+, Strength 13+</prerequisite>
		<description>
			<p class="flavor">General Feat (Prerequisite: Level 4+, Strength 13+)</p>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			Immediately after you score a Critical Hit with a Melee weapon or reduce a creature to 0 Hit Points with one, you can make one attack with the same weapon as a Bonus Action.</description>
```suggestion
			<description>Whenever you deal damage to a creature with a Heavy weapon as part of the Attack action, you can deal an extra {{proficiency}} damage to it. &#13;
			Additionally, after you score a Critical Hit with a Melee weapon or reduce a creature to 0 Hit Points with one, you can make one attack with the same weapon as a Bonus Action.</description>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<p><em>General Feat (Prerequisite: Level 4+, Medium Armor Training)</em></p>
```suggestion
		<prerequisite>Level 4+, Medium Armor Training</prerequisite>
		<description>
			<p class="flavor">General Feat (Prerequisite: Level 4+, Medium Armor Training)</p>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<select type="Feat Feature" name="Ability Score Increase (Heavily Armored)" supports="Heavily Armored" />
```suggestion
			<select type="Ability Score Improvement" name="Ability Score Increase (Heavily Armored)" supports="ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_FEAT_STRENGTH|ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_FEAT_CONSTITUTION" />
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +	</element>
```suggestion
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<p><em>General Feat (Prerequisite: Level 4+, Heavy Armor Training)</em></p>
```suggestion
		<prerequisite>Level 4+, Heavy Armor Training</prerequisite>
		<description>
			<p class="flavor">General Feat (Prerequisite: Level 4+, Heavy Armor Training)</p>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +	</element>
```suggestion
		<sheet>
			<description>While wearing Heavy armor, any Bludgeoning, Piercing, and Slashing damage you receive from an attack is reduced by {{proficiency}}.</description>
		</sheet>
		<rules>
			<select type="Ability Score Improvement" name="Ability Score Increase (Heavy Armor Master)" supports="ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_FEAT_STRENGTH|ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_FEAT_CONSTITUTION" />
		</rules>
	</element>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +	</element>
```suggestion
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<p><em>General Feat (Prerequisite: Level 4+, Wisdom or Charisma 13+)</em></p>
```suggestion
		<prerequisite>Level 4+, Wisdom or Charisma 13+</prerequisite>
		<description>
			<p class="flavor">General Feat (Prerequisite: Level 4+, Wisdom or Charisma 13+)</p>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<stat name="perf:temp" value="level" />
```suggestion
			<select type="Feat Feature" name="Ability Score Increase (Inspiring Leader)" supports="PHB24 Inspiring Leader" />
			<stat name="inspiring leader:thp" value="level" bonus="base" />
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +		<supports>Inspiring Leader</supports>
```suggestion
		<supports>PHB24 Inspiring Leader</supports>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<description>When you finish a Short or Long Rest, you can give an inspiring performance. When you do so, choose up to six allies (can include yourself) within 30ft of yourself who witness the per
```suggestion
			<description>When you finish a Short or Long Rest, you can give an inspiring performance. When you do so, choose up to 6 allies (can include yourself) within 30ft. of yourself who witness the performance. The chosen creatures each gain {{inspiring leader:thp}} Temporary HP.</description>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<stat name="perf:temp" value="wisdom:modifier" />
```suggestion
			<stat name="inspiring leader:thp" value="wisdom:modifier" bonus="ability" />
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +		<supports>Inspiring Leader</supports>
```suggestion
		<supports>PHB24 Inspiring Leader</supports>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<description>When you finish a Short or Long Rest, you can give an inspiring performance. When you do so, choose up to six allies (can include yourself) within 30ft of yourself who witness the per
```suggestion
			<description>When you finish a Short or Long Rest, you can give an inspiring performance. When you do so, choose up to 6 allies (can include yourself) within 30ft. of yourself who witness the performance. The chosen creatures each gain {{inspiring leader:thp}} Temporary HP.</description>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<stat name="perf:temp" value="charisma:modifier" />
```suggestion
			<stat name="inspiring leader:thp" value="charisma:modifier" bonus="ability" />
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<p><em>General Feat (Prerequisite: Level 4+, Intelligence 13+)</em></p>
```suggestion
		<prerequisite>Level 4+, Intelligence 13+</prerequisite>
		<description>
			<p class="flavor">General Feat (Prerequisite: Level 4+, Intelligence 13+)</p>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<select type="Feat Feature" name="Skill Proficiency (Keen Mind)" supports="Keen Mind" />
```suggestion
		<sheet action="Bonus Action">
			<description>You can take the Study action.</description>
		</sheet>
		<rules>
			<stat name="intelligence" value="1" alt="Keen Mind" />
			<select type="Feat Feature" name="Skill Proficiency or Expertise (Keen Mind)" supports="PHB24 Keen Mind" />
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +		</rules>
```suggestion
		<supports>PHB24 Keen Mind</supports>
		<description />
		<sheet display="false" />
		<rules>
			<grant type="Grants" id="ID_INTERNAL_GRANTS_PROFICIENCY_SKILL_OR_DOUBLE_ARCANA" />
		</rules>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +	</element>
```suggestion
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<grant type="Grants" id="ID_INTERNAL_GRANTS_PHB24_PROFICIENCY_SKILL_HISTORY_EXPERTISE" requirements="ID_WOTC_PHB24_PROFICIENCY_SKILL_HISTORY" />
```suggestion
		<supports>PHB24 Keen Mind</supports>
		<description />
		<sheet display="false" />
		<rules>
			<grant type="Grants" id="ID_INTERNAL_GRANTS_PROFICIENCY_SKILL_OR_DOUBLE_HISTORY" />
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +	</element>
```suggestion
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<grant type="Grants" id="ID_INTERNAL_GRANTS_PHB24_PROFICIENCY_SKILL_INVESTIGATION_EXPERTISE" requirements="ID_WOTC_PHB24_PROFICIENCY_SKILL_INVESTIGATION" />
```suggestion
		<supports>PHB24 Keen Mind</supports>
		<description />
		<sheet display="false" />
		<rules>
			<grant type="Grants" id="ID_INTERNAL_GRANTS_PROFICIENCY_SKILL_OR_DOUBLE_INVESTIGATION" />
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +	</element>
```suggestion
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<grant type="Grants" id="ID_INTERNAL_GRANTS_PHB24_PROFICIENCY_SKILL_NATURE_EXPERTISE" requirements="ID_WOTC_PHB24_PROFICIENCY_SKILL_NATURE" />
```suggestion
		<supports>PHB24 Keen Mind</supports>
		<description />
		<sheet display="false" />
		<rules>
			<grant type="Grants" id="ID_INTERNAL_GRANTS_PROFICIENCY_SKILL_OR_DOUBLE_NATURE" />
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +	</element>
```suggestion
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<grant type="Grants" id="ID_INTERNAL_GRANTS_PHB24_PROFICIENCY_SKILL_RELIGION_EXPERTISE" requirements="ID_WOTC_PHB24_PROFICIENCY_SKILL_RELIGION" />
```suggestion
		<supports>PHB24 Keen Mind</supports>
		<description />
		<sheet display="false" />
		<rules>
			<grant type="Grants" id="ID_INTERNAL_GRANTS_PROFICIENCY_SKILL_OR_DOUBLE_RELIGION" />
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +	</element>
```suggestion
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<p><em>General Feat (Prerequisite: Level 4+)</em></p>
```suggestion
		<prerequisite>Level 4+</prerequisite>
		<description>
			<p class="flavor">General Feat (Prerequisite: Level 4+)</p>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<select type="Feat Feature" name="Ability Score Increase (Lightly Armored)" supports="Lightly Armored" />
```suggestion
			<select type="Ability Score Improvement" name="Ability Score Increase (Lightly Armored)" supports="ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_FEAT_STRENGTH|ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_FEAT_DEXTERITY" />
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +	</element>
```suggestion
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<p><em>General Feat (Prerequisite: Level 4+)</em></p>
```suggestion
		<prerequisite>Level 4+</prerequisite>
		<description>
			<p class="flavor">General Feat (Prerequisite: Level 4+)</p>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +	</element>
```suggestion
		<sheet usage="1/Short Rest">
			<description>If you fail an Intelligence, a Wisdom, or a Charisma saving throw, you can cause yourself to succeed instead. &#13;
			Additionally, when you damage a creature that is concentrating, it has Disadvantage on the saving throw it makes to maintain Concentration.</description>
		</sheet>
		<rules>
			<select type="Ability Score Improvement" name="Ability Score Increase (Mage Slayer)" supports="ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_FEAT_STRENGTH|ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_FEAT_DEXTERITY" />
		</rules>
	</element>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +	</element>
```suggestion
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<p><em>General Feat (Prerequisite: Level 4+)</em></p>
```suggestion
		<prerequisite>Level 4+</prerequisite>
		<description>
			<p class="flavor">General Feat (Prerequisite: Level 4+)</p>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<select type="Feat Feature" name="Ability Score Increase (Martial Weapon Training)" supports="Martial Weapon Training" />
```suggestion
			<select type="Ability Score Improvement" name="Ability Score Increase (Martial Weapon Training)" supports="ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_FEAT_STRENGTH|ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_FEAT_DEXTERITY" />
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +	</element>
```suggestion
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<p><em>General Feat (Prerequisite: Level 4+, Medium Armor Training)</em></p>
```suggestion
		<prerequisite>Level 4+, Medium Armor Training</prerequisite>
		<description>
			<p class="flavor">General Feat (Prerequisite: Level 4+, Medium Armor Training)</p>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +	</element>
```suggestion
		<sheet display="false" />
		<rules>
			<select type="Ability Score Improvement" name="Ability Score Increase (Medium Armor Master)" supports="ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_FEAT_STRENGTH|ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_FEAT_DEXTERITY" />
			<stat name="ac:armored:dexterity:cap" value="3" bonus="base" />
		</rules>
	</element>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +	</element>
```suggestion
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<p><em>General Feat (Prerequisite: Level 4+, Light Armor Training)</em></p>
```suggestion
		<prerequisite>Level 4+, Light Armor Training</prerequisite>
		<description>
			<p class="flavor">General Feat (Prerequisite: Level 4+, Light Armor Training)</p>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<select type="Feat Feature" name="Ability Score Increase (Moderately Armored)" supports="Moderately Armored" />
```suggestion
			<select type="Ability Score Improvement" name="Ability Score Increase (Moderately Armored)" supports="ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_FEAT_STRENGTH|ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_FEAT_DEXTERITY" />
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +	</element>
```suggestion
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<p><em>General Feat (Prerequisite: Level 4+)</em></p>
```suggestion
		<prerequisite>Level 4+</prerequisite>
		<description>
			<p class="flavor">General Feat (Prerequisite: Level 4+)</p>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +	</element>
```suggestion
		<sheet>
			<description>While mounted, you have Advantage on attack rolls against any unmounted creature within 5 feet of your mount that is at least one size smaller than the mount. &#13;
			When your mount makes a Dexterity saving throw to take half damage from an effect, it instead takes no damage if it succeeds and only half damage if it fails. For your mount to gain this benefit, you must be riding it, and neither of you can have the Incapacitated condition. &#13;
			While mounted, you can force an attack that hits your mount to hit you instead if you don't have the Incapacitated condition.</description>
		</sheet>
		<rules>
			<select type="Ability Score Improvement" name="Ability Score Increase (Mounted Combatant)" supports="ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_FEAT_STRENGTH|ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_FEAT_DEXTERITY|ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_FEAT_WISDOM" />
		</rules>
	</element>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +	</element>
```suggestion
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<p><em>General Feat (Prerequisite: Level 4+, Intelligence or Wisdom 13+)</em></p>
```suggestion
		<prerequisite>Level 4+, Intelligence or Wisdom 13+</prerequisite>
		<description>
			<p class="flavor">General Feat (Prerequisite: Level 4+, Intelligence or Wisdom 13+)</p>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +	</element>
```suggestion
		<sheet action="Bonus Action">
			<description>You can take the Search action.</description>
		</sheet>
		<rules>
			<select type="Ability Score Improvement" name="Ability Score Increase (Mounted Combatant)" supports="ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_FEAT_INTELLIGENCE|ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_FEAT_WISDOM" />
			<select type="Feat Feature" name="Skill Proficiency or Expertise (Observant)" supports="PHB24 Observant" />
		</rules>
	</element>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +	</element>
```suggestion
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<grant type="Grants" id="ID_INTERNAL_GRANTS_PHB24_PROFICIENCY_SKILL_INSIGHT_EXPERTISE" requirements="ID_WOTC_PHB24_PROFICIENCY_SKILL_INSIGHT" />
```suggestion
		<supports>PHB24 Observant</supports>
		<description />
		<sheet display="false" />
		<rules>
			<grant type="Grants" id="ID_INTERNAL_GRANTS_PROFICIENCY_SKILL_OR_DOUBLE_INSIGHT" />
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +	</element>
```suggestion
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<grant type="Grants" id="ID_INTERNAL_GRANTS_PHB24_PROFICIENCY_SKILL_INVESTIGATION_EXPERTISE" requirements="ID_WOTC_PHB24_PROFICIENCY_SKILL_INVESTIGATION" />
```suggestion
		<supports>PHB24 Observant</supports>
		<description />
		<sheet display="false" />
		<rules>
			<grant type="Grants" id="ID_INTERNAL_GRANTS_PROFICIENCY_SKILL_OR_DOUBLE_INVESTIGATION" />
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<grant type="Grants" id="ID_INTERNAL_GRANTS_PHB24_PROFICIENCY_SKILL_PERCEPTION_EXPERTISE" requirements="ID_WOTC_PHB24_PROFICIENCY_SKILL_PERCEPTION" />
```suggestion
		<supports>PHB24 Observant</supports>
		<description />
		<sheet display="false" />
		<rules>
			<grant type="Grants" id="ID_INTERNAL_GRANTS_PROFICIENCY_SKILL_OR_DOUBLE_PERCEPTION" />
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +	</element>
```suggestion
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<p><em>General Feat (Prerequisite: Level 4+)</em></p>
```suggestion
		<prerequisite>Level 4+</prerequisite>
		<description>
			<p class="flavor">General Feat (Prerequisite: Level 4+)</p>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +	</element>
```suggestion
		<sheet usage="1/Turn">
			<description>When you hit a creature with an attack that deals Piercing damage, you can reroll one of the attack's damage dice, and you must use the new roll. &#13;
			Additionally, whenever you score a Critical Hit that deals Piercing damage to a creature, you can roll one additional damage die when determining the extra Piercing damage.</description>
		</sheet>
		<rules>
			<select type="Ability Score Improvement" name="Ability Score Increase (Piercer)" supports="ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_FEAT_STRENGTH|ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_FEAT_DEXTERITY" />
		</rules>
	</element>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +	</element>
```suggestion
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<p class="indent"><b><i>Brew Poison.</i></b> You gain proficiency with the Poisoner's Kit. With 1 hour of work using such a kit and expending 50 GP worth of materials, you can create a number of p
```suggestion
		<prerequisite>Level 4+</prerequisite>
		<description>
			<p class="flavor">General Feat (Prerequisite: Level 4+)</p>
			<p>You gain the following benefits.</p>
			<p class="indent"><b><i>Ability Score Increase.</i></b> Increase your Dexterity or Intelligence score by 1, to a maximum of 20.</p>
			<p class="indent"><b><i>Potent Poison.</i></b> When you make a damage roll that deals Poison damage, it ignores Resistance to Poison damage.</p>
			<p class="indent"><b><i>Brew Poison.</i></b> You gain proficiency with the Poisoner's Kit. With 1 hour of work using such a kit and expending 50 GP worth of materials, you can create a number of poison doses equal to your Proficiency Bonus. As a Bonus Action, you can apply a poison dose to a weapon or piece of ammunition. Once applied, the poison retains its potency for 1 minute or until you deal damage with the poisoned item, whichever is shorter. When a creature takes damage from the poisoned item, that creature must succeed on a Constitution saving throw (DC 8 plus the modifier of the ability increased by this feat and your Proficiency Bonus) or take 2d8 Poison damage and have the Poisoned condition until the end of your next turn.</p>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<stat name="poison:dose:dc" value="proficiency" />
```suggestion
			<grant type="Proficiency" id="ID_WOTC_PHB24_PROFICIENCY_TOOL_PROFICIENCY_POISONERS_KIT" />
			<stat name="poisoner:dc" value="8" bonus="base" />
			<stat name="poisoner:dc" value="proficiency" bonus="proficiency" />
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			With 1 hour of work using a Poisoner's Kit and expending 50 GP worth of materials, you can create {{proficiency}} poison doses. As a Bonus Action, you can apply a poison dose to a weapon or piece
```suggestion
			<description>When you make a damage roll that deals Poison damage, it ignores Resistance to Poison damage. &#13;
			With 1 hour of work using a Poisoner's Kit and expending 50 GP worth of materials, you can create {{proficiency}} poison doses. As a Bonus Action, you can apply a poison dose to a weapon or piece of ammunition. Once applied, the poison retains its potency for 1 minute or until you deal damage with the poisoned item, whichever is shorter. When a creature takes damage from the poisoned item, that creature must succeed on a DC{{poisoner:dc}} Constitution saving throw or take 2d8 Poison damage and have the Poisoned condition until the end of your next turn.</description>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<stat name="poison:dose:dc" value="dexterity:modifier" />
```suggestion
			<stat name="poisoner:dc" value="dexterity:modifier" bonus="ability" />
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			With 1 hour of work using a Poisoner's Kit and expending 50 GP worth of materials, you can create {{proficiency}} poison doses. As a Bonus Action, you can apply a poison dose to a weapon or piece
```suggestion
			<description>When you make a damage roll that deals Poison damage, it ignores Resistance to Poison damage. &#13;
			With 1 hour of work using a Poisoner's Kit and expending 50 GP worth of materials, you can create {{proficiency}} poison doses. As a Bonus Action, you can apply a poison dose to a weapon or piece of ammunition. Once applied, the poison retains its potency for 1 minute or until you deal damage with the poisoned item, whichever is shorter. When a creature takes damage from the poisoned item, that creature must succeed on a DC{{poisoner:dc}} Constitution saving throw or take 2d8 Poison damage and have the Poisoned condition until the end of your next turn.</description>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<stat name="poison:dose:dc" value="intelligence:modifier" />
```suggestion
			<stat name="poisoner:dc" value="intelligence:modifier" bonus="ability" />
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<p><em>General Feat (Prerequisite: Level 4+, Strength or Dexterity 13+)</em></p>
```suggestion
		<prerequisite>Level 4+, Strength or Dexterity 13+</prerequisite>
		<description>
			<p class="flavor">General Feat (Prerequisite: Level 4+, Strength or Dexterity 13+)</p>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +	</element>
```suggestion
		<sheet>
			<description>Immediately after you take the Attack action and attack with a Quarterstaff, a Spear, or a weapon that has the Heavy and Reach properties, you can use a Bonus Action to make a melee attack with the opposite end of the weapon. The weapon deals Bludgeoning damage, and the weapon's damage die for this attack is a d4. &#13;
			Additionally, while you're holding a Quarterstaff, a Spear, or a weapon that has the Heavy and Reach properties, you can take a Reaction to make one melee attack against a creature that enters the reach you have with that weapon.</description>
		</sheet>
		<rules>
			<select type="Ability Score Improvement" name="Ability Score Increase (Polearm Master)" supports="ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_FEAT_STRENGTH|ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_FEAT_DEXTERITY" />
		</rules>
	</element>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +	</element>
```suggestion
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<p><em>General Feat (Prerequisite: Level 4+)</em></p>
```suggestion
		<prerequisite>Level 4+</prerequisite>
		<description>
			<p class="flavor">General Feat (Prerequisite: Level 4+)</p>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<select type="Feat Feature" name="Ability Score Increase (Resilient)" supports="Resilient" />
```suggestion
			<select type="Feat Feature" name="Ability Score Increase (Resilient)" supports="PHB24 Resilient" />
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<p>You gain proficiency with Strength saving throws.</p>
```suggestion
	<!-- Note: due to how this feat is implemented, any element that requires Saving Throw Proficiency through their relevant IDs won't count proficiency that comes from Resilient Feat. For requirements of such elements you should use "[ability:save:proficiency:1]" stat instead of IDs. -->
	<element name="Strength" type="Feat Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_FEAT_RESILIENT_STRENGTH">
		<requirements>!ID_WOTC_PHB24_PROFICIENCY_SAVINGTHROW_STRENGTH</requirements>
		<compendium display="false" />
		<supports>PHB24 Resilient</supports>
		<description>
			<p>You gain proficiency with Strength saving throws, and increase your Strength by 1, to a maximum of 20.</p>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +		<rules>
```suggestion
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<p>You gain proficiency with Dexterity saving throws.</p>
```suggestion
	<element name="Dexterity" type="Feat Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_FEAT_RESILIENT_DEXTERITY">
		<requirements>!ID_WOTC_PHB24_PROFICIENCY_SAVINGTHROW_DEXTERITY</requirements>
		<compendium display="false" />
		<supports>PHB24 Resilient</supports>
		<description>
			<p>You gain proficiency with Dexterity saving throws, and increase your Dexterity by 1, to a maximum of 20.</p>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +		<rules>
```suggestion
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<p>You gain proficiency with Constitution saving throws.</p>
```suggestion
	<element name="Constitution" type="Feat Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_FEAT_RESILIENT_CONSTITUTION">
		<requirements>!ID_WOTC_PHB24_PROFICIENCY_SAVINGTHROW_CONSTITUTION</requirements>
		<compendium display="false" />
		<supports>PHB24 Resilient</supports>
		<description>
			<p>You gain proficiency with Constitution saving throws, and increase your Constitution by 1, to a maximum of 20.</p>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +		<rules>
```suggestion
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<p>You gain proficiency with Intelligence saving throws.</p>
```suggestion
	<element name="Intelligence" type="Feat Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_FEAT_RESILIENT_INTELLIGENCE">
		<requirements>!ID_WOTC_PHB24_PROFICIENCY_SAVINGTHROW_INTELLIGENCE</requirements>
		<compendium display="false" />
		<supports>PHB24 Resilient</supports>
		<description>
			<p>You gain proficiency with Intelligence saving throws, and increase your Intelligence by 1, to a maximum of 20.</p>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +		<rules>
```suggestion
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<p>You gain proficiency with Wisdom saving throws.</p>
```suggestion
	<element name="Wisdom" type="Feat Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_FEAT_RESILIENT_WISDOM">
		<requirements>!ID_WOTC_PHB24_PROFICIENCY_SAVINGTHROW_WISDOM</requirements>
		<compendium display="false" />
		<supports>PHB24 Resilient</supports>
		<description>
			<p>You gain proficiency with Wisdom saving throws, and increase your Wisdom by 1, to a maximum of 20.</p>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +		<rules>
```suggestion
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<p>You gain proficiency with Charisma saving throws.</p>
```suggestion
	<element name="Charisma" type="Feat Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_FEAT_RESILIENT_CHARISMA">
		<requirements>!ID_WOTC_PHB24_PROFICIENCY_SAVINGTHROW_CHARISMA</requirements>
		<compendium display="false" />
		<supports>PHB24 Resilient</supports>
		<description>
			<p>You gain proficiency with Charisma saving throws, and increase your Charisma by 1, to a maximum of 20.</p>
```

2025-10-01 14:02 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +		<rules>
```suggestion
```

2025-10-01 14:02 UTC, NickVendel requested changes
Review got quite long, so here's part 1 for now.

2025-10-03 11:54 UTC, NickVendel requested changes
Part 2

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<p><em>General Feat (Prerequisite: Level 4+; Intelligence, Wisdom, or Charisma 13+)</em></p>
```suggestion
		<prerequisite>Level 4+, Intelligence, Wisdom, or Charisma 13+</prerequisite>
		<description>
			<p class="flavor">General Feat (Prerequisite: Level 4+; Intelligence, Wisdom, or Charisma 13+)</p>
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<select type="Spell" name="1st-level Spell (Ritual Caster)" supports="Ritual,1" level="17" />
```suggestion
			<select type="Feat Feature" name="Ability Score Increase (Ritual Caster)" supports="PHB24 Ritual Caster" />
			<select type="Spell" name="1st Ritual Spell (Ritual Caster)" supports="Ritual,1" requirements="[proficiency:1]" />
			<select type="Spell" name="2nd Ritual Spell (Ritual Caster)" supports="Ritual,1" requirements="[proficiency:2]" />
			<select type="Spell" name="3rd Ritual Spell (Ritual Caster)" supports="Ritual,1" requirements="[proficiency:3]" />
			<select type="Spell" name="4th Ritual Spell (Ritual Caster)" supports="Ritual,1" requirements="[proficiency:4]" />
			<select type="Spell" name="5th Ritual Spell (Ritual Caster)" supports="Ritual,1" requirements="[proficiency:5]" />
			<select type="Spell" name="6th Ritual Spell (Ritual Caster)" supports="Ritual,1" requirements="[proficiency:6]" />
			<select type="Spell" name="7th Ritual Spell (Ritual Caster)" supports="Ritual,1" requirements="[proficiency:7]" />
			<select type="Spell" name="8th Ritual Spell (Ritual Caster)" supports="Ritual,1" requirements="[proficiency:8]" />
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			You can cast a Ritual spell that you have prepared using its regular casting time rather than the extended time for a Ritual. Doing so doesn't require a spell slot. Once you cast the spell in this
```suggestion
		<supports>PHB24 Ritual Caster</supports>
		<description>
			<p>Increase your Intelligence by 1, to a maximum of 20.</p>
		</description>
		<sheet alt="Ritual Caster" usage="1/Long Rest">
			<description>You can cast a Ritual spell that you have prepared using its regular casting time rather than the extended time for a Ritual without expending a spell slot. &#13;
			Intelligence is your spellcasting ability for this feat's spells.</description>
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			You can cast a Ritual spell that you have prepared using its regular casting time rather than the extended time for a Ritual. Doing so doesn't require a spell slot. Once you cast the spell in this
```suggestion
		<supports>PHB24 Ritual Caster</supports>
		<description>
			<p>Increase your Wisdom by 1, to a maximum of 20.</p>
		</description>
		<sheet alt="Ritual Caster" usage="1/Long Rest">
			<description>You can cast a Ritual spell that you have prepared using its regular casting time rather than the extended time for a Ritual without expending a spell slot. &#13;
			Wisdom is your spellcasting ability for this feat's spells.</description>
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			You can cast a Ritual spell that you have prepared using its regular casting time rather than the extended time for a Ritual. Doing so doesn't require a spell slot. Once you cast the spell in this
```suggestion
		<supports>PHB24 Ritual Caster</supports>
		<description>
			<p>Increase your Charisma by 1, to a maximum of 20.</p>
		</description>
		<sheet alt="Ritual Caster" usage="1/Long Rest">
			<description>You can cast a Ritual spell that you have prepared using its regular casting time rather than the extended time for a Ritual without expending a spell slot. &#13;
			Charisma is your spellcasting ability for this feat's spells.</description>
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<p><em>General Feat (Prerequisite: Level 4+, Strength or Dexterity 13+)</em></p>
```suggestion
		<prerequisite>Level 4+, Strength or Dexterity 13+</prerequisite>
		<description>
			<p class="flavor">General Feat (Prerequisite: Level 4+, Strength or Dexterity 13+)</p>
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +	</element>
```suggestion
		<sheet action="Reaction">
			<description>Immediately after a creature within 5ft. of you takes the Disengage action or hits a target other than you with an attack, you can make an Opportunity Attack against that creature. &#13;
			Additionally, whenever you hit a creature with an Opportunity Attack, the creature's Speed becomes 0 for the rest of the current turn.</description>
		</sheet>
		<rules>
			<select type="Ability Score Improvement" name="Ability Score Increase (Sentinel)" supports="ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_FEAT_STRENGTH|ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_FEAT_DEXTERITY" />
		</rules>
	</element>
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +	</element>
```suggestion
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<p><em>General Feat (Prerequisite: Level 4+)</em></p>
```suggestion
	<element name="Shadow-Touched" type="Feat" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_FEAT_SHADOWTOUCHED">
		<requirements>[level:4]</requirements>
		<supports>General</supports>
		<prerequisite>Level 4+</prerequisite>
		<description>
			<p class="flavor">General Feat (Prerequisite: Level 4+)</p>
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<select type="Spell" name="Spell, Shadow-Touched" supports="1,(Illusion||Necromancy)" />
```suggestion
			<p class="indent"><b><i>Shadow Magic.</i></b> Choose one level 1 spell from the Illusion or Necromancy school of magic. You always have that spell and the <i>Invisibility</i> spell prepared. You can cast each of these spells without expending a spell slot. Once you cast either spell in this way, you can't cast that spell in this way again until you finish a Long Rest. You can also cast these spells using spell slots you have of the appropriate level. The spells' spellcasting ability is the ability increased by this feat.</p>
			<div class="reference">
				<div element="ID_WOTC_PHB24_SPELL_INVISIBILITY" />
			</div>
		</description>
		<sheet display="false" />
		<rules>
			<select type="Feat Feature" name="Ability Score Increase (Shadow-Touched)" supports="PHB24 Shadow-Touched" />
			<grant type="Spell" id="ID_WOTC_PHB24_SPELL_INVISIBILITY" />
			<select type="Spell" name="Spell (Shadow-Touched)" supports="1,(Illusion||Necromancy)" />
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<description>Choose one level 1 spell from the Illusion or Necromancy school of magic. You always have that spell and the Invisibility spell prepared. You can cast each of these spells without exp
```suggestion
	<element name="Intelligence" type="Feat Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_FEAT_FEATURE_SHADOWTOUCHED_INTELLIGENCE">
		<compendium display="false" />
		<supports>PHB24 Shadow-Touched</supports>
		<description>
			<p>Increase your Intelligence by 1, to a maximum of 20.</p>
		</description>
		<sheet alt="Shadow-Touched">
			<description>You can cast each of this feat’s spells without a spell slot once per Long Rest. You can also cast these spells using spell slots you have of the appropriate level. Your spellcasting ability for these spells is Intelligence.</description>
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<description>Choose one level 1 spell from the Illusion or Necromancy school of magic. You always have that spell and the Invisibility spell prepared. You can cast each of these spells without exp
```suggestion
	<element name="Wisdom" type="Feat Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_FEAT_FEATURE_SHADOWTOUCHED_WISDOM">
		<compendium display="false" />
		<supports>PHB24 Shadow-Touched</supports>
		<description>
			<p>Increase your Wisdom by 1, to a maximum of 20.</p>
		</description>
		<sheet alt="Shadow-Touched">
			<description>You can cast each of this feat’s spells without a spell slot once per Long Rest. You can also cast these spells using spell slots you have of the appropriate level. Your spellcasting ability for these spells is Wisdom.</description>
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<stat name="charisma" value="1" alt="Spell Sniper" />
```suggestion
	<element name="Charisma" type="Feat Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_FEAT_FEATURE_SHADOWTOUCHED_CHARISMA">
		<compendium display="false" />
		<supports>PHB24 Shadow-Touched</supports>
		<description>
			<p>Increase your Charisma by 1, to a maximum of 20.</p>
		</description>
		<sheet alt="Shadow-Touched">
			<description>You can cast each of this feat’s spells without a spell slot once per Long Rest. You can also cast these spells using spell slots you have of the appropriate level. Your spellcasting ability for these spells is Charisma.</description>
		</sheet>
		<rules>
			<stat name="charisma" value="1" alt="Shadow-Touched" />
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<p><em>General Feat (Prerequisite: Level 4+, Dexterity 13+)</em></p>
```suggestion
		<prerequisite>Level 4+, Dexterity 13+</prerequisite>
		<description>
			<p class="flavor">General Feat (Prerequisite: Level 4+, Dexterity 13+)</p>
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<description>Your ranged attacks with weapons ignore Half Cover and Three-Quarters Cover. Being within 5ft of an enemy doesn't impose Disadvantage on your attack rolls with Ranged weapons. Attacki
```suggestion
			<description>Your gain the following benefits, when making ranged weapon attacks: Being within 5ft. of an enemy or attacking at long range doesn't impose Disadvantage; you can also ignore Half Cover and Three-Quarters Cover.</description>
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<p><em>General Feat (Prerequisite: Level 4+, Shield Training)</em></p>
```suggestion
		<prerequisite>Level 4+, Shield Training</prerequisite>
		<description>
			<p class="flavor">General Feat (Prerequisite: Level 4+, Shield Training)</p>
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<stat name="shield:bash:dc" value="strength:modifier" />
```suggestion
		<sheet usage="1/Turn">
			<description>When you hit a creature within 5ft of you with a Melee weapon as part of the Attack action, you can immediately bash the target with your Shield if it's equipped, forcing the target to make a DC{{shield master:dc}} Strength saving throw. On a failed save, you either push the target 5ft. from you or cause it to have the Prone condition. &#13;
			Additionally, if you succeed on a Dexterity saving throw to take only half damage while holding a Shield, you can use a Reaction to take no damage instead.</description>
		</sheet>
		<rules>
			<stat name="strength" value="1" alt="Shield Master" />
			<stat name="shield master:dc" value="8" bonus="base" />
			<stat name="shield master:dc" value="proficiency" bonus="proficiency" />
			<stat name="shield master:dc" value="strength:modifier" bonus="ability" />
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<p><em>General Feat (Prerequisite: Level 4+)</em></p>
```suggestion
		<prerequisite>Level 4+</prerequisite>
		<description>
			<p class="flavor">General Feat (Prerequisite: Level 4+)</p>
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<select type="Proficiency" name="Expertise (Skill Expert)" supports="ID_INTERNAL_SUPPORT_EXPERTISE"/>
```suggestion
		<sheet display="false" />
		<rules>
			<select type="Ability Score Improvement" name="Ability Score Increase (Skill Expert)" supports="Feat Ability Score Increase" />
			<select type="Proficiency" name="Skill Proficiency (Skill Expert)" supports="Skill" />
			<select type="Proficiency" name="Expertise (Skill Expert)" supports="Expertise"/>
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<p><em>General Feat (Prerequisite: Level 4+, Dexterity 13+)</em></p>
```suggestion
		<prerequisite>Level 4+, Dexterity 13+</prerequisite>
		<description>
			<p class="flavor">General Feat (Prerequisite: Level 4+, Dexterity 13+)</p>
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<description>You gain you Advantage on any Dexterity (Stealth) check you make as part of the Hide action during combat. If you make an attack roll while hidden and the roll misses, making the atta
i slightly changed second sentence, i feel like it says the same thing. But would need a second opinion on it.
```suggestion
			<description>You have Advantage on any Dexterity (Stealth) check you make as part of the Hide action during combat. Additionally while hidden, you don't reveal yourself when you miss an attack roll.</description>
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<p><em>General Feat (Prerequisite: Level 4+)</em></p>
```suggestion
		<prerequisite>Level 4+</prerequisite>
		<description>
			<p class="flavor">General Feat (Prerequisite: Level 4+)</p>
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +	</element>
```suggestion
		<sheet usage="1/Turn">
			<description>When you hit a creature with an attack that deals Slashing damage, you can reduce the Speed of that creature by 10ft. until the start of your next turn. &#13;
			Additionally, whenever you score a Critical Hit that deals Slashing damage to a creature, it has Disadvantage on attack rolls until the start of your next turn.</description>
		</sheet>
		<rules>
			<select type="Ability Score Improvement" name="Ability Score Increase (Slasher)" supports="ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_FEAT_STRENGTH|ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_FEAT_DEXTERITY" />
		</rules>
	</element>
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +	</element>
```suggestion
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<p><em>General Feat (Prerequisite: Level 4+, Dexterity or Constitution 13+)</em></p>
```suggestion
		<prerequisite>Level 4+, Dexterity or Constitution 13+</prerequisite>
		<description>
			<p class="flavor">General Feat (Prerequisite: Level 4+, Dexterity or Constitution 13+)</p>
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +	</element>
```suggestion
		<sheet>
			<description>When you take the Dash action on your turn, Difficult Terrain doesn't cost you extra movement for the rest of that turn. Additionally, Opportunity Attacks have Disadvantage against you.</description>
		</sheet>
		<rules>
			<select type="Ability Score Improvement" name="Ability Score Increase (Slasher)" supports="ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_FEAT_STRENGTH|ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_FEAT_CONSTITUTION" />
			<stat name="speed" value="10" bonus="speedy" alt="Speedy" />
		</rules>
	</element>
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +	</element>
```suggestion
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<p><em>General Feat (Prerequisite: Level 4+, Spellcasting or Pact Magic Feature)</em></p>
```suggestion
		<requirements>[level:4], (ID_INTERNAL_GRANTS_SPELLCASTING_FEATURE||ID_INTERNAL_GRANTS_PACT_MAGIC_FEATURE)</requirements>
		<supports>General</supports>
		<prerequisite>Level 4+, Spellcasting or Pact Magic Feature</prerequisite>
		<description>
			<p class="flavor">General Feat (Prerequisite: Level 4+, Spellcasting or Pact Magic Feature)</p>
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +	</element>
```suggestion
		<sheet>
			<description>
			Your spell attacks gain following benefits: Being within 5ft. of an enemy doesn't impose Disadvantage; you can also ignore Half Cover and Three-Quarters Cover. &#13;
			Additionally, when you cast a spell that has a range of at least 10ft. and requires you to make an attack roll, you can increase the spell's range by 60ft.</description>
		</sheet>
		<rules>
			<select type="Ability Score Improvement" name="Ability Score Increase (Spell Sniper)" supports="ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_FEAT_INTELLIGENCE|ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_FEAT_WISDOM|ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_FEAT_CHARISMA" />
		</rules>
	</element>
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +	</element>
```suggestion
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<p class="indent"><b><i>Minor Telekinesis.</i></b> You learn the <i>Mage Hand</i> spell. You can cast it without Verbal or Somatic components, you can make the spectral hand invisible, and its ran
```suggestion
		<prerequisite>Level 4+</prerequisite>
		<description>
			<p class="flavor">General Feat (Prerequisite: Level 4+)</p>
			<p>You gain the following benefits.</p>
			<p class="indent"><b><i>Ability Score Increase.</i></b> Increase your Intelligence, Wisdom, or Charisma score by 1, to a maximum of 20.</p>
			<p class="indent"><b><i>Minor Telekinesis.</i></b> You learn the <i>Mage Hand</i> spell. You can cast it without Verbal or Somatic components, you can make the spectral hand invisible, and its range and the distance it can be away from you both increase by 30 feet when you cast it. The spell's spellcasting ability is the ability increased by this feat.</p>
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<stat name="telekinetic:mage hand:dc" value="proficiency" />
```suggestion
			<select type="Feat Feature" name="Ability Score Increase (Telekinetic)" supports="PHB24 Telekinetic" />
			<grant type="Spell" id="ID_WOTC_PHB24_SPELL_MAGE_HAND" />
			<stat name="telekinetic:dc" value="8" bonus="base" />
			<stat name="telekinetic:dc" value="proficiency" bonus="proficiency" />
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			As a bonus action, you can try to telekinetically shove one creature you can see within 30 feet of you. When you do so, the target must succeed on a DC{{telekinetic:mage hand:dc}} Strength save or
```suggestion
		<supports>PHB24 Telekinetic</supports>
		<description>
			<p>Increase your Intelligence by 1, to a maximum of 20.</p>
		</description>
		<sheet alt="Telekinetic" action="Bonus Action">
			<description>You can try to telekinetically shove one creature you can see within 30ft. of you. When you do so, the target must succeed on a DC{{telekinetic:dc}} Strength save or be moved 5ft. toward you or away from you.&#13;
			Additionally, you know the Mage Hand cantrip, can cast it without Verbal or Somatic components, you can make the spectral hand Invisible, and its range and the distance it can be away from you both increase by 30ft. when you cast it. Your spellcasting ability for this spell is Intelligence.</description>
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<stat name="telekinetic:mage hand:dc" value="intelligence:modifier" />
```suggestion
			<stat name="telekinetic:dc" value="intelligence:modifier" bonus="ability" />
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			As a bonus action, you can try to telekinetically shove one creature you can see within 30 feet of you. When you do so, the target must succeed on a DC{{telekinetic:mage hand:dc}} Strength save or
```suggestion
		<supports>PHB24 Telekinetic</supports>
		<description>
			<p>Increase your Wisdom by 1, to a maximum of 20.</p>
		</description>
		<sheet alt="Telekinetic" action="Bonus Action">
			<description>You can try to telekinetically shove one creature you can see within 30ft. of you. When you do so, the target must succeed on a DC{{telekinetic:dc}} Strength save or be moved 5ft. toward you or away from you.&#13;
			Additionally, you know the Mage Hand cantrip, can cast it without Verbal or Somatic components, you can make the spectral hand Invisible, and its range and the distance it can be away from you both increase by 30ft. when you cast it. Your spellcasting ability for this spell is Wisdom.</description>
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<stat name="telekinetic:mage hand:dc" value="wisdom:modifier" />
```suggestion
			<stat name="telekinetic:dc" value="wisdom:modifier" bonus="ability" />
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			As a bonus action, you can try to telekinetically shove one creature you can see within 30 feet of you. When you do so, the target must succeed on a DC{{telekinetic:mage hand:dc}} Strength save or
```suggestion
		<supports>PHB24 Telekinetic</supports>
		<description>
			<p>Increase your Charisma by 1, to a maximum of 20.</p>
		</description>
		<sheet alt="Telekinetic" action="Bonus Action">
			<description>You can try to telekinetically shove one creature you can see within 30ft. of you. When you do so, the target must succeed on a DC{{telekinetic:dc}} Strength save or be moved 5ft. toward you or away from you.&#13;
			Additionally, you know the Mage Hand cantrip, can cast it without Verbal or Somatic components, you can make the spectral hand Invisible, and its range and the distance it can be away from you both increase by 30ft. when you cast it. Your spellcasting ability for this spell is Charisma.</description>
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<stat name="telekinetic:mage hand:dc" value="charisma:modifier" />
```suggestion
			<stat name="telekinetic:dc" value="charisma:modifier" bonus="ability" />
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<p><em>General Feat (Prerequisite: Level 4+)</em></p>
```suggestion
		<prerequisite>Level 4+</prerequisite>
		<description>
			<p class="flavor">General Feat (Prerequisite: Level 4+)</p>
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<select type="Feat Feature" name="Ability Score Increase (Telepathic)" supports="Telepathic" />
```suggestion
			<select type="Feat Feature" name="Ability Score Increase (Telepathic)" supports="PHB24 Telepathic" />
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			You can cast the detect thoughts spell, requiring no spell slot or components, and you must finish a long rest before you can cast this it this way again. Your spellcasting ability for this spell
```suggestion
		<supports>PHB24 Telepathic</supports>
		<description>
			<p>Increase your Intelligence by 1, to a maximum of 20.</p>
		</description>
		<sheet alt="Telepathic">
			<description>Once per Long Rest, you can cast the Detect Thoughts spell, without spell slot or components. You can also cast it using spell slots you have of the appropriate level. Your spellcasting ability for this spell is Intelligence. &#13;
			Additionally, you can speak telepathically to any creature you can see within 60ft. of you. Your telepathic utterances are in a language you know, and the creature understands you only if it knows that language. This effect doesn't give the creature the ability to respond to you telepathically.</description>
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			You can cast the detect thoughts spell, requiring no spell slot or components, and you must finish a long rest before you can cast this it this way again. Your spellcasting ability for this spell
```suggestion
		<supports>PHB24 Telepathic</supports>
		<description>
			<p>Increase your Wisdom by 1, to a maximum of 20.</p>
		</description>
		<sheet alt="Telepathic">
			<description>Once per Long Rest, you can cast the Detect Thoughts spell, without spell slot or components. You can also cast it using spell slots you have of the appropriate level. Your spellcasting ability for this spell is Wisdom. &#13;
			Additionally, you can speak telepathically to any creature you can see within 60ft. of you. Your telepathic utterances are in a language you know, and the creature understands you only if it knows that language. This effect doesn't give the creature the ability to respond to you telepathically.</description>
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			You can cast the detect thoughts spell, requiring no spell slot or components, and you must finish a long rest before you can cast this it this way again. Your spellcasting ability for this spell
```suggestion
		<supports>PHB24 Telepathic</supports>
		<description>
			<p>Increase your Charisma by 1, to a maximum of 20.</p>
		</description>
		<sheet alt="Telepathic">
			<description>Once per Long Rest, you can cast the Detect Thoughts spell, without spell slot or components. You can also cast it using spell slots you have of the appropriate level. Your spellcasting ability for this spell is Charisma. &#13;
			Additionally, you can speak telepathically to any creature you can see within 60ft. of you. Your telepathic utterances are in a language you know, and the creature understands you only if it knows that language. This effect doesn't give the creature the ability to respond to you telepathically.</description>
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<p><em>General Feat (Prerequisite: Level 4+, Spellcasting or Pact Magic Feature)</em></p>
```suggestion
		<requirements>[level:4], (ID_INTERNAL_GRANTS_SPELLCASTING_FEATURE||ID_INTERNAL_GRANTS_PACT_MAGIC_FEATURE)</requirements>
		<supports>General</supports>
		<prerequisite>Level 4+, Spellcasting or Pact Magic Feature</prerequisite>
		<description>
			<p class="flavor">General Feat (Prerequisite: Level 4+, Spellcasting or Pact Magic Feature)</p>
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +	</element>
```suggestion
		<sheet>
			<description>You have Advantage on saving throws to maintain Concentration. &#13;
			You can perform the Somatic components of spells even when you have weapons or a Shield in one or both hands. &#13;
			When a creature provokes an Opportunity Attack from you by leaving your reach, cast a spell at the creature as a Reaction, rather than making an Opportunity Attack. The spell must have a casting time of 1 action and must target only that creature.</description>
		</sheet>
		<rules>
			<select type="Ability Score Improvement" name="Ability Score Increase (War Caster)" supports="ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_FEAT_INTELLIGENCE|ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_FEAT_WISDOM|ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_FEAT_CHARISMA" />
		</rules>
	</element>
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +	</element>
```suggestion
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<p><em>General Feat (Prerequisite: Level 4+)</em></p>
```suggestion
		<prerequisite>Level 4+</prerequisite>
		<description>
			<p class="flavor">General Feat (Prerequisite: Level 4+)</p>
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +			<select type="Class Feature" name="Weapon Mastery" supports="Weapon Mastery"/>
```suggestion
			<p><b>Note:</b> Selection for Mastery appears under the <u>CLASS</u> sub-menu.</p>
		</description>
		<sheet display="false" />
		<rules>
			<select type="Ability Score Improvement" name="Ability Score Increase (Weapon Master)" supports="ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_FEAT_STRENGTH|ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_FEAT_DEXTERITY" />
			<grant type="Class Feature" id="ID_WOTC_PHB24_CLASS_FEATURE_WEAPON_MASTER" />
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-general.xml
> +	</element>
```suggestion
	<!-- sub-feature for the Feat, which allows selected element to appear with the sheet description of the Feat -->
	<element name="Weapon Master" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_WEAPON_MASTER">
		<compendium display="false" />
		<sheet>
			<description>You can use the mastery property of one kind of Simple or Martial weapon you are proficient with. Whenever you finish a Long Rest, you can change the kind of weapon to another eligible kind.</description>
		</sheet>
		<rules>
			<select type="Class Feature" name="Weapon Mastery (Feat)" supports="Weapon Mastery"/>
		</rules>
	</element>
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-fighting-styles.xml
> +		<name></name>
```suggestion
		<name>Fighting Style Category Feats</name>
		<description>The Fighting Style Category Feats from the Player’s Handbook 2024.</description>
		<author url="https://dndstore.wizards.com/us/en/product/1001494/2024-player-s-handbook-digital-plus-physical-bundle">Wizards of the Coast</author>
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-fighting-styles.xml
> +		</sheet>
```suggestion
		<requirements>ID_INTERNAL_GRANTS_FIGHTING_STYLE_FEATURE</requirements>
		<supports>Fighting Style</supports>
		<prerequisite>Fighting Style Feature</prerequisite>
		<description>
    		<p class="flavor">Fighting Style Feat (Prerequisite: Fighting Style Feature)</p>
			<p>You gain a +2 bonus to attack rolls you make with Ranged weapons.</p>
		</description>
		<sheet display="false" />
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-fighting-styles.xml
> +    <element name="Blind Fighting" type="Feat" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_FEAT_BLIND_FIGHTING">
```suggestion
	</element>

    <element name="Blind Fighting" type="Feat" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_FEAT_BLIND_FIGHTING">
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-fighting-styles.xml
> +		</sheet>
```suggestion
		<requirements>ID_INTERNAL_GRANTS_FIGHTING_STYLE_FEATURE</requirements>
		<supports>Fighting Style</supports>
		<prerequisite>Fighting Style Feature</prerequisite>
		<description>
    		<p class="flavor">Fighting Style Feat (Prerequisite: Fighting Style Feature)</p>
			<p>You have Blindsight with a range of 10 feet.</p>
		</description>
		<sheet display="false" />
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-fighting-styles.xml
> +	</element>
```suggestion
	</element>

```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-fighting-styles.xml
> +		</sheet>
```suggestion
		<requirements>ID_INTERNAL_GRANTS_FIGHTING_STYLE_FEATURE</requirements>
		<supports>Fighting Style</supports>
		<prerequisite>Fighting Style Feature</prerequisite>
		<description>
    		<p class="flavor">Fighting Style Feat (Prerequisite: Fighting Style Feature)</p>
			<p>While you’re wearing Light, Medium, or Heavy armor, you gain a +1 bonus to Armor Class.</p>
		</description>
		<sheet display="false" />
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-fighting-styles.xml
> +	</element>
```suggestion
	</element>

```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-fighting-styles.xml
> +    		<p><em>Fighting Style Feat (Prerequisite: Fighting Style Feature)</em></p>
```suggestion
		<requirements>ID_INTERNAL_GRANTS_FIGHTING_STYLE_FEATURE</requirements>
		<supports>Fighting Style</supports>
		<prerequisite>Fighting Style Feature</prerequisite>
		<description>
    		<p class="flavor">Fighting Style Feat (Prerequisite: Fighting Style Feature)</p>
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-fighting-styles.xml
> +	</element>
```suggestion
	</element>

```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-fighting-styles.xml
> +    		<p><em>Fighting Style Feat (Prerequisite: Fighting Style Feature)</em></p>
```suggestion
		<requirements>ID_INTERNAL_GRANTS_FIGHTING_STYLE_FEATURE</requirements>
		<supports>Fighting Style</supports>
		<prerequisite>Fighting Style Feature</prerequisite>
		<description>
    		<p class="flavor">Fighting Style Feat (Prerequisite: Fighting Style Feature)</p>
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-fighting-styles.xml
> +	</element>
```suggestion
	</element>

```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-fighting-styles.xml
> +			<description>When a creature you can see hits another creature within 5feet of you with an attack roll, you can take a Reaction to reduce the damage dealt to the target by 1d10+{{proficiency}}. Yo
```suggestion
		<requirements>ID_INTERNAL_GRANTS_FIGHTING_STYLE_FEATURE</requirements>
		<supports>Fighting Style</supports>
		<prerequisite>Fighting Style Feature</prerequisite>
		<description>
    		<p class="flavor">Fighting Style Feat (Prerequisite: Fighting Style Feature)</p>
			<p>When a creature you can see hits another creature within 5 feet of you with an attack roll, you can take a Reaction to reduce the damage dealt to the target by 1d10 plus your Proficiency Bonus. You must be holding a Shield or a Simple or Martial weapon to use this Reaction.</p>
		</description>
		<sheet action="Reaction">
			<description>When a creature you can see hits another creature within 5ft. of you with an attack roll, you can reduce the damage dealt to the target by 1d10+{{proficiency}}. You must be holding a Shield or a Simple or Martial weapon.</description>
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-fighting-styles.xml
> +	</element>
```suggestion
	</element>

```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-fighting-styles.xml
> +			<description>When a creature you can see attacks a target other than you that is within 5ft of you, you can take a Reaction to impose disadvantage on the attack roll and all other attack rolls aga
```suggestion
		<requirements>ID_INTERNAL_GRANTS_FIGHTING_STYLE_FEATURE</requirements>
		<supports>Fighting Style</supports>
		<prerequisite>Fighting Style Feature</prerequisite>
		<description>
    		<p class="flavor">Fighting Style Feat (Prerequisite: Fighting Style Feature)</p>
			<p>When a creature you can see attacks a target other than you that is within 5 feet of you, you can take a Reaction to interpose your Shield if you're holding one. You impose Disadvantage on the triggering attack roll and all other attack rolls against the target until the start of your next turn if you remain within 5 feet of the target.</p>
		</description>
		<sheet action="Reaction">
			<description>When a creature you can see attacks a target other than you that is within 5ft. of you, you can impose Disadvantage on the attack roll and all other attack rolls against the target until the start of your next turn if you remain within 5ft. of the target. You must be holding a Shield.</description>
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-fighting-styles.xml
> +	</element>
```suggestion
	</element>

```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-fighting-styles.xml
> +			<p>When you hit with a ranged attack roll using a weapon that has the Thrown property, you gain a +2 bonus to the damage roll,</p>
```suggestion
		<requirements>ID_INTERNAL_GRANTS_FIGHTING_STYLE_FEATURE</requirements>
		<supports>Fighting Style</supports>
		<prerequisite>Fighting Style Feature</prerequisite>
		<description>
    		<p class="flavor">Fighting Style Feat (Prerequisite: Fighting Style Feature)</p>
			<p>When you hit with a ranged attack roll using a weapon that has the Thrown property, you gain a +2 bonus to the damage roll.</p>
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-fighting-styles.xml
> +	</element>
```suggestion
	</element>

```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-fighting-styles.xml
> +			<p>When you make an extra attack as a resuit of using a weapon that has the Light property, you can add your ability modifier to the damage of that attack if you aren't already adding it to the da
```suggestion
		<requirements>ID_INTERNAL_GRANTS_FIGHTING_STYLE_FEATURE</requirements>
		<supports>Fighting Style</supports>
		<prerequisite>Fighting Style Feature</prerequisite>
		<description>
    		<p class="flavor">Fighting Style Feat (Prerequisite: Fighting Style Feature)</p>
			<p>When you make an extra attack as a result of using a weapon that has the Light property, you can add your ability modifier to the damage of that attack if you aren't already adding it to the damage.</p>
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-fighting-styles.xml
> +	</element>
```suggestion
	</element>

```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-fighting-styles.xml
> +			<description>When you hit with your Unarmed Strike and deal damage, you can deal 1d{{unarmed strike:dice}}+{{strength:modifier}} Bludgeoning damage instead of the normal damage of an Unarmed Strik
```suggestion
        <requirements>ID_INTERNAL_GRANTS_FIGHTING_STYLE_FEATURE</requirements>
		<supports>Fighting Style</supports>
		<prerequisite>Fighting Style Feature</prerequisite>
		<description>
    		<p class="flavor">Fighting Style Feat (Prerequisite: Fighting Style Feature)</p>
			<p>When you hit with your Unarmed Strike and deal damage, you can deal Bludgeoning damage equal to 1d6 plus your Strength modifier instead of the normal damage of an Unarmed Strike. If you aren't holding any weapons or a Shield when you make the attack roll, the d6 becomes a d8.</p>
            <p class="indent">At the start of each of your turns, you can deal 1d4 Bludgeoning damage to one creature Grappled by you.</p>
		</description>
		<sheet>
			<description>When you hit with your Unarmed Strike and deal damage, you can deal 1d6 (or 1d8, if aren't holding any weapons or a Shield) + {{strength:modifier}} Bludgeoning damage instead of the normal damage of an Unarmed Strike. &#13;
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-epic-boons.xml
> +			<p><em>Epic Boon Feat (Prerequisite: Level 19+)</em></p>
```suggestion
		<supports>Epic Boon</supports>
		<prerequisite>Level 19+</prerequisite>
		<description>
			<p class="flavor">Epic Boon Feat (Prerequisite: Level 19+)</p>
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-epic-boons.xml
> +		<sheet usage="1/Turn">
```suggestion
		<sheet usage="1/Round">
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-epic-boons.xml
> +	</element>
```suggestion
	</element>

```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-epic-boons.xml
> +			<p><em>Epic Boon Feat (Prerequisite: Level 19+)</em></p>
```suggestion
		<supports>Epic Boon</supports>
		<prerequisite>Level 19+</prerequisite>
		<description>
			<p class="flavor">Epic Boon Feat (Prerequisite: Level 19+)</p>
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-epic-boons.xml
> +			<description>Immediately after you take the Attack action or the Magic action, you can teleport up to 30ft to an unoccupied space you can see.</description>
```suggestion
			<description>Immediately after you take the Attack action or the Magic action, you can teleport up to 30ft. to an unoccupied space you can see.</description>
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-epic-boons.xml
> +	</element>
```suggestion
	</element>

```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-epic-boons.xml
> +			<p><em>Epic Boon Feat (Prerequisite: Level 19+)</em></p>
```suggestion
		<supports>Epic Boon</supports>
		<prerequisite>Level 19+</prerequisite>
		<description>
			<p class="flavor">Epic Boon Feat (Prerequisite: Level 19+)</p>
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-epic-boons.xml
> +			<stat name="savingthrow:dc" value="constitution:modifier" bonus="ability" />
```suggestion
			<description>When you take damage of one of the types chosen for this Boon, you can direct damage of the same type toward another creature you can see within 60ft. of yourself that isn't behind Total Cover. If you do so, that creature must succeed on a DC{{energy redirection:dc}} Dexterity saving throw or take 2d12+{{constitution:modifier}} damage.</description>
		</sheet>
		<rules>
			<select type="Ability Score Improvement" name="Ability Score Increase (Boon of Energy Resistance)" supports="Boon Ability Score Increase" />
			<select type="Feat Feature" name="Resistance Type (Boon of Energy Resistance)" supports="PHB24 Boon of Energy Resistance" number="2" />
			<stat name="energy redirection:dc" value="8" bonus="base" />
            <stat name="energy redirection:dc" value="proficiency" bonus="proficiency" />
			<stat name="energy redirection:dc" value="constitution:modifier" bonus="ability" />
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-epic-boons.xml
> +		<description />
```suggestion
	<element name="Acid" type="Feat Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_FEAT_FEATURE_BOON_OF_ENERGY_RESISTANCE_ACID">
		<compendium display="false" />
		<supports>PHB24 Boon of Energy Resistance</supports>
		<description>
			<p>You gain Resistance to Acid damage. Additionally, when you take Acid damage, you can take a Reaction to to direct damage of the same type toward another creature you can see within 60 feet of yourself that isn't behind Total Cover.</p>
		</description>
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-epic-boons.xml
> +		<description />
```suggestion
	<element name="Cold" type="Feat Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_FEAT_FEATURE_BOON_OF_ENERGY_RESISTANCE_COLD">
		<compendium display="false" />
		<supports>PHB24 Boon of Energy Resistance</supports>
		<description>
			<p>You gain Resistance to Cold damage. Additionally, when you take Cold damage, you can take a Reaction to to direct damage of the same type toward another creature you can see within 60 feet of yourself that isn't behind Total Cover.</p>
		</description>
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-epic-boons.xml
> +		<description />
```suggestion
	<element name="Fire" type="Feat Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_FEAT_FEATURE_BOON_OF_ENERGY_RESISTANCE_FIRE">
		<compendium display="false" />
		<supports>PHB24 Boon of Energy Resistance</supports>
		<description>
			<p>You gain Resistance to Fire damage. Additionally, when you take Fire damage, you can take a Reaction to to direct damage of the same type toward another creature you can see within 60 feet of yourself that isn't behind Total Cover.</p>
		</description>
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-epic-boons.xml
> +		<description />
```suggestion
	<element name="Lightning" type="Feat Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_FEAT_FEATURE_BOON_OF_ENERGY_RESISTANCE_LIGHTNING">
		<compendium display="false" />
		<supports>PHB24 Boon of Energy Resistance</supports>
		<description>
			<p>You gain Resistance to Lightning damage. Additionally, when you take Lightning damage, you can take a Reaction to to direct damage of the same type toward another creature you can see within 60 feet of yourself that isn't behind Total Cover.</p>
		</description>
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-epic-boons.xml
> +		<description />
```suggestion
	<element name="Necrotic" type="Feat Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_FEAT_FEATURE_BOON_OF_ENERGY_RESISTANCE_NECROTIC">
		<compendium display="false" />
		<supports>PHB24 Boon of Energy Resistance</supports>
		<description>
			<p>You gain Resistance to Necrotic damage. Additionally, when you take Necrotic damage, you can take a Reaction to to direct damage of the same type toward another creature you can see within 60 feet of yourself that isn't behind Total Cover.</p>
		</description>
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-epic-boons.xml
> +		<description />
```suggestion
	<element name="Poison" type="Feat Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_FEAT_FEATURE_BOON_OF_ENERGY_RESISTANCE_POISON">
		<compendium display="false" />
		<supports>PHB24 Boon of Energy Resistance</supports>
		<description>
			<p>You gain Resistance to Poison damage. Additionally, when you take Poison damage, you can take a Reaction to to direct damage of the same type toward another creature you can see within 60 feet of yourself that isn't behind Total Cover.</p>
		</description>
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-epic-boons.xml
> +		<description />
```suggestion
	<element name="Psychic" type="Feat Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_FEAT_FEATURE_BOON_OF_ENERGY_RESISTANCE_PSYCHIC">
		<compendium display="false" />
		<supports>PHB24 Boon of Energy Resistance</supports>
		<description>
			<p>You gain Resistance to Psychic damage. Additionally, when you take Psychic damage, you can take a Reaction to to direct damage of the same type toward another creature you can see within 60 feet of yourself that isn't behind Total Cover.</p>
		</description>
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-epic-boons.xml
> +		<description />
```suggestion
	<element name="Radiant" type="Feat Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_FEAT_FEATURE_BOON_OF_ENERGY_RESISTANCE_RADIANT">
		<compendium display="false" />
		<supports>PHB24 Boon of Energy Resistance</supports>
		<description>
			<p>You gain Resistance to Radiant damage. Additionally, when you take Radiant damage, you can take a Reaction to to direct damage of the same type toward another creature you can see within 60 feet of yourself that isn't behind Total Cover.</p>
		</description>
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-epic-boons.xml
> +		<description />
```suggestion
	<element name="Thunder" type="Feat Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_FEAT_FEATURE_BOON_OF_ENERGY_RESISTANCE_THUNDER">
		<compendium display="false" />
		<supports>PHB24 Boon of Energy Resistance</supports>
		<description>
			<p>You gain Resistance to Thunder damage. Additionally, when you take Thunder damage, you can take a Reaction to to direct damage of the same type toward another creature you can see within 60 feet of yourself that isn't behind Total Cover.</p>
		</description>
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-epic-boons.xml
> +			<p><em>Epic Boon Feat (Prerequisite: Level 19+)</em></p>
```suggestion

	<element name="Boon of Fate" type="Feat" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_FEAT_BOON_OF_FATE">
		<requirements>[level:19]</requirements>
		<supports>Epic Boon</supports>
		<prerequisite>Level 19+</prerequisite>
		<description>
			<p class="flavor">Epic Boon Feat (Prerequisite: Level 19+)</p>
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-epic-boons.xml
> +			<description>When you or another creature within 60 feet of you succeeds on or fails a D20 Test, you can roll 2d4 and apply the total rolled as a bonus or penalty to the d20 roll.</description>
```suggestion
			<p class="indent"><b><i>Improve Fate.</i></b> When you or another creature within 60 feet of you succeeds on or fails a D20 Test, you can roll 2d4 and apply the total rolled as a bonus or penalty to the d20 roll. Once you use this benefit, you can't use it again until you roll Initiative or finish a Short or Long Rest.</p>
		</description>
		<sheet usage="1/Short Rest">
			<description>When you or another creature within 60ft. of you succeeds on or fails a D20 Test, you can roll 2d4 and apply the total rolled as a bonus or penalty to the d20 roll. You also regain a use of this feature whenever you roll Initiative.</description>
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-epic-boons.xml
> +	</element>
```suggestion
	</element>

```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-epic-boons.xml
> +			<p><em>Epic Boon Feat (Prerequisite: Level 19+)</em></p>
```suggestion
		<supports>Epic Boon</supports>
		<prerequisite>Level 19+</prerequisite>
		<description>
			<p class="flavor">Epic Boon Feat (Prerequisite: Level 19+)</p>
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-epic-boons.xml
> +	</element>
```suggestion
	</element>

```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-epic-boons.xml
> +			<p><em>Epic Boon Feat (Prerequisite: Level 19+)</em></p>
```suggestion
		<supports>Epic Boon</supports>
		<prerequisite>Level 19+</prerequisite>
		<description>
			<p class="flavor">Epic Boon Feat (Prerequisite: Level 19+)</p>
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-epic-boons.xml
> +	</element>
```suggestion
		<sheet display="false" />
		<rules>
			<select type="Feat Feature" name="Ability Score Increase (Boon of Irresistible Offense)" supports="ID_WOTC_PHB24_FEAT_BOON_OF_IRRESISTIBLE_OFFENSE_STRENGTH|ID_WOTC_PHB24_FEAT_BOON_OF_IRRESISTIBLE_OFFENSE_DEXTERITY" />
		</rules>
	</element>
	<element name="Strength" type="Feat Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_FEAT_BOON_OF_IRRESISTIBLE_OFFENSE_STRENGTH">
		<compendium display="false" />
		<description>
			<p>Increase your Strength by 1, to a maximum of 30. Additionally, when you roll a 20 on the attack roll, you deal extra damage equal to your Strength score.</p>
		</description>
		<sheet alt="Boon of Irresistible Offense">
			<description>The Bludgeoning, Piercing, and Slashing damage you deal always ignores Resistance. &#13;
			Additionally, whenever you roll a 20 on the d20 for an attack roll, you can deal {{overwhelming strike:damage}} extra damage of the same type as the attack's type to the target.</description>
		</sheet>
		<rules>
			<stat name="overwhelming strike:damage" value="strength:score" bonus="ability" />
		</rules>
	</element>
	<element name="Dexterity" type="Feat Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_FEAT_BOON_OF_IRRESISTIBLE_OFFENSE_DEXTERITY">
		<compendium display="false" />
		<description>
			<p>Increase your Dexterity by 1, to a maximum of 30. Additionally, when you roll a 20 on the attack roll, you deal extra damage equal to your Dexterity score.</p>
		</description>
		<sheet alt="Boon of Irresistible Offense">
			<description>The Bludgeoning, Piercing, and Slashing damage you deal always ignores Resistance. &#13;
			Additionally, whenever you roll a 20 on the d20 for an attack roll, you can deal {{overwhelming strike:damage}} extra damage of the same type as the attack's type to the target.</description>
		</sheet>
		<rules>
			<stat name="overwhelming strike:damage" value="dexterity:score" bonus="ability" />
		</rules>
	</element>

```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-epic-boons.xml
> +			<p><em>Epic Boon Feat (Prerequisite: Level 19+)</em></p>
```suggestion
		<supports>Epic Boon</supports>
		<prerequisite>Level 19+</prerequisite>
		<description>
			<p class="flavor">Epic Boon Feat (Prerequisite: Level 19+)</p>
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-epic-boons.xml
> +			You have a pool of 10d10s. As a Bonus Action, you can expend dice from the pool, roll those dice, and regain a number of Hit Points equal to the roll's total. You regain all the expended dice when
```suggestion
		<sheet usage="1/Long Rest">
			<description>When you would be reduced to 0 Hit Points, you can drop to 1 Hit Point instead and regain a number of Hit Points equal to half your Hit Point maximum. &#13;
			Additionally, you have a pool of 10d10s. As a Bonus Action, you can expend dice from the pool, roll those dice, and regain a number of Hit Points equal to the roll's total. You regain all the expended dice when you finish a Long Rest.</description>
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-epic-boons.xml
> +	</element>
```suggestion
	</element>

```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-epic-boons.xml
> +			<p><em>Epic Boon Feat (Prerequisite: Level 19+)</em></p>
```suggestion
		<supports>Epic Boon</supports>
		<prerequisite>Level 19+</prerequisite>
		<description>
			<p class="flavor">Epic Boon Feat (Prerequisite: Level 19+)</p>
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-epic-boons.xml
> +		</sheet>
```suggestion
		<sheet display="false" />
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-epic-boons.xml
> +			<select type="Proficiency" name="Expertise (Boon of Skill)" supports="ID_INTERNAL_SUPPORT_EXPERTISE"/>
```suggestion
			<select type="Proficiency" name="Expertise (Boon of Skill)" supports="Expertise" />
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-epic-boons.xml
> +	</element>
```suggestion
	</element>

```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-epic-boons.xml
> +			<p><em>Epic Boon Feat (Prerequisite: Level 19+)</em></p>
```suggestion
		<supports>Epic Boon</supports>
		<prerequisite>Level 19+</prerequisite>
		<description>
			<p class="flavor">Epic Boon Feat (Prerequisite: Level 19+)</p>
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-epic-boons.xml
> +	</element>
```suggestion
	</element>

```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-epic-boons.xml
> +			<p class="indent"><b><i>Ability Score Increase.</i></b> Increase e your Intelligence, Wisdom, or Charisma score by 1, to a maximum of 30.</p>
```suggestion
		<requirements>[level:19],ID_INTERNAL_GRANTS_SPELLCASTING_FEATURE</requirements>
		<supports>Epic Boon</supports>
		<prerequisite>Level 19+, Spellcasting Feature</prerequisite>
		<description>
			<p class="flavor">Epic Boon Feat (Prerequisite: Level 19+, Spellcasting Feature)</p>
			<p>You gain the following benefits.</p>
			<p class="indent"><b><i>Ability Score Increase.</i></b> Increase your Intelligence, Wisdom, or Charisma score by 1, to a maximum of 30.</p>
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-epic-boons.xml
> +	</element>
```suggestion
			<select type="Ability Score Improvement" name="Ability Score Increase (Boon of Spell Recall)" supports="ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_BOON_INTELLIGENCE|ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_BOON_WISDOM|ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_BOON_CHARISMA" />
		</rules>
	</element>

```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-epic-boons.xml
> +			<p><em>Epic Boon Feat (Prerequisite: Level 19+)</em></p>
```suggestion
		<supports>Epic Boon</supports>
		<prerequisite>Level 19+</prerequisite>
		<description>
			<p class="flavor">Epic Boon Feat (Prerequisite: Level 19+)</p>
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-epic-boons.xml
> +			<description>While within Dim Light or Darkness, you have Resistance to all damage except Psychic and Radiant, and as a Bonus Action, you can give yourself the invisible condition. The condition e
```suggestion
		<sheet action="Bonus Action">
			<description>While within Dim Light or Darkness, you can become Invisible. The condition ends on you immediately after you take an action, a Bonus Action, or a Reaction. &#13;
			Additionally, while within Dim Light or Darkness, you have Resistance to all damage except Psychic and Radiant.</description>
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-epic-boons.xml
> +	</element>
```suggestion
	</element>

```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-epic-boons.xml
> +			<p><em>Epic Boon Feat (Prerequisite: Level 19+)</em></p>
```suggestion
		<supports>Epic Boon</supports>
		<prerequisite>Level 19+</prerequisite>
		<description>
			<p class="flavor">Epic Boon Feat (Prerequisite: Level 19+)</p>
```

2025-10-03 11:54 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-epic-boons.xml
> +		</sheet>
```suggestion
		<sheet display="false" />
```

2025-10-03 11:55 UTC, NickVendel requested changes
Part 2

2025-10-03 15:13 UTC, Tel0k commented on core/players-handbook-2024/feats/feats-general.xml
> +			<select type="Spell" name="1st-level Spell (Ritual Caster)" supports="Ritual,1" level="17" />
Nick, why the last 2 selections? PB can't go above 6, aren't those unnecessary?

2025-11-06 18:08 UTC, NickVendel commented on core/players-handbook-2024/feats/feats-origin.xml
> +			<stat name="hp" value="tough:hp" bonus="tough" />
prevents stacking of Tough feats via Additional Feats section.
```suggestion
			<stat name="hp" value="level" bonus="primary"/>
			<stat name="hp" value="level" bonus="secondary"/>
```

2025-12-04 07:18 UTC, tregolani commented on core/players-handbook-2024/feats/feats-general.xml
> +			<select type="Ability Score Improvement" name="Ability Score Increase (Slasher)" supports="ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_FEAT_STRENGTH|ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_FEAT_CONSTITUTI
```suggestion
			<select type="Ability Score Improvement" name="Ability Score Increase (Speedy)" supports="ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_FEAT_DEXTERITY|ID_INTERNAL_ABILITY_SCORE_IMPROVEMENT_FEAT_CONSTITUTION" />
```

2026-01-20 23:18 UTC, FreshRoyal approved these changes

2026-02-01 23:41 UTC, merged