[PHB24] Updated Monk file, plus Monk and Fighter subclasses
AuroraLegacy/elements pull request #290
Opened 2024-11-19 23:26 UTC by tregolani

Created the subclass files for Fighter and Monk, as well as an updated version of the monk class file, based on Zencha's file in their PR.

2025-04-15 18:44 UTC, NickVendel requested changes
Fighter Subclasses review

2025-04-15 18:44 UTC, NickVendel commented on core/players-handbook-2024/archetypes/fighter-battle-master.xml
> +		<supports>Martial Archetype</supports>
```suggestion
		<supports>Fighter Subclass</supports>
```

2025-04-15 18:44 UTC, NickVendel commented on core/players-handbook-2024/archetypes/fighter-battle-master.xml
> +		</description>
```suggestion
			<div element="ID_WOTC_PHB24_ARCHETYPE_FEATURE_FIGHTER_BATTLE_MASTER_ULTIMATE_COMBAT_SUPERIORITY"/>
			<div element="ID_WOTC_PHB24_INFORMATION_FIGHTER_BATTLE_MASTER_MANEUVER_OPTIONS"/>
		</description>
```

2025-04-15 18:44 UTC, NickVendel commented on core/players-handbook-2024/archetypes/fighter-battle-master.xml
> +			You have {{superiority dice:amount}} Superiority Dice which are d{{superiority dice:size}}s. Your DC is {{superiority dice:dc}}.</description>
```suggestion
			<p class="indent"><strong><em>Maneuvers.</em></strong> You learn three maneuvers of your choice from the "Maneuvers Options" section later in this subclass's description. Many maneuvers enhance an attack in some way. You can use only one maneuver per attack.</p>
			<p class="indent">You learn two additional maneuvers of your choice when you reach Fighter levels 7, 10, and 15. Each time you learn new maneuvers, you can also replace one maneuver you know with a different one.</p>
			<p class="indent"><strong><em>Superiority Dice.</em></strong> You have four Superiority Dice, which are d8s. A Superiority Die is expended when you use it. You regain all expended Superiority Dice when you finish a Short or Long Rest.</p>
			<p class="indent">You gain an additional Superiority Die when you reach Fighter levels 7 (five dice total) and 15 (six dice total).</p>
			<p class="indent"><strong><em>Saving Throws.</em></strong> If a maneuver requires a saving throw, the DC equals 8 plus your Strength or Dexterity modifier (your choice) and Proficiency Bonus.</p>
		</description>
		<sheet alt="Combat Superiority" usage="{{combat superiority:dice amount}}d{{combat superiority:dice size}}/Short Rest">
			<description>You can use only one maneuver per attack. You can replace one maneuver you know with a different one when you reach levels 7, 10, and 15.</description>
```

2025-04-15 18:44 UTC, NickVendel commented on core/players-handbook-2024/archetypes/fighter-battle-master.xml
> +			<select type="Archetype Feature" name="Combat Superiority (Level 15)" supports="Maneuver,Battle Master" number="2" level="15" />
```suggestion
			<stat name="combat superiority:dice amount" value="4" bonus="base" />
			<stat name="combat superiority:dice amount" value="5" bonus="base" level="7" />
			<stat name="combat superiority:dice amount" value="6" bonus="base" level="15" />
			<stat name="combat superiority:dice size" value="8" bonus="base"/>
			<stat name="combat superiority:dc:ability" value="strength:modifier" bonus="base" />
			<stat name="combat superiority:dc:ability" value="dexterity:modifier" bonus="base" />
			<stat name="combat superiority:dc" value="8" bonus="base"/>
			<stat name="combat superiority:dc" value="proficiency" bonus="proficiency"/>
			<stat name="combat superiority:dc" value="combat superiority:dc:ability" bonus="ability"/>

			<select type="Archetype Feature" name="Maneuver (Combat Superiority 3)" supports="Maneuver, Battle Master" number="3" />
			<select type="Archetype Feature" name="Maneuver (Combat Superiority 7)" supports="Maneuver, Battle Master" number="2" level="7" />
			<select type="Archetype Feature" name="Maneuver (Combat Superiority 10)" supports="Maneuver, Battle Master" number="2" level="10" />
			<select type="Archetype Feature" name="Maneuver (Combat Superiority 15)" supports="Maneuver, Battle Master" number="2" level="15" />
```

2025-04-15 18:44 UTC, NickVendel commented on core/players-handbook-2024/archetypes/fighter-battle-master.xml
> +	<element name="Level 3: Student of War" type="Archetype Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ARCHETYPE_FEATURE_FIGHTER_BATTLE_MASTER_STUDENT_OF_WAR">
```suggestion
	</element>

	<element name="Level 3: Student of War" type="Archetype Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ARCHETYPE_FEATURE_FIGHTER_BATTLE_MASTER_STUDENT_OF_WAR">
```

2025-04-15 18:44 UTC, NickVendel commented on core/players-handbook-2024/archetypes/fighter-battle-master.xml
> +			You can also restore a use of the feature by expending one Superiority Die (no action required).</description>
```suggestion
		<sheet alt="Know Your Enemy" action="Bonus Action" usage="1/Long Rest">
			<description>Choose one creature you can see within 30 feet of yourself. You learn what Immunities, Resistances, and Vulnerabilities that creature has. &#13;
			You can restore a use of the feature by expending one Superiority Die.</description>
```

2025-04-15 18:44 UTC, NickVendel commented on core/players-handbook-2024/archetypes/fighter-battle-master.xml
> +			<stat name="superiority dice:size" value="10" bonus="size"/>
```suggestion
			<stat name="combat superiority:dice size" value="10" bonus="base"/>
```

2025-04-15 18:44 UTC, NickVendel commented on core/players-handbook-2024/archetypes/fighter-battle-master.xml
> +		<sheet usage="1/Turn" alt="Relentless">
```suggestion
		<sheet alt="Relentless" usage="1/Turn">
```

2025-04-15 18:44 UTC, NickVendel commented on core/players-handbook-2024/archetypes/fighter-battle-master.xml
> +			<stat name="superiority dice:size" value="12" bonus="size"/>
```suggestion
			<stat name="combat superiority:dice size" value="12" bonus="base"/>
```

2025-04-15 18:44 UTC, NickVendel commented on core/players-handbook-2024/archetypes/fighter-battle-master.xml
> +
```suggestion

	<element name="Maneuver Options" type="Information" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_INFORMATION_FIGHTER_BATTLE_MASTER_MANEUVER_OPTIONS">
		<description>
			<p>The maneuvers are presented here in alphabetical order.</p>
			<p class="indent"><i><b>Ambush.</b></i> When you make a Dexterity (Stealth) check or an Initiative roll, you can expend one Superiority Die and add the die to the roll, unless you have the Incapacitated condition.</p>
			<p class="indent"><i><b>Bait and Switch.</b></i> When you’re within 5 feet of a creature on your turn, you can expend one Superiority Die and switch places with that creature, provided you spend at least 5 feet of movement and the creature is willing and doesn’t have the Incapacitated condition. This movement doesn’t provoke Opportunity Attacks.</p>
			<p class="indent">Roll the Superiority Die. Until the start of your next turn, you or the other creature (your choice) gains a bonus to AC equal to the number rolled.</p>
			<p class="indent"><i><b>Commander’s Strike.</b></i> When you take the Attack action on your turn, you can replace one of your attacks to direct one of your companions to strike. When you do so, choose a willing creature who can see or hear you and expend one Superiority Die. That creature can immediately use its Reaction to make one attack with a weapon or an Unarmed Strike, adding the Superiority Die to the attack’s damage roll on a hit.</p>
			<p class="indent"><i><b>Commanding Presence.</b></i> When you make a Charisma (Intimidation, Performance, or Persuasion) check, you can expend one Superiority Die and add that die to the roll.</p>
			<p class="indent"><i><b>Disarming Attack.</b></i> When you hit a creature with an attack roll, you can expend one Superiority Die to attempt to disarm the target. Add the Superiority Die roll to the attack’s damage roll. The target must succeed on a Strength saving throw or drop one object of your choice that it’s holding, with the object landing in its space.</p>
			<p class="indent"><i><b>Distracting Strike.</b></i> When you hit a creature with an attack roll, you can expend one Superiority Die to distract the target. Add the Superiority Die roll to the attack’s damage roll. The next attack roll against the target by an attacker other than you has Advantage if the attack is made before the start of your next turn.</p>
			<p class="indent"><i><b>Evasive Footwork.</b></i> As a Bonus Action, you can expend one Superiority Die and take the Disengage action. You also roll the die and add the number rolled to your AC until the start of your next turn.</p>
			<p class="indent"><i><b>Feinting Attack.</b></i> As a Bonus Action, you can expend one Superiority Die to feint, choosing one creature within 5 feet of yourself as your target. You have Advantage on your next attack roll against that target this turn. If that attack hits, add the Superiority Die to the attack’s damage roll.</p>
			<p class="indent"><i><b>Goading Attack.</b></i> When you hit a creature with an attack roll, you can expend one Superiority Die to attempt to goad the target into attacking you. Add the Superiority Die to the attack’s damage roll. The target must succeed on a Wisdom saving throw or have Disadvantage on attack rolls against targets other than you until the end of your next turn.</p>
			<p class="indent"><i><b>Lunging Attack.</b></i> As a Bonus Action, you can expend one Superiority Die and take the Dash action. If you move at least 5 feet in a straight line immediately before hitting with a melee attack as part of the Attack action on this turn, you can add the Superiority Die to the attack’s damage roll.</p>
			<p class="indent"><i><b>Maneuvering Attack.</b></i> When you hit a creature with an attack roll, you can expend one Superiority Die to maneuver one of your comrades into another position. Add the Superiority Die roll to the attack’s damage roll, and choose a willing creature who can see or hear you. That creature can use its Reaction to move up to half its Speed without provoking an Opportunity Attack from the target of your attack.</p>
			<p class="indent"><i><b>Menacing Attack.</b></i> When you hit a creature with an attack roll, you can expend one Superiority Die to attempt to frighten the target. Add the Superiority Die to the attack’s damage roll. The target must succeed on a Wisdom saving throw or have the Frightened condition until the end of your next turn.</p>
			<p class="indent"><i><b>Parry.</b></i> When another creature damages you with a melee attack roll, you can take a Reaction and expend one Superiority Die to reduce the damage by the number you roll on your Superiority Die plus your Strength or Dexterity modifier (your choice).</p>
			<p class="indent"><i><b>Precision Attack.</b></i> When you miss with an attack roll, you can expend one Superiority Die, roll that die, and add it to the attack roll, potentially causing the attack to hit.</p>
			<p class="indent"><i><b>Pushing Attack.</b></i> When you hit a creature with an attack roll using a weapon or an Unarmed Strike, you can expend one Superiority Die to attempt to drive the target back. Add the Superiority Die to the attack’s damage roll. If the target is Large or smaller, it must succeed on a Strength saving throw or be pushed up to 15 feet directly away from you.</p>
			<p class="indent"><i><b>Rally.</b></i> As a Bonus Action, you can expend one Superiority Die to bolster the resolve of a companion. Choose an ally of yours within 30 feet of yourself who can see or hear you. That creature gains Temporary Hit Points equal to the Superiority Die roll plus half your Fighter level (round down).</p>
			<p class="indent"><i><b>Riposte.</b></i> When a creature misses you with a melee attack roll, you can take a Reaction and expend one Superiority Die to make a melee attack roll with a weapon or an Unarmed Strike against the creature. If you hit, add the Superiority Die to the attack’s damage.</p>
			<p class="indent"><i><b>Sweeping Attack.</b></i> When you hit a creature with a melee attack roll using a weapon or an Unarmed Strike, you can expend one Superiority Die to attempt to damage another creature. Choose another creature within 5 feet of the original target and within your reach. If the original attack roll would hit the second creature, it takes damage equal to the number you roll on your Superiority Die. The damage is of the same type dealt by the original attack.</p>
			<p class="indent"><i><b>Tactical Assessment.</b></i> When you make an Intelligence (History or Investigation) check or a Wisdom (Insight) check, you can expend one Superiority Die and add that die to the ability check.</p>
			<p class="indent"><i><b>Trip Attack.</b></i> When you hit a creature with an attack roll using a weapon or an Unarmed Strike, you can expend one Superiority Die and add the die to the attack’s damage roll. If the target is Large or smaller, it must succeed on a Strength saving throw or have the Prone condition.</p>
		</description>
	</element>

```

2025-04-15 18:44 UTC, NickVendel commented on core/players-handbook-2024/archetypes/fighter-battle-master.xml
> +			<description>When you make a Dexterity (Stealth) check or an Initiative roll, you can expend one Superiority Die and add the die to the roll, unless you have the Incapacitated condition.</descript
```suggestion
		<sheet usage="Superiority Die">
			<description>When you make a Dexterity (Stealth) check or an Initiative roll and aren't Incapacitated, you can roll the die and add it to the roll.</description>
```

2025-04-15 18:44 UTC, NickVendel commented on core/players-handbook-2024/archetypes/fighter-battle-master.xml
> +			Until the start of your next turn, you or the other creature (your choice) gains a bonus to AC equal to a roll of your Superiority Die.</description>
```suggestion
		<sheet usage="Superiority Die">
			<description>When you're within 5 feet of a willing creature without the Incapacitated condition on your turn, you can switch places with that creature, provided you spend at least 5 feet of movement. This movement doesn't provoke Opportunity Attacks. &#13;
			Until the start of your next turn, you or the other creature (your choice) gains a bonus to AC equal to a roll of Superiority Die.</description>
```

2025-04-15 18:44 UTC, NickVendel commented on core/players-handbook-2024/archetypes/fighter-battle-master.xml
> +		</sheet>
```suggestion
		<sheet usage="Superiority Die">
			<description>You can replace one of your attacks to direct one of your companions to strike. Choose a willing creature who can see or hear you. That creature can immediately use its Reaction to make one attack with a weapon or an Unarmed Strike, adding the die to the attack's damage roll on a hit.</description>
```

2025-04-15 18:44 UTC, NickVendel commented on core/players-handbook-2024/archetypes/fighter-battle-master.xml
> +			<description>When you make a Charisma (Intimidation, Performance, or Persuasion) check, you can expend one Superiority Die and add that die to the roll.</description>
```suggestion
		<sheet usage="Superiority Die">
			<description>When you make a Charisma (Intimidation, Performance, or Persuasion) check, you can roll the die and add it to the check.</description>
```

2025-04-15 18:44 UTC, NickVendel commented on core/players-handbook-2024/archetypes/fighter-battle-master.xml
> +			<description>When you hit a creature with an attack roll, you can expend one Superiority Die to attempt to disarm the target. Add the Superiority Die roll to the attack's damage roll. The target m
```suggestion
		<sheet usage="Superiority Die">
			<description>When you hit a creature with an attack roll, you can attempt to disarm the target. Add the die to the attack's damage roll. The target must succeed on a DC{{combat superiority:dc}} Strength saving throw or drop one object of your choice that it's holding, with the object landing in its space.</description>
```

2025-04-15 18:44 UTC, NickVendel commented on core/players-handbook-2024/archetypes/fighter-battle-master.xml
> +			<description>When you hit a creature with an attack roll, you can expend one Superiority Die to distract the target. Add the Superiority Die roll to the attack's damage roll. The next attack roll
```suggestion
		<sheet usage="Superiority Die">
			<description>On hit, you can distract the target. Add the die to the attack's damage roll. The next attack roll against the target by an attacker other than you has Advantage if the attack is made before the start of your next turn.</description>
```

2025-04-15 18:44 UTC, NickVendel commented on core/players-handbook-2024/archetypes/fighter-battle-master.xml
> +			<description>You can expend one Superiority Die and take the Disengage action. You also roll the die and add the number rolled to your AC until the start of your next turn.</description>
```suggestion
		<sheet action="Bonus Action" usage="Superiority Die">
			<description>Take the Disengage action. You also roll the die and add the number rolled to your AC until the start of your next turn.</description>
```

2025-04-15 18:44 UTC, NickVendel commented on core/players-handbook-2024/archetypes/fighter-battle-master.xml
> +			<description>You can expend one Superiority Die to feint, choosing one creature within 5 feet of yourself as your target. You have Advantage on your next attack roll against that target this turn.
```suggestion
		<sheet action="Bonus Action" usage="Superiority Die">
			<description>Choose one creature within 5 feet of yourself as your target. You have Advantage on your next attack roll against that target this turn. If that attack hits, add the die to the attack's damage roll.</description>
```

2025-04-15 18:44 UTC, NickVendel commented on core/players-handbook-2024/archetypes/fighter-battle-master.xml
> +			<description>When you hit a creature with an attack roll, you can expend one Superiority Die to attempt to goad the target into attacking you. Add the Superiority Die to the attack's damage roll.
```suggestion
		<sheet usage="Superiority Die">
			<description>On hit, add the die to the attack's damage roll. The target must then succeed on a DC{{combat superiority:dc}} Wisdom saving throw or have Disadvantage on attack rolls against targets other than you until the end of your next turn.</description>
```

2025-04-15 18:44 UTC, NickVendel commented on core/players-handbook-2024/archetypes/fighter-battle-master.xml
> +			<description>You can expend one Superiority Die and take the Dash action. If you move at least 5 feet in a straight line immediately before hitting with a melee attack as part of the Attack action
```suggestion
		<sheet action="Bonus Action" usage="Superiority Die">
			<description>Take the Dash action. If you move at least 5 feet in a straight line immediately before hitting with a melee attack as part of the Attack action on this turn, you can add the die to the attack's damage roll.</description>
```

2025-04-15 18:44 UTC, NickVendel commented on core/players-handbook-2024/archetypes/fighter-battle-master.xml
> +			<description>When you hit a creature with an attack roll, you can expend one Superiority Die to maneuver one of your comrades into another position. Add the Superiority Die roll to the attack's da
```suggestion
		<sheet usage="Superiority Die">
			<description>On hit, you add the die to the attack's damage roll, and choose a willing creature who can see or hear you. That creature can use its Reaction to move up to half its Speed without provoking an Opportunity Attacks from the target of your attack.</description>
```

2025-04-15 18:44 UTC, NickVendel commented on core/players-handbook-2024/archetypes/fighter-battle-master.xml
> +			<description>When you hit a creature with an attack roll, you can expend one Superiority Die to attempt to frighten the target. Add the Superiority Die to the attack's damage roll. The target must
```suggestion
		<sheet usage="Superiority Die">
			<description>On hit, you add the die to the attack's damage roll. The target must then succeed on a DC{{combat superiority:dc}} Wisdom saving throw or have the Frightened condition until the end of your next turn.</description>
```

2025-04-15 18:44 UTC, NickVendel commented on core/players-handbook-2024/archetypes/fighter-battle-master.xml
> +		</sheet>
```suggestion
		<sheet action="Reaction" usage="Superiority Die">
			<description>When another creature damages you with a melee attack roll, you can reduce the damage by 1d{{combat superiority:dice size}} (Superiority Die) + {{combat superiority:dc:ability}}.</description>
```

2025-04-15 18:44 UTC, NickVendel commented on core/players-handbook-2024/archetypes/fighter-battle-master.xml
> +			<description>When you miss with an attack roll, you can expend one Superiority Die, roll that die, and add it to the attack roll, potentially causing the attack to hit.</description>
```suggestion
		<sheet usage="Superiority Die">
			<description>When you miss with an attack roll, you can add the Superiority Die to the attack roll, potentially causing the attack to hit.</description>
```

2025-04-15 18:44 UTC, NickVendel commented on core/players-handbook-2024/archetypes/fighter-battle-master.xml
> +			<description>When you hit a creature with an attack roll using a weapon or an Unarmed Strike, you can expend one Superiority Die to attempt to drive the target back. Add the Superiority Die to the
```suggestion
		<sheet usage="Superiority Die">
			<description>On hit with a weapon or an Unarmed Strike, you add the die to the attack's damage roll. If the target is Large or smaller, it must succeed on a DC{{combat superiority:dc}} Strength saving throw or be pushed up to 15 feet directly away from you.</description>
```

2025-04-15 18:44 UTC, NickVendel commented on core/players-handbook-2024/archetypes/fighter-battle-master.xml
> +			<description>You can expend one Superiority Die to bolster the resolve of an ally of yours within 30 feet of yourself who can see or hear you. That creature gains 1d{{superiority dice:size}}+{{lev
```suggestion
		<sheet action="Bonus Action" usage="Superiority Die">
			<description>Choose an ally within 30 feet of yourself who can see or hear you. That creature gains 1d{{combat superiority:dice size}} (Superiority Die) + {{level:fighter:half}} Temporary Hit Points.</description>
```

2025-04-15 18:44 UTC, NickVendel commented on core/players-handbook-2024/archetypes/fighter-battle-master.xml
> +			<description>When a creature misses you with a melee attack roll, you can expend one Superiority Die to make a melee attack roll with a weapon or an Unarmed Strike against the creature. If you hit
```suggestion
		<sheet action="Reaction" usage="Superiority Die">
			<description>When a creature misses you with a melee attack, you can make a melee attack roll with a weapon or an Unarmed Strike against the creature. If you hit, add the die to the attack's damage roll.</description>
```

2025-04-15 18:44 UTC, NickVendel commented on core/players-handbook-2024/archetypes/fighter-battle-master.xml
> +			<description>When you hit a creature with a melee attack roll using a weapon or an Unarmed Strike, you can expend one Superiority Die to attempt to damage another creature of your choice within 5
```suggestion
		<sheet usage="Superiority Die">
			<description>On a melee hit with a weapon or an Unarmed Strike, you can attempt to damage another creature of your choice within 5 feet of the original target and within your reach. If the original attack roll would hit the second creature, it takes the weapon's damage equal to the number you rolled on your Superiority Die.</description>
```

2025-04-15 18:44 UTC, NickVendel commented on core/players-handbook-2024/archetypes/fighter-battle-master.xml
> +			<description>When you make an Intelligence (History or Investigation) check or a Wisdom (Insight) check, you can expend one Superiority Die and add that die to the ability check.</description>
```suggestion
		<sheet usage="Superiority Die">
			<description>When you make an Intelligence (History or Investigation) check or a Wisdom (Insight) check, you can add the die to the ability check.</description>
```

2025-04-15 18:44 UTC, NickVendel commented on core/players-handbook-2024/archetypes/fighter-battle-master.xml
> +			<description>When you hit a creature with an attack roll using a weapon or an Unarmed Strike, you can expend one Superiority Die and add the die to the attack's damage roll. If the target is Large
```suggestion
		<sheet usage="Superiority Die">
			<description>On hit with a weapon or an Unarmed Strike, you add the die to the attack's damage roll. If the target is Large or smaller, it must succeed on a DC{{combat superiority:dc}} Strength saving throw or have the Prone condition.</description>
```

2025-04-15 18:44 UTC, NickVendel commented on core/players-handbook-2024/archetypes/fighter-champion.xml
> +		<supports>Martial Archetype</supports>
```suggestion
		<supports>Fighter Subclass</supports>
```

2025-04-15 18:44 UTC, NickVendel commented on core/players-handbook-2024/archetypes/fighter-champion.xml
> +			<description alt="Superior Critical" level="15">Your attack rolls with weapons and Unarmed Strikes can score a Critical Hit on a roll of 18–20.</description>
```suggestion
		<sheet alt="Improved Critical">
			<description>Your attack rolls with weapons and Unarmed Strikes can score a Critical Hit on a roll of 19–20.</description>
			<description level="15">Your attack rolls with weapons and Unarmed Strikes can score a Critical Hit on a roll of 18–20.</description>
```

2025-04-15 18:44 UTC, NickVendel commented on core/players-handbook-2024/archetypes/fighter-champion.xml
> +
```suggestion
```

2025-04-15 18:44 UTC, NickVendel commented on core/players-handbook-2024/archetypes/fighter-eldritch-knight.xml
> +		<supports>Martial Archetype</supports>
```suggestion
		<supports>Fighter Subclass</supports>
```

2025-04-15 18:44 UTC, NickVendel commented on core/players-handbook-2024/archetypes/fighter-eldritch-knight.xml
> +			<div element="ID_WOTC_PHB24_ARCHETYPE_FEATURE_FIGHTER_ELDRITCH_KNIGHT_SPELLCASTING"/>
```suggestion
			<div element="ID_WOTC_PHB24_ARCHETYPE_FEATURE_FIGHTER_ELDRITCH_KNIGHT_SPELLCASTING"/>
			<h5>ELDRITCH KNIGHT SPELLCASTING</h5>
			<table class="class-features">
				<tr style="font-weight: bold">
					<td class="col-20" rowspan="2">Fighter<br />Level</td>
					<td class="col-20" rowspan="2">Prepared<br />Spells</td>
					<td colspan="4" style="vertical-align:bottom; border-bottom: 0px">Spell Slots per Level</td>
				</tr>
				<tr style="font-weight: bold"><td>1</td><td>2</td><td>3</td><td>4</td></tr>
				<tr><td>3</td><td>3</td><td>2</td><td>—</td><td>—</td><td>—</td></tr>
				<tr><td>4</td><td>4</td><td>3</td><td>—</td><td>—</td><td>—</td></tr>
				<tr><td>5</td><td>4</td><td>3</td><td>—</td><td>—</td><td>—</td></tr>
				<tr><td>6</td><td>4</td><td>3</td><td>—</td><td>—</td><td>—</td></tr>
				<tr><td>7</td><td>5</td><td>4</td><td>2</td><td>—</td><td>—</td></tr>
				<tr><td>8</td><td>6</td><td>4</td><td>2</td><td>—</td><td>—</td></tr>
				<tr><td>9</td><td>6</td><td>4</td><td>2</td><td>—</td><td>—</td></tr>
				<tr><td>10</td><td>7</td><td>4</td><td>3</td><td>—</td><td>—</td></tr>
				<tr><td>11</td><td>8</td><td>4</td><td>3</td><td>—</td><td>—</td></tr>
				<tr><td>12</td><td>8</td><td>4</td><td>3</td><td>—</td><td>—</td></tr>
				<tr><td>13</td><td>9</td><td>4</td><td>3</td><td>2</td><td>—</td></tr>
				<tr><td>14</td><td>10</td><td>4</td><td>3</td><td>2</td><td>—</td></tr>
				<tr><td>15</td><td>10</td><td>4</td><td>3</td><td>2</td><td>—</td></tr>
				<tr><td>16</td><td>11</td><td>4</td><td>3</td><td>3</td><td>—</td></tr>
				<tr><td>17</td><td>11</td><td>4</td><td>3</td><td>3</td><td>—</td></tr>
				<tr><td>18</td><td>11</td><td>4</td><td>3</td><td>3</td><td>—</td></tr>
				<tr><td>19</td><td>12</td><td>4</td><td>3</td><td>3</td><td>1</td></tr>
				<tr><td>20</td><td>13</td><td>4</td><td>3</td><td>3</td><td>1</td></tr>
			</table>
```

2025-04-15 18:44 UTC, NickVendel commented on core/players-handbook-2024/archetypes/fighter-eldritch-knight.xml
> +			<div element="ID_WOTC_PHB24_ARCHETYPE_FEATURE_FIGHTER_ELDRITCH_KNIGHT_WEAPON_BOND"/>
```suggestion
			<div element="ID_WOTC_PHB24_ARCHETYPE_FEATURE_FIGHTER_ELDRITCH_KNIGHT_WAR_BOND"/>
```

2025-04-15 18:44 UTC, NickVendel commented on core/players-handbook-2024/archetypes/fighter-eldritch-knight.xml
> +			<grant type="Archetype Feature" id="ID_WOTC_PHB24_ARCHETYPE_FEATURE_FIGHTER_ELDRITCH_KNIGHT_WEAPON_BOND" level="3"/>
```suggestion
			<grant type="Archetype Feature" id="ID_WOTC_PHB24_ARCHETYPE_FEATURE_FIGHTER_ELDRITCH_KNIGHT_WAR_BOND" level="3"/>
```

2025-04-15 18:44 UTC, NickVendel commented on core/players-handbook-2024/archetypes/fighter-eldritch-knight.xml
> +			</table>
```suggestion
			<p>You have learned to cast spells.</p>
			<p class="indent"><strong><em>Cantrips.</em></strong> You know two cantrips of your choice from the Wizard spell list. <em>Ray of Frost</em> and <em>Shocking Grasp</em> are recommended. Whenever you gain a Fighter level, you can replace one of these cantrips with another cantrip of your choice from the Wizard spell list.</p>
			<p class="indent">When you reach Fighter level 10, you learn another Wizard cantrip of your choice.</p>
			<p class="indent"><strong><em>Spell Slots.</em></strong> The Eldritch Knight Spellcasting table shows how many spell slots you have to cast your level 1+ spells. You regain all expended slots when you finish a Long Rest.</p>
			<p class="indent"><strong><em>Prepared Spells of Level 1+.</em></strong> You prepare the list of level 1+ spells that are available for you to cast with this feature. To start, choose three level 1 spells from the Wizard spell list. <em>Burning Hands</em>, <em>Jump</em>, and <em>Shield</em> are recommended.</p>
			<p class="indent">The number of spells on your list increases as you gain Fighter levels, as shown in the Prepared Spells column of the Eldritch Knight Spellcasting table. Whenever that number increases, choose additional spells from the Wizard spell list until the number of spells on your list matches the number on the table. The chosen spells must be of a level for which you have spell slots. For example, if you're a level 7 Fighter, your list of prepared spells can include five Wizard spells of levels 1 and 2 in any combination.</p>
			<p class="indent"><em><strong>Changing your Prepared Spells.</strong></em> Whenever you gain a Fighter level, you can replace one spell on your list with another Wizard spell for which you have spell slots.</p>
			<p class="indent"><strong><em>Spellcasting Ability.</em></strong> Intelligence is your spellcasting ability for your Wizard spells.</p>
			<p class="indent"><strong><em>Spellcasting Focus.</em></strong> You can use an Arcane Focus as a Spellcasting Focus for your Wizard spells.</p>
			<center>
				<p><strong>Spell save DC</strong> = 8 + your proficiency bonus + your Intelligence modifier</p>
				<p><strong>Spell attack modifier</strong> = your proficiency bonus + your Intelligence modifier</p>
			</center>
```

2025-04-15 18:44 UTC, NickVendel commented on core/players-handbook-2024/archetypes/fighter-eldritch-knight.xml
> +		<spellcasting name="Eldritch Knight" ability="Intelligence" prepare="false" allowReplace="true">
```suggestion
		<sheet alt="Spellcasting">
			<description>You can replace one of your spells and/or cantrips whenever you gain a Fighter level.</description>
		</sheet>
		<spellcasting name="Eldritch Knight" ability="Intelligence" allowReplace="true">
```

2025-04-15 18:44 UTC, NickVendel commented on core/players-handbook-2024/archetypes/fighter-eldritch-knight.xml
> +			<select type="Spell" name="Spellcasting (Eldritch Knight)" supports="$(spellcasting:list), $(spellcasting:slots)" level="20" spellcasting="Eldritch Knight"/>
```suggestion

			<select type="Spell" name="Cantrip (Eldritch Knight)" supports="Wizard, 0" number="2" spellcasting="Eldritch Knight" />
			<select type="Spell" name="Cantrip (Eldritch Knight)" supports="Wizard, 0" level="10" spellcasting="Eldritch Knight" />
			<select type="Spell" name="Spell (Eldritch Knight)" supports="$(spellcasting:list), $(spellcasting:slots)" level="3" number="3" spellcasting="Eldritch Knight" />
			<select type="Spell" name="Spell (Eldritch Knight)" supports="$(spellcasting:list), $(spellcasting:slots)" level="4" spellcasting="Eldritch Knight"/>
			<select type="Spell" name="Spell (Eldritch Knight)" supports="$(spellcasting:list), $(spellcasting:slots)" level="7" spellcasting="Eldritch Knight"/>
			<select type="Spell" name="Spell (Eldritch Knight)" supports="$(spellcasting:list), $(spellcasting:slots)" level="8" spellcasting="Eldritch Knight"/>
			<select type="Spell" name="Spell (Eldritch Knight)" supports="$(spellcasting:list), $(spellcasting:slots)" level="10" spellcasting="Eldritch Knight"/>
			<select type="Spell" name="Spell (Eldritch Knight)" supports="$(spellcasting:list), $(spellcasting:slots)" level="11" spellcasting="Eldritch Knight"/>
			<select type="Spell" name="Spell (Eldritch Knight)" supports="$(spellcasting:list), $(spellcasting:slots)" level="13" spellcasting="Eldritch Knight"/>
			<select type="Spell" name="Spell (Eldritch Knight)" supports="$(spellcasting:list), $(spellcasting:slots)" level="14" spellcasting="Eldritch Knight"/>
			<select type="Spell" name="Spell (Eldritch Knight)" supports="$(spellcasting:list), $(spellcasting:slots)" level="16" spellcasting="Eldritch Knight"/>
			<select type="Spell" name="Spell (Eldritch Knight)" supports="$(spellcasting:list), $(spellcasting:slots)" level="19" spellcasting="Eldritch Knight"/>
			<select type="Spell" name="Spell (Eldritch Knight)" supports="$(spellcasting:list), $(spellcasting:slots)" level="20" spellcasting="Eldritch Knight"/>
```

2025-04-15 18:44 UTC, NickVendel commented on core/players-handbook-2024/archetypes/fighter-eldritch-knight.xml
> +		<requirements>!ID_INTERNAL_PHB24_FEATURE_REPLACEMENT_FIGHTER_ELDRITCH_KNIGHT_WEAPON_BOND</requirements>
```suggestion

	<element name="Level 3: War Bond" type="Archetype Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ARCHETYPE_FEATURE_FIGHTER_ELDRITCH_KNIGHT_WAR_BOND">
		<requirements>!ID_INTERNAL_PHB24_FEATURE_REPLACEMENT_FIGHTER_ELDRITCH_KNIGHT_WAR_BOND</requirements>
```

2025-04-15 18:44 UTC, NickVendel commented on core/players-handbook-2024/archetypes/fighter-eldritch-knight.xml
> +			<description>You can spend 1 hour or a Short Rest to bond with a weapon. The weapon must be within reach throughout the ritual. You can bond with a maximum of 2 weapons at any one time, performing
```suggestion
		<sheet alt="War Bond">
			<description>You can spend 1 hour to bond with a weapon. The weapon must be within reach throughout the ritual. You can be bonded only to 2 weapons at a time. &#13;
```

2025-04-15 18:44 UTC, NickVendel commented on core/players-handbook-2024/archetypes/fighter-eldritch-knight.xml
> +			<description>You can replace one of the attacks with a casting of one of your Wizard cantrips that has a casting time of an Action.</description>
```suggestion
		<sheet alt="War Magic">
			<description>You can replace one of the attacks to cast a Wizard cantrip that has a casting time of an Action.</description>
```

2025-04-15 18:44 UTC, NickVendel commented on core/players-handbook-2024/archetypes/fighter-eldritch-knight.xml
> +			<description>When you hit a creature with an attack using a weapon, that creature has Disadvantage on the next saving throw it makes against a spell you cast before the end of your next turn.</des
```suggestion
		<sheet alt="Eldritch Strike">
			<description>On hit with a weapon, your target gains Disadvantage on the next saving throw it makes against a spell you cast before the end of your next turn.</description>
```

2025-04-15 18:44 UTC, NickVendel commented on core/players-handbook-2024/archetypes/fighter-eldritch-knight.xml
> +			<description>When you use your Action Surge, you can teleport up to 30 feet to an unoccupied space you can see. You can teleport before or after the additional Action.</description>
```suggestion
			<description>When you use your Action Surge, you can teleport up to 30 feet to an unoccupied space you can see. You can do so before or after the additional Action.</description>
```

2025-04-15 18:44 UTC, NickVendel commented on core/players-handbook-2024/archetypes/fighter-eldritch-knight.xml
> +			<description>You can replace two of the attacks with a casting of one of your level 1 or level 2 Wizard spells that has a casting time of an Action.</description>
```suggestion
		<sheet alt="Improved War Magic">
			<description>You can replace two of the attacks with a casting of a Wizard spell of level 1 or 2 that has a casting time of an Action.</description>
```

2025-04-15 18:44 UTC, NickVendel commented on core/players-handbook-2024/archetypes/fighter-eldritch-knight.xml
> +	<element name="Weapon Bond Feature Replacement" type="Grants" source="Internal" id="ID_INTERNAL_PHB24_FEATURE_REPLACEMENT_FIGHTER_ELDRITCH_KNIGHT_WEAPON_BOND" />
```suggestion
	<element name="Spellcasting Feature Replacement" type="Grants" source="Internal" id="ID_INTERNAL_PHB24_FEATURE_REPLACEMENT_FIGHTER_ELDRITCH_KNIGHT_SPELLCASTING" />
	<element name="War Bond Feature Replacement" type="Grants" source="Internal" id="ID_INTERNAL_PHB24_FEATURE_REPLACEMENT_FIGHTER_ELDRITCH_KNIGHT_WAR_BOND" />
```

2025-04-15 18:44 UTC, NickVendel commented on core/players-handbook-2024/archetypes/fighter-psi-warrior.xml
> +		<supports>Martial Archetype</supports>
```suggestion
		<supports>Fighter Subclass</supports>
```

2025-04-15 18:44 UTC, NickVendel commented on core/players-handbook-2024/archetypes/fighter-psi-warrior.xml
> +				<tr><td class="center">17</td><td class="center">d12</td><td class="center">12</td></tr>
```suggestion
			<h5>Psi Warrior Energy Dice</h5>
			<table class="class-features">
				<thead>
					<tr><td>Fighter Level</td><td>Die Size</td><td>Number</td></tr>
				</thead>
				<tr><td>3</td><td>D6</td><td>4</td></tr>
				<tr><td>5</td><td>D8</td><td>6</td></tr>
				<tr><td>9</td><td>D8</td><td>8</td></tr>
				<tr><td>11</td><td>D10</td><td>8</td></tr>
				<tr><td>13</td><td>D10</td><td>10</td></tr>
				<tr><td>17</td><td>D12</td><td>12</td></tr>
```

2025-04-15 18:44 UTC, NickVendel commented on core/players-handbook-2024/archetypes/fighter-psi-warrior.xml
> +			<p><em><strong>Telekinetic Movement.</strong></em> You can move an object or a creature with your mind. As a Magic action, choose one target you can see within 30 feet of yourself; the target must
```suggestion
			<p class="indent"><em><strong>Protective Field.</strong></em> When you or another creature you can see within 30 feet of you takes damage, you can take a Reaction to expend one Psionic Energy Die, roll the die, and reduce the damage taken by the number rolled plus your Intelligence modifier (minimum reduction of 1), as you create a momentary shield of telekinetic force.</p>
			<p class="indent"><em><strong>Psionic Strike.</strong></em> You can propel your weapons with psionic force. Once on each of your turns, immediately after you hit a target within 30 feet of yourself with an attack and deal damage to it with a weapon, you can expend one Psionic Energy Die, rolling it and dealing Force damage to the target equal to the number rolled plus your Intelligence modifier.</p>
			<p class="indent"><em><strong>Telekinetic Movement.</strong></em> You can move an object or a creature with your mind. As a Magic action, choose one target you can see within 30 feet of yourself; the target must be a loose object that is Large or smaller or one willing creature other than you. You transport the target up to 30 feet to an unoccupied space you can see. Alternatively, if the target is a Tiny object, you can transport it to or from your hand.</p>
```

2025-04-15 18:44 UTC, NickVendel commented on core/players-handbook-2024/archetypes/fighter-psi-warrior.xml
> +			<select type="Archetype Feature" name="Telekinetic Thrust" supports="ID_WOTC_PHB24_ARCHETYPE_FEATURE_FIGHTER_PSI_WARRIOR_TELEKINETIC_ADEPT_TELEKINETIC_THRUST" default="ID_WOTC_PHB24_ARCHETYPE_FEAT
```suggestion
		<sheet alt="Psionic Power" usage="{{fighter:psionic power:dice amount}}d{{fighter:psionic power:dice size}}/Long Rest">
			<description>You regain 1 expended die when you finish a Short Rest.</description>
		</sheet>
		<rules>
			<stat name="fighter:psionic power:dice size" value="6" bonus="base" />
			<stat name="fighter:psionic power:dice size" value="8" level="5" bonus="base" />
			<stat name="fighter:psionic power:dice size" value="10" level="11" bonus="base" />
			<stat name="fighter:psionic power:dice size" value="12" level="17" bonus="base" />
			<stat name="fighter:psionic power:dice amount" value="4" bonus="base" />
			<stat name="fighter:psionic power:dice amount" value="6" level="5" bonus="base" />
			<stat name="fighter:psionic power:dice amount" value="8" level="9" bonus="base" />
			<stat name="fighter:psionic power:dice amount" value="10" level="13" bonus="base" />
			<stat name="fighter:psionic power:dice amount" value="12" level="17" bonus="base" />
			<stat name="fighter:psionic power:dc" value="8" bonus="base" />
			<stat name="fighter:psionic power:dc" value="proficiency" bonus="proficiency" />
			<stat name="fighter:psionic power:dc" value="intelligence:modifier" bonus="ability" />

			<select type="Archetype Feature" name="Protective Field" supports="PHB24 Protective Field" default="ID_WOTC_PHB24_ARCHETYPE_FEATURE_FIGHTER_PSI_WARRIOR_PSIONIC_POWER_PROTECTIVE_FIELD" requirements="!ID_INTERNAL_PHB24_FEATURE_REPLACEMENT_FIGHTER_PSI_WARRIOR_PSIONIC_POWER_PROTECTIVE_FIELD" />
			<select type="Archetype Feature" name="Psionic Strike" supports="PHB24 Psionic Strike" default="ID_WOTC_PHB24_ARCHETYPE_FEATURE_FIGHTER_PSI_WARRIOR_PSIONIC_POWER_PSIONIC_STRIKE" requirements="!(ID_INTERNAL_PHB24_FEATURE_REPLACEMENT_FIGHTER_PSI_WARRIOR_PSIONIC_POWER_PSIONIC_STRIKE||ID_INTERNAL_PHB24_FEATURE_REPLACEMENT_FIGHTER_PSI_WARRIOR_TELEKINETIC_ADEPT_TELEKINETIC_THRUST)" />
			<select type="Archetype Feature" name="Telekinetic Movement" supports="PHB24 Telekinetic Movement" default="ID_WOTC_PHB24_ARCHETYPE_FEATURE_FIGHTER_PSI_WARRIOR_PSIONIC_POWER_TELEKINETIC_MOVEMENT" requirements="!ID_INTERNAL_PHB24_FEATURE_REPLACEMENT_FIGHTER_PSI_WARRIOR_PSIONIC_POWER_TELEKINETIC_MOVEMENT" />
			<select type="Archetype Feature" name="Psi-Powered Leap" supports="PHB24 Psi-Powered Leap" default="ID_WOTC_PHB24_ARCHETYPE_FEATURE_FIGHTER_PSI_WARRIOR_TELEKINETIC_ADEPT_PSI_POWERED_LEAP" level="7" requirements="!ID_INTERNAL_PHB24_FEATURE_REPLACEMENT_FIGHTER_PSI_WARRIOR_TELEKINETIC_ADEPT_PSI_POWERED_LEAP" />
```

2025-04-15 18:44 UTC, NickVendel commented on core/players-handbook-2024/archetypes/fighter-psi-warrior.xml
> +	</element>
```suggestion
		<supports>PHB24 Protective Field</supports>
		<compendium display="false" />
		<description>
			<p>When you or another creature you can see within 30 feet of you takes damage, you can take a Reaction to expend one Psionic Energy Die, roll the die, and reduce the damage taken by the number rolled plus your Intelligence modifier (minimum reduction of 1), as you create a momentary shield of telekinetic force.</p>
		</description>
		<sheet action="Reaction" usage="Psionic Energy Die">
			<description>When you or another creature you can see within 30 feet of you takes damage, you can reduce the damage taken by 1d{{fighter:psionic power:dice size}}+{{intelligence:modifier}} (minimum reduction of 1).</description>
		</sheet>
	</element>
```

2025-04-15 18:44 UTC, NickVendel commented on core/players-handbook-2024/archetypes/fighter-psi-warrior.xml
> +			<description>Immediately after you hit a target within 30 feet of you with an attack and deal damage to it with a weapon, you can expend one Psionic Energy die and deal 1d{{psionic power:dice:size
```suggestion
		<supports>PHB24 Psionic Strike</supports>
		<compendium display="false" />
		<description>
			<p>You can propel your weapons with psionic force. Once on each of your turns, immediately after you hit a target within 30 feet of yourself with an attack and deal damage to it with a weapon, you can expend one Psionic Energy Die, rolling it and dealing Force damage to the target equal to the number rolled plus your Intelligence modifier.</p>
		</description>
		<sheet usage="1/Turn — Psionic Energy Die">
			<description>Immediately after you hit with a weapon and deal damage to a target within 30 feet of you, you can add 1d{{fighter:psionic power:dice size}}+{{intelligence:modifier}} force damage to it.</description>
			<description level="7">Immediately after you hit with a weapon and deal damage to a target within 30 feet of you, you can add 1d{{fighter:psionic power:dice size}}+{{intelligence:modifier}} force damage to it and force the target to make a DC{{fighter:psionic power:dc}} Strength saving throw. On a failed save, you can give the target the Prone condition or transport it up to 10 feet horizontally.</description>
```

2025-04-15 18:44 UTC, NickVendel commented on core/players-handbook-2024/archetypes/fighter-psi-warrior.xml
> +		<requirements>!ID_INTERNAL_PHB24_FEATURE_REPLACEMENT_FIGHTER_PSI_WARRIOR_PSIONIC_POWER_TELEKINETIC_MOVEMENT</requirements>
```suggestion
		<supports>PHB24 Telekinetic Movement</supports>
```

2025-04-15 18:44 UTC, NickVendel commented on core/players-handbook-2024/archetypes/fighter-psi-warrior.xml
> +			You can expend a Psionic Energy Die (no action required) to restore your use of this feature.</description>
```suggestion
		<sheet action="Action" usage="1/Short Rest">
			<description>You target one loose object that is Large or smaller or one willing creature other than yourself. If you can see the target and it is within 30 feet of you, you can magically move it up to 30 feet to an unoccupied space you can see. Alternatively, if it is a Tiny object, you can move it to or from your hand. &#13;
			You can expend a Psionic Energy Die to restore a use of this feature.</description>
```

2025-04-15 18:44 UTC, NickVendel commented on core/players-handbook-2024/archetypes/fighter-psi-warrior.xml
> +			<p><em><strong>Telekinetic Thrust.</strong></em> When you deal damage to a target with your Psionic Strike, you can force the target to make a Strength saving throw (DC 8 plus your Intelligence mo
```suggestion
			<p class="indent"><em><strong>Psi-Powered Leap.</strong></em> As a Bonus Action, you gain a Fly Speed equal to twice your Speed until the end of the current turn. Once you take this Bonus Action, you can't do so again until you finish a Short or Long Rest unless you expend a Psionic Energy Die (no action required) to restore your use of it.</p>
			<p class="indent"><em><strong>Telekinetic Thrust.</strong></em> When you deal damage to a target with your Psionic Strike, you can force the target to make a Strength saving throw (DC 8 plus your Intelligence modifier and Proficiency Bonus). On a failed save, you can give the target the Prone condition or transport it up to 10 feet horizontally.</p>
```

2025-04-15 18:44 UTC, NickVendel commented on core/players-handbook-2024/archetypes/fighter-psi-warrior.xml
> +		<requirements>!ID_INTERNAL_PHB24_FEATURE_REPLACEMENT_FIGHTER_PSI_WARRIOR_TELEKINETIC_ADEPT_PSI_POWERED_LEAP</requirements>
```suggestion
		<supports>PHB24 Psi-Powered Leap</supports>
```

2025-04-15 18:44 UTC, NickVendel commented on core/players-handbook-2024/archetypes/fighter-psi-warrior.xml
> +			You can expend a Psionic Energy Die (no action required) to restore your use of this feature.</description>
```suggestion
			You can expend a Psionic Energy Die to restore a use of this feature.</description>
```

2025-04-15 18:44 UTC, NickVendel commented on core/players-handbook-2024/archetypes/fighter-psi-warrior.xml
> +	</element>
```suggestion
```

2025-04-15 18:44 UTC, NickVendel commented on core/players-handbook-2024/archetypes/fighter-psi-warrior.xml
> +			<description>If you start your turn with the Charmed or Frightened condition, you can expend a Psionic Energy Die (no action required) and end every effect on yourself giving you those conditions.
```suggestion
		<sheet alt="Guarded Mind" usage="Psionic Energy Die">
			<description>If you start your turn with the Charmed or Frightened condition, you can end every effect on yourself giving you those conditions.</description>
```

2025-04-15 18:44 UTC, NickVendel commented on core/players-handbook-2024/archetypes/fighter-psi-warrior.xml
> +			You can expend a Psionic Energy Die (no action required) to restore your use of this feature.</description>
```suggestion
		<sheet alt="Bulwark of Force" action="Bonus Action" usage="1/Long Rest">
			<description>Choose up to {{bulwark of force:count}} creatures within 30 feet of yourself. Each of the chosen creatures have Half Cover for 1 minute or until you have the Incapacitated condition. &#13;
			You can expend a Psionic Energy Die to restore a use of this feature.</description>
```

2025-04-15 18:44 UTC, NickVendel commented on core/players-handbook-2024/archetypes/fighter-psi-warrior.xml
> +		</rules>
```suggestion
		<sheet alt="Telekinetic Master" action="Action" usage="1/Long Rest" >
			<description>You cast the Telekinesis spell without components, using Intelligence as your spellcasting ability. On each of your turns while you maintain Concentration on it, you can make one attack with a weapon as a Bonus Action. &#13;
			You can expend a Psionic Energy Die to restore a use of this feature.</description>
		</sheet>
```

2025-04-18 02:51 UTC, NickVendel requested changes
Monk + Monk Subclass review

2025-04-18 02:51 UTC, NickVendel commented on core/players-handbook-2024/classes/class-monk.xml
> +			<p class="indent">Many Monks find that a structured life of ascetic withdrawal helps them cultivate the physical and mental focus they need to harness their power. Other Monks believe that immersi
```suggestion
			<p class="indent">Many Monks find that a structured life of ascetic withdrawal helps them cultivate the physical and mental focus they need to harness their power. Other Monks believe that immersing themselves in the vibrant confusion of life helps to fuel their determination and discipline.</p>
```

2025-04-18 02:51 UTC, NickVendel commented on core/players-handbook-2024/classes/class-monk.xml
> +					<tr><td><b>Armor Training</b></td><td class="left">None.</td></tr>
```suggestion
					<tr><td><b>Primary Ability</b></td><td class="left">Dexterity and Wisdom</td></tr>
					<tr><td><b>Hit Point Die</b></td><td class="left">D8 per Monk level</td></tr>
					<tr><td><b>Saving Throw Proficiencies</b></td><td class="left">Strength and Dexterity</td></tr>
					<tr><td><b>Skill Proficiencies</b></td><td class="left"><i>Choose 2:</i> Acrobatics, Athletics, History, Insight, Religion, or Stealth</td></tr>
					<tr><td><b>Weapon Proficiencies</b></td><td class="left>">Simple weapons and Martial weapons that have the Light property</td></tr>
					<tr><td><b>Tool Proficiencies</b></td><td class="left"><i>Choose one type of Artisan's Tools or Musical Instrument</i></td></tr>
					<tr><td><b>Armor Training</b></td><td class="left">None</td></tr>
```

2025-04-18 02:51 UTC, NickVendel commented on core/players-handbook-2024/classes/class-monk.xml
> +				<tr><td>3</td><td>+2</td><td class="left">Monk Subclass, Deflect Attacks</td><td>1d6</td><td>3</td><td>+10 ft</td></tr>
```suggestion
				<tr><td>1</td><td>+2</td><td class="left">Martial Arts, Unarmored Defense</td><td>1d6</td><td>—</td><td>—</td></tr>
				<tr><td>2</td><td>+2</td><td class="left">Monk's Focus, Unarmored Movement, Uncanny Metabolism</td><td>1d6</td><td>2</td><td>+10 ft</td></tr>
				<tr><td>3</td><td>+2</td><td class="left">Deflect Attacks, Monk Subclass</td><td>1d6</td><td>3</td><td>+10 ft</td></tr>
```

2025-04-18 02:51 UTC, NickVendel commented on core/players-handbook-2024/classes/class-monk.xml
> +			<div element="ID_WOTC_PHB24_CLASS_FEATURE_MONK_ABILITY_SCORE_IMPROVEMENT" />
```suggestion
			<div element="ID_WOTC_PHB24_CLASS_FEATURE_MONK_MARTIAL_ARTS" />
			<div element="ID_WOTC_PHB24_CLASS_FEATURE_MONK_UNARMORED_DEFENSE" />
			<div element="ID_WOTC_PHB24_CLASS_FEATURE_MONK_MONKS_FOCUS" />
			<div element="ID_WOTC_PHB24_CLASS_FEATURE_MONK_UNARMORED_MOVEMENT" />
			<div element="ID_WOTC_PHB24_CLASS_FEATURE_MONK_UNCANNY_METABOLISM" />
			<div element="ID_WOTC_PHB24_CLASS_FEATURE_MONK_DEFLECT_ATTACKS" />
			<div element="ID_WOTC_PHB24_CLASS_FEATURE_MONK_MONK_SUBCLASS" />
			<div element="ID_WOTC_PHB24_CLASS_FEATURE_MONK_ABILITY_SCORE_IMPROVEMENT" />
```

2025-04-18 02:51 UTC, NickVendel commented on core/players-handbook-2024/classes/class-monk.xml
> +			<grant type="Class Feature" id="ID_WOTC_PHB24_CLASS_FEATURE_MONK_DEFLECT_ENERGY" level="13" />
```suggestion

			<grant type="Class Feature" id="ID_WOTC_PHB24_CLASS_FEATURE_MONK_MARTIAL_ARTS" level="1" />
			<grant type="Class Feature" id="ID_WOTC_PHB24_CLASS_FEATURE_MONK_UNARMORED_DEFENSE" level="1" />
			<grant type="Class Feature" id="ID_WOTC_PHB24_CLASS_FEATURE_MONK_MONKS_FOCUS" level="2" />
			<grant type="Class Feature" id="ID_WOTC_PHB24_CLASS_FEATURE_MONK_UNARMORED_MOVEMENT" level="2" />
			<grant type="Class Feature" id="ID_WOTC_PHB24_CLASS_FEATURE_MONK_UNCANNY_METABOLISM" level="2" />
			<grant type="Class Feature" id="ID_WOTC_PHB24_CLASS_FEATURE_MONK_DEFLECT_ATTACKS" level="3" />
			<grant type="Class Feature" id="ID_WOTC_PHB24_CLASS_FEATURE_MONK_MONK_SUBCLASS" level="3" />
			<grant type="Class Feature" id="ID_WOTC_PHB24_CLASS_FEATURE_MONK_ABILITY_SCORE_IMPROVEMENT" level="4" />
			<grant type="Class Feature" id="ID_WOTC_PHB24_CLASS_FEATURE_MONK_SLOW_FALL" level="4" />
			<grant type="Class Feature" id="ID_WOTC_PHB24_CLASS_FEATURE_MONK_EXTRA_ATTACK" level="5" />
			<grant type="Class Feature" id="ID_WOTC_PHB24_CLASS_FEATURE_MONK_STUNNING_STRIKE" level="5" />
			<grant type="Class Feature" id="ID_WOTC_PHB24_CLASS_FEATURE_MONK_EMPOWERED_STRIKES" level="6" />
			<grant type="Class Feature" id="ID_WOTC_PHB24_CLASS_FEATURE_MONK_EVASION" level="7" />
			<grant type="Class Feature" id="ID_WOTC_PHB24_CLASS_FEATURE_MONK_ACROBATIC_MOVEMENT" level="9" />
			<grant type="Class Feature" id="ID_WOTC_PHB24_CLASS_FEATURE_MONK_HEIGHTENED_FOCUS" level="10" />
			<grant type="Class Feature" id="ID_WOTC_PHB24_CLASS_FEATURE_MONK_SELF_RESTORATION" level="10" />
			<grant type="Class Feature" id="ID_WOTC_PHB24_CLASS_FEATURE_MONK_DEFLECT_ENERGY" level="13" />
```

2025-04-18 02:51 UTC, NickVendel commented on core/players-handbook-2024/classes/class-monk.xml
> +			<p class="indent">You gain the following benefits while you are unarmed or wielding only Monk weapons and you aren't wearing armor or wielding a Shield.</p>
```suggestion
		<requirements>!(ID_INTERNAL_PHB24_FEATURE_REPLACEMENT_MONK_MARTIAL_ARTS||ID_INTERNAL_PHB24_FEATURE_REPLACEMENT_MONK_EMPOWERED_STRIKES)</requirements>
		<description>
			<p>Your practice of martial arts gives you mastery of combat styles that use your Unarmed Strike and Monk weapons, which are the following:</p>
			<ul style="margin-top:-1em; margin-bottom: 0.5em">
				<li>Simple Melee weapons</li>
				<li>Martial Melee weapons that have the Light property</li>
			</ul>
			<p>You gain the following benefits while you are unarmed or wielding only Monk weapons and you aren't wearing armor or wielding a Shield.</p>
```

2025-04-18 02:51 UTC, NickVendel commented on core/players-handbook-2024/classes/class-monk.xml
> +			You can make an Unarmed Strike as a Bonus Action on your turn.</description>
```suggestion
			<description>You can make an Unarmed Strike as a Bonus Action. &#13;
			Additionally, your Unarmed Strikes deal 1d{{martial arts:dice}}+{{martial arts:ability modifier}} Bludgeoning damage, and your Grapple or Shove DC is {{martial arts:dc}}.</description>
			<description level="6">You can make an Unarmed Strike as a Bonus Action. &#13;
			Additionally, your Unarmed Strikes deal 1d{{martial arts:dice}}+{{martial arts:ability modifier}} Bludgeoning or Force damage, and your Grapple or Shove DC is {{martial arts:dc}}.</description>
```

2025-04-18 02:51 UTC, NickVendel commented on core/players-handbook-2024/classes/class-monk.xml
> +		</rules>
```suggestion
		<rules>
			<stat name="martial arts:dice" value="6" bonus="martial arts" />
			<stat name="martial arts:dice" value="8" bonus="martial arts" level="5" />
			<stat name="martial arts:dice" value="10" bonus="martial arts" level="11" />
			<stat name="martial arts:dice" value="12" bonus="martial arts" level="17" />
			<stat name="martial arts:ability modifier" value="strength:modifier" bonus="ability" />
			<stat name="martial arts:ability modifier" value="dexterity:modifier" bonus="ability" />
			<stat name="martial arts:dc" value="8" />
			<stat name="martial arts:dc" value="proficiency" />
			<stat name="martial arts:dc" value="martial arts:ability modifier" bonus="ability" />
		</rules>
```

2025-04-18 02:51 UTC, NickVendel commented on core/players-handbook-2024/classes/class-monk.xml
> +	<element name="Level 1: Unarmored Defense" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_MONK_UNARMORED_DEFENSE">
```suggestion
	</element>

	<element name="Level 1: Unarmored Defense" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_MONK_UNARMORED_DEFENSE">
```

2025-04-18 02:51 UTC, NickVendel commented on core/players-handbook-2024/classes/class-monk.xml
> +		</rules>
```suggestion
		<rules>
			<stat name="ac:unarmored defense monk" value="10" bonus="base" />
			<stat name="ac:unarmored defense monk" value="dexterity:modifier" bonus="primary ability" />
			<stat name="ac:unarmored defense monk" value="wisdom:modifier" bonus="secondary ability" />

			<stat name="ac:calculation" value="ac:unarmored defense monk" bonus="calculation" equipped="[armor:none],[shield:none]" alt="Unarmored Defense (Monk)" />
		</rules>
```

2025-04-18 02:51 UTC, NickVendel commented on core/players-handbook-2024/classes/class-monk.xml
> +		<requirements>!ID_INTERNAL_PHB24_FEATURE_REPLACEMENT_MONK_MONKS_FOCUS</requirements>
```suggestion
		<requirements>!(ID_INTERNAL_PHB24_FEATURE_REPLACEMENT_MONK_MONKS_FOCUS||ID_INTERNAL_PHB24_FEATURE_REPLACEMENT_MONK_HEIGHTENED_FOCUS)</requirements>
```

2025-04-18 02:51 UTC, NickVendel commented on core/players-handbook-2024/classes/class-monk.xml
> +			<p><em><strong>Step of the Wind.</strong></em> You can take the Dash action as a Bonus Action. Alternatively, you can expend 1 Focus Point to take both the Disengage and Dash actions as a Bonus Ac
i think it's fine to remove DC part for non-spellcasting classes.
```suggestion
			<p class="indent">Some features that use Focus Points require your target to make a saving throw. The save DC equals 8 plus your Wisdom modifier and Proficiency Bonus.</p>
			<p class="indent"><em><strong>Flurry of Blows.</strong></em> You can expend 1 Focus Point to make two Unarmed Strikes as a Bonus Action.</p>
			<p class="indent"><em><strong>Patient Defense.</strong></em> You can take the Disengage action as a Bonus Action. Alternatively, you can expend 1 Focus Point to take both the Disengage and the Dodge actions as a Bonus Action.</p>
			<p class="indent"><em><strong>Step of the Wind.</strong></em> You can take the Dash action as a Bonus Action. Alternatively, you can expend 1 Focus Point to take both the Disengage and Dash actions as a Bonus Action, and your jump distance is doubled for the turn.</p>
```

2025-04-18 02:51 UTC, NickVendel commented on core/players-handbook-2024/classes/class-monk.xml
> +			<description>You have {{focus:points}} Focus Points and your Focus DC is {{focus:dc}}.</description>
DC is always displayed in the sub-features, so it's fine to leave it out from the main one.
```suggestion
			<description>You have {{monks focus:points}} Focus Points.</description>
```

2025-04-18 02:51 UTC, NickVendel commented on core/players-handbook-2024/classes/class-monk.xml
> +		</rules>
```suggestion
		<rules>
			<stat name="monks focus:points" value="level:monk" bonus="base" />
			<stat name="monks focus:dc" value="8" bonus="base"/>
			<stat name="monks focus:dc" value="proficiency" bonus="proficiency"/>
			<stat name="monks focus:dc" value="wisdom:modifier" bonus="ability"/>
			<select type="Class Feature" name="Flurry of Blows" supports="PHB24 Flurry of Blows" default="ID_WOTC_PHB24_CLASS_FEATURE_MONK_FOCUS_FLURRY_OF_BLOWS" requirements="!ID_INTERNAL_PHB24_FEATURE_REPLACEMENT_MONK_MONKS_FOCUS_FLURRY_OF_BLOWS"/>
			<select type="Class Feature" name="Patient Defense" supports="PHB24 Patient Defense" default="ID_WOTC_PHB24_CLASS_FEATURE_MONK_FOCUS_PATIENT_DEFENSE" requirements="!ID_INTERNAL_PHB24_FEATURE_REPLACEMENT_MONK_MONKS_FOCUS_PATIENT_DEFENSE"/>
			<select type="Class Feature" name="Step of the Wind" supports="PHB24 Step of the Wind" default="ID_WOTC_PHB24_CLASS_FEATURE_MONK_FOCUS_STEP_OF_THE_WIND" requirements="!ID_INTERNAL_PHB24_FEATURE_REPLACEMENT_MONK_MONKS_FOCUS_STEP_OF_THE_WIND"/>
		</rules>
```

2025-04-18 02:51 UTC, NickVendel commented on core/players-handbook-2024/classes/class-monk.xml
> +		<requirements>!ID_INTERNAL_PHB24_FEATURE_REPLACEMENT_MONK_MONKS_FOCUS_FLURRY_OF_BLOWS</requirements>
```suggestion
		<supports>PHB24 Flurry of Blows</supports>
```

2025-04-18 02:51 UTC, NickVendel commented on core/players-handbook-2024/classes/class-monk.xml
> +		</sheet>
```suggestion
		<sheet action="Bonus Action" usage="Focus Point">
			<description>You can make two Unarmed Strikes</description>
			<description level="10">You can make three Unarmed Strikes</description>
		</sheet>
```

2025-04-18 02:51 UTC, NickVendel commented on core/players-handbook-2024/classes/class-monk.xml
> +		<requirements>!ID_INTERNAL_PHB24_FEATURE_REPLACEMENT_MONK_MONKS_FOCUS_PATIENT_DEFENSE</requirements>
```suggestion
		<supports>PHB24 Patient Defense</supports>
```

2025-04-18 02:51 UTC, NickVendel commented on core/players-handbook-2024/classes/class-monk.xml
> +		</sheet>
```suggestion
		<sheet action="Bonus Action">
			<description>You can take the Disengage action. &#13;
			Alternatively, you can expend 1 Focus Point to take both the Disengage and the Dodge actions.</description>
			<description level="10">You can take the Disengage action. &#13;
			Alternatively, you can expend 1 Focus Point to take both the Disengage and the Dodge actions, and gain 2d{{martial arts:dice}} Temporary Hit Points.</description>
		</sheet>
```

2025-04-18 02:51 UTC, NickVendel commented on core/players-handbook-2024/classes/class-monk.xml
> +		<requirements>!ID_INTERNAL_PHB24_FEATURE_REPLACEMENT_MONK_MONKS_FOCUS_STEP_OF_THE_WIND</requirements>
```suggestion
		<supports>PHB24 Step of the Wind</supports>
```

2025-04-18 02:51 UTC, NickVendel commented on core/players-handbook-2024/classes/class-monk.xml
> +			<description level="10">You can take the Dash action. Alternatively, you can expend 1 Focus Point to take both the Disengage and Dash actions, and your jump distance is doubled for the turn. When
```suggestion
		<sheet action="Bonus Action">
			<description>You can take the Dash action. &#13;
			Alternatively, you can expend 1 Focus Point to take both the Disengage and Dash actions, and your jump distance is doubled for the turn.</description>
			<description level="10">You can take the Dash action. &#13;
			Alternatively, you can expend 1 Focus Point to take both the Disengage and Dash actions, and your jump distance is doubled for the turn. When you use this option, you can choose a willing creature within 5 feet of yourself that is Large or smaller to move with you until the end of your turn. The creature’s movement doesn’t provoke Opportunity Attacks.</description>
```

2025-04-18 02:51 UTC, NickVendel commented on core/players-handbook-2024/classes/class-monk.xml
> +		<requirements>!ID_INTERNAL_PHB24_FEATURE_REPLACEMENT_MONK_UNARMORED_MOVEMENT</requirements>
```suggestion

	<element name="Level 2: Unarmored Movement" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_MONK_UNARMORED_MOVEMENT">
		<requirements>!(ID_INTERNAL_PHB24_FEATURE_REPLACEMENT_MONK_UNARMORED_MOVEMENT||ID_INTERNAL_PHB24_FEATURE_REPLACEMENT_MONK_ACROBATIC_MOVEMENT)</requirements>
```

2025-04-18 02:51 UTC, NickVendel commented on core/players-handbook-2024/classes/class-monk.xml
> +			<description>Your Speed increases by {{monk:unarmored movement}} feet while you are not wearing armor or wielding a shield.</description>
```suggestion
			<description>Your Speed increases by {{monk:unarmored movement}} feet while you are not wearing armor or wielding a Shield.</description>
			<description level="9">Your Speed increases by {{monk:unarmored movement}} feet and you can move along vertical surfaces and across liquids on your turn without falling while you are not wearing armor or wielding a Shield.</description>
```

2025-04-18 02:51 UTC, NickVendel commented on core/players-handbook-2024/classes/class-monk.xml
> +			<stat name="monk:unarmored movement" value="30" bonus="unarmored movement" level="18" />
```suggestion
			<stat name="monk:unarmored movement" value="10" bonus="base" />
			<stat name="monk:unarmored movement" value="15" bonus="base" level="6" />
			<stat name="monk:unarmored movement" value="20" bonus="base" level="10" />
			<stat name="monk:unarmored movement" value="25" bonus="base" level="14" />
			<stat name="monk:unarmored movement" value="30" bonus="base" level="18" />
```

2025-04-18 02:51 UTC, NickVendel commented on core/players-handbook-2024/classes/class-monk.xml
> +	<element name="Level 2: Uncanny Metabolism" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_MONK_UNCANNY_METABOLISM">
```suggestion

	<element name="Level 2: Uncanny Metabolism" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_MONK_UNCANNY_METABOLISM">
```

2025-04-18 02:51 UTC, NickVendel commented on core/players-handbook-2024/classes/class-monk.xml
> +		<requirements>!ID_INTERNAL_PHB24_FEATURE_REPLACEMENT_MONK_DEFLECT_ATTACKS</requirements>
```suggestion
		<sheet alt="Uncanny Metabolism" usage="1/Long Rest">
			<description>When you roll Initiative, you can regain all Focus Points and regain 1d{{martial arts:dice}}+{{level:monk}} Hit Points.</description>
		</sheet>
	</element>

	<element name="Level 3: Deflect Attacks" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_MONK_DEFLECT_ATTACKS">
		<requirements>!(ID_INTERNAL_PHB24_FEATURE_REPLACEMENT_MONK_DEFLECT_ATTACKS||ID_INTERNAL_PHB24_FEATURE_REPLACEMENT_MONK_DEFLECT_ENERGY)</requirements>
```

2025-04-18 02:51 UTC, NickVendel commented on core/players-handbook-2024/classes/class-monk.xml
> +			If you reduce the damage to 0, you can spend 1 Focus Point to redirect damage. Melee attacks can be directed at a creature you can see within 5 feet, while Ranged can be directed against a creatur
```suggestion
			<description>You can reduce the damage of melee or ranged attack that deals Bludgeoning, Piercing, or Slashing damage by 1d10+{{deflect attacks:bonus}}. If you reduce the damage to 0, you can spend 1 Focus Point to redirect damage. Melee attack can be directed at a creature you can see within 5 feet, while Ranged attack can be directed against a creature you can see within 60 feet that isn't behind Total Cover. The target must succeed on a DC{{monks focus:dc}} Dexterity saving throw or takes damage equal to 2d{{martial arts:dice}}+{{dexterity:modifier}} of the original attack's type.</description>
			<description level="13">You can reduce the damage of any melee or ranged attack by 1d10+{{deflect attacks:bonus}}. If you reduce the damage to 0, you can spend 1 Focus Point to redirect damage. Melee attacks can be directed at a creature you can see within 5 feet, while Ranged can be directed against a creature you can see within 60 feet that isn't behind Total Cover. The target must succeed on a DC{{monks focus:dc}} Dexterity saving throw or take damage equal to 2d{{martial arts:dice}}+{{dexterity:modifier}} of the original attack's type.</description>
```

2025-04-18 02:51 UTC, NickVendel commented on core/players-handbook-2024/classes/class-monk.xml
> +			<stat name="monk:deflect attacks bonus" value="level:monk" />
```suggestion
			<stat name="deflect attacks:bonus" value="level:monk" bonus="base" />
			<stat name="deflect attacks:bonus" value="dexterity:modifier" bonus="ability" />
```

2025-04-18 02:51 UTC, NickVendel commented on core/players-handbook-2024/classes/class-monk.xml
> +	<element name="Level 3: Monk Subclass" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_MONK_MONK_SUBCLASS">
```suggestion
	</element>

	<element name="Level 3: Monk Subclass" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_MONK_MONK_SUBCLASS">
```

2025-04-18 02:51 UTC, NickVendel commented on core/players-handbook-2024/classes/class-monk.xml
> +			<select type="Feat" name="Ability Score Improvement (Monk 16)" level="16" />
```suggestion
			<select type="Feat" name="Ability Score Improvement (Monk 4)" supports="!Boon" />
			<select type="Feat" name="Ability Score Improvement (Monk 8)" supports="!Boon" level="8" />
			<select type="Feat" name="Ability Score Improvement (Monk 12)" supports="!Boon" level="12" />
			<select type="Feat" name="Ability Score Improvement (Monk 16)" supports="!Boon" level="16" />
```

2025-04-18 02:51 UTC, NickVendel commented on core/players-handbook-2024/classes/class-monk.xml
> +	<element name="Level 4: Slow Fall" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_MONK_SLOW_FALL">
```suggestion
	</element>

	<element name="Level 4: Slow Fall" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_MONK_SLOW_FALL">
```

2025-04-18 02:51 UTC, NickVendel commented on core/players-handbook-2024/classes/class-monk.xml
> +			<stat name="monk:slowfall" value="level:monk" />
```suggestion
			<description>Reduce any falling damage you take by {{slowfall:amount}}.</description>
		</sheet>
		<rules>
			<stat name="slowfall:amount" value="level:monk" />
			<stat name="slowfall:amount" value="level:monk" />
			<stat name="slowfall:amount" value="level:monk" />
			<stat name="slowfall:amount" value="level:monk" />
			<stat name="slowfall:amount" value="level:monk" />
```

2025-04-18 02:51 UTC, NickVendel commented on core/players-handbook-2024/classes/class-monk.xml
> +	<element name="Level 5: Extra Attack" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_MONK_EXTRA_ATTACK">
```suggestion
	</element>

	<element name="Level 5: Extra Attack" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_MONK_EXTRA_ATTACK">
```

2025-04-18 02:51 UTC, NickVendel commented on core/players-handbook-2024/classes/class-monk.xml
> +	<element name="Level 5: Stunning Strike" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_MONK_STUNNING_STRIKE">
```suggestion
	</element>

	<element name="Level 5: Stunning Strike" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_MONK_STUNNING_STRIKE">
```

2025-04-18 02:51 UTC, NickVendel commented on core/players-handbook-2024/classes/class-monk.xml
> +			<description>When you hit another creature with a Monk weapon or Unarmed Strike, you can spend 1 Focus Point to attempt a stunning strike. The target must succeed on a DC{{focus:dc}} Constitution
```suggestion
		<sheet alt="Stunning Strike" usage="Focus Point — 1/Turn">
			<description>On hit with a Monk weapon or Unarmed Strike, you can force the target to make a DC{{monks focus:dc}} Constitution saving throw. On failure, it is Stunned until the start of your next turn. On a success, its Speed is halved, and the next attack roll made against it before then has Advantage.</description>
```

2025-04-18 02:51 UTC, NickVendel commented on core/players-handbook-2024/classes/class-monk.xml
> +	<element name="Level 6: Empowered Strikes" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_MONK_EMPOWERED_STRIKES">
```suggestion
	</element>

	<element name="Level 6: Empowered Strikes" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_MONK_EMPOWERED_STRIKES">
```

2025-04-18 02:51 UTC, NickVendel commented on core/players-handbook-2024/classes/class-monk.xml
> +		</sheet>
```suggestion
		<sheet display="false" />
```

2025-04-18 02:51 UTC, NickVendel commented on core/players-handbook-2024/classes/class-monk.xml
> +	<element name="Level 7: Evasion" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_MONK_EVASION">
```suggestion
	</element>

	<element name="Level 7: Evasion" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_MONK_EVASION">
```

2025-04-18 02:51 UTC, NickVendel commented on core/players-handbook-2024/classes/class-monk.xml
> +	<element name="Level 9: Acrobatic Movement" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_MONK_ACROBATIC_MOVEMENT">
```suggestion
	</element>

	<element name="Level 9: Acrobatic Movement" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_MONK_ACROBATIC_MOVEMENT">
```

2025-04-18 02:51 UTC, NickVendel commented on core/players-handbook-2024/classes/class-monk.xml
> +		</sheet>
```suggestion
		<sheet display="false" />
```

2025-04-18 02:51 UTC, NickVendel commented on core/players-handbook-2024/classes/class-monk.xml
> +	<element name="Level 10: Heightened Focus" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_MONK_HEIGHTENED_FOCUS">
```suggestion
	</element>

	<element name="Level 10: Heightened Focus" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_MONK_HEIGHTENED_FOCUS">
```

2025-04-18 02:51 UTC, NickVendel commented on core/players-handbook-2024/classes/class-monk.xml
> +			<p><em><strong>Step of the Wind.</strong></em> When you expend a Focus Point to use Step of the Wind, you can choose a willing creature within 5 feet of yourself that is Large or smaller. You move
```suggestion
			<p class="indent"><em><strong>Flurry of Blows.</strong></em> You can expend 1 Focus Point to use Flurry of Blows and make three Unarmed Strikes with it instead of two.</p>
			<p class="indent"><em><strong>Patient Defense.</strong></em> When you expend a Focus Point to use Patient Defense, you gain a number of Temporary Hit Points equal to two rolls of your Martial Arts die.</p>
			<p class="indent"><em><strong>Step of the Wind.</strong></em> When you expend a Focus Point to use Step of the Wind, you can choose a willing creature within 5 feet of yourself that is Large or smaller. You move the creature with you until the end of your turn. The creature's movement doesn't provoke Opportunity Attacks.</p>
```

2025-04-18 02:51 UTC, NickVendel commented on core/players-handbook-2024/classes/class-monk.xml
> +	<element name="Level 10: Self-Restoration" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_MONK_SELF_RESTORATION">
```suggestion
	</element>

	<element name="Level 10: Self-Restoration" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_MONK_SELF_RESTORATION">
```

2025-04-18 02:51 UTC, NickVendel commented on core/players-handbook-2024/classes/class-monk.xml
> +		<sheet alt="Self Restoration">
```suggestion
		<sheet alt="Self-Restoration">
```

2025-04-18 02:51 UTC, NickVendel commented on core/players-handbook-2024/classes/class-monk.xml
> +	<element name="Level 13: Deflect Energy" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_MONK_DEFLECT_ENERGY">
```suggestion
	</element>

	<element name="Level 13: Deflect Energy" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_MONK_DEFLECT_ENERGY">
```

2025-04-18 02:51 UTC, NickVendel commented on core/players-handbook-2024/classes/class-monk.xml
> +	<element name="Level 14: Disciplined Survivor" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_MONK_DISCIPLINED_SURVIVOR">
```suggestion
	</element>

	<element name="Level 14: Disciplined Survivor" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_MONK_DISCIPLINED_SURVIVOR">
```

2025-04-18 02:51 UTC, NickVendel commented on core/players-handbook-2024/classes/class-monk.xml
> +			<description>Whenever you make a saving throw and fail, you can spend 1 Focus Point to reroll it and take the second result.</description>
```suggestion
		<sheet alt="Disciplined Survivor" usage="Focus Point">
			<description>Whenever you fail a saving throw, you can reroll it and take the second result.</description>
```

2025-04-18 02:51 UTC, NickVendel commented on core/players-handbook-2024/classes/class-monk.xml
> +	<element name="Level 15: Perfect Focus" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_MONK_PERFECT_FOCUS">
```suggestion
	</element>

	<element name="Level 15: Perfect Focus" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_MONK_PERFECT_FOCUS">
```

2025-04-18 02:51 UTC, NickVendel commented on core/players-handbook-2024/classes/class-monk.xml
> +			<description>When you roll Initiative with 3 or less Focus Points and don't use Uncanny Metabolism, you regain expended Focus Points until you have 4.</description>
Rare case when you really can't make the description shorter. And while i don't particularly like how it is worded, i think it makes sense to leave as is.
```suggestion
			<description>When you roll Initiative and don't use Uncanny Metabolism, you regain expended Focus Points until you have 4 if you have 3 or fewer.</description>
```

2025-04-18 02:51 UTC, NickVendel commented on core/players-handbook-2024/classes/class-monk.xml
> +	<element name="Level 18: Superior Defense" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_MONK_SUPERIOR_DEFENSE">
```suggestion
	</element>

	<element name="Level 18: Superior Defense" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_MONK_SUPERIOR_DEFENSE">
```

2025-04-18 02:51 UTC, NickVendel commented on core/players-handbook-2024/classes/class-monk.xml
> +			<description>You can spend 3 Focus Points at the start of your turn to gain Resistance to all damage types except Force for 1 minute.</description>
```suggestion
		<sheet alt="Superior Defense" usage="3 Focus Points">
			<description>At the start of your turn, you gain Resistance to all damage types except Force for 1 minute.</description>
```

2025-04-18 02:51 UTC, NickVendel commented on core/players-handbook-2024/classes/class-monk.xml
> +	<element name="Level 19: Epic Boon" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_MONK_EPIC_BOON">
```suggestion
	</element>

	<element name="Level 19: Epic Boon" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_MONK_EPIC_BOON">
```

2025-04-18 02:51 UTC, NickVendel commented on core/players-handbook-2024/classes/class-monk.xml
> +	<element name="Level 20: Body and Mind" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_MONK_BODY_AND_MIND">
```suggestion
	</element>

	<element name="Level 20: Body and Mind" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_MONK_BODY_AND_MIND">
```

2025-04-18 02:51 UTC, NickVendel commented on core/players-handbook-2024/archetypes/monk-mercy.xml
> +		<requirements>!ID_INTERNAL_PHB24_FEATURE_REPLACEMENT_MONK_MERCY_HAND_OF_HARM</requirements>
```suggestion
		<requirements>!(ID_INTERNAL_PHB24_FEATURE_REPLACEMENT_MONK_MERCY_HAND_OF_HARM||ID_INTERNAL_PHB24_FEATURE_REPLACEMENT_MONK_MERCY_PHYSICIANS_TOUCH)</requirements>
```

2025-04-18 02:51 UTC, NickVendel commented on core/players-handbook-2024/archetypes/monk-mercy.xml
> +			<description>When you hit a creature with an Unarmed Strike and deal damage, you can expend 1 Focus Point to deal 1d{{martial arts:dice}}+{{wisdom:modifier}} extra Necrotic damage to the target.</
```suggestion
		<sheet alt="Hand of Harm" usage="Focus Point — 1/Turn" >
			<description>When you deal damage to a creature with an Unarmed Strike, you can deal extra 1d{{martial arts:dice}}+{{wisdom:modifier}} Necrotic damage to the target.</description>
			<description level="6">When you deal damage to a creature with an Unarmed Strike, you can deal extra 1d{{martial arts:dice}}+{{wisdom:modifier}} Necrotic damage to the target and it becomes Poisoned until the end of your next turn.</description>
```

2025-04-18 02:51 UTC, NickVendel commented on core/players-handbook-2024/archetypes/monk-mercy.xml
> +		<requirements>!ID_INTERNAL_PHB24_FEATURE_REPLACEMENT_MONK_MERCY_HAND_OF_HEALING</requirements>
```suggestion
	</element>

	<element name="Level 3: Hand of Healing" type="Archetype Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ARCHETYPE_FEATURE_MONK_MERCY_HAND_OF_HEALING">
		<requirements>!(ID_INTERNAL_PHB24_FEATURE_REPLACEMENT_MONK_MERCY_HAND_OF_HEALING||ID_INTERNAL_PHB24_FEATURE_REPLACEMENT_MONK_MERCY_PHYSICIANS_TOUCH)</requirements>
```

2025-04-18 02:51 UTC, NickVendel commented on core/players-handbook-2024/archetypes/monk-mercy.xml
> +			<p>As a Magic action, you can expend 1 Focus Point to touch a creature and restore a number of Hit Points equal to a roll of your Martial Arts die plus your Wisdom modifier. When you use your Flur
```suggestion
			<p>As a Magic action, you can expend 1 Focus Point to touch a creature and restore a number of Hit Points equal to a roll of your Martial Arts die plus your Wisdom modifier.</p>
			<p class="indent">When you use your Flurry of Blows, you can replace one of the Unarmed Strikes with a use of this feature without expending a Focus Point for the healing.</p>
```

2025-04-18 02:51 UTC, NickVendel commented on core/players-handbook-2024/archetypes/monk-mercy.xml
> +			When you use your Flurry of Blows, you can replace one of the Unarmed Strikes with a use of this feature without expending a Focus Point for the healing.</description>
```suggestion
		<sheet alt="Hand of Healing" action="Action" usage="Focus Point" >
			<description>You can touch a creature and magically restore 1d{{martial arts:dice}}+{{wisdom:modifier}} Hit Points to them. When you use your Flurry of Blows, you can replace one of the Unarmed Strikes with a use of this feature without expending a Focus Point for the healing.</description>
			<description level="6">You can touch a creature to magically restore 1d{{martial arts:dice}}+{{wisdom:modifier}} Hit Points to them and end a Blinded, Deafened, Paralyzed, Poisoned, or Stunned condition. When you use your Flurry of Blows, you can replace one of the Unarmed Strikes with a use of this feature without expending a Focus Point for the healing.</description>
```

2025-04-18 02:51 UTC, NickVendel commented on core/players-handbook-2024/archetypes/monk-mercy.xml
> +	<element name="Level 3: Implements of Mercy" type="Archetype Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ARCHETYPE_FEATURE_MONK_MERCY_IMPLEMENTS_OF_MERCY">
```suggestion
	</element>

	<element name="Level 3: Implements of Mercy" type="Archetype Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_ARCHETYPE_FEATURE_MONK_MERCY_IMPLEMENTS_OF_MERCY">
```

2025-04-18 02:51 UTC, NickVendel commented on core/players-handbook-2024/archetypes/monk-mercy.xml
> +		</sheet>
```suggestion
		<sheet display="false" />
```

2025-04-18 02:51 UTC, NickVendel commented on core/players-handbook-2024/archetypes/monk-mercy.xml
> +		<sheet usage="{{flurry of healing and harm:count}}/Long Rest" alt="Flurry of Healing and Harm">
```suggestion
		<sheet alt="Flurry of Healing and Harm" usage="{{flurry of healing and harm:usage}}/Long Rest">
```

2025-04-18 02:51 UTC, NickVendel commented on core/players-handbook-2024/archetypes/monk-mercy.xml
> +			<stat name="flurry of healing and harm:count" value="wisdom:modifier" bonus="base" />
```suggestion
			<stat name="flurry of healing and harm:usage" value="1" bonus="base" />
			<stat name="flurry of healing and harm:usage" value="wisdom:modifier" bonus="base" />
```

2025-04-18 02:51 UTC, NickVendel commented on core/players-handbook-2024/archetypes/monk-mercy.xml
> +			<description>You can touch the corpse of a creature that died within the past 24 hours and expend 5 Focus Points. The creature then returns to life with 4d10+{{wisdom:modifier}} Hit Points. If the
```suggestion
			<p class="indent">Once you use this feature, you can't use it again until you finish a Long Rest.</p>
		</description>
		<sheet alt="Hand of Ultimate Mercy" action="Action" usage="5 Focus Points — 1/Long Rest">
			<description>You can magically touch the corpse of a creature that died within the past 24 hours and return it to life with 4d10+{{wisdom:modifier}} Hit Points. When creature is revived, you remove any Blinded, Deafened, Paralyzed, Poisoned, and Stunned conditions it had.</description>
```

2025-04-18 02:51 UTC, NickVendel commented on core/players-handbook-2024/archetypes/monk-shadow.xml
> +		</rules>
```suggestion
		<sheet alt="Shadow Arts" usage="Focus Point">
			<description>You can cast the Darkness spell without spell components. You can see within the spell's area when you cast it with this feature. While the spell persists, you can move its area of Darkness to a space within 60 feet of yourself at the start of each of your turns. &#13;
			Additionally, you know Minor Illusion cantrip and Wisdom is your spellcasting ability for it.</description>
		</sheet>
		<rules>
			<grant type="Vision" id="ID_VISION_LESSER_DARKVISION" />
			<stat name="darkvision:range" value="60" />
			<grant type="Spell" id="ID_WOTC_PHB24_SPELL_MINOR_ILLUSION" />
		</rules>
```

2025-04-18 02:51 UTC, NickVendel commented on core/players-handbook-2024/archetypes/monk-shadow.xml
> +	</element>
```suggestion
```

2025-04-18 02:51 UTC, NickVendel commented on core/players-handbook-2024/archetypes/monk-shadow.xml
> +		<requirements>!ID_INTERNAL_PHB24_FEATURE_REPLACEMENT_MONK_SHADOW_SHADOW_STEP</requirements>
```suggestion
		<requirements>!(ID_INTERNAL_PHB24_FEATURE_REPLACEMENT_MONK_SHADOW_SHADOW_STEP||ID_INTERNAL_PHB24_FEATURE_REPLACEMENT_MONK_SHADOW_IMPROVED_SHADOW_STEP)</requirements>
```

2025-04-18 02:51 UTC, NickVendel commented on core/players-handbook-2024/archetypes/monk-shadow.xml
> +			<description level="11">While entirely within Dim Light or Darkness, you can teleport up to 60 feet to an unoccupied space you can see that is also in Dim Light or Darkness. You can remove these L
```suggestion
		<sheet alt="Shadow Step" action="Bonus Action">
			<description>While in Dim Light or Darkness, you can teleport up to 60 feet to an unoccupied space you can see that is also in Dim Light or Darkness. You then have Advantage on the next melee attack you make before the end of the current turn.</description>
			<description level="11">You have two ways of using this feature: &#13;
			• While in Dim Light or Darkness, you can teleport up to 60 feet to an unoccupied space you can see that is also in Dim Light or Darkness. &#13;
			• You can spend 1 Focus Point to remove light requirements for this use of the feature, and you can make an Unarmed Strike immediately after you teleport. &#13;
			Regardless of your choice, after you teleport you gain Advantage on the next melee attack you make before the end of the current turn.</description>
```

2025-04-18 02:51 UTC, NickVendel commented on core/players-handbook-2024/archetypes/monk-shadow.xml
> +			<description>While entirely within Dim Light or Darkness, you can shroud yourself with shadows for 1 minute, until you have the Incapacitated condition, or until you end your turn in Bright Light.
```suggestion
		<sheet alt="Cloak of Shadows" action="Action" usage="3 Focus Points">
			<description>While in Dim Light or Darkness, you can shroud yourself with shadows for 1 minute, until you have the Incapacitated condition, or until you end your turn in Bright Light. While shrouded, you have the Invisible condition; can move through occupied spaces as if they were Difficult Terrain, but if you end your turn in such a space you're shunted to the last unoccupied space you were in; and can use Flurry of Blows without expending Focus Points.</description>
```

2025-04-18 02:51 UTC, NickVendel commented on core/players-handbook-2024/archetypes/monk-shadow.xml
> +	<element name="Shadow Step Feature Replacement" type="Grants" source="Internal" id="ID_INTERNAL_PHB24_FEATURE_REPLACEMENT_MONK_SHADOW_SHADOW_STEP" />
```suggestion
	<element name="Shadow Arts Feature Replacement" type="Grants" source="Internal" id="ID_INTERNAL_PHB24_FEATURE_REPLACEMENT_MONK_SHADOW_SHADOW_ARTS" />
	<element name="Shadow Step Feature Replacement" type="Grants" source="Internal" id="ID_INTERNAL_PHB24_FEATURE_REPLACEMENT_MONK_SHADOW_SHADOW_STEP" />
```

2025-04-18 02:51 UTC, NickVendel commented on core/players-handbook-2024/archetypes/monk-elements.xml
> +		<requirements>!ID_INTERNAL_PHB24_FEATURE_REPLACEMENT_MONK_ELEMENTS_ELEMENTAL_ATTUNEMENT</requirements>
```suggestion
		<requirements>!(ID_INTERNAL_PHB24_FEATURE_REPLACEMENT_MONK_ELEMENTS_ELEMENTAL_ATTUNEMENT||ID_INTERNAL_PHB24_FEATURE_REPLACEMENT_MONK_ELEMENTS_STRIDE_OF_THE_ELEMENTS||ID_INTERNAL_PHB24_FEATURE_REPLACEMENT_MONK_ELEMENTS_ELEMENTAL_EPITOME)</requirements>
```

2025-04-18 02:51 UTC, NickVendel commented on core/players-handbook-2024/archetypes/monk-elements.xml
> +		</rules>
```suggestion
		<sheet alt="Elemental Attunement" usage="Focus Point">
			<description>At the start of your turn, you can imbue yourself with elemental energy for the next 10 minutes, or until you have the Incapacitated condition. You gain following benefits: &#13;
			• You add 10 feet to the reach of your Unarmed Strike. &#13;
			• On Unarmed Strike hit, you can change its damage type to Acid, Cold, Fire, Lightning, or Thunder. When you do so, you can force the target to make a DC{{monks focus:dc}} Strength saving throw. On a failure, you can move it 10 feet towards or away from you.</description>
			<description level="11">At the start of your turn, you can imbue yourself with elemental energy for the next 10 minutes, or until you have the Incapacitated condition. You gain following benefits: &#13;
			• You add 10 feet to the reach of your Unarmed Strike. &#13;
			• On Unarmed Strike hit, you can change its damage type to Acid, Cold, Fire, Lightning, or Thunder. When you do so, you can force the target to make a DC{{monks focus:dc}} Strength saving throw. On a failure, you can move it 10 feet towards or away from you. &#13;
			• You have a Fly Speed and a Swim Speed of {{speed}}ft.</description>
			<description level="17">At the start of your turn, you can imbue yourself with elemental energy for the next 10 minutes, or until you have the Incapacitated condition. You gain following benefits: &#13;
			• You add 10 feet to the reach of your Unarmed Strike. &#13;
			• On Unarmed Strike hit, you can change its damage type to Acid, Cold, Fire, Lightning, or Thunder. When you do so, you can force the target to make a DC{{monks focus:dc}} Strength saving throw. On a failure, you can move it 10 feet towards or away from you. &#13;
			• You have a Fly Speed and a Swim Speed of {{speed}}ft. &#13;
			• You gain Resistance to Acid, Cold, Fire, Lightning, or Thunder damage (your choice). At the start of each of your turns, you can change this choice. &#13;
			• When you use your Step of the Wind, your Speed increases by 20 ft. until the end of the turn. For that duration, any creature of your choice takes 1d{{martial arts:dice}} Acid, Cold, Fire, Lightning, or Thunder damage (your choice) when you enter a space within 5 feet of it. A creature can take this damage only once per turn. &#13;
			• Once on your turns, you can deal 1d{{martial arts:dice}} extra damage to a target when you hit it with an Unarmed Strike. The extra damage is the same type dealt by that strike.</description>
		</sheet>
```

2025-04-18 02:51 UTC, NickVendel commented on core/players-handbook-2024/archetypes/monk-elements.xml
> +	</element>
```suggestion
```

2025-04-18 02:51 UTC, NickVendel commented on core/players-handbook-2024/archetypes/monk-elements.xml
> +		<sheet display="false" />
```suggestion
		<sheet alt="Manipulate Elements">
			<description>You know the Elementalism cantrip. Wisdom is your spellcasting ability for it.</description>
		</sheet>
```

2025-04-18 02:51 UTC, NickVendel commented on core/players-handbook-2024/archetypes/monk-elements.xml
> +			<description>You can cause elemental energy to burst in a 20-foot-radius Sphere centered on a point within 120 feet of yourself. Choose a damage type: Acid, Cold, Fire, Lightning, or Thunder. Each
```suggestion
		<sheet alt="Elemental Burst" action="Action" usage="2 Focus Points">
			<description>You can magically cause elemental energy to burst in a 20-foot-radius Sphere centered on a point within 120 feet of yourself. Each creature in the Sphere must make a DC{{monks focus:dc}} Dexterity saving throw. On a failed save, a creature takes 3d{{martial arts:dice}} Acid, Cold, Fire, Lightning, or Thunder damage (your choice). On a successful save, a creature takes half as much damage.</description>
```

2025-04-18 02:51 UTC, NickVendel commented on core/players-handbook-2024/archetypes/monk-elements.xml
> +	</element>
```suggestion
		<sheet display="false" />
	</element>
```

2025-04-18 02:51 UTC, NickVendel commented on core/players-handbook-2024/archetypes/monk-elements.xml
> +</elements>
```suggestion
	<element name="Elemental Attunement Feature Replacement" type="Grants" source="Internal" id="ID_INTERNAL_PHB24_FEATURE_REPLACEMENT_MONK_ELEMENTS_ELEMENTAL_ATTUNEMENT" />
	<element name="Manipulate Elements Feature Replacement" type="Grants" source="Internal" id="ID_INTERNAL_PHB24_FEATURE_REPLACEMENT_MONK_ELEMENTS_MANIPULATE_ELEMENTS" />
	<element name="Elemental Burst Feature Replacement" type="Grants" source="Internal" id="ID_INTERNAL_PHB24_FEATURE_REPLACEMENT_MONK_ELEMENTS_ELEMENTAL_BURST" />
	<element name="Stride of the Elements Feature Replacement" type="Grants" source="Internal" id="ID_INTERNAL_PHB24_FEATURE_REPLACEMENT_MONK_ELEMENTS_STRIDE_OF_THE_ELEMENTS" />
	<element name="Elemental Epitome Feature Replacement" type="Grants" source="Internal" id="ID_INTERNAL_PHB24_FEATURE_REPLACEMENT_MONK_ELEMENTS_ELEMENTAL_EPITOME" />
</elements>
```

2025-04-18 02:51 UTC, NickVendel commented on core/players-handbook-2024/archetypes/monk-open-hand.xml
> +		</rules>
```suggestion
		<sheet alt="Open Hand Technique">
			<description>On hit using your Flurry of Blows, you can force one of the following effects on the target: &#13;
			• It can't make Opportunity Attacks until the start of its next turn. &#13;
			• It must succeed on a DC{{monks focus:dc}} Strength saving throw or be pushed up to 15 ft. away from you. &#13;
			• It must succeed on a DC{{monks focus:dc}} Dexterity saving throw or have the Prone condition.</description>
		</sheet>
```

2025-04-18 02:51 UTC, NickVendel commented on core/players-handbook-2024/archetypes/monk-open-hand.xml
> +	</element>
```suggestion
```

2025-04-18 02:51 UTC, NickVendel commented on core/players-handbook-2024/archetypes/monk-open-hand.xml
> +			<stat name="wholeness of body:count" value="wisdom:modifier" bonus="base" />
```suggestion
		<sheet alt="Wholeness of Body" action="Bonus Action" usage="{{wholeness of body:usage}}/Long Rest">
			<description>You regain 1d{{martial arts:dice}}+{{wisdom:modifier}} Hit Points (minimum of 1).</description>
		</sheet>
		<rules>
			<stat name="wholeness of body:usage" value="1" bonus="base" />
			<stat name="wholeness of body:usage" value="wisdom:modifier" bonus="base" />
```

2025-04-18 02:51 UTC, NickVendel commented on core/players-handbook-2024/archetypes/monk-open-hand.xml
> +		<sheet action="Bonus Action" alt="Fleet Step">
```suggestion
		<sheet alt="Fleet Step">
```

2025-04-18 02:51 UTC, NickVendel commented on core/players-handbook-2024/archetypes/monk-open-hand.xml
> +			<description>When you hit a creature with an Unarmed Strike, you can start imperceptible vibrations, which last for {{level:monk}} days. The vibrations are harmless unless you take an action to en
```suggestion
			<p class="indent">You can have only one creature under the effect of this feature at a time. You can end the vibrations harmlessly (no action required).</p>
		</description>
		<sheet alt="Quivering Palm" usage="4 Focus Points" >
			<description>When you hit a creature with an Unarmed Strike, you can start imperceptible vibrations, which last for {{level:monk}} days. The vibrations are harmless unless you take an action or forgo one of the attacks to end them. To end them, you and the target must be on the same plane of existence. When you end them, the target must make a DC{{monks focus:dc}} Constitution saving throw, taking 10d12 Force damage on a failed save or half as much damage on a successful one. You can have only one creature under the effect of this feature at a time. You can end the vibrations harmlessly (no action required).</description>
```

2025-04-18 02:51 UTC, NickVendel commented on core/players-handbook-2024/archetypes/monk-open-hand.xml
> +	<element name="Wholeness of Body Feature Replacement" type="Grants" source="Internal" id="ID_INTERNAL_PHB24_FEATURE_REPLACEMENT_MONK_OPEN_HAND_WHOLENESS_OF_BODY" />
```suggestion
	<element name="Open Hand Technique Feature Replacement" type="Grants" source="Internal" id="ID_INTERNAL_PHB24_FEATURE_REPLACEMENT_MONK_OPEN_HAND_OPEN_HAND_TECHNIQUE" />
	<element name="Wholeness of Body Feature Replacement" type="Grants" source="Internal" id="ID_INTERNAL_PHB24_FEATURE_REPLACEMENT_MONK_OPEN_HAND_WHOLENESS_OF_BODY" />
```

2026-01-21 17:41 UTC, FreshRoyal approved these changes

2026-01-30 16:21 UTC, NickVendel requested changes
my file clearly had some issues, so i am fixing them in this short review

2026-01-30 16:21 UTC, NickVendel commented on core/players-handbook-2024/classes/class-monk.xml
> +				<tr><td><b>Hit Point Die</b></td><td class="left">D8 per Monk level</td></tr>
```suggestion
					<tr><td><b>Primary Ability</b></td><td class="left">Dexterity and Wisdom</td></tr>
					<tr><td><b>Hit Point Die</b></td><td class="left">D8 per Monk level</td></tr>
```

2026-01-30 16:21 UTC, NickVendel commented on core/players-handbook-2024/classes/class-monk.xml
> +			</table>
```suggestion
					<tr><td><b>Skill Proficiencies</b></td><td class="left"><i>Choose 2:</i> Acrobatics, Athletics, History, Insight, Religion, or Stealth</td></tr>
					<tr><td><b>Weapon Proficiencies</b></td><td class="left>">Simple weapons and Martial weapons that have the Light property</td></tr>
					<tr><td><b>Tool Proficiencies</b></td><td class="left"><i>Choose one type of Artisan's Tools or Musical Instrument</i></td></tr>
					<tr><td><b>Armor Training</b></td><td class="left">None</td></tr>
					<tr><td><b>Starting Equipment</b></td><td class="left"><i> Choose A or B:</i> (A) Spear, 5 Daggers, Artisan's Tools or Musical Instrument chosen for the tool proficiency above, Explorer's Pack, and ll GP; or (B) 50 GP</td></tr>
				</table>
```

2026-01-30 16:21 UTC, NickVendel commented on core/players-handbook-2024/classes/class-monk.xml
> +		<sheet alt="Marital Arts">
```suggestion
		<sheet alt="Martial Arts">
```

2026-01-30 16:21 UTC, NickVendel commented on core/players-handbook-2024/classes/class-monk.xml
> +	<element name="Level 9: Acrobatic Movement" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_MONK_ACROBATIC_MOVEMENT">
```suggestion
	</element>

	<element name="Level 9: Acrobatic Movement" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_MONK_ACROBATIC_MOVEMENT">
```

2026-01-30 16:21 UTC, NickVendel commented on core/players-handbook-2024/classes/class-monk.xml
> +	<element name="Level 10: Heightened Focus" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_MONK_HEIGHTENED_FOCUS">
```suggestion
	</element>

	<element name="Level 10: Heightened Focus" type="Class Feature" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_CLASS_FEATURE_MONK_HEIGHTENED_FOCUS">
```

2026-02-01 23:46 UTC, merged