[PHB24] Spells
AuroraLegacy/elements pull request #291
Opened 2024-11-22 07:29 UTC by MeriadarGoblin

Created spells with help from Tregolani.

2024-12-03 04:38 UTC, tregolani commented on core/players-handbook-2024/spells.xml
> +<elements>
Did a full review of the spells file, and found a bunch of typos in need of correcting in both of our sections. Would be over 100 different comments here, so I'm just uploading the file itself and you can review and merge it. 

[spells.zip](https://github.com/user-attachments/files/17987405/spells.zip)

2024-12-31 06:22 UTC, tregolani commented on core/players-handbook-2024/spells.xml
> +	</element>
Animal Messenger spell seems to be missing.
```suggestion
	</element>
	<element name="Animal Messenger" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_ANIMAL_MESSENGER">
		<supports>Bard, Druid, Ranger, Spell Saving Throw</supports>
		<description>
			<p>A Tiny Beast of your choice that you can see within range must succeed on a Charisma saving throw, or it attempts to deliver a message for you (if the target's Challenge Rating isn't 0, it automatically succeeds). You specify a location you have visited and a recipient who matches a general description, such as "a person dressed in the uniform of the town guard" or "a red-haired dwarf wearing a pointed hat." You also communicate a message of up to twenty-five words. The Beast travels for the duration toward the specified location, covering about 25 miles per 24 hours or 50 miles if the Beast can fly.</p>
			<p class="indent">When the Beast arrives, it delivers your message to the creature that you described, mimicking your communication. If the Beast doesn't reach its destination before the spell ends, the message is lost, and the Beast returns to where you cast the spell.</p>
			<p class="indent"><b><i>Using a Higher-Level Spell Slot.</i></b> The spell's duration increases by 48 hours for each spell slot level above 2.</p>
		</description>
		<setters>
			<set name="keywords"></set>
			<set name="level">2</set>
			<set name="school">Enchantment</set>
			<set name="time">Action or Ritual</set>
			<set name="range">30 feet</set>
			<set name="duration">24 hours</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="hasMaterialComponent">true</set>
			<set name="materialComponent">a morsel of food</set>
			<set name="isConcentration">false</set>
			<set name="isRitual">true</set>
		</setters>
	</element>
```

2025-01-01 08:34 UTC, MeriadarGoblin commented on core/players-handbook-2024/spells.xml
> +	</element>
got it, thanks!

2025-02-25 04:40 UTC, tregolani requested changes
Class list corrections to a handful of spells

2025-02-25 04:40 UTC, tregolani commented on core/players-handbook-2024/spells.xml
> +		<supports>Sorcerer, Wizard, Damaging Spell, Spell Saving Throw</supports>
```suggestion
		<supports>Artificer, Sorcerer, Wizard, Damaging Spell, Spell Saving Throw</supports>
```

2025-02-25 04:40 UTC, tregolani commented on core/players-handbook-2024/spells.xml
> +		<supports>Bard, Cleric, Druid, Paladin, Ranger, Healing Spell</supports>
```suggestion
		<supports>Artificer, Bard, Cleric, Druid, Paladin, Ranger, Healing Spell</supports>
```

2025-02-25 04:40 UTC, tregolani commented on core/players-handbook-2024/spells.xml
> +		<supports>Ranger, Wizard</supports>
```suggestion
		<supports>Artificer, Ranger, Wizard</supports>
```

2025-02-25 04:40 UTC, tregolani commented on core/players-handbook-2024/spells.xml
> +		<supports>Sorcerer, Wizard</supports>
```suggestion
		<supports>Artificer, Sorcerer, Wizard</supports>
```

2025-02-25 04:40 UTC, tregolani commented on core/players-handbook-2024/spells.xml
> +		<supports>Bard, Sorcerer, Wizard</supports>
```suggestion
		<supports>Artificer, Bard, Sorcerer, Wizard</supports>
```

2025-02-25 04:40 UTC, tregolani commented on core/players-handbook-2024/spells.xml
> +		<supports>Wizard</supports>
```suggestion
		<supports>Artificer, Wizard</supports>
```

2025-02-25 04:40 UTC, tregolani commented on core/players-handbook-2024/spells.xml
> +		<supports>Wizard</supports>
```suggestion
		<supports>Artificer, Wizard</supports>
```

2025-02-25 04:40 UTC, tregolani commented on core/players-handbook-2024/spells.xml
> +		<supports>Sorcerer, Wizard, Damaging Spell, Spell Saving Throw</supports>
```suggestion
		<supports>Artificer, Sorcerer, Wizard, Damaging Spell, Spell Saving Throw</supports>
```

2025-02-25 04:40 UTC, tregolani commented on core/players-handbook-2024/spells.xml
> +		<supports>Sorcerer, Wizard</supports>
```suggestion
		<supports>Artificer, Sorcerer, Wizard</supports>
```

2025-02-25 04:40 UTC, tregolani commented on core/players-handbook-2024/spells.xml
> +		<supports>Sorcerer, Wizard</supports>
```suggestion
		<supports>Artificer, Sorcerer, Wizard</supports>
```

2025-02-25 04:40 UTC, tregolani commented on core/players-handbook-2024/spells.xml
> +		<supports>Cleric, Druid, Wizard</supports>
```suggestion
		<supports>Artificer, Cleric, Druid, Wizard</supports>
```

2025-02-25 04:40 UTC, tregolani commented on core/players-handbook-2024/spells.xml
> +		<supports>Cleric, Paladin</supports>
```suggestion
		<supports>Artificer, Cleric, Paladin</supports>
```

2025-02-25 04:40 UTC, tregolani commented on core/players-handbook-2024/spells.xml
> +		<supports>Sorcerer, Wizard</supports>
```suggestion
		<supports>Artificer, Sorcerer, Wizard</supports>
```

2025-02-25 04:40 UTC, tregolani commented on core/players-handbook-2024/spells.xml
> +		<supports>Druid, Wizard, Damaging Spell, Spell Saving Throw</supports>
```suggestion
		<supports>Druid, Sorcerer, Wizard, Damaging Spell, Spell Saving Throw</supports>
```

2025-02-25 04:40 UTC, tregolani commented on core/players-handbook-2024/spells.xml
> +			<set
```suggestion
		<supports>Druid, Sorcerer, Wizard, Damaging Spell, Spell Saving Throw</supports>
```

2025-02-25 04:40 UTC, tregolani commented on core/players-handbook-2024/spells.xml
> +			<set
```suggestion
		<supports>Bard, Cleric, Healing Spell</supports>
```

2025-02-25 04:40 UTC, tregolani commented on core/players-handbook-2024/spells.xml
> +			<set
```suggestion
		<supports>Bard, Sorcerer, Wizard, Spell Saving Throw</supports>
```

2025-02-25 04:40 UTC, tregolani commented on core/players-handbook-2024/spells.xml
> +			<set
```suggestion
		<supports>Bard, Sorcerer, Warlock, Wizard</supports>
```

2025-02-25 04:40 UTC, tregolani commented on core/players-handbook-2024/spells.xml
> +			<set
```suggestion
		<supports>Sorcerer, Wizard, Damaging Spell, Spell Saving Throw</supports>
```

2025-02-25 04:40 UTC, tregolani commented on core/players-handbook-2024/spells.xml
> +			<set
```suggestion
	<element name="Power Word Fortify" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_POWER_WORD_FORTIFY">
		<supports>Bard, Cleric, Healing Spell</supports>
		<description>
			<p>You fortify up to six creatures you can see within range. The spell bestows 120 Temporary Hit Points, which you divide among the spell's recipients.</p>
		</description>
		<setters>
			<set name="keywords">thp</set>
			<set name="level">7</set>
			<set name="school">Enchantment</set>
			<set name="time">Action</set>
			<set name="duration">Instantaneous</set>
			<set name="range">60</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">false</set>
			<set name="hasMaterialComponent">false</set>
			<set name="materialComponent" />
			<set name="isConcentration">false</set>
			<set name="isRitual">false</set>
		</setters>
	</element>
	<element name="Power Word Heal" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_POWER_WORD_HEAL">
```

2025-02-25 04:40 UTC, tregolani commented on core/players-handbook-2024/spells.xml
> +			<set
```suggestion
		<supports>Bard, Wizard, Damaging Spell, Spell Saving Throw</supports>
```

2025-02-25 04:40 UTC, tregolani commented on core/players-handbook-2024/spells.xml
> +			<set
```suggestion
		<supports>Bard, Wizard</supports>
```

2025-02-25 04:40 UTC, tregolani commented on core/players-handbook-2024/spells.xml
> +			<set
```suggestion
		<supports>Cleric, Druid, Paladin, Ranger, Artificer, Healing Spell</supports>
```

2025-02-25 04:40 UTC, tregolani commented on core/players-handbook-2024/spells.xml
> +			<set
```suggestion
		<supports>Bard, Sorcerer, Wizard, Damaging Spell, Spell Saving Throw</supports>
```

2025-02-25 04:40 UTC, tregolani commented on core/players-handbook-2024/spells.xml
> +			<set
```suggestion
		<supports>Bard, Sorcerer, Warlock, Wizard</supports>
```

2025-02-25 04:40 UTC, tregolani commented on core/players-handbook-2024/spells.xml
> +			<set
```suggestion
		<supports>Warlock, Wizard, Damaging Spell, Spell Saving Throw</supports>
```

2025-12-09 04:32 UTC, tregolani reviewed
ID error I found

2025-12-09 04:32 UTC, tregolani commented on core/players-handbook-2024/spells.xml
> +	<element name="Commune with Nature" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_COMMUNE_WITH_NATURE">
```suggestion
	<element name="Commune with Nature" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_COMMUNE_WITH_NATURE">
```

2026-01-20 17:58 UTC, NickVendel requested changes
Part 1, planned to do more today, but got seriously distracted

2026-01-20 17:58 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +		<update version="0.0.3">
let's go back to first version, since there's no reason to start with `0.0.3`, unless i'm forgetting one
```suggestion
		<update version="0.0.1">
```

2026-01-20 17:58 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	<element name="Aid" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_AID">
vast majority of my suggestion in this PR are following the same logic (there are still some actual fixes though):
• adding keywords
• removing unused setters
• adding a blank line after the element
• moving `Artificer` support to be the first support, to keep the alphabetical logic for classes.
• placed statblocks for creatures under relevant spells, for easier referencing.

Also, just to clarify things with keywords right away, here's the rules for them that i personally follow:
**1\)** if potential keyword (or key-phrase) is used in `supports`, in `set`s or in the name of the element, it is ignored, as those are already treated as keywords. Example: `healing`, when `<supports>` already have `Healing Spell` support.
**2\)** if there's an alternative spellings for the keyword, they are added. Example: `save` or `damage`, as an alternative to existing `Saving Throw` and `Damaging Spell` supports.
**3\)** if existing keywords have synonyms or associated words that are appropriate, they are added. Example: `upcasting`, a common way to refer to the `Using a Higher-Level Spell Slot`-mechanic.
**4\)** if potential keyword already is a part of another keyword, it is ignored. Example: `attack rolls` keyword can be considered both it and `attack roll` (without `s`) support. (This in a way creates an issue where searching specifically for `attack roll` will bring up `attack rolls` as well, but i think it's a minor, and somewhat unavoidable, problem.)
**5\)** less so a rule, and more personal preference, i sometimes add names of features or subtitles/sub-effects of the spells to keywords as well, though not always, kinda depends on if i feel people would be searching for those or not. Example: `Control Water` has a bunch of sub-effects, such as `Whirlpool`, which i added as keywords.
**6\)** in a similar vein, i typically remove `summon` keywords from spells that don't actually give stats for the thing you're creating/summoning, such as Arcane Eye, as i feel like they're more of a single-goal utility spells rather than flexible "summon creature/thing, that can follow variety of commands"-spells.

back to actual suggestion now:
```suggestion
		<setters>
			<set name="keywords">sphere, damage, dexterity, save, upgrade</set>
			<set name="level">0</set>
			<set name="school">Evocation</set>
			<set name="time">Action</set>
			<set name="range">60 feet</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="duration">Instantaneous</set>
		</setters>
	</element>

	<element name="Aid" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_AID">
```

2026-01-20 17:58 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	<element name="Alarm" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_ALARM">
```suggestion
		<setters>
			<set name="keywords">upcasting, higher-level spell slot</set>
			<set name="level">2</set>
			<set name="school">Abjuration</set>
			<set name="time">Action</set>
			<set name="range">30 feet</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="hasMaterialComponent">true</set>
			<set name="materialComponent">a strip of white cloth</set>
			<set name="duration">8 hours</set>
		</setters>
	</element>

	<element name="Alarm" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_ALARM">
```

2026-01-20 17:58 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +			<p class="indent"><b><i>Mental Alarm.</i></b> You are alerted by a mental ping if you are within 1 mile of the warded area. This ping awakens you if you’re asleep.</p>
```suggestion
			<p style="text-indent: -1em; margin-left: 1em"><b><i>Audible Alarm.</i></b> The alarm produces the sound of a handbell for 10 seconds within 60 feet of the warded area.</p>
			<p style="text-indent: -1em; margin-left: 1em"><b><i>Mental Alarm.</i></b> You are alerted by a mental ping if you are within 1 mile of the warded area. This ping awakens you if you’re asleep.</p>
```

2026-01-20 17:58 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +			<set name="isConcentration">false</set>
```suggestion
```

2026-01-20 17:58 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
	</element>

```

2026-01-20 17:58 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	<element name="Animal Friendship" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_ANIMAL_FRIENDSHIP">
```suggestion
		<setters>
			<set name="keywords">underwater, breathing, swim speed, natural weapons, bludgeoning, piercing, slashing</set>
			<set name="level">2</set>
			<set name="school">Transmutation</set>
			<set name="time">Action</set>
			<set name="range">Self</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="isConcentration">true</set>
			<set name="duration">Concentration, up to 1 hour</set>
		</setters>
	</element>

	<element name="Animal Friendship" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_ANIMAL_FRIENDSHIP">
```

2026-01-20 17:58 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	<element name="Animal Messenger" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_ANIMAL_MESSENGER">
```suggestion
		<setters>
			<set name="keywords">beast, wisdom, charmed, upcasting, higher-level spell slot</set>
			<set name="level">1</set>
			<set name="school">Enchantment</set>
			<set name="time">Action</set>
			<set name="range">30 feet</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="hasMaterialComponent">true</set>
			<set name="materialComponent">a morsel of food</set>
			<set name="duration">24 hours</set>
		</setters>
	</element>

	<element name="Animal Messenger" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_ANIMAL_MESSENGER">
```

2026-01-20 17:58 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	<element name="Animal Shapes" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_ANIMAL_SHAPES">
```suggestion
		<setters>
			<set name="keywords">communication, beast, charisma, upcasting, higher-level spell slot</set>
			<set name="level">2</set>
			<set name="school">Enchantment</set>
			<set name="time">Action or Ritual</set>
			<set name="isRitual">true</set>
			<set name="range">30 feet</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="hasMaterialComponent">true</set>
			<set name="materialComponent">a morsel of food</set>
			<set name="duration">24 hours</set>
		</setters>
	</element>

	<element name="Animal Shapes" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_ANIMAL_SHAPES">
```

2026-01-20 17:58 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	<element name="Animate Dead" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_ANIMATE_DEAD">
```suggestion
		<setters>
			<set name="keywords">thp, beast, shapeshift</set>
			<set name="level">8</set>
			<set name="school">Transmutation</set>
			<set name="time">Action</set>
			<set name="range">30 feet</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="duration">24 hours</set>
		</setters>
	</element>

	<element name="Animate Dead" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_ANIMATE_DEAD">
```

2026-01-20 17:58 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +			<p>Choose a pile of bones or a corpse of a Medium or Small Humanoid within range. The target becomes an Undead creature: a Skeleton if you chose bones or a Zombie if you chose a corpse (see append
```suggestion
			<p>Choose a pile of bones or a corpse of a Medium or Small Humanoid within range. The target becomes an Undead creature: a <b>Skeleton</b> if you chose bones or a <b>Zombie</b> if you chose a corpse (see <i>Player's Handbook (2024)</i> pages 356 (Skeleton) and 359 (Zombie) for stat-blocks).</p>
```

2026-01-20 17:58 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	<element name="Animate Objects" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_ANIMATE_OBJECTS">
```suggestion
			<!-- to do: add a reference to Information type stat-blocks for Skeleton and Zombie here. Then remove "(see <i>Player's Handbook (2024)</i> pages 356 (Skeleton) and 359 (Zombie) for stat-blocks)" part at the end of first paragraph. -->
		</description>
		<setters>
			<set name="keywords">control, humanoid, undead, skeleton, zombie, bonus action, upcasting, higher-level spell slot</set>
			<set name="level">3</set>
			<set name="school">Necromancy</set>
			<set name="time">1 minute</set>
			<set name="range">10 feet</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="hasMaterialComponent">true</set>
			<set name="materialComponent">a drop of blood, a piece of flesh, and a pinch of bone dust</set>
			<set name="duration">Instantaneous</set>
		</setters>
	</element>

	<element name="Animate Objects" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_ANIMATE_OBJECTS">
```

2026-01-20 17:58 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +		</setters>
```suggestion
			<div class="reference">
				<div element="ID_WOTC_PHB24_INFORMATION_ANIMATED_OBJECT" />
			</div>
		</description>
		<setters>
			<set name="keywords">summon, upcasting, higher-level spell slot</set>
			<set name="level">5</set>
			<set name="school">Transmutation</set>
			<set name="time">Action</set>
			<set name="range">120 feet</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="isConcentration">true</set>
			<set name="duration">Concentration, up to 1 minute</set>
		</setters>
```

2026-01-20 17:58 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	<element name="Antilife Shell" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_ANTILIFE_SHELL">
```suggestion
	</element>
	<element name="Animated Object" type="Information" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_INFORMATION_ANIMATED_OBJECT">
		<description>
			<p style="margin-bottom:5px"><em>Huge or Smaller Construct, Unaligned</em></p>
			<ul class="unstyled">
				<li><strong>AC</strong> 15</li>
				<li><strong>HP</strong> 10 (Medium or smaller), 20 (Large), 40 (Huge)</li>
				<li><strong>Speed</strong> 30 ft.</li>
			</ul>
			<table style="text-align:center;margin-top:2px;margin-bottom:10px">
				<tr style="font-size:8px"><td colspan="2" /><td>MOD</td><td>SAVE</td><td colspan="2" /><td>MOD</td><td>SAVE</td><td colspan="2" /><td>MOD</td><td>SAVE</td></tr>
				<tr><td><b>STR</b></td><td>16</td><td>+3</td><td>+3</td><td><b>DEX</b></td><td>10</td><td>+0</td><td>+0</td><td><b>CON</b></td><td>10</td><td>+0</td><td>+0</td></tr>
				<tr><td><b>INT</b></td><td>3</td><td>-4</td><td>-4</td><td><b>WIS</b></td><td>3</td><td>-4</td><td>-4</td><td><b>CHA</b></td><td>1</td><td>-5</td><td>-5</td></tr>
			</table>
			<ul class="unstyled">
				<li><strong>Immunities</strong> Poison, Psychic; Charmed, Exhaustion, Frightened, Paralyzed, Poisoned</li>
				<li><strong>Senses</strong> Blindsight 30 ft., Passive Perception 6</li>
				<li><strong>Languages</strong> Understands the languages you know</li>
				<li><strong>CR</strong> None (XP 0; PB equals your Proficiency Bonus)</li>
			</ul>
			<h4 style="margin-top:5px">Actions</h4>
			<ul class="unstyled">
				<li><em><strong>Slam.</strong> Melee Attack Roll:</em> Bonus equals your spell attack modifier, reach 5 ft. <em>Hit:</em> Force damage equal to 1d4 + 3 (Medium or smaller), 2d6 + 3 + your spellcasting ability modifier (Large), or 2d12 + 3 + your spellcasting ability modifier (Huge).</li>
			</ul>
		</description>
	</element>

	<element name="Antilife Shell" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_ANTILIFE_SHELL">
```

2026-01-20 17:58 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	<element name="Antimagic Field" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_ANTIMAGIC_FIELD">
```suggestion
		<setters>
			<set name="keywords">aura, emanation</set>
			<set name="level">5</set>
			<set name="school">Abjuration</set>
			<set name="time">Action</set>
			<set name="range">Self (10-foot Emanation)</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="isConcentration">true</set>
			<set name="duration">Concentration, up to 1 hour</set>
		</setters>
	</element>

	<element name="Antimagic Field" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_ANTIMAGIC_FIELD">
```

2026-01-20 17:58 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	<element name="Antipathy/Sympathy" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_ANTIPATHY_SYMPATHY">
```suggestion
		<setters>
			<set name="keywords">aura, emanation</set>
			<set name="level">8</set>
			<set name="school">Abjuration</set>
			<set name="time">Action</set>
			<set name="range">Self (10-foot Emanation)</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="hasMaterialComponent">true</set>
			<set name="materialComponent">iron filings</set>
			<set name="isConcentration">true</set>
			<set name="duration">Concentration, up to 1 hour</set>
		</setters>
	</element>

	<element name="Antipathy/Sympathy" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_ANTIPATHY_SYMPATHY">
```

2026-01-20 17:58 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +			<p><b>Sympathy.</b> The creature has the Charmed condition. The Charmed creature must use its movement on its turns to get as close as possible to the target, moving by the safest route. If the cr
```suggestion
			<p style="text-indent: -1em; margin-left: 1em"><b>Antipathy.</b> The creature has the Frightened condition. The Frightened creature must use its movement on its turns to get as far away as possible from the target, moving by the safest route.</p>
			<p style="text-indent: -1em; margin-left: 1em"><b>Sympathy.</b> The creature has the Charmed condition. The Charmed creature must use its movement on its turns to get as close as possible to the target, moving by the safest route. If the creature is within 5 feet of the target, the creature can’t willingly move away. If the target damages the Charmed creature, that creature can make a Wisdom saving throw to end the effect, as described below.</p>
```

2026-01-20 17:58 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	<element name="Arcane Eye" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_ARCANE_EYE">
```suggestion
		<setters>
			<set name="keywords">wisdom, save, charmed, frightened</set>
			<set name="level">8</set>
			<set name="school">Enchantment</set>
			<set name="time">1 hour</set>
			<set name="range">60 feet</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="hasMaterialComponent">true</set>
			<set name="materialComponent">a mix of vinegar and honey</set>
			<set name="duration">10 days</set>
		</setters>
	</element>

	<element name="Arcane Eye" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_ARCANE_EYE">
```

2026-01-20 17:58 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	<element name="Arcane Gate" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_ARCANE_GATE">
```suggestion
		<setters>
			<set name="keywords">bonus action, darkvision</set>
			<set name="level">4</set>
			<set name="school">Divination</set>
			<set name="time">Action</set>
			<set name="range">30 feet</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="hasMaterialComponent">true</set>
			<set name="materialComponent">a bit of bat fur</set>
			<set name="isConcentration">true</set>
			<set name="duration">Concentration, up to 1 hour</set>
		</setters>
	</element>

	<element name="Arcane Gate" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_ARCANE_GATE">
```

2026-01-20 17:58 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	<element name="Arcane Lock" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_ARCANE_LOCK">
```suggestion
		<setters>
			<set name="keywords">teleport, portal, bonus action</set>
			<set name="level">6</set>
			<set name="school">Conjuration</set>
			<set name="time">Action</set>
			<set name="range">500 feet</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="isConcentration">true</set>
			<set name="duration">Concentration, up to 10 minutes</set>
		</setters>
	</element>

	<element name="Arcane Lock" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_ARCANE_LOCK">
```

2026-01-20 17:58 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	<element name="Arcane Vigor" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_ARCANE_VIGOR">
```suggestion
		<setters>
			<set name="keywords"></set>
			<set name="level">2</set>
			<set name="school">Abjuration</set>
			<set name="time">Action</set>
			<set name="range">Touch</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="hasMaterialComponent">true</set>
			<set name="materialComponent">gold dust worth 25+ GP, which the spell consumes</set>
			<set name="duration">Until dispelled</set>
		</setters>
	</element>

	<element name="Arcane Vigor" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_ARCANE_VIGOR">
```

2026-01-20 17:58 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	<element name="Armor of Agathys" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_ARMOR_OF_AGATHYS">
```suggestion
		<setters>
			<set name="keywords">hit point dice, hp dice, hit dice, hd, upcasting, higher-level spell slot</set>
			<set name="level">2</set>
			<set name="school">Abjuration</set>
			<set name="time">Bonus Action</set>
			<set name="range">Self</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="duration">Instantaneous</set>
		</setters>
	</element>

	<element name="Armor of Agathys" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_ARMOR_OF_AGATHYS">
```

2026-01-20 17:58 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	<element name="Arms of Hadar" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_ARMS_OF_HADAR">
```suggestion
		<setters>
			<set name="keywords">thp, cold, damage, upcasting, higher-level spell slot</set>
			<set name="level">1</set>
			<set name="school">Abjuration</set>
			<set name="time">Bonus Action</set>
			<set name="range">Self</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="hasMaterialComponent">true</set>
			<set name="materialComponent">a shard of blue glass</set>
			<set name="duration">1 hour</set>
		</setters>
	</element>

	<element name="Arms of Hadar" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_ARMS_OF_HADAR">
```

2026-01-20 17:58 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	<element name="Astral Projection" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_ASTRAL_PROJECTION">
```suggestion
		<setters>
			<set name="keywords">emanation, strength, save, necrotic, damage, upcasting, higher-level spell slot</set>
			<set name="level">1</set>
			<set name="school">Conjuration</set>
			<set name="time">Action</set>
			<set name="range">Self (10-foot Emanation)</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="duration">Instantaneous</set>
		</setters>
	</element>

	<element name="Astral Projection" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_ASTRAL_PROJECTION">
```

2026-01-20 17:58 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	<element name="Augury" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_AUGURY">
```suggestion
		<setters>
			<set name="keywords">planar travel, astral plane</set>
			<set name="level">9</set>
			<set name="school">Necromancy</set>
			<set name="time">1 hour</set>
			<set name="range">10 feet</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="hasMaterialComponent">true</set>
			<set name="materialComponent">for each of the spell’s targets, one jacinth worth 1,000+ GP and one silver bar worth 100+ GP, all of which the spell consumes</set>
			<set name="duration">Until dispelled</set>
		</setters>
	</element>

	<element name="Augury" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_AUGURY">
```

2026-01-20 17:58 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +					<tr><td class="col-10">Omen</td><td>For Results That Will Be...</td></tr>
```suggestion
					<tr><td class="col-20">Omen</td><td>For Results That Will Be...</td></tr>
```

2026-01-20 17:58 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	<element name="Aura of Life" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_AURA_OF_LIFE">
```suggestion
		<setters>
			<set name="keywords">omen, weal, woe</set>
			<set name="level">2</set>
			<set name="school">Divination</set>
			<set name="time">1 minute or Ritual</set>
			<set name="isRitual">true</set>
			<set name="range">Self</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="hasMaterialComponent">true</set>
			<set name="materialComponent">specially marked sticks, bones, cards, or other divinatory tokens worth 25+ GP</set>
			<set name="duration">Instantaneous</set>
		</setters>
	</element>

	<element name="Aura of Life" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_AURA_OF_LIFE">
```

2026-01-20 17:58 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	<element name="Aura of Purity" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_AURA_OF_PURITY">
```suggestion
		<setters>
			<set name="keywords">emanation, resistance, necrotic</set>
			<set name="level">4</set>
			<set name="school">Abjuration</set>
			<set name="time">Action</set>
			<set name="range">Self (30-foot Emanation)</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">false</set>
			<set name="isConcentration">true</set>
			<set name="duration">Concentration, up to 10 minutes</set>
		</setters>
	</element>

	<element name="Aura of Purity" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_AURA_OF_PURITY">
```

2026-01-20 17:58 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	<element name="Aura of Vitality" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_AURA_OF_VITALITY">
```suggestion
		<setters>
			<set name="keywords">emanation, resistance, poison, advantage, charmed, deafened, frightened, paralyzed, poisoned, stunned</set>
			<set name="level">4</set>
			<set name="school">Abjuration</set>
			<set name="time">Action</set>
			<set name="range">Self (30-foot Emanation)</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">false</set>
			<set name="isConcentration">true</set>
			<set name="duration">Concentration, up to 10 minutes</set>
		</setters>
	</element>

	<element name="Aura of Vitality" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_AURA_OF_VITALITY">
```

2026-01-20 17:58 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	<element name="Awaken" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_AWAKEN">
```suggestion
		<setters>
			<set name="keywords">emanation</set>
			<set name="level">3</set>
			<set name="school">Abjuration</set>
			<set name="time">Action</set>
			<set name="range">Self (30-foot Emanation)</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">false</set>
			<set name="isConcentration">true</set>
			<set name="duration">Concentration, up to 1 minute</set>
		</setters>
	</element>

	<element name="Awaken" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_AWAKEN">
```

2026-01-20 17:58 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +			<p class="indent">The awakened target has the Charmed condition for 30 days or until you or your allies deal damage to it. When that condition ends, the awakened creature chooses its attitude towa
```suggestion
			<p>You spend the casting time tracing magical pathways within a precious gemstone, and then touch the target. The target must be either a Beast or Plant creature with an Intelligence of 3 or less or a natural plant that isn’t a creature. The target gains an Intelligence of 10 and the ability to speak one language you know. If the target is a natural plant, it becomes a Plant creature and gains the ability to move its limbs, roots, vines, creepers, and so forth, and it gains senses similar to a human’s. The DM chooses statistics appropriate for the awakened Plant, such as the statistics for the <b>Awakened Shrub</b> or <b>Awakened Tree</b> (see page 23 of <i>Monster Manual (2025)</i> for stat-blocks).</p>
			<p class="indent">The awakened target has the Charmed condition for 30 days or until you or your allies deal damage to it. When that condition ends, the awakened creature chooses its attitude toward you.</p>
			<!-- to do: add a reference to Information type stat-blocks for Awakened Shrub and Awakened Tree here. Then replace "(see page 23 of <i>Monster Manual (2025)</i> for stat-blocks)" part at the end of first paragraph with original "in the <i>Monster Manual (2025)</i>". -->
```

2026-01-20 17:58 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	<element name="Bane" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_BANE">
```suggestion
		<setters>
			<set name="keywords">beast, plant, intelligence, sentience, charmed</set>
			<set name="level">5</set>
			<set name="school">Transmutation</set>
			<set name="time">8 hours</set>
			<set name="range">Touch</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="hasMaterialComponent">true</set>
			<set name="materialComponent">an agate worth 1,000+ GP, which the spell consumes</set>
			<set name="duration">Instantaneous</set>
		</setters>
	</element>

	<element name="Bane" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_BANE">
```

2026-01-20 17:58 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +			<p>Up to three creatures of your choice that you can see within range must each make a Charisma saving throw. Whenever a target that fails this save makes an attack roll or a saving throw before t
```suggestion
			<p>Up to three creatures of your choice that you can see within range must each make a Charisma saving throw. Whenever a target that fails this save makes an attack roll or a saving throw before the spell ends, the target must subtract 1d4 from the attack roll or save.</p>
			<p class="indent"><b><i>Using a Higher-Level Spell Slot.</i></b> You can target one additional creature for each spell slot level above 1.</p>
```

2026-01-20 17:58 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	<element name="Banishing Smite" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_BANISHING_SMITE">
```suggestion
		<setters>
			<set name="keywords">charisma, save, debuff, upcasting, higher-level spell slot</set>
			<set name="level">1</set>
			<set name="school">Enchantment</set>
			<set name="time">Action</set>
			<set name="range">30 feet</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="hasMaterialComponent">true</set>
			<set name="materialComponent">a drop of blood</set>
			<set name="isConcentration">true</set>
			<set name="duration">Concentration, up to 1 minute</set>
		</setters>
	</element>

	<element name="Banishing Smite" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_BANISHING_SMITE">
```

2026-01-20 17:58 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	<element name="Banishment" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_BANISHMENT">
```suggestion
		<setters>
			<set name="keywords">on hit, melee, weapon, unarmed strike, force, damage, charisma, save, incapacitated</set>
			<set name="level">5</set>
			<set name="school">Conjuration</set>
			<set name="time">Bonus Action, which you take immediately after hitting a creature with a Melee weapon or an Unarmed Strike</set>
			<set name="range">Self</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">false</set>
			<set name="isConcentration">true</set>
			<set name="duration">Concentration, up to 1 minute</set>
		</setters>
	</element>

	<element name="Banishment" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_BANISHMENT">
```

2026-01-20 17:58 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	<element name="Barkskin" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_BARKSKIN">
```suggestion
		<setters>
			<set name="keywords">charisma, save, incapacitated, upcasting, higher-level spell slot</set>
			<set name="level">4</set>
			<set name="school">Abjuration</set>
			<set name="time">Action</set>
			<set name="range">30 feet</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="hasMaterialComponent">true</set>
			<set name="materialComponent">a pentacle</set>
			<set name="isConcentration">true</set>
			<set name="duration">Concentration, up to 1 minute</set>
		</setters>
	</element>

	<element name="Barkskin" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_BARKSKIN">
```

2026-01-20 17:58 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	<element name="Beacon of Hope" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_BEACON_OF_HOPE">
```suggestion
		<setters>
			<set name="keywords">armor class, ac, buff</set>
			<set name="level">2</set>
			<set name="school">Transmutation</set>
			<set name="time">Bonus Action</set>
			<set name="range">Touch</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="hasMaterialComponent">true</set>
			<set name="materialComponent">a handful of bark</set>
			<set name="duration">1 hour</set>
		</setters>
	</element>

	<element name="Beacon of Hope" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_BEACON_OF_HOPE">
```

2026-01-20 17:58 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +		<supports>Cleric, Spell Saving Throw, Healing Spell</supports>
spell itself doesn't provide any healing, so i will remove the supports, but i'll add `healing` as keyword, since it does affect it.
```suggestion
		<supports>Cleric, Spell Saving Throw</supports>
```

2026-01-20 17:58 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	<element name="Beast Sense" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_BEAST_SENSE">
```suggestion
		<setters>
			<set name="keywords">advantage, death saving throws, death saves, healing, buff</set>
			<set name="level">3</set>
			<set name="school">Abjuration</set>
			<set name="time">Action</set>
			<set name="range">30 feet</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="isConcentration">true</set>
			<set name="duration">Concentration, up to 1 minute</set>
		</setters>
	</element>

	<element name="Beast Sense" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_BEAST_SENSE">
```

2026-01-20 17:58 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	<element name="Befuddlement" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_BEFUDDLEMENT">
```suggestion
		<setters>
			<set name="keywords"></set>
			<set name="level">2</set>
			<set name="school">Divination</set>
			<set name="time">Action or Ritual</set>
			<set name="isRitual">true</set>
			<set name="range">Touch</set>
			<set name="hasVerbalComponent">false</set>
			<set name="hasSomaticComponent">true</set>
			<set name="isConcentration">true</set>
			<set name="duration">Concentration, up to 1 hour</set>
		</setters>
	</element>

	<element name="Befuddlement" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_BEFUDDLEMENT">
```

2026-01-20 17:58 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	<element name="Bestow Curse" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_BESTOW_CURSE">
```suggestion
		<setters>
			<set name="keywords">intelligence, save, psychic</set>
			<set name="level">8</set>
			<set name="school">Enchantment</set>
			<set name="time">Action</set>
			<set name="range">150 feet</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="hasMaterialComponent">true</set>
			<set name="materialComponent">a key ring with no keys</set>
			<set name="duration">Instantaneous</set>
		</setters>
	</element>

	<element name="Bestow Curse" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_BESTOW_CURSE">
```

2026-01-20 17:58 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	<element name="Bigby's Hand" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_BIGBYS_HAND">
```suggestion
		<setters>
			<set name="keywords">wisdom, save, disadvantage, ability checks, attack rolls, necrotic, damage</set>
			<set name="level">3</set>
			<set name="school">Necromancy</set>
			<set name="time">Action</set>
			<set name="range">Touch</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="isConcentration">true</set>
			<set name="duration">Concentration, up to 1 minute</set>
		</setters>
	</element>

	<element name="Bigby's Hand" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_BIGBYS_HAND">
```

2026-01-20 17:58 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +			<p class="indent"><b><i>Using a Higher-Level Spell Slot.</i></b> The damage of the Clenched Fist increases by 2d8 and the damage of the Grasping Hand increases by 2d6 for each spell slot level abo
```suggestion
			<p class="indent">The hand an object that has AC 20 and Hit Points equal to your Hit Point maximum. If it drops to 0 Hit Points, the spell ends. The hand doesn’t occupy its space.</p>
			<p class="indent">When you cast the spell and as a Bonus Action on your later turns, you can move the hand up to 60  feet and then cause one of the following effects:</p>
			<p style="text-indent: -1em; margin-left: 1em"><b>Clenched Fist.</b> The hand strikes a target within 5 feet of it. Make a melee spell attack. On a hit, the target takes 5d8 Force damage.</p>
			<p style="text-indent: -1em; margin-left: 1em"><b>Forceful Hand.</b> The hand attempts to push a Huge or smaller creature within 5 feet of it. The target must succeed on a Strength saving throw, or the hand pushes the target up to 5 feet plus a number of feet equal to five times your spellcasting ability modifier. The hand moves with the target, remaining within 5 feet of it.</p>
			<p style="text-indent: -1em; margin-left: 1em"><b>Grasping Hand.</b> The hand attempts to grapple a Huge or smaller creature within 5 feet of it. The target must succeed on a Dexterity saving throw, or the target has the Grappled condition, with an escape DC equal to your spell save DC. While the hand grapples the target, you can take a Bonus Action to cause the hand to crush it, dealing Bludgeoning damage to the target equal to 4d6 plus your spellcasting ability modifier.</p>
			<p style="text-indent: -1em; margin-left: 1em"><b>Interposing Hand.</b> The hand grants you Half Cover against attacks and other effects that originate from its space or that pass through it. In addition, its space counts as Difficult Terrain for your enemies.</p>
			<p class="indent"><b><i>Using a Higher-Level Spell Slot.</i></b> The damage of the Clenched Fist increases by 2d8 and the damage of the Grasping Hand increases by 2d6 for each spell slot level above 5.</p>
```

2026-01-20 17:58 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	<element name="Blade Barrier" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_BLADE_BARRIER">
```suggestion
		<setters>
			<set name="keywords">summon, bludgeoning, force, damage, bonus action, strength, dexterity, save, grappled, cover, difficult terrain, upcasting, higher-level spell slot</set>
			<set name="level">5</set>
			<set name="school">Evocation</set>
			<set name="time">Action</set>
			<set name="range">120 feet</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="hasMaterialComponent">true</set>
			<set name="materialComponent">an eggshell and a glove</set>
			<set name="isConcentration">true</set>
			<set name="duration">Concentration, up to 1 minute</set>
		</setters>
	</element>

	<element name="Blade Barrier" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_BLADE_BARRIER">
```

2026-01-20 17:58 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	<element name="Blade Ward" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_BLADE_WARD">
```suggestion
		<setters>
			<set name="keywords">wall, force, damage, difficult terrain, cover, dexterity, save, blade wall</set>
			<set name="level">6</set>
			<set name="school">Evocation</set>
			<set name="time">Action</set>
			<set name="range">90 feet</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="isConcentration">true</set>
			<set name="duration">Concentration, up to 10 minutes</set>
		</setters>
	</element>

	<element name="Blade Ward" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_BLADE_WARD">
```

2026-01-20 17:58 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	<element name="Bless" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_BLESS">
```suggestion
		<setters>
			<set name="keywords">attack rolls, buff, debuff</set>
			<set name="level">0</set>
			<set name="school">Abjuration</set>
			<set name="time">Action</set>
			<set name="range">Self</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="isConcentration">true</set>
			<set name="duration">Concentration, up to 1 minute</set>
		</setters>
	</element>

	<element name="Bless" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_BLESS">
```

2026-01-20 17:58 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	<element name="Blight" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_BLIGHT">
```suggestion
		<setters>
			<set name="keywords">buff, attack rolls, save, upcasting, higher-level spell slot</set>
			<set name="level">1</set>
			<set name="school">Enchantment</set>
			<set name="time">Action</set>
			<set name="range">30 feet</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="hasMaterialComponent">true</set>
			<set name="materialComponent">a Holy Symbol worth 5+ GP</set>
			<set name="isConcentration">true</set>
			<set name="duration">Concentration, up to 1 minute</set>
		</setters>
	</element>

	<element name="Blight" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_BLIGHT">
```

2026-01-20 17:58 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +			<p>A creature that you can see within range makes a Constitution saving throw, taking 8d8 Necrotic damage on a failed save or half as much damage on a successful one. A Plant creature automaticall
```suggestion
			<p>A creature that you can see within range makes a Constitution saving throw, taking 8d8 Necrotic damage on a failed save or half as much damage on a successful one. A Plant creature automatically fails the save.</p>
```

2026-01-20 17:58 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	<element name="Blinding Smite" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_BLINDING_SMITE">
```suggestion
		<setters>
			<set name="keywords">constitution, save, necrotic, damage, plant, upcasting, higher-level spell slot</set>
			<set name="level">4</set>
			<set name="school">Necromancy</set>
			<set name="time">Action</set>
			<set name="range">30 feet</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="duration">Instantaneous</set>
		</setters>
	</element>

	<element name="Blinding Smite" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_BLINDING_SMITE">
```

2026-01-20 17:58 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	<element name="Blindness/Deafness" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_BLINDNESS_DEAFNESS">
```suggestion
		<setters>
			<set name="keywords">on hit, melee, weapon, unarmed strike, radiant, damage, blinded, constitution, save, upcasting, higher-level spell slot</set>
			<set name="level">3</set>
			<set name="school">Evocation</set>
			<set name="time">Bonus Action, which you take immediately after hitting a creature with a Melee weapon or an Unarmed Strike</set>
			<set name="range">Self</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">false</set>
			<set name="duration">1 minute</set>
		</setters>
	</element>

	<element name="Blindness/Deafness" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_BLINDNESS_DEAFNESS">
```

2026-01-21 14:26 UTC, NickVendel requested changes
Part 2

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	<element name="Blink" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_BLINK">
```suggestion
		<setters>
			<set name="keywords">constitution, save, blinded, deafened, upcasting, higher-level spell slot</set>
			<set name="level">2</set>
			<set name="school">Transmutation</set>
			<set name="time">Action</set>
			<set name="range">120 feet</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">false</set>
			<set name="duration">1 minute</set>
		</setters>
	</element>

	<element name="Blink" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_BLINK">
```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	<element name="Blur" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_BLUR">
```suggestion
		<setters>
			<set name="keywords">planar travel, ethereal plane</set>
			<set name="level">3</set>
			<set name="school">Transmutation</set>
			<set name="time">Action</set>
			<set name="range">Self</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="duration">1 minute</set>
		</setters>
	</element>

	<element name="Blur" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_BLUR">
```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	<element name="Burning Hands" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_BURNING_HANDS">
```suggestion
		<setters>
			<set name="keywords">buff, disadvantage, attack rolls</set>
			<set name="level">2</set>
			<set name="school">Illusion</set>
			<set name="time">Action</set>
			<set name="range">Self</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">false</set>
			<set name="isConcentration">true</set>
			<set name="duration">Concentration, up to 1 minute</set>
		</setters>
	</element>

	<element name="Burning Hands" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_BURNING_HANDS">
```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	<element name="Call Lightning" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_CALL_LIGHTNING">
```suggestion
		<setters>
			<set name="keywords">cone, dexterity, save, fire, damage, upcasting, higher-level spell slot</set>
			<set name="level">1</set>
			<set name="school">Evocation</set>
			<set name="time">Action</set>
			<set name="range">Self (15-foot Cone)</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="duration">Instantaneous</set>
		</setters>
	</element>

	<element name="Call Lightning" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_CALL_LIGHTNING">
```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	<element name="Calm Emotions" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_CALM_EMOTIONS">
```suggestion
		<setters>
			<set name="keywords">cylinder, dexterity, save, lightning, damage</set>
			<set name="level">3</set>
			<set name="school">Conjuration</set>
			<set name="time">Action</set>
			<set name="range">120 feet</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="isConcentration">true</set>
			<set name="duration">Concentration, up to 10 minutes</set>
		</setters>
	</element>

	<element name="Calm Emotions" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_CALM_EMOTIONS">
```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	<element name="Chain Lightning" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_CHAIN_LIGHTNING">
```suggestion
		<setters>
			<set name="keywords">sphere, charisma, save, immunity, charmed, frightened</set>
			<set name="level">2</set>
			<set name="school">Enchantment</set>
			<set name="time">Action</set>
			<set name="range">60 feet</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="isConcentration">true</set>
			<set name="duration">Concentration, up to 1 minute</set>
		</setters>
	</element>

	<element name="Chain Lightning" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_CHAIN_LIGHTNING">
```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	<element name="Charm Monster" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_CHARM_MONSTER">
```suggestion
		<setters>
			<set name="keywords">dexterity, save, lightning, damage, upcasting, higher-level spell slot</set>
			<set name="level">6</set>
			<set name="school">Evocation</set>
			<set name="time">Action</set>
			<set name="range">150 feet</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="hasMaterialComponent">true</set>
			<set name="materialComponent">three silver pins</set>
			<set name="duration">Instantaneous</set>
		</setters>
	</element>

	<element name="Charm Monster" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_CHARM_MONSTER">
```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	<element name="Charm Person" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_CHARM_PERSON">
```suggestion
		<setters>
			<set name="keywords">wisdom, save, charmed, upcasting, higher-level spell slot</set>
			<set name="level">4</set>
			<set name="school">Enchantment</set>
			<set name="time">Action</set>
			<set name="range">30 feet</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="duration">1 hour</set>
		</setters>
	</element>

	<element name="Charm Person" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_CHARM_PERSON">
```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	<element name="Chill Touch" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_CHILL_TOUCH">
```suggestion
		<setters>
			<set name="keywords">wisdom, save, charmed, upcasting, higher-level spell slot</set>
			<set name="level">1</set>
			<set name="school">Enchantment</set>
			<set name="time">Action</set>
			<set name="range">30 feet</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="duration">1 hour</set>
		</setters>
	</element>

	<element name="Chill Touch" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_CHILL_TOUCH">
```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	<element name="Chromatic Orb" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_CHROMATIC_ORB">
```suggestion
		<setters>
			<set name="keywords">necrotic, damage, upgrade</set>
			<set name="level">0</set>
			<set name="school">Necromancy</set>
			<set name="time">Action</set>
			<set name="range">Touch</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="duration">Instantaneous</set>
		</setters>
	</element>

	<element name="Chromatic Orb" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_CHROMATIC_ORB">
```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	<element name="Circle of Death" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_CIRCLE_OF_DEATH">
```suggestion
		<setters>
			<set name="keywords">acid, cold, fire, lightning, poison, thunder, damage, upcasting, higher-level spell slot</set>
			<set name="level">1</set>
			<set name="school">Evocation</set>
			<set name="time">Action</set>
			<set name="range">90 feet</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="hasMaterialComponent">true</set>
			<set name="materialComponent">a diamond worth 50+ GP</set>
			<set name="duration">Instantaneous</set>
		</setters>
	</element>

	<element name="Circle of Death" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_CIRCLE_OF_DEATH">
```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	<element name="Circle of Power" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_CIRCLE_OF_POWER">
```suggestion
		<setters>
			<set name="keywords">sphere, constitution, save, necrotic, damage, upcasting, higher-level spell slot</set>
			<set name="level">6</set>
			<set name="school">Necromancy</set>
			<set name="time">Action</set>
			<set name="range">150 feet</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="hasMaterialComponent">true</set>
			<set name="materialComponent">the powder of a crushed black pearl worth 500+ GP</set>
			<set name="duration">Instantaneous</set>
		</setters>
	</element>

	<element name="Circle of Power" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_CIRCLE_OF_POWER">
```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	<element name="Clairvoyance" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_CLAIRVOYANCE">
```suggestion
		<setters>
			<set name="keywords">aura, emanation, advantage, saving throws, saves, evasion, buff</set>
			<set name="level">5</set>
			<set name="school">Abjuration</set>
			<set name="time">Action</set>
			<set name="range">Self (30-foot Emanation)</set>
			<set name="hasVerbalComponent">true</set>
			<set name="isConcentration">true</set>
			<set name="duration">Concentration, up to 10 minutes</set>
		</setters>
	</element>

	<element name="Clairvoyance" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_CLAIRVOYANCE">
```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +			<p class="indent">A creature that sees the sensor (such as a creature benefiting from See Invisibility or Truesight) sees a luminous orb about the size of your fist.</p>
```suggestion
			<p class="indent">A creature that sees the sensor (such as a creature benefiting from <i>See Invisibility</i> or Truesight) sees a luminous orb about the size of your fist.</p>
```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	<element name="Clone" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_CLONE">
```suggestion
		<setters>
			<set name="keywords">sensor, seeing, hearing, bonus action</set>
			<set name="level">3</set>
			<set name="school">Divination</set>
			<set name="time">10 minutes</set>
			<set name="range">1 mile</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="hasMaterialComponent">true</set>
			<set name="materialComponent">a focus worth 100+ GP, either a jeweled horn for hearing or a glass eye for seeing</set>
			<set name="isConcentration">true</set>
			<set name="duration">Concentration, up to 10 minutes</set>
		</setters>
	</element>

	<element name="Clone" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_CLONE">
```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +		</setters>
```suggestion
		<setters>
			<set name="keywords"></set>
			<set name="level">8</set>
			<set name="school">Necromancy</set>
			<set name="time">1 hour</set>
			<set name="range">Touch</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="hasMaterialComponent">true</set>
			<set name="materialComponent">a diamond worth 1,000+ GP, which the spell consumes, and a sealable vessel worth 2,000+ GP that is large enough to hold the creature being cloned</set>
			<set name="duration">Instantaneous</set>
		</setters>
```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	<element name="Cloud of Daggers" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_CLOUD_OF_DAGGERS">
```suggestion
	</element>

	<element name="Cloudkill" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_CLOUDKILL">
		<supports>Sorcerer, Wizard, Damaging Spell, Spell Saving Throw</supports>
		<description>
			<p>You create a 20-foot-radius Sphere of yellow-green fog centered on a point within range. The fog lasts for the duration or until strong wind (such as the one created by <i>Gust of Wind</i>) disperses it, ending the spell. Its area is Heavily Obscured.</p>
			<p class="indent">Each creature in the Sphere makes a Constitution saving throw, taking 5d8 Poison damage on a failed save or half as much damage on a successful one. A creature must also make this save when the Sphere moves into its space and when it enters the Sphere or ends its turn there. A creature makes this save only once per turn.</p>
			<p class="indent">The Sphere moves 10 feet away from you at the start of each of your turns.</p>
			<p class="indent"><b><i>Using a Higher-Level Spell Slot.</i></b> The damage increases by 1d8 for each spell slot level above 5.</p>
		</description>
		<setters>
			<set name="keywords">heavily obscured, obscured, sphere, constitution, save, poison, damage, upcasting, higher-level spell slot</set>
			<set name="level">5</set>
			<set name="school">Conjuration</set>
			<set name="time">Action</set>
			<set name="range">120 feet</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="isConcentration">true</set>
			<set name="duration">Concentration, up to 10 minutes</set>
		</setters>
	</element>

	<element name="Cloud of Daggers" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_CLOUD_OF_DAGGERS">
```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
		<setters>
			<set name="keywords">cube, slashing, damage, upcasting, higher-level spell slot</set>
			<set name="level">2</set>
			<set name="school">Conjuration</set>
			<set name="time">Action</set>
			<set name="range">60 feet</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="hasMaterialComponent">true</set>
			<set name="materialComponent">a sliver of glass</set>
			<set name="isConcentration">true</set>
			<set name="duration">Concentration, up to 1 minute</set>
		</setters>
	</element>

```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	<element name="Command" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_COMMAND">
```suggestion
		<setters>
			<set name="keywords">cone, constitution, save, blinded</set>
			<set name="level">1</set>
			<set name="school">Illusion</set>
			<set name="time">Action</set>
			<set name="range">Self (15-foot Cone)</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="hasMaterialComponent">true</set>
			<set name="materialComponent">a pinch of colorful sand</set>
			<set name="duration">Instantaneous</set>
		</setters>
	</element>

	<element name="Command" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_COMMAND">
```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +			<p><b>Halt.</b> On its turn, the target doesn't move and takes no action or Bonus Action.</p>
```suggestion
			<p style="text-indent: -1em; margin-left: 1em"><b>Approach.</b> The target moves toward you by the shortest and most direct route, ending its turn if it moves within 5 feet of you.</p>
			<p style="text-indent: -1em; margin-left: 1em"><b>Drop.</b> The target drops whatever it is holding and then ends its turn.</p>
			<p style="text-indent: -1em; margin-left: 1em"><b>Flee.</b> The target spends its turn moving away from you by the fastest available means.</p>
			<p style="text-indent: -1em; margin-left: 1em"><b>Grovel.</b> The target has the Prone condition and then ends its turn.</p>
			<p style="text-indent: -1em; margin-left: 1em"><b>Halt.</b> On its turn, the target doesn't move and takes no action or Bonus Action.</p>
```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	<element name="Commune" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_COMMUNE">
```suggestion
		<setters>
			<set name="keywords">wisdom, save, disarm, prone, upcasting, higher-level spell slot</set>
			<set name="level">1</set>
			<set name="school">Enchantment</set>
			<set name="time">Action</set>
			<set name="range">60 feet</set>
			<set name="hasVerbalComponent">true</set>
			<set name="duration">Instantaneous</set>
		</setters>
	</element>

	<element name="Commune" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_COMMUNE">
```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	<element name="Commune with Nature" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_COMMUNE_WITH_NATURE">
```suggestion
		<setters>
			<set name="keywords">contact, divine, knowledge, information</set>
			<set name="level">5</set>
			<set name="school">Divination</set>
			<set name="time">1 minute or Ritual</set>
			<set name="isRitual">true</set>
			<set name="range">Self</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="hasMaterialComponent">true</set>
			<set name="materialComponent">incense</set>
			<set name="duration">1 minute</set>
		</setters>
	</element>

	<element name="Commune with Nature" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_COMMUNE_WITH_NATURE">
```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	<element name="Compelled Duel" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_COMPELLED_DUEL">
```suggestion
		<setters>
			<set name="keywords">outdoors, knowledge, information</set>
			<set name="level">5</set>
			<set name="school">Divination</set>
			<set name="time">1 minute or Ritual</set>
			<set name="isRitual">true</set>
			<set name="range">Self</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="duration">Instantaneous</set>
		</setters>
	</element>

	<element name="Compelled Duel" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_COMPELLED_DUEL">
```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	<element name="Comprehend Languages" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_COMPREHEND_LANGUAGES">
```suggestion
		<setters>
			<set name="keywords">wisdom, save, disadvantage</set>
			<set name="level">1</set>
			<set name="school">Enchantment</set>
			<set name="time">Bonus Action</set>
			<set name="range">30 feet</set>
			<set name="hasVerbalComponent">true</set>
			<set name="isConcentration">true</set>
			<set name="duration">Concentration, up to 1 minute</set>
		</setters>
	</element>

	<element name="Comprehend Languages" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_COMPREHEND_LANGUAGES">
```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	<element name="Compulsion" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_COMPULSION">
```suggestion
			<set name="materialComponent">a pinch of soot and salt</set>
			<set name="duration">1 hour</set>
		</setters>
	</element>

	<element name="Compulsion" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_COMPULSION">
```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	<element name="Cone of Cold" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_CONE_OF_COLD">
```suggestion
		<setters>
			<set name="keywords">wisdom, save, charmed</set>
			<set name="level">4</set>
			<set name="school">Enchantment</set>
			<set name="time">Action</set>
			<set name="range">30 feet</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="isConcentration">true</set>
			<set name="duration">Concentration, up to 1 minute</set>
		</setters>
	</element>

	<element name="Cone of Cold" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_CONE_OF_COLD">
```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	<element name="Confusion" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_CONFUSION">
```suggestion
		<setters>
			<set name="keywords">constitution, save, damage, upcasting, higher-level spell slot</set>
			<set name="level">5</set>
			<set name="school">Evocation</set>
			<set name="time">Action</set>
			<set name="range">Self (60-foot Cone)</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="hasMaterialComponent">true</set>
			<set name="materialComponent">a small crystal or glass cone</set>
			<set name="duration">Instantaneous</set>
		</setters>
	</element>

	<element name="Confusion" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_CONFUSION">
```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +				<tr><td>4</td><td>The target chooses its behavior.</td></tr>
```suggestion
				<tr><td>7-8</td><td>The target doesn't move, and it takes the Attack action to make one melee attack against a random creature within reach. If none are within reach, the target takes no action.</td></tr>
				<tr><td>9-10</td><td>The target chooses its behavior.</td></tr>
```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	<element name="Conjure Animals" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_CONJURE_ANIMALS">
```suggestion
		<setters>
			<set name="keywords">sphere, wisdom, save, limiting actions, limited actions, debuff, upcasting, higher-level spell slot</set>
			<set name="level">4</set>
			<set name="school">Enchantment</set>
			<set name="time">Action</set>
			<set name="range">90 feet</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="hasMaterialComponent">true</set>
			<set name="materialComponent">three nut shells</set>
			<set name="isConcentration">true</set>
			<set name="duration">Concentration, up to 1 minute</set>
		</setters>
	</element>

	<element name="Conjure Animals" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_CONJURE_ANIMALS">
```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	<element name="Conjure Barrage" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_CONJURE_BARRAGE">
```suggestion
		<setters>
			<set name="keywords">summon, advantage, saving throws, saves, dexterity, slashing, damage, upcasting, higher-level spell slot</set>
			<set name="level">3</set>
			<set name="school">Conjuration</set>
			<set name="time">Action</set>
			<set name="range">60 feet</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="isConcentration">true</set>
			<set name="duration">Concentration, up to 10 minutes</set>
		</setters>
	</element>

	<element name="Conjure Barrage" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_CONJURE_BARRAGE">
```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	<element name="Conjure Celestial" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_CONJURE_CELESTIAL">
```suggestion
		<setters>
			<set name="keywords">cone, dexterity, save, force, damage, upcasting, higher-level spell slot</set>
			<set name="level">3</set>
			<set name="school">Conjuration</set>
			<set name="time">Action</set>
			<set name="range">Self (60-foot Cone)</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="hasMaterialComponent">true</set>
			<set name="materialComponent">a Melee or Ranged weapon worth at least 1 CP</set>
			<set name="duration">Instantaneous</set>
		</setters>
	</element>

	<element name="Conjure Celestial" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_CONJURE_CELESTIAL">
```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +			<p><b>Searing Light.</b> The target makes a Dexterity saving throw, taking 6d12 Radiant damage on a failed save or half as much damage on a successful one. </p>
```suggestion
			<p style="text-indent: -1em; margin-left: 1em"><b>Healing Light.</b> The target regains Hit Points equal to 4d12 plus your spellcasting ability modifier.</p>
			<p style="text-indent: -1em; margin-left: 1em"><b>Searing Light.</b> The target makes a Dexterity saving throw, taking 6d12 Radiant damage on a failed save or half as much damage on a successful one. </p>
```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	<element name="Conjure Elemental" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_CONJURE_ELEMENTAL">
```suggestion
		<setters>
			<set name="keywords">cylinder, dexterity, save, radiant, damage, upcasting, higher-level spell slot</set>
			<set name="level">7</set>
			<set name="school">Conjuration</set>
			<set name="time">Action</set>
			<set name="range">90 feet</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="isConcentration">true</set>
			<set name="duration">Concentration, up to 10 minutes</set>
		</setters>
	</element>

	<element name="Conjure Elemental" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_CONJURE_ELEMENTAL">
```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	<element name="Conjure Fey" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_CONJURE_FEY">
```suggestion
		<setters>
			<set name="keywords">lightning, thunder, fire, cold, dexterity, save, restrained, upcasting, higher-level spell slot</set>
			<set name="level">5</set>
			<set name="school">Conjuration</set>
			<set name="time">Action</set>
			<set name="range">60 feet</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="isConcentration">true</set>
			<set name="duration">Concentration, up to 10 minutes</set>
		</setters>
	</element>

	<element name="Conjure Fey" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_CONJURE_FEY">
```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	<element name="Conjure Minor Elementals" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_CONJURE_MINOR_ELEMENTALS">
```suggestion
		<setters>
			<set name="keywords">psychic, damage, frightened, bonus action, upcasting, higher-level spell slot</set>
			<set name="level">6</set>
			<set name="school">Conjuration</set>
			<set name="time">Action</set>
			<set name="range">60 feet</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="isConcentration">true</set>
			<set name="duration">Concentration, up to 10 minutes</set>
		</setters>
	</element>

	<element name="Conjure Minor Elementals" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_CONJURE_MINOR_ELEMENTALS">
```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	<element name="Conjure Volley" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_CONJURE_VOLLEY">
```suggestion
		<setters>
			<set name="keywords">emanation, acid, cold, fire, lightning, damage, difficult terrain, upcasting, higher-level spell slot</set>
			<set name="level">4</set>
			<set name="school">Conjuration</set>
			<set name="time">Action</set>
			<set name="range">Self (15-foot Emanation)</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="isConcentration">true</set>
			<set name="duration">Concentration, up to 10 minutes</set>
		</setters>
	</element>

	<element name="Conjure Volley" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_CONJURE_VOLLEY">
```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	<element name="Conjure Woodland Beings" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_CONJURE_WOODLAND_BEINGS">
```suggestion
		<setters>
			<set name="keywords">cylinder, dexterity, save, force, damage</set>
			<set name="level">5</set>
			<set name="school">Conjuration</set>
			<set name="time">Action</set>
			<set name="range">150 feet</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="hasMaterialComponent">true</set>
			<set name="materialComponent">a Melee or Ranged weapon worth at least 1 CP</set>
			<set name="duration">Instantaneous</set>
		</setters>
	</element>

	<element name="Conjure Woodland Beings" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_CONJURE_WOODLAND_BEINGS">
```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	<element name="Contact Other Plane" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_CONTACT_OTHER_PLANE">
```suggestion
		<setters>
			<set name="keywords">emanation, wisdom, save, force, damage, disengage, bonus action, upcasting, higher-level spell slot</set>
			<set name="level">4</set>
			<set name="school">Conjuration</set>
			<set name="time">Action</set>
			<set name="range">Self (10-foot Emanation)</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="isConcentration">true</set>
			<set name="duration">Concentration, up to 10 minutes</set>
		</setters>
	</element>

	<element name="Contact Other Plane" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_CONTACT_OTHER_PLANE">
```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +		<supports>Warlock, Wizard, Spell Saving Throw, Damaging Spell</supports>
i think it doesn't make sense to consider backlash from the spell to be part of these supports
```suggestion
		<supports>Warlock, Wizard</supports>
```
same logic applies to keywords

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	<element name="Contagion" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_CONTAGION">
```suggestion
		<setters>
			<set name="keywords">commune, knowledge, information</set>
			<set name="level">5</set>
			<set name="school">Divination</set>
			<set name="time">1 minute or Ritual</set>
			<set name="isRitual">true</set>
			<set name="range">Self</set>
			<set name="hasVerbalComponent">true</set>
			<set name="duration">1 minute</set>
		</setters>
	</element>

	<element name="Contagion" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_CONTAGION">
```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	<element name="Contingency" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_CONTINGENCY">
```suggestion
		<setters>
			<set name="keywords">constitution, saving throws, saves, necrotic, damage, poisoned, disadvantage</set>
			<set name="level">5</set>
			<set name="school">Necromancy</set>
			<set name="time">Action</set>
			<set name="range">Touch</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="duration">7 Days</set>
		</setters>
	</element>

	<element name="Contingency" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_CONTINGENCY">
```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +			<p class="indent">The contingent spell takes effect only on you, even if it can normally target others. You can use only one Contingency spell at a time. If you cast this spell again, the effect o
```suggestion
			<p>Choose a spell of level 5 or lower that you can cast, that has a casting time of an action, and that can target you. You cast that spell—called the contingent spell—as part of casting <i>Contingency</i>, expending spell slots for both, but the contingent spell doesn't come into effect. Instead, it takes effect when a certain trigger occurs. You describe that trigger when you cast the two spells. For example, a <i>Contingency</i> cast with <i>Water Breathing</i> might stipulate that <i>Water Breathing</i> comes into effect when you are engulfed in water or a similar liquid.</p>
			<p class="indent">The contingent spell takes effect immediately after the trigger occurs for the first time, whether or not you want it to, and then <i>Contingency</i> ends.</p>
			<p class="indent">The contingent spell takes effect only on you, even if it can normally target others. You can use only one <i>Contingency</i> spell at a time. If you cast this spell again, the effect of another <i>Contingency</i> spell on you ends. Also, <i>Contingency</i> ends on you if its material component is ever not on your person.</p>
```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="time">10 minutes</set>
			<set name="range">Self</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="hasMaterialComponent">true</set>
			<set name="materialComponent">a gem-encrusted statuette of yourself worth 1,500+ GP</set>
			<set name="duration">10 days</set>
		</setters>
	</element>

```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="keywords">bright, dim, light</set>
			<set name="level">2</set>
			<set name="school">Evocation</set>
			<set name="time">Action</set>
			<set name="range">Touch</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="hasMaterialComponent">true</set>
			<set name="materialComponent">ruby dust worth 50+ GP, which the spell consumes</set>
			<set name="duration">Until dispelled</set>
		</setters>
	</element>

```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="keywords">cube, flood, part water, redirect flow, whirlpool, strength, save, bludgeoning, damage</set>
			<set name="level">4</set>
			<set name="school">Transmutation</set>
			<set name="time">Action</set>
			<set name="range">300 feet</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="hasMaterialComponent">true</set>
			<set name="materialComponent">a mixture of water and dust</set>
			<set name="isConcentration">true</set>
			<set name="duration">Concentration, up to 10 minutes</set>
		</setters>
	</element>

```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +				<tr><td>5</td><td>Torrential rain, driving hail, or blizzard</td></tr>
```suggestion
					<tr><td class="col-10">Stage</td><td class="left">Condition</td></tr>
				</thead>
				<tr><td>1</td><td class="left">Clear</td></tr>
				<tr><td>2</td><td class="left">Light Clouds</td></tr>
				<tr><td>3</td><td class="left">Overcast or ground fog</td></tr>
				<tr><td>4</td><td class="left">Rain, hail, or snow</td></tr>
				<tr><td>5</td><td class="left">Torrential rain, driving hail, or blizzard</td></tr>
```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +				<tr><td>6</td><td>Freezing</td></tr>
```suggestion
					<tr><td class="col-10">Stage</td><td class="left">Condition</td></tr>
				</thead>
				<tr><td>1</td><td class="left">Heat Wave</td></tr>
				<tr><td>2</td><td class="left">Hot</td></tr>
				<tr><td>3</td><td class="left">Warm</td></tr>
				<tr><td>4</td><td class="left">Cool</td></tr>
				<tr><td>5</td><td class="left">Cold</td></tr>
				<tr><td>6</td><td class="left">Freezing</td></tr>
```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +				<tr><td>5</td><td>Storm</td></tr>
```suggestion
					<tr><td class="col-10">Stage</td><td class="left">Condition</td></tr>
				</thead>
				<tr><td>1</td><td class="left">Calm</td></tr>
				<tr><td>2</td><td class="left">Moderate Wind</td></tr>
				<tr><td>3</td><td class="left">Strong Wind</td></tr>
				<tr><td>4</td><td class="left">Gale</td></tr>
				<tr><td>5</td><td class="left">Storm</td></tr>
```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="keywords">precipitation, temperature, wind</set>
			<set name="level">8</set>
			<set name="school">Transmutation</set>
			<set name="time">10 minutes</set>
			<set name="range">Self (5-mile radius)</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="hasMaterialComponent">true</set>
			<set name="materialComponent">burning incense</set>
			<set name="isConcentration">true</set>
			<set name="duration">Concentration, up to 8 hours</set>
		</setters>
	</element>

```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="keywords">dexterity, save, piercing, damage, upcasting, higher-level spell slot</set>
			<set name="level">2</set>
			<set name="school">Transmutation</set>
			<set name="time">Action</set>
			<set name="range">Touch</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="hasMaterialComponent">true</set>
			<set name="materialComponent">an ornamental braid</set>
			<set name="duration">8 hours</set>
		</setters>
	</element>

```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="keywords">constitution, save, anti-magic</set>
			<set name="level">3</set>
			<set name="school">Abjuration</set>
			<set name="time">Reaction, which you take when you see a creature within 60 feet of yourself casting a spell with Verbal, Somatic, or Material components</set>
			<set name="range">60 feet</set>
			<set name="hasSomaticComponent">true</set>
			<set name="duration">Instantaneous</set>
		</setters>
	</element>

```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="time">Action</set>
			<set name="range">30 feet</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="duration">Instantaneous</set>
		</setters>
	</element>

```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +			<p class="indent"><b>Destroy Water.</b> You destroy up to 10 gallons of water in an open container within range. Alternatively, you destroy fog in a 30-foot Cube within range.</p>
```suggestion
			<p style="text-indent: -1em; margin-left: 1em"><b>Create Water.</b> You create up to 10 gallons of clean water within range in an open container. Alternatively, the water falls as rain in a 30-foot Cube within range, extinguishing exposed flames there.</p>
			<p style="text-indent: -1em; margin-left: 1em"><b>Destroy Water.</b> You destroy up to 10 gallons of water in an open container within range. Alternatively, you destroy fog in a 30-foot Cube within range.</p>
```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="keywords">cube, rain, upcasting, higher-level spell slot</set>
			<set name="level">1</set>
			<set name="school">Transmutation</set>
			<set name="time">Action</set>
			<set name="isRitual">false</set>
			<set name="range">30 feet</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="hasMaterialComponent">true</set>
			<set name="materialComponent">a mix of water and sand</set>
			<set name="duration">Instantaneous</set>
		</setters>
	</element>

```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +			<p>You can cast this spell only at night. Choose up to three corpses of Medium or Small Humanoids within range. Each one becomes a Ghoul under your control (see the Monster Manual for its stat blo
```suggestion
			<p>You can cast this spell only at night. Choose up to three corpses of Medium or Small Humanoids within range. Each one becomes a <b>Ghoul</b> under your control (see page 132 of the <i>Monster Manual (2025)</i> for the stat-block).</p>
```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +			<p class="indent"><b><i>Using a Higher-Level Spell Slot.</i></b> If you use a level 7 spell slot, you can animate or reassert control over four Ghouls. If you use a level 8 spell slot, you can ani
```suggestion
			<p class="indent"><b><i>Using a Higher-Level Spell Slot.</i></b> If you use a level 7 spell slot, you can animate or reassert control over four <b>Ghouls</b>. If you use a level 8 spell slot, you can animate or reassert control over five <b>Ghouls</b> or two <b>Ghasts</b> or <b>Wights</b>. If you use a level 9 spell slot, you can animate or reassert control over six <b>Ghouls</b>, three <b>Ghasts</b> or <b>Wights</b>, or two <b>Mummies</b> (see <i>Monster Manual (2025)</i> pages 130 (Ghast), 332 (Wight) and 219 (Mummy) for stat-blocks).</p>
			<!-- to do: Create references with Information type statblocks. Similar to Awaken and Animate Dead spells -->
```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="keywords">summon, ghoul, ghast, wight, mummy, bonus action, upcasting, higher-level spell slot</set>
			<set name="level">6</set>
			<set name="school">Necromancy</set>
			<set name="time">1 minute</set>
			<set name="range">10 feet</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="hasMaterialComponent">true</set>
			<set name="materialComponent">one 150+ GP black onyx stone for each corpse</set>
			<set name="duration">Instantaneous</set>
		</setters>
	</element>

```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +			</table>
```suggestion
					<tr><td class="left">Material</td><td class="left">Duration</td></tr>
				</thead>
				<tr><td class="left">Vegetable Matter</td><td class="left">24 hours</td></tr>
				<tr><td class="left">Stone or crystal</td><td class="left">12 hours</td></tr>
				<tr><td class="left">Precious metals</td><td class="left">1 hour</td></tr>
				<tr><td class="left">Gems</td><td class="left">10 minutes</td></tr>
				<tr><td class="left">Adamantine or mithral</td><td class="left">1 minute</td></tr>
			</table>
			<p class="indent"><b><i>Using a Higher-Level Spell Slot.</i></b> The Cube increases by 5 feet for each spell slot level above 5.</p>
```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="keywords">cube, upcasting, higher-level spell slot</set>
			<set name="level">5</set>
			<set name="school">Illusion</set>
			<set name="time">1 minute</set>
			<set name="range">30 feet</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="hasMaterialComponent">true</set>
			<set name="materialComponent">a paintbrush</set>
			<set name="duration">Special</set>
		</setters>
	</element>

```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="time">Action</set>
			<set name="range">120 feet</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="isConcentration">true</set>
			<set name="duration">Concentration, up to 1 minute</set>
		</setters>
	</element>

```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="keywords">aura, radiant, damage, emanation, buff</set>
			<set name="level">3</set>
			<set name="school">Evocation</set>
			<set name="time">Action</set>
			<set name="range">Self (30-foot Emanation)</set>
			<set name="hasVerbalComponent">true</set>
			<set name="isConcentration">true</set>
			<set name="duration">Concentration, up to 1 minute</set>
		</setters>
	</element>

```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +		<supports>Bard, Cleric, Druid, Paladin, Ranger, Artificer, Healing Spell</supports>
```suggestion
		<supports>Artificer, Bard, Cleric, Druid, Paladin, Ranger, Healing Spell</supports>
```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="keywords">upcasting, higher-level spell slot</set>
			<set name="level">1</set>
			<set name="school">Abjuration</set>
			<set name="time">Action</set>
			<set name="range">Touch</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="duration">Instantaneous</set>
		</setters>
	</element>

```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +		<supports>Bard, Sorcerer, Wizard, Artificer</supports>
```suggestion
		<supports>Artificer, Bard, Sorcerer, Wizard</supports>
```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="keywords">light</set>
			<set name="level">0</set>
			<set name="school">Illusion</set>
			<set name="time">Action</set>
			<set name="range">120 feet</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="hasMaterialComponent">true</set>
			<set name="materialComponent">a bit of phosphorous</set>
			<set name="isConcentration">true</set>
			<set name="duration">Concentration, up to 1 minute</set>
		</setters>
	</element>

```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="keywords">sphere, emanation, dispel</set>
			<set name="level">2</set>
			<set name="school">Evocation</set>
			<set name="time">Action</set>
			<set name="isRitual">false</set>
			<set name="range">60 feet</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">false</set>
			<set name="hasMaterialComponent">true</set>
			<set name="materialComponent">bat fur and a piece of coal</set>
			<set name="isConcentration">true</set>
			<set name="duration">Concentration, up to 10 minutes</set>
		</setters>
	</element>

```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +		<supports>Druid, Ranger, Sorcerer, Wizard, Artificer</supports>
```suggestion
		<supports>Artificer, Druid, Ranger, Sorcerer, Wizard</supports>
```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="time">Action</set>
			<set name="range">Touch</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="hasMaterialComponent">true</set>
			<set name="materialComponent">a dried carrot</set>
			<set name="duration">8 hours</set>
		</setters>
	</element>

```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="keywords">sphere, emanation, sunlight, bright, dim</set>
			<set name="level">3</set>
			<set name="school">Evocation</set>
			<set name="time">Action</set>
			<set name="range">60 feet</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="duration">1 hour</set>
		</setters>
	</element>

```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +		<supports>Cleric, Paladin, Healing Spell</supports>
Spell doesn't actually heal.
```suggestion
		<supports>Cleric, Paladin</supports>
```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="keywords"></set>
			<set name="level">4</set>
			<set name="school">Abjuration</set>
			<set name="time">Action</set>
			<set name="range">Touch</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="duration">8 hours</set>
		</setters>
	</element>

```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="keywords">sphere, dexterity, save, fire, damage, upcasting, higher-level spell slot</set>
			<set name="level">7</set>
			<set name="school">Evocation</set>
			<set name="time">Action</set>
			<set name="range">150 feet</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="hasMaterialComponent">true</set>
			<set name="materialComponent">a ball of bat guano and sulfur</set>
			<set name="isConcentration">true</set>
			<set name="duration">Concentration, up to 1 minute</set>
		</setters>
	</element>

```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="time">Action</set>
			<set name="range">60 feet</set>
			<set name="hasSomaticComponent">true</set>
			<set name="duration">1 hour</set>
		</setters>
	</element>

```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="keywords">emanation, constitution, save, thunder, radiant, necrotic, damage, prone</set>
			<set name="level">5</set>
			<set name="school">Evocation</set>
			<set name="time">Action</set>
			<set name="range">Self (30-foot Emanation)</set>
			<set name="hasVerbalComponent">true</set>
			<set name="duration">Instantaneous</set>
		</setters>
	</element>

```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="time">Action</set>
			<set name="range">Self</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="isConcentration">true</set>
			<set name="duration">Concentration, up to 10 minutes</set>
		</setters>
	</element>

```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +		<supports>Bard, Cleric, Druid, Paladin, Ranger, Sorcerer, Warlock, Wizard, Artificer</supports>
```suggestion
		<supports>Artificer, Bard, Cleric, Druid, Paladin, Ranger, Sorcerer, Warlock, Wizard</supports>
```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="keywords">sense</set>
			<set name="level">1</set>
			<set name="school">Divination</set>
			<set name="time">Action or Ritual</set>
			<set name="isRitual">true</set>
			<set name="range">Self</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="isConcentration">true</set>
			<set name="duration">Concentration, up to 10 minutes</set>
		</setters>
	</element>

```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +			<p><b><i>Read Thoughts.</i></b> Target one creature you can see within 30 feet of yourself or one creature within 30 feet of yourself that you detected with the Sense Thoughts option. You learn wh
```suggestion
			<p class="indent"><b><i>Sense Thoughts.</i></b> You sense the presence of thoughts within 30 feet of yourself that belong to creatures that know languages or are telepathic. You don't read the thoughts, but you know that a thinking creature is present.</p>
			<p class="indent">The spell is blocked by 1 foot of stone, dirt, or wood; 1 inch of metal; or a thin sheet of lead.</p>
			<p class="indent"><b><i>Read Thoughts.</i></b> Target one creature you can see within 30 feet of yourself or one creature within 30 feet of yourself that you detected with the Sense Thoughts option. You learn what is most on the target's mind right now. If the target doesn't know any languages and isn't telepathic, you learn nothing.</p>
```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="keywords">sense thoughts, read thoughts, wisdom, save</set>
			<set name="level">2</set>
			<set name="school">Divination</set>
			<set name="time">Action</set>
			<set name="range">Self</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="hasMaterialComponent">true</set>
			<set name="materialComponent">1 Copper Piece</set>
			<set name="isConcentration">true</set>
			<set name="duration">Concentration, up to 1 minute</set>
		</setters>
	</element>

```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="keywords">teleport</set>
			<set name="level">4</set>
			<set name="school">Conjuration</set>
			<set name="time">Action</set>
			<set name="range">500 feet</set>
			<set name="hasVerbalComponent">true</set>
			<set name="duration">Instantaneous</set>
		</setters>
	</element>

```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="keywords">camouflage</set>
			<set name="level">1</set>
			<set name="school">Illusion</set>
			<set name="time">Action</set>
			<set name="range">Self</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="duration">1 hour</set>
		</setters>
	</element>

```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +			<p class="indent">A creature targeted by this spell makes a Dexterity saving throw. On a failed save, the target takes 10d6 + 40 Force damage. If this damage reduces it to 0 Hit Points, it and eve
```suggestion
			<p>You launch a green ray at a target you can see within range. The target can be a creature, a nonmagical object, or a creation of magical force, such as the wall created by <i>Wall of Force</i>.</p>
			<p class="indent">A creature targeted by this spell makes a Dexterity saving throw. On a failed save, the target takes 10d6 + 40 Force damage. If this damage reduces it to 0 Hit Points, it and everything nonmagical it is wearing and carrying are disintegrated into gray dust. The target can be revived only by a <i>True Resurrection</i> or a <i>Wish</i> spell.</p>
```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="keywords">dexterity, save, force, damage, upcasting, higher-level spell slot</set>
			<set name="level">6</set>
			<set name="school">Transmutation</set>
			<set name="time">Action</set>
			<set name="range">60 feet</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="hasMaterialComponent">true</set>
			<set name="materialComponent">a lodestone and dust</set>
			<set name="duration">Instantaneous</set>
		</setters>
	</element>

```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="keywords">celestials, elementals, fey, fiends, undead, disadvantage, attack rolls, charisma, save, banishment</set>
			<set name="level">5</set>
			<set name="school">Abjuration</set>
			<set name="time">Action</set>
			<set name="range">Self</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="hasMaterialComponent">true</set>
			<set name="materialComponent">powdered silver and iron</set>
			<set name="isConcentration">true</set>
			<set name="duration">Concentration, up to 1 minute</set>
		</setters>
	</element>

```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="keywords">upcasting, higher-level spell slot</set>
			<set name="level">3</set>
			<set name="school">Abjuration</set>
			<set name="time">Action</set>
			<set name="range">120 feet</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="duration">Instantaneous</set>
		</setters>
	</element>

```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="keywords">wisdom, save, psychic, damage, upcasting, higher-level spell slot</set>
			<set name="level">1</set>
			<set name="school">Enchantment</set>
			<set name="time">Action</set>
			<set name="range">60 feet</set>
			<set name="hasVerbalComponent">true</set>
			<set name="duration">Instantaneous</set>
		</setters>
	</element>

```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="keywords">contact, divine, knowledge, information</set>
			<set name="level">4</set>
			<set name="school">Divination</set>
			<set name="time">Action or Ritual</set>
			<set name="isRitual">true</set>
			<set name="range">Self</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="hasMaterialComponent">true</set>
			<set name="materialComponent">incense worth 25+ GP, which the spell consumes</set>
			<set name="duration">Instantaneous</set>
		</setters>
	</element>

```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="keywords">radiant, damage, buff</set>
			<set name="level">1</set>
			<set name="school">Transmutation</set>
			<set name="time">Bonus Action</set>
			<set name="range">Self</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="duration">1 minute</set>
		</setters>
	</element>

```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="keywords">on hit, melee, weapon, unarmed strike, radiant, damage, fiend, undead, upcasting, higher-level spell slot</set>
			<set name="level">1</set>
			<set name="school">Evocation</set>
			<set name="time">Bonus Action, which you take immediately after hitting a target with a Melee weapon or an Unarmed Strike</set>
			<set name="range">Self</set>
			<set name="hasVerbalComponent">true</set>
			<set name="duration">Instantaneous</set>
		</setters>
	</element>

```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="keywords">charisma, save, celestial, elemental, fey, fiend, banishment, blinded, deafened, stunned</set>
			<set name="level">7</set>
			<set name="school">Evocation</set>
			<set name="time">Bonus Action</set>
			<set name="range">30 feet</set>
			<set name="hasVerbalComponent">true</set>
			<set name="duration">Instantaneous</set>
		</setters>
	</element>

```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="keywords">wisdom, save, charmed, telepathy, telepathic link, command, reaction, upcasting, higher-level spell slot</set>
			<set name="level">4</set>
			<set name="school">Enchantment</set>
			<set name="time">Action</set>
			<set name="range">60 feet</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="isConcentration">true</set>
			<set name="duration">Concentration, up to 1 minute</set>
		</setters>
	</element>

```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="keywords">wisdom, save, charmed, telepathy, telepathic link, command, reaction, upcasting, higher-level spell slot</set>
			<set name="level">8</set>
			<set name="school">Enchantment</set>
			<set name="time">Action</set>
			<set name="range">60 feet</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="isConcentration">true</set>
			<set name="duration">Concentration, up to 1 hour</set>
		</setters>
	</element>

```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="keywords">wisdom, save, charmed, telepathy, telepathic link, command, reaction, upcasting, higher-level spell slot</set>
			<set name="level">5</set>
			<set name="school">Enchantment</set>
			<set name="time">Action</set>
			<set name="range">60 feet</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="isConcentration">true</set>
			<set name="duration">Concentration, up to 1 minute</set>
		</setters>
	</element>

```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="keywords">acid, cold, fire, lightning, poison, action, cone, dexterity, save, damage, upcasting, higher-level spell slot</set>
			<set name="level">2</set>
			<set name="school">Transmutation</set>
			<set name="time">Bonus Action</set>
			<set name="range">Touch</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="hasMaterialComponent">true</set>
			<set name="materialComponent">a hot pepper</set>
			<set name="isConcentration">true</set>
			<set name="duration">Concentration, up to 1 minute</set>
		</setters>
	</element>

```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="materialComponent">a sapphire worth 1,000+ GP</set>
			<set name="duration">Until dispelled</set>
		</setters>
	</element>

```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="keywords">communication, message, wisdom, save, psychic, damage</set>
			<set name="level">5</set>
			<set name="school">Illusion</set>
			<set name="time">1 minute</set>
			<set name="range">Special</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="hasMaterialComponent">true</set>
			<set name="materialComponent">a handful of sand</set>
			<set name="duration">8 hours</set>
		</setters>
	</element>

```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="keywords">weather sensor, bloom, sensory effect, fire play, cube</set>
			<set name="level">0</set>
			<set name="school">Transmutation</set>
			<set name="time">Action</set>
			<set name="range">30 feet</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="duration">Instantaneous</set>
		</setters>
	</element>

```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="keywords">circle, difficult terrain, dexterity, save, prone, bludgeoning, damage</set>
			<set name="level">8</set>
			<set name="school">Transmutation</set>
			<set name="time">Action</set>
			<set name="range">500 feet</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="hasMaterialComponent">true</set>
			<set name="materialComponent">a fractured rock</set>
			<set name="isConcentration">true</set>
			<set name="duration">Concentration, up to 1 minute</set>
		</setters>
	</element>

```

2026-01-21 14:26 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="keywords">force, damage, upgrade</set>
			<set name="level">0</set>
			<set name="school">Evocation</set>
			<set name="time">Action</set>
			<set name="range">120 feet</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="duration">Instantaneous</set>
		</setters>
	</element>

```

2026-01-21 16:12 UTC, NickVendel requested changes
Part 3... i hate Github right now, will come back tomorrow probably... damn...

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="keywords">cube, square, beckon, air, earth, fire, water, sculpt element</set>
			<set name="level">0</set>
			<set name="school">Transmutation</set>
			<set name="time">Action</set>
			<set name="range">30 feet</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="duration">Instantaneous</set>
		</setters>
	</element>

```

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	<element name="Enhance Ability" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_ENHANCE_ABILITY">
```suggestion
	<element name="Elemental Weapon" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_ELEMENTAL_WEAPON">
		<supports>Artificer, Druid, Paladin, Ranger</supports>
		<description>
			<p>A nonmagical weapon you touch becomes a magic weapon. Choose one of the following damage types: Acid, Cold, Fire, Lightning, or Thunder. For the duration, the weapon has a +1 bonus to attack rolls and deals an extra 1d4 damage of the chosen type when it hits.</p>
			<p class="indent"><b><i>Using a Higher-Level Spell Slot.</i></b> If you use a level 5-6 spell slot, the bonus to attack rolls increases to +2, and the extra damage increases to 2d4. If you use a level 7+ spell slot, the bonus increases to +3, and the extra damage increases to 3d4.</p>
		</description>
		<setters>
			<set name="keywords">magic weapon, acid, cold, fire, lightning, thunder, +1, +2, +3, bonus, enhancement, attack rolls, damage, upcasting, higher-level spell slot</set>
			<set name="level">3</set>
			<set name="school">Transmutation</set>
			<set name="time">Action</set>
			<set name="range">Touch</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="isConcentration">true</set>
			<set name="duration">Concentration, up to 1 hour</set>
		</setters>
	</element>

	<element name="Enhance Ability" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_ENHANCE_ABILITY">
```

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +		<supports>Bard, Cleric, Druid, Ranger, Sorcerer, Wizard, Artificer</supports>
```suggestion
		<supports>Artificer, Bard, Cleric, Druid, Ranger, Sorcerer, Wizard</supports>
```

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="keywords">advantage, ability checks, upcasting, higher-level spell slot</set>
			<set name="level">2</set>
			<set name="school">Transmutation</set>
			<set name="time">Action</set>
			<set name="range">Touch</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="hasMaterialComponent">true</set>
			<set name="materialComponent">fur or a feather</set>
			<set name="isConcentration">true</set>
			<set name="duration">Concentration, up to 1 hour</set>
		</setters>
	</element>

```

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +		<supports>Bard, Druid, Sorcerer, Wizard, Artificer, Spell Saving Throw</supports>
```suggestion
		<supports>Artificer, Bard, Druid, Sorcerer, Wizard, Spell Saving Throw</supports>
```

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="keywords">constitution, save, advantage, strength, ability checks, saving throws, saves, damage</set>
			<set name="level">2</set>
			<set name="school">Transmutation</set>
			<set name="time">Action</set>
			<set name="range">30 feet</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="hasMaterialComponent">true</set>
			<set name="materialComponent">a pinch of powdered iron</set>
			<set name="isConcentration">true</set>
			<set name="duration">Concentration, up to 1 minute</set>
		</setters>
	</element>

```

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="keywords">on hit, melee, ranged, weapon, strength, save, restrained, piercing, damage, upcasting, higher-level spell slot</set>
			<set name="level">1</set>
			<set name="school">Conjuration</set>
			<set name="time">Bonus Action, which you take immediately after hitting a creature with a weapon</set>
			<set name="range">Self</set>
			<set name="hasVerbalComponent">true</set>
			<set name="isConcentration">true</set>
			<set name="duration">Concentration, up to 1 minute</set>
		</setters>
	</element>

```

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="keywords">square, difficult terrain, strength, save, restrained</set>
			<set name="level">1</set>
			<set name="school">Conjuration</set>
			<set name="time">Action</set>
			<set name="range">90 feet</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="isConcentration">true</set>
			<set name="duration">Concentration, up to 1 minute</set>
		</setters>
	</element>

```

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="keywords">distraction, wisdom, save, perception, ability checks, passive perception</set>
			<set name="level">2</set>
			<set name="school">Enchantment</set>
			<set name="time">Action</set>
			<set name="range">60 feet</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="isConcentration">true</set>
			<set name="duration">Concentration, up to 1 minute</set>
		</setters>
	</element>

```

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="keywords">planar travel, ethereal plane, upcasting, higher-level spell slot</set>
			<set name="level">7</set>
			<set name="school">Conjuration</set>
			<set name="time">Action</set>
			<set name="range">Self</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="duration">Up to 8 hours</set>
		</setters>
	</element>

```

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="keywords">square, difficult terrain, strength, save, bludgeoning, damage, restrained</set>
			<set name="level">4</set>
			<set name="school">Conjuration</set>
			<set name="time">Action</set>
			<set name="range">90 feet</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="hasMaterialComponent">true</set>
			<set name="materialComponent">a tentacle</set>
			<set name="isConcentration">true</set>
			<set name="duration">Concentration, up to 1 minute</set>
		</setters>
	</element>

```

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +		<supports>Sorcerer, Warlock, Wizard, Artificer</supports>
```suggestion
		<supports>Artificer, Sorcerer, Warlock, Wizard</supports>
```

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="keywords">dash, movement</set>
			<set name="level">1</set>
			<set name="school">Transmutation</set>
			<set name="time">Bonus Action</set>
			<set name="range">Self</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="isConcentration">true</set>
			<set name="duration">Concentration, up to 10 minutes</set>
		</setters>
	</element>

```

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="keywords">wisdom, save, frightened, poisoned, unconscious</set>
			<set name="level">6</set>
			<set name="school">Necromancy</set>
			<set name="time">Action</set>
			<set name="range">Self</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="isConcentration">true</set>
			<set name="duration">Concentration, up to 1 minute</set>
		</setters>
	</element>

```

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +		<supports>Wizard, Artificer</supports>
```suggestion
		<supports>Artificer, Wizard</supports>
```

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="keywords">create, produce, cube</set>
			<set name="level">4</set>
			<set name="school">Transmutation</set>
			<set name="time">10 minutes</set>
			<set name="range">120 feet</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="duration">Instantaneous</set>
		</setters>
	</element>

```

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +		<supports>Bard, Druid, Artificer, Spell Saving Throw</supports>
```suggestion
		<supports>Artificer, Bard, Druid, Spell Saving Throw</supports>
```

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="keywords">cube, light, dexterity, save, dim, debuff, advantage, attack rolls</set>
			<set name="level">1</set>
			<set name="school">Evocation</set>
			<set name="time">Action</set>
			<set name="range">60 feet</set>
			<set name="hasVerbalComponent">true</set>
			<set name="isConcentration">true</set>
			<set name="duration">Concentration, up to 1 minute</set>
		</setters>
	</element>

```

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +		<supports>Sorcerer, Wizard, Artificer</supports>
```suggestion
		<supports>Artificer, Sorcerer, Wizard</supports>
```

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="keywords">thp, upcasting, higher-level spell slot</set>
			<set name="level">1</set>
			<set name="school">Necromancy</set>
			<set name="time">Action</set>
			<set name="isRitual">false</set>
			<set name="range">Self</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="hasMaterialComponent">true</set>
			<set name="materialComponent">a drop of alcohol</set>
			<set name="duration">Instantaneous</set>
		</setters>
	</element>

```

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="keywords">cone, wisdom, save, frightened</set>
			<set name="level">3</set>
			<set name="school">Illusion</set>
			<set name="time">Action</set>
			<set name="range">Self (30-foot Cone)</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="hasMaterialComponent">true</set>
			<set name="materialComponent">a white feather</set>
			<set name="isConcentration">true</set>
			<set name="duration">Concentration, up to 1 minute</set>
		</setters>
	</element>

```

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +		<supports>Bard, Sorcerer, Wizard, Artificer</supports>
```suggestion
		<supports>Artificer, Bard, Sorcerer, Wizard</supports>
```

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="keywords">slow fall</set>
			<set name="level">1</set>
			<set name="school">Transmutation</set>
			<set name="time">Reaction, which you take when you or a creature you can see within 60 feet of you falls</set>
			<set name="range">60 feet</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasMaterialComponent">true</set>
			<set name="materialComponent">a small feather or piece of down</set>
			<set name="duration">1 minute</set>
		</setters>
	</element>

```

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="keywords">blinded, incapacitated, resistance, immunity, poisoned</set>
			<set name="level">3</set>
			<set name="school">Necromancy</set>
			<set name="time">Action or Ritual</set>
			<set name="isRitual">true</set>
			<set name="range">Touch</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="hasMaterialComponent">true</set>
			<set name="materialComponent">a pinch of graveyard dirt</set>
			<set name="duration">1 hour</set>
		</setters>
	</element>

```

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +			<p><b><i>Telepathic Connection.</i></b> While your familiar is within 100 feet of you, you can communicate with it telepathically. Additionally, as a Bonus Action, you can see through the familiar
```suggestion
			<p>You gain the service of a familiar, a spirit that takes an animal form you choose: <b>Bat, Cat, Frog, Hawk, Lizard, Octopus, Owl, Rat, Raven, Spider, Weasel</b>, or another Beast that has a Challenge Rating of 0. Appearing in an unoccupied space within range, the familiar has the statistics of the chosen form, though it is a Celestial, Fey, or Fiend (your choice) instead of a Beast. Your familiar acts independently of you, but it obeys your commands.</p>
			<p class="indent"><b><i>Telepathic Connection.</i></b> While your familiar is within 100 feet of you, you can communicate with it telepathically. Additionally, as a Bonus Action, you can see through the familiar's eyes and hear what it hears until the start of your next turn, gaining the benefits of any special senses it has.</p>
```

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +			<p><b><i>One Familiar Only.</i></b> You can't have more than one familiar at a time. If you cast this spell while you have a familiar, you instead cause it to adopt a new eligible form.</p>
```suggestion
			<p class="indent"><b><i>Combat.</i></b> The familiar is an ally to you and your allies. It rolls its own Initiative and acts on its own turn. A familiar can't attack, but it can take other actions as normal.</p>
			<p class="indent"><b><i>Disappearance of the Familiar.</i></b> When the familiar drops to 0 Hit Points, it disappears. It reappears after you cast this spell again. As a Magic action, you can temporarily dismiss the familiar to a pocket dimension. Alternatively, you can dismiss it forever. As a Magic action while it is temporarily dismissed, you can cause it to reappear in an unoccupied space within 30 feet of you. Whenever the familiar drops to 0 Hit Points or disappears into the pocket dimension, it leaves behind in its space anything it was wearing or carrying.</p>
			<p class="indent"><b><i>One Familiar Only.</i></b> You can't have more than one familiar at a time. If you cast this spell while you have a familiar, you instead cause it to adopt a new eligible form.</p>
```

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
		<setters>
			<set name="keywords">summon, bat, cat, frog, hawk, lizard, octopus, owl, rat, raven, spider, weasel, beast, celestial, fey, fiend, telepathy, seeing, hearing, bonus action, action</set>
			<set name="level">1</set>
			<set name="school">Conjuration</set>
			<set name="time">1 hour or Ritual</set>
			<set name="isRitual">true</set>
			<set name="range">10 feet</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="hasMaterialComponent">true</set>
			<set name="materialComponent">burning incense worth 10+ GP, which the spell consumes</set>
			<set name="duration">Instantaneous</set>
		</setters>
		<rules>
			<select type="Companion" name="Find Familiar" supports="Familiar||Beast,0" />
		</rules>
	</element>
```

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +			<p>You summon an otherworldly being that appears as a loyal steed in an unoccupied space of your choice within range. This creature uses the Otherworldly Steed stat block. If you already have a st
```suggestion
			<p>You summon an otherworldly being that appears as a loyal steed in an unoccupied space of your choice within range. This creature uses the <b>Otherworldly Steed</b> stat block. If you already have a steed from this spell, the steed is replaced by the new one.</p>
```

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +			<set name="duration">Instantaneous</set>
```suggestion
			<set name="keywords">summon, upcasting, higher-level spell slot</set>
			<set name="level">2</set>
			<set name="school">Conjuration</set>
			<set name="time">Action</set>
			<set name="range">30 feet</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="duration">Instantaneous</set>
```

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
	</element>
	<element name="Otherworldly Steed" type="Information" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_INFORMATION_OTHERWORLDLY_STEED_STATBLOCK">
		<description>
			<p style="margin-bottom:5px"><em>Large Celestial, Fey, or Fiend (Your Choice), Neutral</em></p>
			<ul class="unstyled mb">
				<li><strong>AC</strong> 10 + the spell's level</li>
				<li><strong>HP</strong> 5 + 10 per spell level (the steed has a number of Hit Dice [d10s] equal to the spell's level)</li>
				<li><strong>Speed</strong> 60 ft., Fly 60 ft. (requires level 4+ spell)</li>
			</ul>
			<table style="text-align:center;margin-top:2px;margin-bottom:10px">
				<tr style="font-size:8px"><td colspan="2" /><td>MOD</td><td>SAVE</td><td colspan="2" /><td>MOD</td><td>SAVE</td><td colspan="2" /><td>MOD</td><td>SAVE</td></tr>
				<tr><td>STR</td><td>18</td><td>+4</td><td>+4</td><td>DEX</td><td>12</td><td>+1</td><td>+1</td><td>CON</td><td>14</td><td>+2</td><td>+2</td></tr>
				<tr><td>INT</td><td>6</td><td>-2</td><td>-2</td><td>WIS</td><td>12</td><td>+1</td><td>+1</td><td>CHA</td><td>8</td><td>-1</td><td>-1</td></tr>
			</table>
			<ul class="unstyled mb">
				<li><strong>Senses</strong> Passive Perception 11</li>
				<li><strong>Languages</strong> Telepathy 1 mile (works only with you)</li>
				<li><strong>CR</strong> None (XP 0; PB equals your Proficiency Bonus)</li>
			</ul>
			<h4 style="margin-top:5px">Traits</h4>
			<ul class="unstyled">
				<li><strong><em>Life Bond.</em></strong> When you regain Hit Points from a level 1+ spell, the steed regains the same number of Hit Points if you're within 5 feet of it.</li>
			</ul>
			<h4 style="margin-top:5px">Actions</h4>
			<ul class="unstyled">
				<li><em><strong>Otherworldly Slam.</strong> Melee Attack Roll:</em> Bonus equals your spell attack modifier, reach 5 ft. <em>Hit:</em> 1d8 plus the spell's level of Radiant (Celestial), Psychic (Fey), or Necrotic (Fiend) damage.</li>
			</ul>
			<h4 style="margin-top:5px">Bonus Actions</h4>
			<ul class="unstyled">
				<li><em><strong>Fell Glare (Fiend Only; Recharges after a Long Rest).</strong> Wisdom Saving Throw:</em> DC equals your spell save DC, one creature within 60 feet the steed can see. <em>Failure:</em> The target has the Frightened condition until the end of your next turn.</li>
				<li><em><strong>Fey Step (Fey Only; Recharges after a Long Rest).</strong></em> The steed teleports, along with its rider, to an unoccupied space of your choice up to 60 feet away from itself.</li>
				<li><em><strong>Healing Touch (Celestial Only; Recharges after a Long Rest).</strong></em> One creature within 5 feet of the steed regains a number of Hit Points equal to 2d8 plus the spell's level.</li>
			</ul>
		</description>
	</element>

```

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="keywords">guide, guiding, guidance</set>
			<set name="level">6</set>
			<set name="school">Divination</set>
			<set name="time">1 minute</set>
			<set name="range">Self</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="hasMaterialComponent">true</set>
			<set name="materialComponent">a set of divination tools—such as cards or runes—worth 100+ GP</set>
			<set name="isConcentration">true</set>
			<set name="duration">Concentration, up to 1 day</set>
		</setters>
	</element>

```

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="time">Action</set>
			<set name="range">120 feet</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="duration">Instantaneous</set>
		</setters>
	</element>

```

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +			<p class="indent">A Humanoid killed by this spell rises at the start of your next turn as a Zombie that follows your verbal orders.</p>
```suggestion
			<p class="indent">A Humanoid killed by this spell rises at the start of your next turn as a <b>Zombie</b> that follows your verbal orders.</p>
			<!-- to do: add a reference to Information type stat-blocks for Zombie here. -->
```

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="keywords">constitution, save, necrotic, damage, humanoid, zombie</set>
			<set name="level">7</set>
			<set name="school">Necromancy</set>
			<set name="time">Action</set>
			<set name="range">60 feet</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="duration">Instantaneous</set>
		</setters>
	</element>

```

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	<element name="Fire Bolt" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_FIRE_BOLT">
```suggestion
	<element name="Fireball" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_FIREBALL">
		<supports>Sorcerer, Wizard, Damaging Spell, Spell Saving Throw</supports>
		<description>
			<p>A bright streak flashes from you to a point you choose within range and then blossoms with a low roar into a fiery explosion. Each creature in a 20-foot-radius Sphere centered on that point makes a Dexterity saving throw, taking 8d6 Fire damage on a failed save or half as much damage on a successful one.</p>
			<p class="indent">Flammable objects in the area that aren't being worn or carried start burning.</p>
			<p class="indent"><b><i>Using a Higher-Level Spell Slot.</i></b> The damage increases by 1d6 for each spell slot level above 3.</p>
		</description>
		<setters>
			<set name="keywords">sphere, dexterity, save, fire, damage, burning, upcasting, higher-level spell slot</set>
			<set name="level">3</set>
			<set name="school">Evocation</set>
			<set name="time">Action</set>
			<set name="range">150 feet</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="hasMaterialComponent">true</set>
			<set name="materialComponent">a ball of bat guano and sulfur</set>
			<set name="duration">Instantaneous</set>
		</setters>
	</element>

	<element name="Fire Bolt" type="Spell" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_SPELL_FIRE_BOLT">
```

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +		<supports>Sorcerer, Wizard, Artificer, Damaging Spell, Ranged, Spell Attack</supports>
```suggestion
		<supports>Artificer, Sorcerer, Wizard, Damaging Spell, Ranged, Spell Attack</supports>
```

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="keywords">fire, damage, burning, upgrade</set>
			<set name="level">0</set>
			<set name="school">Evocation</set>
			<set name="time">Action</set>
			<set name="range">120 feet</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="duration">Instantaneous</set>
		</setters>
	</element>

```

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="keywords">light, bright, dim, resistance, fire, cold, damage, armor</set>
			<set name="level">4</set>
			<set name="school">Evocation</set>
			<set name="time">Action</set>
			<set name="range">Self</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="hasMaterialComponent">true</set>
			<set name="materialComponent">a bit of phosphorus or a firefly</set>
			<set name="duration">10 minutes</set>
		</setters>
	</element>

```

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="time">Action</set>
			<set name="range">150 feet</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="duration">Instantaneous</set>
		</setters>
	</element>

```

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="keywords">action, fire, damage, bright, dim, light, upcasting, higher-level spell slot</set>
			<set name="level">2</set>
			<set name="school">Evocation</set>
			<set name="time">Bonus Action</set>
			<set name="range">Self</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="hasMaterialComponent">true</set>
			<set name="materialComponent">a sumac leaf</set>
			<set name="isConcentration">true</set>
			<set name="duration">Concentration, up to 10 minutes</set>
		</setters>
	</element>

```

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="keywords">cylinder, dexterity, save, fire, radiant, upcasting, higher-level spell slot</set>
			<set name="level">5</set>
			<set name="school">Evocation</set>
			<set name="time">Action</set>
			<set name="range">60 feet</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="hasMaterialComponent">true</set>
			<set name="materialComponent">a pinch of sulfur</set>
			<set name="duration">Instantaneous</set>
		</setters>
	</element>

```

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="keywords">sphere, dexterity, save, fire, damage, bonus action, upcasting, higher-level spell slot</set>
			<set name="level">2</set>
			<set name="school">Conjuration</set>
			<set name="time">Action</set>
			<set name="range">60 feet</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="hasMaterialComponent">true</set>
			<set name="materialComponent">a ball of wax</set>
			<set name="isConcentration">true</set>
			<set name="duration">Concentration, up to 1 minute</set>
		</setters>
	</element>

```

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +			<p class="indent">If you maintain your Concentration on this spell for the entire possible duration, the target is Petrified until the condition is ended by Greater Restoration or similar magic.</
```suggestion
			<p class="indent">If you maintain your Concentration on this spell for the entire possible duration, the target is Petrified until the condition is ended by <i>Greater Restoration</i> or similar magic.</p>
```

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="keywords">constitution, save, restrained, petrified</set>
			<set name="level">6</set>
			<set name="school">Transmutation</set>
			<set name="time">Action</set>
			<set name="range">60 feet</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="hasMaterialComponent">true</set>
			<set name="materialComponent">a cockatrice feather</set>
			<set name="isConcentration">true</set>
			<set name="duration">Concentration, up to 1 minute</set>
		</setters>
	</element>

```

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +		<supports>Sorcerer, Warlock, Wizard, Artificer</supports>
```suggestion
		<supports>Artificer, Sorcerer, Warlock, Wizard</supports>
```

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="keywords">movement, speed, upcasting, higher-level spell slot</set>
			<set name="level">3</set>
			<set name="school">Transmutation</set>
			<set name="time">Action</set>
			<set name="range">Touch</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="hasMaterialComponent">true</set>
			<set name="materialComponent">a feather</set>
			<set name="isConcentration">true</set>
			<set name="duration">Concentration, up to 10 minutes</set>
		</setters>
	</element>

```

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="keywords">sphere, heavily obscured, upcasting, higher-level spell slot</set>
			<set name="level">1</set>
			<set name="school">Conjuration</set>
			<set name="time">Action</set>
			<set name="range">120 feet</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="isConcentration">true</set>
			<set name="duration">Concentration, up to 1 hour</set>
		</setters>
	</element>

```

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +		<supports>Cleric</supports>
```suggestion
		<supports>Cleric, Damaging Spell</supports>
```

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +			<p>You create a ward against magical travel that protects up to 40,000 square feet of floor space to a height of 30 feet above the floor. For the duration, creatures can't teleport into the area o
```suggestion
			<p>You create a ward against magical travel that protects up to 40,000 square feet of floor space to a height of 30 feet above the floor. For the duration, creatures can't teleport into the area or use portals, such as those created by the <i>Gate</i> spell, to enter the area. The spell proofs the area against planar travel, and therefore prevents creatures from accessing the area by way of the Astral Plane, the Ethereal Plane, the Feywild, the Shadowfell, or the <i>Plane Shift</i> spell.</p>
```

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="keywords">radiant, necrotic, damage</set>
			<set name="level">6</set>
			<set name="school">Abjuration</set>
			<set name="time">10 minutes or Ritual</set>
			<set name="isRitual">true</set>
			<set name="range">Touch</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="hasMaterialComponent">true</set>
			<set name="materialComponent">ruby dust worth 1,000+ GP</set>
			<set name="duration">1 day</set>
		</setters>
	</element>

```

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="keywords">cube, prison, charisma, save</set>
			<set name="level">7</set>
			<set name="school">Evocation</set>
			<set name="time">Action</set>
			<set name="range">100 feet</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="hasMaterialComponent">true</set>
			<set name="materialComponent">ruby dust worth 1,500+ GP, which the spell consumes</set>
			<set name="isConcentration">true</set>
			<set name="duration">Concentration, up to 1 hour</set>
		</setters>
	</element>

```

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="keywords">buff, advantage, d20 tests, ability checks, saving throws, attack rolls, disadvantage</set>
			<set name="level">9</set>
			<set name="school">Divination</set>
			<set name="time">1 minute</set>
			<set name="range">Touch</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="hasMaterialComponent">true</set>
			<set name="materialComponent">a hummingbird feather</set>
			<set name="duration">8 hours</set>
		</setters>
	</element>

```

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="keywords">bright, dim, light, resistance, radiant, melee, attack rolls, damage, reaction, constitution, save, blinded</set>
			<set name="level">4</set>
			<set name="school">Evocation</set>
			<set name="time">Action</set>
			<set name="range">Self</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="isConcentration">true</set>
			<set name="duration">Concentration, up to 10 minutes</set>
		</setters>
	</element>

```

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +		<supports>Bard, Cleric, Druid, Ranger, Artificer</supports>
```suggestion
		<supports>Artificer, Bard, Cleric, Druid, Ranger</supports>
```

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="keywords">difficult terrain, buff, swim, speed, upcasting, higher-level spell slot</set>
			<set name="level">4</set>
			<set name="school">Abjuration</set>
			<set name="time">Action</set>
			<set name="isRitual">false</set>
			<set name="range">Touch</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="hasMaterialComponent">true</set>
			<set name="materialComponent">a leather strap</set>
			<set name="duration">1 hour</set>
		</setters>
	</element>

```

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="keywords">wisdom, save, charmed</set>
			<set name="level">0</set>
			<set name="school">Enchantment</set>
			<set name="time">Action</set>
			<set name="range">10 feet</set>
			<set name="hasSomaticComponent">true</set>
			<set name="hasMaterialComponent">true</set>
			<set name="materialComponent">some makeup</set>
			<set name="isConcentration">true</set>
			<set name="duration">Concentration, up to 1 minute</set>
		</setters>
	</element>

```

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="keywords">shape-shift, shapeshift, transformation, polymorph, movement, fly, speed, hover, resistance, bludgeoning, piercing, slashing, immunity, prone, advantage, strength, dexterity, constitution, saving throws, saves, upcasting, higher-level spell slot</set>
			<set name="level">3</set>
			<set name="school">Transmutation</set>
			<set name="time">Action</set>
			<set name="range">Touch</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="hasMaterialComponent">true</set>
			<set name="materialComponent">a bit of gauze</set>
			<set name="isConcentration">true</set>
			<set name="duration">Concentration, up to 1 hour</set>
		</setters>
	</element>

```

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="keywords">teleport, portal, planar travel</set>
			<set name="level">9</set>
			<set name="school">Conjuration</set>
			<set name="time">Action</set>
			<set name="range">60 feet</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="hasMaterialComponent">true</set>
			<set name="materialComponent">a diamond worth 5,000+ GP</set>
			<set name="isConcentration">true</set>
			<set name="duration">Concentration, up to 1 minute</set>
		</setters>
	</element>

```

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="keywords">wisdom, save, charmed, psychic, upcasting, higher-level spell slot</set>
			<set name="level">5</set>
			<set name="school">Enchantment</set>
			<set name="time">1 minute</set>
			<set name="range">60 feet</set>
			<set name="hasVerbalComponent">true</set>
			<set name="duration">30 days</set>
		</setters>
	</element>

```

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +			<p class="indent">The spell also effectively extends the time limit on raising the target from the dead, since days spent under the influence of this spell don't count against the time limit of sp
```suggestion
			<p class="indent">The spell also effectively extends the time limit on raising the target from the dead, since days spent under the influence of this spell don't count against the time limit of spells such as <i>Raise Dead</i>.</p>
```

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="keywords">protection, raise dead, decay</set>
			<set name="level">2</set>
			<set name="school">Necromancy</set>
			<set name="time">Action or Ritual</set>
			<set name="isRitual">true</set>
			<set name="range">Touch</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="hasMaterialComponent">true</set>
			<set name="materialComponent">2 Copper Pieces, which the spell consumes</set>
			<set name="duration">10 days</set>
		</setters>
	</element>

```

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +			<p>You summon a giant centipede, spider, or wasp (chosen when you cast the spell). It manifests in an unoccupied space you can see within range and uses the Giant Insect stat block. The form you c
```suggestion
			<p>You summon a giant centipede, spider, or wasp (chosen when you cast the spell). It manifests in an unoccupied space you can see within range and uses the <b>Giant Insect</b> stat block. The form you choose determines certain details in its stat block. The creature disappears when it drops to 0 Hit Points or when the spell ends.</p>
```

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +			<set name="duration">Concentration, up to 10 minutes</set>
```suggestion
			<set name="keywords">summon, centipede, spider, wasp, upcasting, higher-level spell slot</set>
			<set name="level">4</set>
			<set name="school">Conjuration</set>
			<set name="time">Action</set>
			<set name="range">60 feet</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="isConcentration">true</set>
			<set name="duration">Concentration, up to 10 minutes</set>
```

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
	</element>
	<element name="Giant Insect" type="Information" source="Player’s Handbook 2024" id="ID_WOTC_PHB24_INFORMATION_GIANT_INSECT_STATBLOCK">
		<description>
			<p style="margin-bottom:5px"><em>Large Beast, Unaligned</em></p>
			<ul class="unstyled mb">
				<li><strong>AC</strong> 11 + the spell's level</li>
				<li><strong>HP</strong> 30 + 10 for each spell level above 4</li>
				<li><strong>Speed</strong> 40 ft., Climb 40ft., Fly 40 ft. (Wasp only)</li>
			</ul>
			<table style="text-align:center;margin-top:2px;margin-bottom:10px">
				<tr style="font-size:8px"><td colspan="2" /><td>MOD</td><td>SAVE</td><td colspan="2" /><td>MOD</td><td>SAVE</td><td colspan="2" /><td>MOD</td><td>SAVE</td></tr>
				<tr><td>STR</td><td>17</td><td>+3</td><td>+3</td><td>DEX</td><td>12</td><td>+1</td><td>+1</td><td>CON</td><td>15</td><td>+2</td><td>+2</td></tr>
				<tr><td>INT</td><td>4</td><td>-3</td><td>-3</td><td>WIS</td><td>14</td><td>+2</td><td>+2</td><td>CHA</td><td>3</td><td>-4</td><td>-4</td></tr>
			</table>
			<ul class="unstyled mb">
				<li><strong>Senses</strong> Darkvision 60 ft., Passive Perception 12</li>
				<li><strong>Languages</strong> Understands the languages you know</li>
				<li><strong>CR</strong> None (XP 0; PB equals your Proficiency Bonus)</li>
			</ul>
			<h4 style="margin-top:5px">Traits</h4>
			<ul class="unstyled">
				<li><strong><em>Spider Climb.</em></strong> The insect can climb difficult surfaces, including along ceilings, without needing to make an ability check.</li>
			</ul>
			<h4 style="margin-top:5px">Actions</h4>
			<ul class="unstyled">
				<li><em><strong>Multiattack.</strong></em> The insect makes a number of attacks equal to half this spell's level (round down).</li>
				<li><em><strong>Poison Jab.</strong> Melee Attack Roll:</em> Bonus equals your spell attack modifier, reach 10 ft. <em>Hit:</em> 1d6 + 3 + the spell’s level Piercing damage plus 1d4 Poison damage.</li>
				<li><em><strong>Web Bolt (Spider Only).</strong> Ranged Attack Roll:</em> Bonus equals your spell attack modifier, range 60 ft. <em>Hit:</em> 1d10 + 3 + the spell’s level Bludgeoning damage, and the target's Speed is reduced to 0 until the start of the insect's next turn.</li>
			</ul>
			<h4 style="margin-top:5px">Bonus Actions</h4>
			<ul class="unstyled">
				<li><em><strong>Venomous Spew (Centipede Only).</strong> Constitution Saving Throw:</em> DC equals your spell save DC, one creature the insect can see within 10 feet of itself. <i>Failure:</i> The target has the Poisoned condition until the start of the insect's next turn.</li>
			</ul>
		</description>
	</element>

```

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="keywords">charisma, ability check</set>
			<set name="level">8</set>
			<set name="school">Enchantment</set>
			<set name="time">Action</set>
			<set name="range">Self</set>
			<set name="hasVerbalComponent">true</set>
			<set name="duration">1 hour</set>
		</setters>
	</element>

```

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="keywords">emanation, anti-magic, upcasting, higher-level spell slot</set>
			<set name="level">6</set>
			<set name="school">Abjuration</set>
			<set name="time">Action</set>
			<set name="range">Self (10-foot Emanation)</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="hasMaterialComponent">true</set>
			<set name="materialComponent">a glass bead</set>
			<set name="isConcentration">true</set>
			<set name="duration">Concentration, up to 1 minute</set>
		</setters>
	</element>

```

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +		<supports>Bard, Cleric, Wizard, Artificer, Damaging Spell, Spell Saving Throw</supports>
```suggestion
		<supports>Artificer, Bard, Cleric, Wizard, Damaging Spell, Spell Saving Throw</supports>
```

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="keywords">sphere, dexterity, save, acid, cold, fire, lightning, thunder, damage, upcasting, higher-level spell slot</set>
			<set name="level">3</set>
			<set name="school">Abjuration</set>
			<set name="time">1 hour</set>
			<set name="range">Touch</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="hasMaterialComponent">true</set>
			<set name="materialComponent">powdered diamond worth 200+ GP, which the spell consumes</set>
			<set name="duration">Until dispelled or triggered</set>
		</setters>
	</element>

```

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="keywords">bonus action</set>
			<set name="level">1</set>
			<set name="school">Conjuration</set>
			<set name="time">Action</set>
			<set name="range">Touch</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="hasMaterialComponent">true</set>
			<set name="materialComponent">a sprig of mistletoe</set>
			<set name="duration">24 hours</set>
		</setters>
	</element>

```

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="keywords">bludgeoning, damage, grappled, upcasting, higher-level spell slot</set>
			<set name="level">4</set>
			<set name="school">Conjuration</set>
			<set name="time">Bonus Action</set>
			<set name="range">60 feet</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="isConcentration">true</set>
			<set name="duration">Concentration, up to 1 minute</set>
		</setters>
	</element>

```

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="keywords">square, difficult terrain, dexterity, save, prone</set>
			<set name="level">1</set>
			<set name="school">Conjuration</set>
			<set name="time">Action</set>
			<set name="range">60 feet</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="hasMaterialComponent">true</set>
			<set name="materialComponent">a bit of pork rind or butter</set>
			<set name="duration">1 minute</set>
		</setters>
	</element>

```

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="keywords">invisible, buff</set>
			<set name="level">4</set>
			<set name="school">Illusion</set>
			<set name="time">Action</set>
			<set name="range">Touch</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="isConcentration">true</set>
			<set name="duration">Concentration, up to 1 minute</set>
		</setters>
	</element>

```

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +		<supports>Bard, Cleric, Druid, Paladin, Ranger, Artificer</supports>
```suggestion
		<supports>Artificer, Bard, Cleric, Druid, Paladin, Ranger</supports>
```

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="keywords">healing, exhaustion, charmed, petrified, curse, reduction, conditions</set>
			<set name="level">5</set>
			<set name="school">Abjuration</set>
			<set name="time">Action</set>
			<set name="range">Touch</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="hasMaterialComponent">true</set>
			<set name="materialComponent">diamond dust worth 100+ GP, which the spell consumes</set>
			<set name="duration">Instantaneous</set>
		</setters>
	</element>

```

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="keywords">summon, dexterity, save, radiant, damage</set>
			<set name="level">4</set>
			<set name="school">Conjuration</set>
			<set name="time">Action</set>
			<set name="range">30 feet</set>
			<set name="hasVerbalComponent">true</set>
			<set name="duration">8 hours</set>
		</setters>
	</element>

```

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +			<p class="indent">The spell creates the effects below within the warded area. Dispel Magic has no effect on Guards and Wards itself, but each of the following effects can be dispelled. If all four
```suggestion
			<p class="indent">The spell creates the effects below within the warded area. <i>Dispel Magic</i> has no effect on <i>Guards and Wards</i> itself, but each of the following effects can be dispelled. If all four are dispelled, <i>Guards and Wards</i> ends. If you cast the spell every day for 365 days on the same area, the spell thereafter lasts until all its effects are dispelled.</p>
```

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +				<li><i>Stinking Cloud</i> in two locations (the vapors return within 10 minutes if dispersed while Guards and Wards lasts)</li>
```suggestion
			<p class="indent"><strong><em>Doors.</em></strong> All doors in the warded area are magically locked, as if sealed by the <i>Arcane Lock</i> spell. In addition, you can cover up to ten doors with an illusion to make them appear as plain sections of wall.</p>
			<p class="indent"><strong><em>Stairs.</em></strong> Webs fill all stairs in the warded area from top to bottom, as in the <i>Web</i> spell. These strands regrow in 10 minutes if they are destroyed while <i>Guards and Wards</i> lasts.</p>
			<p class="indent"><strong><em>Other Spell Effect.</em></strong> Place one of the following magical effects within the warded area:</p>
			<ul>
				<li><i>Dancing Lights</i> in four corridors, with a simple program that the lights repeat as long as <i>Guards and Wards</i> lasts</li>
				<li><i>Magic Mouth</i> in two locations.</li>
				<li><i>Stinking Cloud</i> in two locations (the vapors return within 10 minutes if dispersed while <i>Guards and Wards</i> lasts)</li>
```

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="keywords">square, fog, heavily obscured, arcane lock, illusion, illusory walls, web, dancing lights, magic mouth, stinking cloud, gust of wind, suggestion</set>
			<set name="level">6</set>
			<set name="school">Abjuration</set>
			<set name="time">1 hour</set>
			<set name="range">Touch</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="hasMaterialComponent">true</set>
			<set name="materialComponent">a silver rod worth 10+ GP</set>
			<set name="duration">24 hours</set>
		</setters>
	</element>

```

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +		<supports>Cleric, Druid, Artificer</supports>
```suggestion
		<supports>Artificer, Cleric, Druid</supports>
```

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="time">Action</set>
			<set name="range">Touch</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="isConcentration">true</set>
			<set name="duration">Concentration, up to 1 minute</set>
		</setters>
	</element>

```

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="keywords">radiant, damage, advantage, attack rolls, upcasting, higher-level spell slot</set>
			<set name="level">1</set>
			<set name="school">Evocation</set>
			<set name="time">Action</set>
			<set name="range">120 feet</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="duration">1 round</set>
		</setters>
	</element>

```

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="keywords">line, strength, save, push, forced movement, bonus action</set>
			<set name="level">2</set>
			<set name="school">Evocation</set>
			<set name="time">Action</set>
			<set name="range">Self (60-foot long, 10 feet wide line)</set>
			<set name="hasVerbalComponent">true</set>
			<set name="hasSomaticComponent">true</set>
			<set name="hasMaterialComponent">true</set>
			<set name="materialComponent">a legume seed</set>
			<set name="isConcentration">true</set>
			<set name="duration">Concentration, up to 1 minute</set>
		</setters>
	</element>

```

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +	</element>
```suggestion
			<set name="keywords">on hit, weapon, dexterity, save, piercing, damage, upcasting, higher-level spell slot</set>
			<set name="level">1</set>
			<set name="school">Conjuration</set>
			<set name="time">Bonus Action, which you take immediately after hitting a creature with a Ranged weapon</set>
			<set name="range">Self</set>
			<set name="hasVerbalComponent">true</set>
			<set name="duration">Instantaneous</set>
		</setters>
	</element>

```

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +			<p class="indent"><strong><i>Courage.</i></strong> Creatures of any types you choose can't gain the Frightened condition while in the area.</p>
```suggestion
			<p style="text-indent: -1em; margin-left: 1em"><strong><i>Courage.</i></strong> Creatures of any types you choose can't gain the Frightened condition while in the area.</p>
```

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +			<p class="indent"><strong><i>Darkness.</i></strong> Darkness fills the area. Normal light, as well as magical light created by spells of a level lower than this spell, can't illuminate the area.</
```suggestion
			<p style="text-indent: -1em; margin-left: 1em"><strong><i>Darkness.</i></strong> Darkness fills the area. Normal light, as well as magical light created by spells of a level lower than this spell, can't illuminate the area.</p>
```

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +
i have no idea wtf is going on with Github, but it refuses to properly display this line, it's the _Daylight_ line in Hallow spell.
```suggestion
			<p style="text-indent: -1em; margin-left: 1em"><strong><i>Daylight.</i></strong> Bright light fills the area. Magical Darkness created by spells of a level lower than this spell can't extinguish the light.</p>
```

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +
```suggestion
			<p style="text-indent: -1em; margin-left: 1em"><strong><i>Peaceful Rest.</i></strong> Dead bodies interred in the area can't be turned into Undead.</p>
			<p style="text-indent: -1em; margin-left: 1em"><strong><i>Extradimensional Interference.</i></strong> Creatures of any types you choose can't enter or exit the area using teleportation or interplanar travel.</p>
```
once again, it displays correct preview, but once i actually add comment it breaks... whatever.

<img width="911" height="337" alt="Image" src="https://github.com/user-attachments/assets/d518b2b1-d5bb-4296-bfd8-ca2b4d10a745" />

2026-01-21 16:12 UTC, NickVendel commented on core/players-handbook-2024/spells.xml
> +
fuck Github
```suggestion
			<p style="text-indent: -1em; margin-left: 1em"><strong><i>Fear.</i></strong> Creatures of any types you choose have the Frightened condition while in the area.</p>
			<p style="text-indent: -1em; margin-left: 1em"><strong><i>Resistance.</i></strong> Creatures of any types you choose have Resistance to one damage type of your choice while in the area.</p>
			<p style="text-indent: -1em; margin-left: 1em"><strong><i>Silence.</i></strong> No sound can emanate from within the area, and no sound can reach into it.</p>
			<p style="text-indent: -1em; margin-left: 1em"><strong><i>Tongues.</i></strong> Creatures of any types you choose can communicate with any other creature in the area even if they don't share a common language.</p>
			<p style="text-indent: -1em; margin-left: 1em"><strong><i>Vulnerability.</i></strong> Creatures of any types you choose have Vulnerability to one damage type of your choice while in the area.</p>
```

2026-01-21 16:13 UTC, NickVendel requested changes
Part 3... i hate Github right now, will come back tomorrow probably... damn...

2026-01-22 06:56 UTC, Krishna-Sivakumar commented
The Astral Projection spell is missing a closing description tag and one of its setters was misconfigured when I tried testing this PR

2026-01-22 07:10 UTC, NickVendel commented
> The Astral Projection spell is missing a closing description tag and one of its setters was misconfigured when I tried testing this PR

@Krishna-Sivakumar yeah, i can see that, seems to happen when Meriadar was doing suggestions, but it's likely the issue with Github, lately we have a massive problem of dealing with it... so i assume something gone wrong there. We gonna try to fix it today. In the worse case scenario we'll just recreate this PR with new files.
Though not sure what you mean by "misconfigured", as far as i can tell, everything is correct in that regard.

2026-01-22 07:32 UTC, Krishna-Sivakumar commented
@NickVendel I'm not sure either, Aurora complained about a setting within the spell, and I'm finding it hard to wipe Aurora's content sources to reproduce it.

2026-01-22 07:33 UTC, NickVendel commented
@Krishna-Sivakumar what version of the app are you using?

2026-01-22 07:34 UTC, Krishna-Sivakumar commented
@NickVendel I downloaded it from the website today, so I think it is the latest one.

2026-01-22 07:35 UTC, NickVendel commented
@Krishna-Sivakumar hm, weird, are you in any of our Discord servers?

2026-01-22 07:36 UTC, Krishna-Sivakumar commented
@NickVendel Nope, I'll let you know if I join

2026-01-27 03:13 UTC, FreshRoyal approved these changes

2026-02-01 23:47 UTC, merged