Fix overwrite issue on 20201026.xml
AuroraLegacy/elements pull request #3
Opened 2020-11-06 02:30 UTC by kgirtxd

2020-11-06 18:12 UTC, Azzzzzy approved these changes

2020-11-06 20:31 UTC, NickVendel requested changes
in 20170116.xml should change ID of the Source element to the same date, for consistency sake.

2020-11-06 22:15 UTC, NickVendel reviewed
I think this is fine, but let this pull to stay for now, i want to recheck if there are other UAs that need some minor fixes.

2020-11-20 22:44 UTC, Azzzzzy approved these changes

2020-11-23 07:19 UTC, Azzzzzy commented
Should add in the armorer artificer fix.

2020-11-27 18:20 UTC, closed without merging