[WDMM] Shield of the Uven Rune attunement fix
AuroraLegacy/elements pull request #36
Opened 2021-01-04 19:09 UTC by kgirtxd

Resolves #35

2021-01-04 23:07 UTC, Azzzzzy approved these changes

2021-01-06 20:59 UTC, NickVendel requested changes
update version number

2021-01-06 22:27 UTC, NickVendel approved these changes

2021-01-07 08:34 UTC, AngryGuineaPig approved these changes

2021-01-07 14:36 UTC, merged