Errata - Sage Advice Compendium v2.6
AuroraLegacy/elements pull request #5
Opened 2020-11-17 00:27 UTC by NickVendel

Includes:
• PHB Errata Version 2.0.2
• MM Errata Version 2.0
• DMG Errata Version 2.0
• CoS Errata Version 1.0
• RftLW Errata Version 2.0
• HOTDQ Errata Version 1.0
• PotA Errata Version 1.5
• SCAG Errata Version 2.0
• VGtM Errata Version 2.0
• XGTE Errata Version 1.0

Has potential to break:
• VGtM Orc Race: "Menacing Trait" got replaced with "Primal Intuition" Trait
• RftLW Artificer's Battle Smith: Steel Defender lost "Might of the Master" Trait

2020-11-17 17:03 UTC, kgirtxd requested changes
Is there a reason we are moving away from using (Spellcasting Charisma) and usage="1 / Long Rest"?  I feel that using it makes the sheet less wordy and needed info stands out better at a glance.

SCAG 
-Bladesong needs to be Long Rest
-Add the following to Feral Tiefling rules "<stat name="innate speed:fly" value="50" bonus="base" equipped="![armor:heavy]" />"

2020-11-17 20:04 UTC, kgirtxd approved these changes

2020-11-23 10:49 UTC, Azzzzzy commented on supplements/eberron-rising-from-the-last-war/class-artificer.xml
> +			<p>Using this infusion, you replicate a particular magic item. You can learn this infusion multiple times; each time you do so, choose a magic item that you can make with it, picking from the Repl
Were going to have to make elements for every single common magic item across all the books now.
Also you made the changes to the replicate able magic item table but it also needs to be removed and added to the selects.
This also has the potential to break existing characters.

2020-11-23 14:19 UTC, NickVendel commented
Test

2020-11-23 15:39 UTC, Azzzzzy approved these changes

2020-11-23 15:54 UTC, Azzzzzy approved these changes

2020-11-23 16:55 UTC, merged