[DMG] Aasimar Race
AuroraLegacy/elements pull request #52
Opened 2021-02-05 01:54 UTC by kgirtxd

2021-04-09 04:04 UTC, NickVendel requested changes

2021-04-09 04:04 UTC, NickVendel commented on core/dungeon-masters-guide/races/race-aasimar.xml
> +			<description level="5">You can cast the Light cantrip. Also you can cast the lesser restoration spell and the daylight spell once each per long rest. (Spellcasting: Charisma)</description>
```suggestion
			<description>You can cast the light cantrip. Charisma is your spellcasting ability for this spell.</description>
			<description level="3">You can cast the light cantrip. Also you can cast the lesser restoration spell once per long rest. Charisma is your spellcasting ability for these spells.</description>
			<description level="5">You can cast the light cantrip. Also you can cast the lesser restoration spell and the daylight spell once each per long rest. Charisma is your spellcasting ability for these spells.</description>
```

2021-04-09 04:04 UTC, NickVendel commented on core/dungeon-masters-guide/races/race-aasimar.xml
> +		<sheet action="Action">
Ability itself doesn't require any actions.
```suggestion
		<sheet>
```

2021-04-09 04:04 UTC, NickVendel commented on core/dungeon-masters-guide/races/race-aasimar.xml
> +			<p>You know the light cantrip. Once you reach 3rd level, you can cast the lesser restoration spell once with this trait, and you regain the ability to do so when you finish a long rest. Once you r
Additionally, maybe would be nice to reference spells below original description.

2021-04-13 10:49 UTC, NickVendel commented
What about referencing spells that you get from a Trait?

2021-04-13 13:18 UTC, kgirtxd commented
Thanks a great idea.  Now we just need to remember to do that for other races :sweat_smile:

2021-09-12 10:59 UTC, NickVendel requested changes

2021-09-12 10:59 UTC, NickVendel commented on core/dungeon-masters-guide/races/race-aasimar.xml
> +			<p class="indent"><strong><em>Ability Score Increase.</em></strong> Your Charisma score increases by 2 and Wisdom score increases by 1.</p>
It maybe would make sense to add first paragraph from the Aasimar description from the book here.

2021-09-12 10:59 UTC, NickVendel commented on core/dungeon-masters-guide/races/race-aasimar.xml
> +		</sheet>
I think there's no reason for sheet description, since app displays resistances on the sheet.
```suggestion
		<sheet display="false" />
```

2021-09-12 13:21 UTC, NickVendel approved these changes

2021-09-14 17:17 UTC, JayPea00101010 requested changes
Needs to grant lesser restoration and daylight in rules section of celestial legacy, currently only references them

2021-09-14 17:25 UTC, JayPea00101010 approved these changes

2021-09-14 21:29 UTC, merged