[SCAG] Missing Deities
AuroraLegacy/elements pull request #53
Opened 2021-02-05 04:32 UTC by kgirtxd

2021-04-09 03:36 UTC, NickVendel requested changes

2021-04-09 03:36 UTC, NickVendel commented on supplements/sword-coast-adventurers-guide/deities.xml
> +			<description>goddess of winter</description>
```suggestion
			<description>duergar god of magic and slavery</description>
```

2021-04-09 03:36 UTC, NickVendel commented on supplements/sword-coast-adventurers-guide/deities.xml
> +			<set name="domains">Arcana, Trickery</set>
```suggestion
			<set name="domains">Nature, Trickery</set>
```

2021-04-09 03:36 UTC, NickVendel commented on supplements/sword-coast-adventurers-guide/deities.xml
> +			<p class="flavor">goddess of spider</p>
```suggestion
			<p class="flavor">goddess of spiders</p>
```

2021-04-09 03:36 UTC, NickVendel commented on supplements/sword-coast-adventurers-guide/deities.xml
> +	<!--Halfling Pantheon-->
```suggestion
	<!--Gnomish Pantheon-->
```

2021-04-09 03:36 UTC, NickVendel commented on supplements/sword-coast-adventurers-guide/deities.xml
> +			<description>god of stealth and darkness</description>
```suggestion
			<p class="flavor">god of death and disease</p>
		</description>
		<setters>
			<set name="setting">Forgotten Realms</set>
			<set name="alignment">NE</set>
			<set name="domains">Death</set>
			<set name="symbol">White hand, palm outward</set>
			<set name="gender">male</set>
		</setters>
		<sheet>
			<description>god of death and disease</description>
```

2021-04-09 13:57 UTC, NickVendel requested changes

2021-04-09 13:57 UTC, NickVendel commented on supplements/sword-coast-adventurers-guide/deities.xml
> +	<element name="Kossuth" type="Deity" source="Sword Coast Adventurer’s Guide" id="ID_WOTC_SCAG_DEITY_KELEMVOR">
```suggestion
	<element name="Kossuth" type="Deity" source="Sword Coast Adventurer’s Guide" id="ID_WOTC_SCAG_DEITY_KOSSUTH">
```

2021-09-12 11:52 UTC, NickVendel requested changes

2021-09-12 11:52 UTC, NickVendel commented on supplements/sword-coast-adventurers-guide/deities.xml
> +			<set name="symbol">Black disk encircled with a border</set>
```suggestion
			<set name="symbol">Black disk encircled with a purple border</set>
```

2021-09-12 11:52 UTC, NickVendel commented on supplements/sword-coast-adventurers-guide/deities.xml
> +	<element name="Henali Celanil" type="Deity" source="Sword Coast Adventurer’s Guide" id="ID_WOTC_SCAG_DEITY_HENALI_CELANIL">
```suggestion
	<element name="Hanali Celanil" type="Deity" source="Sword Coast Adventurer’s Guide" id="ID_WOTC_SCAG_DEITY_HANALI_CELANIL">
```

2021-09-12 11:52 UTC, NickVendel commented on supplements/sword-coast-adventurers-guide/deities.xml
> +			<set name="gender">female</set>
```suggestion
			<set name="gender">male</set>
```

2021-09-12 13:22 UTC, NickVendel approved these changes

2021-09-17 20:17 UTC, JayPea00101010 requested changes

2021-09-17 20:17 UTC, JayPea00101010 commented on supplements/sword-coast-adventurers-guide/deities.xml
> +			<set name="symbol">A coin with a two-faced heard</set>
Typo, 'heard' -> 'head

2021-09-17 20:17 UTC, JayPea00101010 commented on supplements/sword-coast-adventurers-guide/deities.xml
> +			<p class="flavor">god of the fire</p>
Typo, 'god of the fire' -> 'god of fire'
Same mistake on line 340

2021-09-17 20:17 UTC, JayPea00101010 commented on supplements/sword-coast-adventurers-guide/deities.xml
> +			<set name="symbol">Golden Heart</set>
typo, 'Heart' -> 'heart' (inkeeping with only first letter uppercase for other symbols)

2021-09-17 20:17 UTC, JayPea00101010 commented on supplements/sword-coast-adventurers-guide/deities.xml
> +			<set name="symbol">Sword-weilding dancing drow female silhouetted against the full moon</set>
Typo, 'weilding' -> 'wielding'

2021-09-17 20:17 UTC, JayPea00101010 commented on supplements/sword-coast-adventurers-guide/deities.xml
> +			<set name="gender">male female</set>
Typo, 'male female' -> 'female'

2021-09-17 20:24 UTC, JayPea00101010 commented on supplements/sword-coast-adventurers-guide/deities.xml
> +			<description>Faerunian god of the fire</description>
```suggestion
			<p class="flavor">god of fire</p>
		</description>
		<setters>
			<set name="setting">Forgotten Realms</set>
			<set name="alignment">N</set>
			<set name="domains">Light</set>
			<set name="symbol">Flame</set>
			<set name="gender">male</set>
		</setters>
		<sheet>
			<description>Faerunian god of fire</description>
```

2021-09-19 16:13 UTC, JayPea00101010 approved these changes

2021-09-19 22:27 UTC, merged