[UA] 20210311: Folk of the Feywild
AuroraLegacy/elements pull request #68
Opened 2021-03-13 17:23 UTC by NickVendel

> Wander into the magical realm of the Feywild in this month’s Unearthed Arcana! With the playtest options in the PDF below, your D&D character can be a member of one of these new D&D races: fairy, hobgoblin of the Feywild, owlfolk, or rabbitfolk.

2021-03-13 21:45 UTC, kgirtxd requested changes

2021-03-13 21:45 UTC, kgirtxd commented on unearthed-arcana/2021/20210311.xml
> +			<description level="3">You can use this trait to take the Help action. Additionally, choose one of the options below each time you take the Help action, whether as a bonus action or an action: &#1
Maybe add bullet points to the Fey Gift upgrades to help them pop on the sheet.

2021-03-13 21:45 UTC, kgirtxd commented on unearthed-arcana/2021/20210311.xml
> +			<grant type="Proficiency" id="ID_PROFICIENCY_SKILL_STEALTH" />
Add TCOE Skill Swap option

2021-03-13 21:45 UTC, kgirtxd commented on unearthed-arcana/2021/20210311.xml
> +			<grant type="Language" id="ID_LANGUAGE_COMMON" />
Add TCOE Language option

2021-03-13 21:45 UTC, kgirtxd commented on unearthed-arcana/2021/20210311.xml
> +			<grant type="Language" id="ID_LANGUAGE_COMMON" />
Add TCOE Language option

2021-03-13 21:45 UTC, kgirtxd commented on unearthed-arcana/2021/20210311.xml
> +			<grant type="Language" id="ID_LANGUAGE_COMMON" />
Add TCOE Language option

2021-03-13 21:45 UTC, kgirtxd commented on unearthed-arcana/2021/20210311.xml
> +			<grant type="Proficiency" id="ID_PROFICIENCY_SKILL_PERCEPTION" />
Add TCOE Skill Swap option

2021-03-13 21:45 UTC, kgirtxd commented on unearthed-arcana/2021/20210311.xml
> +			<grant type="Language" id="ID_LANGUAGE_COMMON" />
Add TCOE Language option

2021-03-14 16:08 UTC, kgirtxd requested changes

2021-03-14 16:08 UTC, kgirtxd commented on unearthed-arcana/2021/20210126.xml
> +			<select type="Language" name="Customized Language" supports="Custom Race Language" number="2"  requirements="ID_WOTC_TCOE_OPTION_CUSTOMIZED_LANGUAGE" />
```suggestion
			<select type="Language" name="Customized Language" supports="Custom Race Language" requirements="ID_WOTC_TCOE_OPTION_CUSTOMIZED_LANGUAGE" />
```
Only Common is being swapped the other language has more options

2021-03-14 16:08 UTC, kgirtxd commented on unearthed-arcana/2021/20210126.xml
> +			<select type="Language" name="Customized Language" supports="Custom Race Language" number="2"  requirements="ID_WOTC_TCOE_OPTION_CUSTOMIZED_LANGUAGE" />
```suggestion
			<select type="Language" name="Customized Language" supports="Custom Race Language" requirements="ID_WOTC_TCOE_OPTION_CUSTOMIZED_LANGUAGE" />
```
Only Common is being swapped the other language has more options

2021-03-14 16:08 UTC, kgirtxd commented on unearthed-arcana/2021/20210126.xml
> +			<select type="Language" name="Customized Language" supports="Custom Race Language" number="2"  requirements="ID_WOTC_TCOE_OPTION_CUSTOMIZED_LANGUAGE" />
```suggestion
			<select type="Language" name="Customized Language" supports="Custom Race Language" requirements="ID_WOTC_TCOE_OPTION_CUSTOMIZED_LANGUAGE" />
```
Only Common is being swapped the other language has more options

2021-03-14 16:08 UTC, kgirtxd commented on unearthed-arcana/2021/20210311.xml
> +			<select type="Language" name="Customized Language" supports="Custom Race Language" number="2"  requirements="ID_WOTC_TCOE_OPTION_CUSTOMIZED_LANGUAGE" />
```suggestion
			<select type="Language" name="Customized Language" supports="Custom Race Language" requirements="ID_WOTC_TCOE_OPTION_CUSTOMIZED_LANGUAGE" />
```
Only Common is being swapped the other language has more options

2021-03-14 16:08 UTC, kgirtxd commented on unearthed-arcana/2021/20210311.xml
> +			<select type="Language" name="Customized Language" supports="Custom Race Language" number="2"  requirements="ID_WOTC_TCOE_OPTION_CUSTOMIZED_LANGUAGE" />
```suggestion
			<select type="Language" name="Customized Language" supports="Custom Race Language" requirements="ID_WOTC_TCOE_OPTION_CUSTOMIZED_LANGUAGE" />
```
Only Common is being swapped the other language has more options

2021-03-14 16:08 UTC, kgirtxd commented on unearthed-arcana/2021/20210311.xml
> +			<select type="Language" name="Customized Language" supports="Custom Race Language" number="2"  requirements="ID_WOTC_TCOE_OPTION_CUSTOMIZED_LANGUAGE" />
```suggestion
			<select type="Language" name="Customized Language" supports="Custom Race Language" requirements="ID_WOTC_TCOE_OPTION_CUSTOMIZED_LANGUAGE" />
```
Only Common is being swapped the other language has more options

2021-03-14 16:08 UTC, kgirtxd commented on unearthed-arcana/2021/20210311.xml
> +			<select type="Language" name="Customized Language" supports="Custom Race Language" number="2"  requirements="ID_WOTC_TCOE_OPTION_CUSTOMIZED_LANGUAGE" />
```suggestion
			<select type="Language" name="Customized Language" supports="Custom Race Language" requirements="ID_WOTC_TCOE_OPTION_CUSTOMIZED_LANGUAGE" />
```
Only Common is being swapped the other language has more options

2021-03-14 16:14 UTC, kgirtxd approved these changes

2021-03-14 18:38 UTC, AngryGuineaPig approved these changes

2021-03-14 18:41 UTC, merged