[XGTE] Added Firearm Support for Way of Kensei
AuroraLegacy/elements pull request #72
Opened 2021-04-01 20:05 UTC by Azzzzzy

2021-04-02 16:39 UTC, NickVendel approved these changes

2021-04-03 01:04 UTC, kgirtxd requested changes

2021-04-03 01:04 UTC, kgirtxd commented on core/dungeon-masters-guide/items/items-firearms.xml
> +			<grant type="Proficiency" id="ID_WOTC_DMG_PROFICIENCY_WEAPON_MODERN_FIREARMS_RIFLE_AUTOMATIC" />
Need to create the proficiency elements for the new versions.  When selecting the kensei weapons client will throw error.

2021-04-03 17:23 UTC, kgirtxd approved these changes

2021-04-03 17:25 UTC, merged