[UA] 20210414: Draconic Options
AuroraLegacy/elements pull request #76
Opened 2021-04-18 16:04 UTC by NickVendel

• includes ASI Options for internal.xml

2021-04-18 16:40 UTC, kgirtxd requested changes
Hide all the ancestry colors/metals/gems and the race/feat options from the compendium.

2021-04-18 16:47 UTC, NickVendel commented
@kgirtxd like this, or there's something more/less?

2021-04-18 18:04 UTC, kgirtxd approved these changes

2021-04-21 00:41 UTC, Azzzzzy approved these changes

2021-04-21 00:48 UTC, merged