[VRGTR] Van Richten'S Guide To Ravenloft
AuroraLegacy/elements pull request #89
Opened 2021-05-18 16:27 UTC by kgirtxd

2021-05-21 17:15 UTC, NickVendel requested changes

2021-05-21 17:15 UTC, NickVendel commented on supplements/van-richtens-guide-to-ravenloft/warlock-undead.xml
> +			<description>As an action, you can project your spirit from your body. The body you leave behind is unconscious and in a state of suspended animation.&#13;
```suggestion
			<description>You can project your spirit from your body. The body you leave behind is unconscious and in a state of suspended animation.&#13; 
```

2021-05-21 18:04 UTC, kgirtxd commented on supplements/van-richtens-guide-to-ravenloft/backgrounds.xml
> +			<set name="short">2 Arcana / Investigation / Religion / Survival, Language, Exotic Language </set>
We can update those others later

2021-05-23 17:04 UTC, NickVendel requested changes

2021-05-29 14:07 UTC, FireWallach commented
Looking forward to this, thanks for your hard work!

2021-06-02 18:55 UTC, NickVendel requested changes

2021-06-02 18:55 UTC, NickVendel commented on supplements/van-richtens-guide-to-ravenloft/items.xml
> +			<p>Upon donning or removing the necklace, whether you are attuned to it or not, you are afflicted with <em>werewolf lycanthropy</em> as detailed in the <em>Monster Manual</em>. The curse lasts unt
book doesn't seem to have words "werewolf lycanthropy" in italics.
```suggestion
			<p>Upon donning or removing the necklace, whether you are attuned to it or not, you are afflicted with werewolf lycanthropy as detailed in the <em>Monster Manual</em>. The curse lasts until the dawn after the next full moon. If you are still wearing the necklace at this time, you are afflicted with the lycanthropy again.</p>
```

2021-06-02 18:55 UTC, NickVendel commented on supplements/van-richtens-guide-to-ravenloft/items.xml
> +			<p class="indent"><strong><em>Curse. </em></strong>Attuning to Harkon’s Bite curses you until either Harkon Lukas removes the necklace from you or you are targeted by a <em>remove curse</em> spell
```suggestion
			<p class="indent"><strong><em>Curse. </em></strong>Attuning to <em>Harkon’s Bite</em> curses you until either Harkon Lukas removes the necklace from you or you are targeted by a <em>remove curse</em> spell or similar magic. As long as you remain cursed, you cannot remove the necklace.</p>
```

2021-06-02 20:05 UTC, NickVendel approved these changes

2021-06-03 17:11 UTC, AngryGuineaPig approved these changes

2021-06-03 17:32 UTC, merged