[UA] 20210608: Mages of Strixhaven
AuroraLegacy/elements pull request #91
Opened 2021-06-22 17:08 UTC by NickVendel

Base Structure by @eterean
Editing and Formatting by @NickVendel

2021-07-05 17:32 UTC, Azzzzzy commented on unearthed-arcana/2021/20210608.xml
> +			<select type="Archetype Feature" name="4th Feature (Mage of Lorehold)" supports="ID_WOTC_UA20210608_ARCHETYPE_FEATURE_MAGE_OF_SILVERQUILL_INFUSION_OF_ELOQUENCE|ID_WOTC_UA20210608_ARCHETYPE_FEATURE
Should be "Mage of Silverquill"

2021-07-05 17:42 UTC, Azzzzzy commented on unearthed-arcana/2021/20210608.xml
> +	<element name="Selfless Invocation" type="Archetype Feature" source="Unearthed Arcana: Mages of Strixhaven" id="ID_WOTC_UA20210608_ARCHETYPE_FEATURE_MAGE_OF_SILVERQUILL_WORD_OF_POWER_DEADLY_DESPAIR"
Wrong ID

2021-07-10 20:40 UTC, kgirtxd requested changes

2021-07-10 20:40 UTC, kgirtxd commented on unearthed-arcana/2021/20210608.xml
> +			<h5>Lorehold Spells</h5>
```suggestion
			<h5>Witherbloom Spells</h5>
```

2021-07-10 20:40 UTC, kgirtxd commented on unearthed-arcana/2021/20210608.xml
> +	</element>
These spells should just be granted for the appropriate spellcating ability.  Nothing in Eloquent Apprentice or Inky Shroud implies that they can be swapped later.  Other subclasses like the Divine Soul and the TCoE sorcerers have specific language for swapping the spells.

2021-07-11 16:35 UTC, kgirtxd approved these changes

2021-07-12 02:44 UTC, Azzzzzy approved these changes

2021-07-12 02:49 UTC, merged